<?php
declare(strict_types=1);

$provider=is_array($linkedinProvider??null)?$linkedinProvider:[];$connections=array_values(array_filter((array)($provider['connections']??[]),'is_array'));$connected=$connections!==[];$oauthRevision=(int)($linkedinOAuthRevision??0);$oauthOutcome=(string)($linkedinOAuthOutcome??'');
$h=static fn(mixed$value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$steps=[['file-pen-line','Prepare','Create and review the post in Sense CMS.'],['list-checks','Choose','Select a LinkedIn profile and customize its message.'],['calendar-clock','Publish','Send now or schedule one idempotent delivery.'],['activity','Monitor','Inspect the result and retry a failed delivery safely.']];
?>
<div class="sensecms-unified-workspace social-publishing-page social-linkedin-page" data-linkedin-page data-linkedin-oauth-revision="<?= $oauthRevision ?>" data-linkedin-oauth-outcome="<?= $h($oauthOutcome) ?>">
    <header class="sensecms-section-hero social-publishing-hero is-linkedin"><div class="sensecms-section-hero-main"><span class="sensecms-section-hero-icon"><i data-lucide="linkedin"></i></span><div><span class="sensecms-section-overline">Social Publishing provider</span><h2>LinkedIn profile</h2><p>Connect one or more LinkedIn member profiles through the official Sense CMS application and publish only posts explicitly selected by an editor.</p></div></div><div class="social-hero-actions"><?php if($connected): ?><span class="social-hero-summary"><i data-lucide="circle-check"></i><span><strong><?= count($connections) ?> connected</strong><small>LinkedIn <?= count($connections)===1?'profile':'profiles' ?></small></span></span><?php endif; ?><a class="btn border-default-200" href="/social-publishing"><i data-lucide="arrow-left"></i>Social Publishing</a></div></header>
    <section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="<?= $connected?'badge-check':'link' ?>"></i></span><div><h2 class="card-title"><?= $connected?'Connected profiles':'Connect LinkedIn' ?></h2><p><?= $connected?'Connect and manage multiple member profiles, then choose destinations per post.':'Sign in at LinkedIn and approve only identity and member publishing permissions.' ?></p></div></div><form method="post" action="/social-publishing/linkedin/connect" data-linkedin-connect><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn bg-primary text-white" type="submit" data-sensecms-native><i data-lucide="plus"></i><?= $connected?'Add LinkedIn profile':'Connect with LinkedIn' ?></button></form></header><div class="card-body">
    <?php if($connected): ?><div class="social-account-list"><?php foreach($connections as$connection): ?><article class="social-account-card"><div class="social-account-primary"><span class="social-provider-icon"><i data-lucide="linkedin"></i></span><div><span class="social-account-kicker">LinkedIn member profile</span><strong><?= $h($connection['display_name']?:'LinkedIn profile') ?></strong><small>An editor can select this destination independently.</small></div></div><div class="social-account-actions"><span class="social-status-badge is-connected"><i data-lucide="check"></i>Connected</span><form method="post" action="/social-publishing/linkedin/connections/<?= (int)$connection['id'] ?>/disconnect" data-sensecms-confirm="Disconnect this LinkedIn profile? Existing delivery history will be preserved."><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn border-default-200" type="submit" data-sensecms-native><i data-lucide="unlink"></i>Disconnect</button></form></div></article><?php endforeach; ?></div><?php else: ?><div class="social-empty-state"><span><i data-lucide="linkedin"></i></span><h3>No LinkedIn profile connected</h3><p>The central service exchanges authorization securely. The LinkedIn Client Secret is never copied into this CMS installation.</p></div><?php endif; ?>
    </div></section>
    <section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="route"></i></span><div><h2 class="card-title">How publishing works</h2><p>Every destination remains review-first, traceable and independently disconnectable.</p></div></div></header><div class="card-body"><div class="social-workflow-grid"><?php foreach($steps as$i=>$step): ?><article class="social-workflow-step"><span class="social-step-number"><?= $i+1 ?></span><i data-lucide="<?= $step[0] ?>"></i><div><strong><?= $h($step[1]) ?></strong><p><?= $h($step[2]) ?></p></div></article><?php endforeach; ?></div><div class="social-provider-note"><i data-lucide="building-2"></i><p><strong>Company Pages are a separate access tier.</strong> This first release uses LinkedIn's self-service member publishing product. Organization publishing will be enabled only after LinkedIn grants Community Management API access.</p></div></div></section>
    <div class="linkedin-oauth-modal" data-linkedin-oauth-modal role="dialog" aria-modal="true" aria-labelledby="linkedin-oauth-title" hidden><section><span class="linkedin-oauth-icon"><i data-lucide="linkedin"></i></span><h2 id="linkedin-oauth-title">Connecting LinkedIn</h2><p data-linkedin-oauth-status>Complete authorization in the LinkedIn window. This page will update automatically.</p><button class="btn border-default-200" type="button" data-linkedin-oauth-cancel>Cancel</button></section></div>
</div>
