<?php
declare(strict_types=1);
$provider=is_array($blueskyProvider??null)?$blueskyProvider:[];$connections=array_values(array_filter((array)($provider['connections']??[]),'is_array'));$connected=$connections!==[];$oauthRevision=(int)($blueskyOAuthRevision??0);$oauthOutcome=(string)($blueskyOAuthOutcome??'');$h=static fn(mixed$value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');$steps=[['file-pen-line','Prepare','Create and review the post in Sense CMS.'],['list-checks','Choose','Select a Bluesky account and customize its message.'],['calendar-clock','Publish','Send now or schedule one idempotent delivery.'],['activity','Monitor','Inspect the result and retry a failed delivery safely.']];
?>
<div class="sensecms-unified-workspace social-publishing-page social-bluesky-page" data-bluesky-page data-bluesky-oauth-revision="<?= $oauthRevision ?>" data-bluesky-oauth-outcome="<?= $h($oauthOutcome) ?>">
<header class="sensecms-section-hero social-publishing-hero is-bluesky"><div class="sensecms-section-hero-main"><span class="sensecms-section-hero-icon"><i data-lucide="cloud"></i></span><div><span class="sensecms-section-overline">Social Publishing provider</span><h2>Bluesky account</h2><p>Connect one or more Bluesky accounts with AT Protocol OAuth and publish only posts explicitly selected by an editor.</p></div></div><div class="social-hero-actions"><?php if($connected): ?><span class="social-hero-summary"><i data-lucide="circle-check"></i><span><strong><?= count($connections) ?> connected</strong><small>Bluesky <?= count($connections)===1?'account':'accounts' ?></small></span></span><?php endif; ?><a class="btn border-default-200" href="/social-publishing"><i data-lucide="arrow-left"></i>Social Publishing</a></div></header>
<section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="<?= $connected?'badge-check':'link' ?>"></i></span><div><h2 class="card-title"><?= $connected?'Connected accounts':'Connect Bluesky' ?></h2><p><?= $connected?'Manage multiple accounts and choose destinations per post.':'Sign in at Bluesky and approve permission to create posts only.' ?></p></div></div><form method="post" action="/social-publishing/bluesky/connect" data-bluesky-connect><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn bg-primary text-white" type="submit" data-sensecms-native><i data-lucide="plus"></i><?= $connected?'Add Bluesky account':'Connect with Bluesky' ?></button></form></header><div class="card-body">
<?php if($connected): ?><div class="social-account-list"><?php foreach($connections as$connection): ?><article class="social-account-card"><div class="social-account-primary"><span class="social-provider-icon bluesky-provider-icon"><i data-lucide="cloud"></i></span><div><span class="social-account-kicker">Bluesky account</span><strong><?= $h($connection['display_name']?:'Bluesky account') ?></strong><small>An editor can select this destination independently.</small></div></div><dl class="social-account-meta"><div><dt>Connection</dt><dd><span class="social-status is-connected"><i data-lucide="circle-check"></i>Connected</span></dd></div><div><dt>DID</dt><dd class="bluesky-did"><?= $h($connection['external_account_id']) ?></dd></div><div><dt>Last verified</dt><dd><?= $h($connection['last_verified_at']?:'Not available') ?></dd></div></dl><form class="social-account-actions" method="post" action="/social-publishing/bluesky/connections/<?= (int)$connection['id'] ?>/disconnect"><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn social-disconnect" type="submit" data-sensecms-native><i data-lucide="unlink"></i>Disconnect</button></form></article><?php endforeach; ?></div>
<?php else: ?><div class="social-empty social-connect-empty"><span class="bluesky-provider-icon"><i data-lucide="cloud"></i></span><strong>No Bluesky account connected</strong><p>OAuth requests only permission to create Bluesky posts. Tokens and proof keys are encrypted inside this installation; account passwords never enter Sense CMS.</p></div><?php endif; ?>
</div></section>
<section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="route"></i></span><div><h2 class="card-title">How publishing works</h2><p>A controlled four-step flow from review to delivery.</p></div></div></header><div class="card-body"><ol class="social-steps"><?php foreach($steps as$index=>[$icon,$title,$description]): ?><li><span class="social-step-number"><?= $index+1 ?></span><span class="social-step-icon"><i data-lucide="<?= $h($icon) ?>"></i></span><div><strong><?= $h($title) ?></strong><p><?= $h($description) ?></p></div></li><?php endforeach; ?></ol></div></section>
<div class="bluesky-oauth-modal" data-bluesky-oauth-modal hidden><section role="dialog" aria-modal="true" aria-labelledby="bluesky-oauth-title"><div class="bluesky-oauth-icon"><i data-lucide="cloud"></i></div><h2 id="bluesky-oauth-title">Connect Bluesky</h2><p data-bluesky-oauth-status aria-live="polite">Continue securely in the Bluesky window. This page will update automatically when you finish.</p><button class="btn border-default-200" type="button" data-bluesky-oauth-cancel>Cancel</button></section></div>
</div>
