<?php
declare(strict_types=1);

namespace SenseCMS\Bluesky {
    function curl_init(string$url):object{return(object)['url'=>$url,'options'=>[],'status'=>0];}
    function curl_setopt_array(object$curl,array$options):bool{$curl->options=$options;return true;}
    function curl_exec(object$curl):bool{$GLOBALS['bluesky_requests'][]=$curl;$next=array_shift($GLOBALS['bluesky_responses']);if(!$next)throw new \RuntimeException('Unexpected Bluesky request.');$curl->status=$next[0];foreach((array)($next[2]??[])as$name=>$value)($curl->options[CURLOPT_HEADERFUNCTION])($curl,$name.': '.$value."\r\n");$body=is_array($next[1])?json_encode($next[1]):$next[1];return($curl->options[CURLOPT_WRITEFUNCTION])($curl,$body)===strlen($body);}
    function curl_error(object$curl):string{return'';}function curl_getinfo(object$curl,int$kind):int{return$curl->status;}function curl_close(object$curl):void{}
}
namespace {
    require dirname(__DIR__).'/.src/AtprotoCrypto.php';require dirname(__DIR__).'/.src/BlueskyBrokerService.php';[$private,$jwk]=SenseCMS\Website\AtprotoCrypto::generate();$provider=require dirname(__DIR__).'/.plugins/bluesky-publisher/src/provider.php';$checks=0;$did='did:plc:abcdefghijklmnopqrstuv23';
    function blueskyCheck(bool$ok,string$label):void{global$checks;if(!$ok)throw new RuntimeException($label);$checks++;echo"PASS $label\n";}function blueskyRejects(callable$fn,string$label,?int$code=null):void{try{$fn();}catch(RuntimeException$error){blueskyCheck($code===null||$error->getCode()===$code,$label);return;}throw new RuntimeException($label);}function blueskyResponses(array$items):void{$GLOBALS['bluesky_responses']=$items;$GLOBALS['bluesky_requests']=[];}
    $manifest=json_decode((string)file_get_contents(dirname(__DIR__).'/.plugins/bluesky-publisher/plugin.json'),true,32,JSON_THROW_ON_ERROR);$license=(array)($manifest['license']??[]);blueskyCheck(($license['price']??null)===15&&($license['currency']??'')==='USD'&&($license['billing_period']??'')==='year','Bluesky subscription is USD 15 per year');blueskyCheck(($license['product_name']??'')==='Sense CMS Bluesky Publisher Plugin'&&($license['product_model']??'')==='Bluesky Publisher Plugin'&&($license['product_version']??'')==='1.0','Bluesky uses its own fixed licence identity');
    $render=static function(array$provider):string{$blueskyProvider=$provider;$blueskyOAuthRevision=2;$blueskyOAuthOutcome='success';$csrf='fixture-csrf';ob_start();require dirname(__DIR__).'/.plugins/bluesky-publisher/views/bluesky.php';return(string)ob_get_clean();};$disconnected=$render([]);blueskyCheck(str_contains($disconnected,'data-bluesky-connect')&&str_contains($disconnected,'data-bluesky-oauth-modal'),'Bluesky OAuth popup and accessible progress dialog rendered');$connected=$render(['connections'=>[['id'=>7,'enabled'=>true,'display_name'=>'@sensecms.bsky.social','external_account_id'=>$did,'last_verified_at'=>'now'],['id'=>8,'enabled'=>true,'display_name'=>'@second.bsky.social','external_account_id'=>'did:plc:222222222222222222222222','last_verified_at'=>'later']]]);blueskyCheck(substr_count($connected,'class="social-account-card"')===2&&str_contains($connected,'/connections/7/disconnect')&&str_contains($connected,'Add Bluesky account'),'Bluesky settings manage multiple independent accounts');$popup=(string)file_get_contents(dirname(__DIR__).'/.plugins/bluesky-publisher/assets/bluesky.js');blueskyCheck(str_contains($popup,"window.open('about:blank',popupName")&&str_contains($popup,"url.pathname!=='/api/social/bluesky/v1/authorize'"),'Bluesky popup validates broker destination');blueskyCheck(str_contains($popup,"if(window.name!==popupName)return false")&&str_contains($popup,'if(window.opener&&!window.opener.closed)')&&str_contains($popup,'window.close()'),'Bluesky OAuth popup closes after a provider-isolated return without requiring its opener');
    $credentials=['did'=>$did,'handle'=>'sensecms.bsky.social','name'=>'Sense CMS','pds'=>'https://morel.us-east.host.bsky.network','access_token'=>'access-'.str_repeat('a',64),'refresh_token'=>'refresh-'.str_repeat('r',64),'expires_at'=>time()+900,'scope'=>'atproto repo:app.bsky.feed.post?action=create','dpop_private_key'=>$private,'dpop_x'=>$jwk['x'],'dpop_y'=>$jwk['y'],'auth_nonce'=>'auth-nonce','resource_nonce'=>''];$payload=['message'=>'A reviewed story','title'=>'Article title','excerpt'=>'Article description','url'=>'https://example.test/en/posts/story'];
    blueskyResponses([[400,['error'=>'use_dpop_nonce'],['DPoP-Nonce'=>'resource-1']],[200,['did'=>$did,'handle'=>'sensecms.bsky.social'],['DPoP-Nonce'=>'resource-2']]]);$verified=$provider->verify($credentials);blueskyCheck($verified['external_id']===$did&&$verified['display_name']==='@sensecms.bsky.social'&&$verified['credentials']['resource_nonce']==='resource-2','Bluesky identity verified after DPoP nonce negotiation');blueskyCheck(str_starts_with($GLOBALS['bluesky_requests'][0]->url,'https://morel.us-east.host.bsky.network/xrpc/')&&array_any($GLOBALS['bluesky_requests'][1]->options[CURLOPT_HTTPHEADER],static fn($h)=>str_starts_with($h,'Authorization: DPoP ')),'Bluesky API uses the official account PDS and DPoP authorization');
    blueskyResponses([[200,['uri'=>'at://'.$did.'/app.bsky.feed.post/3mfixturepost','cid'=>'bafyreifixture'],['DPoP-Nonce'=>'resource-3']]]);$published=$provider->publish(array_replace($credentials,['resource_nonce'=>'resource-2']),$payload);blueskyCheck($published['external_id']==='3mfixturepost'&&$published['external_url']==='https://bsky.app/profile/'.$did.'/post/3mfixturepost','Bluesky publication identity and canonical URL accepted');$request=$GLOBALS['bluesky_requests'][0];$body=json_decode((string)$request->options[CURLOPT_POSTFIELDS],true);blueskyCheck($body['repo']===$did&&$body['collection']==='app.bsky.feed.post'&&$body['record']['text']==='A reviewed story'&&$body['record']['embed']['external']['uri']==='https://example.test/en/posts/story','Bluesky post contains reviewed message and website card');
    blueskyResponses([]);blueskyRejects(fn()=>$provider->publish(array_replace($credentials,['did'=>'bad']),$payload),'invalid Bluesky credentials rejected before network');blueskyCheck(!$GLOBALS['bluesky_requests'],'invalid Bluesky credentials send no request');foreach(['https://evil.example','https://host.bsky.network.evil.example','http://morel.us-east.host.bsky.network','https://morel.us-east.host.bsky.network/xrpc']as$unsafe)blueskyRejects(fn()=>$provider->publish(array_replace($credentials,['pds'=>$unsafe]),$payload),'unsafe Bluesky PDS rejected before network');blueskyCheck(!$GLOBALS['bluesky_requests'],'unsafe Bluesky PDS sends no request');blueskyRejects(fn()=>$provider->publish($credentials,array_replace($payload,['url'=>'http://example.test/story'])),'non-HTTPS Bluesky destination rejected');blueskyResponses([]);blueskyRejects(fn()=>$provider->publish(array_replace($credentials,['expires_at'=>time()-60]),array_replace($payload,['message'=>str_repeat('x',301)])),'oversized Bluesky message is rejected before token refresh');blueskyCheck(!$GLOBALS['bluesky_requests'],'oversized Bluesky message does not consume refresh credentials');$source=(string)file_get_contents(dirname(__DIR__).'/.plugins/bluesky-publisher/src/provider.php');blueskyCheck(str_contains($source,'$installed=$runtime->read(\'installed\')')&&str_contains($source,'$baseUrl=$runtime->baseUrl()'),'Bluesky token refresh loads workspace configuration with runtime context');blueskyResponses([[429,['error'=>'RateLimitExceeded'],['DPoP-Nonce'=>'resource-4']]]);blueskyRejects(fn()=>$provider->publish($credentials,$payload),'Bluesky rate limit remains a failure',429);echo"$checks Bluesky Publisher protocol checks passed; no live Bluesky requests.\n";
}
