<?php
declare(strict_types=1);

require dirname(__DIR__).'/.cms/source/bootstrap.php';
require dirname(__DIR__).'/.src/AtprotoCrypto.php';
require dirname(__DIR__).'/.src/BlueskyBrokerService.php';
require dirname(__DIR__).'/.src/BlueskyOAuthEndpoint.php';

use SenseCMS\Website\AtprotoCrypto;
use SenseCMS\Website\BlueskyBrokerService;
use SenseCMS\Website\BlueskyOAuthEndpoint;

$root=sys_get_temp_dir().'/sensecms-bluesky-test-'.bin2hex(random_bytes(8));if(!mkdir($root,0700)||!mkdir($root.'/storage',0700))throw new RuntimeException('Cannot create private Bluesky fixture.');$key=random_bytes(32);[$clientPrivate]=AtprotoCrypto::generate();$access='access-'.str_repeat('a',64);$refresh='refresh-'.str_repeat('r',64);$nextAccess='access-'.str_repeat('b',64);$nextRefresh='refresh-'.str_repeat('s',64);$did='did:plc:abcdefghijklmnopqrstuv23';$pds='https://morel.us-east.host.bsky.network';$calls=[];$count=0;
$http=static function(string$method,string$url,array$headers,string$payload)use(&$calls,$access,$refresh,$nextAccess,$nextRefresh,$did,&$pds):array{$calls[]=[$method,$url,$headers,$payload];
    if($url==='https://www.chivale.com/license/'){parse_str($payload,$form);return($form['LicenseKey']??'')===str_repeat('K',32)?[200,json_encode(['error'=>false,'data'=>['product'=>['name'=>'Sense CMS','model'=>'Sense CMS System','version'=>'1.0'],'valid_from'=>null,'valid_to'=>null]]),[]]:[403,'{"error":true}',[]];}
    if($url==='https://bsky.social/.well-known/oauth-authorization-server')return[200,json_encode(['issuer'=>'https://bsky.social','authorization_endpoint'=>'https://bsky.social/oauth/authorize','token_endpoint'=>'https://bsky.social/oauth/token','pushed_authorization_request_endpoint'=>'https://bsky.social/oauth/par','response_types_supported'=>['code'],'grant_types_supported'=>['authorization_code','refresh_token'],'code_challenge_methods_supported'=>['S256'],'token_endpoint_auth_methods_supported'=>['none','private_key_jwt'],'dpop_signing_alg_values_supported'=>['ES256'],'require_pushed_authorization_requests'=>true,'client_id_metadata_document_supported'=>true]),[]];
    if($url==='https://bsky.social/oauth/par'){parse_str($payload,$form);if(!in_array('DPoP: ',array_map(static fn($h)=>str_starts_with($h,'DPoP: ')?'DPoP: ':'',$headers),true))throw new RuntimeException('Missing DPoP fixture proof.');$nonce=in_array('DPoP: retry',[],true);$seen=count(array_filter($calls,static fn($c)=>$c[1]==='https://bsky.social/oauth/par'));return$seen===1?[400,'{"error":"use_dpop_nonce"}',['dpop-nonce'=>'fixture-par-1']]:[201,'{"request_uri":"urn:ietf:params:oauth:request_uri:fixture"}',['dpop-nonce'=>'fixture-par-2']];}
    if($url==='https://bsky.social/oauth/token'){parse_str($payload,$form);$rotated=($form['grant_type']??'')==='refresh_token';return[200,json_encode(['token_type'=>'DPoP','expires_in'=>900,'scope'=>'atproto repo:app.bsky.feed.post?action=create','sub'=>$rotated?'':$did,'access_token'=>$rotated?$nextAccess:$access,'refresh_token'=>$rotated?$nextRefresh:$refresh]),['dpop-nonce'=>$rotated?'fixture-refresh':'fixture-token']];}
    if($url==='https://plc.directory/'.$did)return[200,json_encode(['service'=>[['id'=>'#atproto_pds','type'=>'AtprotoPersonalDataServer','serviceEndpoint'=>$pds]]]),[]];
    if($url==='https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor='.rawurlencode($did))return[200,'{"did":"'.$did.'","handle":"sensecms.bsky.social","displayName":"Sense CMS"}',[]];
    throw new RuntimeException('Unexpected Bluesky fixture URL '.$url);
};
$broker=new BlueskyBrokerService($root,$key,$clientPrivate,$http);$server=['HTTP_AUTHORIZATION'=>'Bearer '.str_repeat('K',32),'HTTP_X_SENSECMS_DOMAIN'=>'https://tenant.example'];$other=array_replace($server,['HTTP_X_SENSECMS_DOMAIN'=>'https://other.example']);$check=static function(bool$ok,string$label)use(&$count):void{if(!$ok)throw new RuntimeException($label);$count++;echo"PASS $label\n";};$reject=static function(callable$fn,int$code,string$label)use($check):void{try{$fn();}catch(RuntimeException$error){$check($error->getCode()===$code,$label);return;}throw new RuntimeException($label);};$requestToken=static function(array$start):string{parse_str((string)parse_url($start['authorize_url'],PHP_URL_QUERY),$query);return(string)($query['request']??'');};
try{
    $metadata=$broker->clientMetadata();$jwks=$broker->jwks();$check($metadata['scope']==='atproto repo:app.bsky.feed.post?action=create'&&$metadata['client_uri']==='https://www.sensecms.com/'&&$metadata['token_endpoint_auth_method']==='private_key_jwt'&&!isset($metadata['jwks_uri'])&&($metadata['jwks']['keys'][0]['kid']??'')===$jwks['keys'][0]['kid']&&$jwks['keys'][0]['alg']==='ES256','Bluesky metadata embeds its confidential minimal-scope client key');
    $reject(fn()=>$broker->start([],[]),401,'Bluesky broker requires installation licence');$start=$broker->start($server,['return_url'=>'https://tenant.example/social-publishing/bluesky/callback']);$request=$requestToken($start);$check(strlen($request)===43,'short-lived Bluesky authorization request');$authorize=$broker->authorize($request);parse_str((string)parse_url($authorize,PHP_URL_QUERY),$auth);$check(str_starts_with($authorize,'https://bsky.social/oauth/authorize?')&&$auth['client_id']===BlueskyBrokerService::CLIENT_ID&&str_starts_with($auth['request_uri'],'urn:ietf:params:oauth:request_uri:'),'Bluesky PAR and PKCE authorization accepted');
    $redirect=$broker->callback(['state'=>$request,'iss'=>'https://bsky.social','code'=>'fixture-code']);parse_str((string)parse_url($redirect,PHP_URL_QUERY),$claimQuery);$claim=(string)($claimQuery['claim']??'');$check(strlen($claim)===43&&str_starts_with($redirect,'https://tenant.example/social-publishing/bluesky/callback?claim='),'Bluesky callback returns opaque installation claim');$reject(fn()=>$broker->claim($other,$claim),403,'Bluesky claim bound to licensed installation');$credentials=$broker->claim($server,$claim);$check($credentials['did']===$did&&$credentials['handle']==='sensecms.bsky.social'&&$credentials['pds']==='https://morel.us-east.host.bsky.network'&&$credentials['access_token']===$access&&str_starts_with($credentials['dpop_private_key'],'-----BEGIN PRIVATE KEY-----'),'Bluesky identity, official account PDS, rotating tokens and proof key claimed once');$reject(fn()=>$broker->claim($server,$claim),410,'Bluesky claim consumed once');
    $fresh=$broker->refresh($server,$credentials);$check($fresh['access_token']===$nextAccess&&$fresh['refresh_token']===$nextRefresh&&$fresh['auth_nonce']==='fixture-refresh','Bluesky refresh rotates single-use credentials with DPoP');
    foreach(['https://evil.example','https://host.bsky.network.evil.example','http://morel.us-east.host.bsky.network','https://morel.us-east.host.bsky.network/xrpc']as$unsafe){$pds=$unsafe;$bad=$broker->start($server,['return_url'=>'https://tenant.example/social-publishing/bluesky/callback']);$badRequest=$requestToken($bad);$broker->authorize($badRequest);$reject(fn()=>$broker->callback(['state'=>$badRequest,'iss'=>'https://bsky.social','code'=>'fixture-code']),422,'Unsafe Bluesky PDS rejected: '.$unsafe);}$pds='https://morel.us-east.host.bsky.network';
    $edge=['HTTPS'=>'on','HTTP_HOST'=>'www.sensecms.com','REQUEST_METHOD'=>'GET','REQUEST_URI'=>'/api/social/bluesky/v1/client-metadata.json']+$server;[$status,$headers,$body]=BlueskyOAuthEndpoint::response($edge,'',$broker);$check($status===200&&($headers['Content-Type']??'')==='application/json; charset=utf-8'&&json_decode($body,true)['client_id']===BlueskyBrokerService::CLIENT_ID,'public Bluesky client metadata endpoint');$edge['REQUEST_URI']='/api/social/bluesky/v1/jwks.json';$check(BlueskyOAuthEndpoint::response($edge,'',$broker)[0]===200,'public Bluesky JWKS endpoint');
    $raw='';foreach(glob($root.'/storage/*.json')?:[]as$file)$raw.=file_get_contents($file);$check(!str_contains($raw,$access)&&!str_contains($raw,$refresh)&&!str_contains($raw,str_repeat('K',32)),'Bluesky temporary state is encrypted');echo"$count Bluesky broker checks passed; isolated transport only.\n";
}finally{$broker=null;gc_collect_cycles();foreach(glob($root.'/storage/*.json')?:[]as$file)unlink($file);if(is_file($root.'/broker.lock'))unlink($root.'/broker.lock');rmdir($root.'/storage');rmdir($root);}
