<?php
declare(strict_types=1);
require dirname(__DIR__).'/.cms/source/bootstrap.php';
use App\Core\PageBuilder;
$count=0;
$check=static function(bool $ok,string $label)use(&$count):void{if(!$ok)throw new RuntimeException($label);$count++;echo "PASS $label\n";};
$reject=static function(callable $fn,string $label)use($check):void{try{$fn();}catch(RuntimeException){$check(true,$label);return;}$check(false,$label);};
$catalog=PageBuilder::catalog([]);
$check(array_keys($catalog)===['hero','hero-slider','gallery','admissions','contact-form','custom-html','separator','spacer','story','values','programs','statistics','motion','news','cta','text','image-text'],'All 15 legacy components plus the two Core structural sections retain stable order');
$patterns=PageBuilder::patterns($catalog);
$check(array_keys($patterns)===['landing-page','campaign','newsletter-landing','about-us','contact','product-presentation','service-page','pricing','documentation','event','faq'],'Core exposes all 11 professional page patterns in stable order');
foreach($patterns as$key=>$pattern){
    $check($pattern['sections']===array_values(array_filter($pattern['sections'],static fn(string$type):bool=>isset($catalog[$type]))),'Pattern '.$key.' contains only available section types');
    $singletons=[];foreach($pattern['sections']as$type)if($catalog[$type]['singleton']){$check(!isset($singletons[$type]),'Pattern '.$key.' does not duplicate singleton '.$type);$singletons[$type]=true;}
}
$restrictedPatterns=PageBuilder::patterns(['text'=>$catalog['text']]);
$check(array_reduce($restrictedPatterns,static fn(bool$valid,array$pattern):bool=>$valid&&$pattern['sections']===array_fill(0,count($pattern['sections']),'text'),true),'Patterns fail closed to the currently available catalog');
$check($catalog['admissions']['label']==='Process steps'&&$catalog['programs']['label']==='Services','Generic labels preserve legacy keys');
$fill=static function(array $data,array $fields)use(&$fill):array{
    foreach($fields as$field){$key=$field['key'];if($field['type']==='repeater'){$data[$key]=array_map(fn($row)=>$fill($row,$field['fields']),$data[$key]??[]);continue;}
        if(in_array($field['type'],['image','video'],true)&&($data[$key]??'')==='')$data[$key]='/media/legacy/school.'.($field['type']==='video'?'mp4':'webp');
    }return$data;
};
foreach($catalog as$type=>$definition){
    $check($definition['source']==='core','Core-owned definition '.$type);
    foreach(['en','km','zh']as$locale){
        $defaults=$locale==='en'?$definition['defaults']:($definition['localized_defaults'][$locale]??[]);
        $check(!$definition['fields']||(bool)$defaults,'Localized preset '.$type.'/'.$locale);
        $text=json_encode($defaults,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
        $check(!preg_match('/school|student|learner|admission|curriculum|learning|trilingual|学校|学生|学习|校园|招生|សាលា|សិស្ស|សិក្សា/iu',$text),'No inherited school copy '.$type.'/'.$locale);
        $check(!str_contains($text,'/theme-assets/'),'No dependency on old theme media '.$type.'/'.$locale);
    }
    $block=['uid'=>'12345678-1234-4234-8234-123456789abc','type'=>$type,'visible'=>true,'shared'=>$definition['shared_defaults'],'localized'=>[]];
    foreach(['en','km','zh']as$locale){
        $data=$fill($locale==='en'?$definition['defaults']:($definition['localized_defaults'][$locale]??$definition['defaults']),$definition['fields']);
        // Education remains a valid user choice, not a forced product default.
        if(isset($data['title']))$data['title']='Saved school admissions — '.$locale;
        $block['localized'][$locale]=$data;
    }
    $saved=PageBuilder::sanitizeBlocks([$block],$catalog,['en','km','zh'])[0];
    $check($saved['localized']===$block['localized']&&$saved['shared']===$block['shared'],'Saved values and media paths round-trip unchanged '.$type);
}
$check($catalog['gallery']['defaults']['items'][0]['image']==='','New galleries require the users own image');
foreach(['hero','hero-slider','gallery']as$type){
    $block=['uid'=>'12345678-1234-4234-8234-123456789abc','type'=>$type,'shared'=>$catalog[$type]['shared_defaults'],'localized'=>['en'=>$catalog[$type]['defaults']]];
    $reject(fn()=>PageBuilder::sanitizeBlocks([$block],$catalog,['en']),'Missing required media still rejected '.$type);
}
$empty=PageBuilder::catalog(['builder'=>['blocks'=>['qa-fields'=>['fields'=>[['key'=>'items','type'=>'repeater','min'=>1,'max'=>2,'fields'=>[['key'=>'image','type'=>'image','required'=>true]]]],'defaults'=>['items'=>[['image'=>'']]]]]]]);
$check(isset($empty['qa-fields']),'Blank nested required field permitted only in preset catalogue');
$reject(fn()=>PageBuilder::sanitizeBlocks([['uid'=>'12345678-1234-4234-8234-123456789abc','type'=>'qa-fields','localized'=>['en'=>['items'=>[['image'=>'']]]]]],$empty,['en']),'Theme-defined required fields remain enforced on save');
$reject(fn()=>PageBuilder::catalog(['builder'=>['blocks'=>['qa-bad'=>['fields'=>[['key'=>'image','type'=>'image']],'defaults'=>['image'=>'javascript:alert(1)']]]]]),'Unsafe preset URL still rejected');
$theme=json_decode(file_get_contents(dirname(__DIR__).'/.themes/sensecms/theme.json'),true,512,JSON_THROW_ON_ERROR);
$check(array_keys(PageBuilder::catalog($theme))===array_keys($catalog),'Official theme exposes every Core section');
$restricted=$theme;$restricted['supported_blocks']=['text'];
$check(array_keys(PageBuilder::catalog($restricted))===array_keys($catalog),'Theme metadata cannot remove portable Core sections');
$resolved=App\Core\ThemeContract::resolve('minimal',['minimal'=>['slug'=>'minimal','contract_version'=>1,'version'=>'1.0.0','release_channel'=>'stable','_path'=>dirname(__DIR__).'/.themes/sensecms','supported_blocks'=>['text']]]);
$check(array_slice($resolved['supported_blocks'],0,17)===array_keys($catalog),'Resolved theme contract advertises the complete Core standard');
$draftBlock=['uid'=>'12345678-1234-4234-8234-123456789abc','type'=>'hero','visible'=>true,'shared'=>$catalog['hero']['shared_defaults'],'localized'=>['en'=>array_replace($catalog['hero']['defaults'],['title'=>'Work in progress','image'=>'','video'=>''])]];
$draft=PageBuilder::sanitizeBlocks([$draftBlock],$catalog,['en'],true);
$check(($draft[0]['localized']['en']['title']??'')==='Work in progress','Recovery draft preserves incomplete in-progress content');
$unsafe=$draftBlock;$unsafe['localized']['en']['image']='javascript:alert(1)';
$reject(fn()=>PageBuilder::sanitizeBlocks([$unsafe],$catalog,['en'],true),'Recovery draft rejects executable media URLs');
$migration=(string)file_get_contents(dirname(__DIR__).'/.cms/source/database/workspace/032_page_builder_drafts.sql');
$check(str_contains($migration,'PRIMARY KEY (page_id, user_id)')&&str_contains($migration,'base_version'),'Recovery drafts are private per user and version-bound');
$repository=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/Core/CmsRepository.php');
$check(str_contains($repository,'function saveBuilderDraft')&&str_contains($repository,"DELETE FROM page_builder_drafts WHERE page_id=? AND user_id=?"),'Manual page save clears only the current users recovery draft');
$view=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/Views/console-page-builder.php');
$check(str_contains($view,'data-builder-undo')&&str_contains($view,'data-builder-recovery-dialog'),'Builder exposes editing history and explicit recovery choice');
$script=(string)file_get_contents(dirname(__DIR__).'/.cms/source/public/theme/sensecms-page-builder.js');
$check(str_contains($script,'function applyHistory')&&str_contains($script,'function flushDraft')&&str_contains($script,"addEventListener('pagehide'"),'Builder provides Undo Redo and close-tab recovery autosave');
$navigation=(string)file_get_contents(dirname(__DIR__).'/.cms/source/public/theme/sensecms-content-management.js');
$check(str_contains($navigation,'async function pageBuilder()')&&str_contains($navigation,'sensecms-page-builder.js?v=20260921-ai-1'),'AJAX content navigation loads and rehydrates Page Builder safely');
$console=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/Views/console.php');
$searchIndex=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/Core/ConsoleSearchIndex.php');
$check(str_contains($console,"if(\$can('content.pages.collaborate'))")&&str_contains($searchIndex,"'content.pages.collaborate'"),'Reviewers can discover and open Page Builder through its collaboration permission');
$style=(string)file_get_contents(dirname(__DIR__).'/.cms/source/public/theme/sensecms-page-builder.css');
$check(str_contains($style,'[data-builder-global-library] .sensecms-builder-library-item{grid-template-columns:34px minmax(0,1fr) auto')&&str_contains($style,'overflow-x:hidden;overflow-y:auto'),'Shared section library keeps content and actions inside its responsive panel');
$clipboardMigration=(string)file_get_contents(dirname(__DIR__).'/.cms/source/database/workspace/033_page_builder_clipboard.sql');
$check(str_contains($clipboardMigration,'user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY')&&str_contains($clipboardMigration,'blocks_json JSON NOT NULL'),'Section clipboard is private per user and persists sanitized sections server-side');
$check(str_contains($repository,'function saveBuilderClipboard')&&str_contains($repository,'count($blocks)>20')&&str_contains($repository,'strlen($json)>2_000_000'),'Section clipboard enforces bounded count and payload size');
$controller=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/Http/DashboardController.php');
$check(str_contains($controller,'function copyPageBuilderSections')&&str_contains($controller,'$block[\'global_section_id\']=null')&&str_contains($controller,'PageBuilder::sanitizeBlocks($raw,$catalog,$locales,true)'),'Copied sections are sanitized and detached from shared-section identity');
$check(str_contains($view,'data-library-tab="outline"')&&str_contains($view,'data-builder-copy-selected')&&str_contains($view,'data-builder-paste'),'Builder exposes the Core navigator and cross-page clipboard controls');
$check(str_contains($script,'function renderOutline()')&&str_contains($script,'function pasteClipboard()')&&str_contains($script,'60-blocks.length')&&str_contains($script,'copy.uid=uuid()'),'Navigator pastes fresh independent sections without exceeding the Core page limit');
$check(str_contains($view,'data-library-tab="patterns"')&&str_contains($view,'data-builder-patterns'),'Builder exposes the Core pattern library alongside sections and shared content');
$check(str_contains($script,'function renderPatterns()')&&str_contains($script,'function insertPattern(pattern)')&&str_contains($script,'plan.types.map(freshBlock)'),'Pattern insertion creates ordinary independent sections through the standard builder model');
$presets=PageBuilder::layoutPresets();
$check(array_column($presets,'key')===['container','columns-50','columns-33','columns-25','grid','stack','sidebar-left','sidebar-right','full-width'],'Core exposes the complete controlled layout preset catalogue');
$defaultLayout=PageBuilder::sanitizeLayout(['mode'=>'unsafe','container'=>'unsafe','desktop'=>['span'=>99,'order'=>-99,'hidden'=>true]]);
$check($defaultLayout['mode']==='stack'&&$defaultLayout['container']==='content'&&$defaultLayout['desktop']===['span'=>12,'order'=>-20,'hidden'=>true],'Layout input fails closed and bounds responsive values');
$layoutUid='22345678-1234-4234-8234-123456789abc';$layoutGroup='32345678-1234-4234-8234-123456789abc';
$layoutBlock=static fn(string$uid,?string$group,array$layout=[]):array=>['uid'=>$uid,'type'=>'text','visible'=>true,'layout'=>array_replace_recursive(['group'=>$group],$layout),'shared'=>$catalog['text']['shared_defaults'],'localized'=>['en'=>$catalog['text']['defaults']]];
$grouped=PageBuilder::sanitizeBlocks([$layoutBlock($layoutUid,$layoutGroup,['mode'=>'columns','container'=>'wide','desktop'=>['span'=>4]]),$layoutBlock('42345678-1234-4234-8234-123456789abc',$layoutGroup,['mode'=>'grid','container'=>'full','desktop'=>['span'=>8]])],$catalog,['en']);
$check($grouped[0]['layout']['group']===$layoutGroup&&$grouped[1]['layout']['mode']==='columns'&&$grouped[1]['layout']['container']==='wide'&&$grouped[1]['layout']['desktop']['span']===8,'Consecutive layout members keep independent spans and normalized group settings');
$single=PageBuilder::sanitizeBlocks([$layoutBlock($layoutUid,$layoutGroup,['mode'=>'columns'])],$catalog,['en']);
$check($single[0]['layout']['group']===null&&$single[0]['layout']['mode']==='stack','Orphaned layout groups safely become independent stack sections');
$reject(fn()=>PageBuilder::sanitizeBlocks([$layoutBlock($layoutUid,$layoutGroup),$layoutBlock('52345678-1234-4234-8234-123456789abc',null),$layoutBlock('62345678-1234-4234-8234-123456789abc',$layoutGroup)],$catalog,['en']),'Non-consecutive layout groups are rejected');
$layoutMigration=(string)file_get_contents(dirname(__DIR__).'/.cms/source/database/workspace/034_page_builder_layouts.sql');
$check(str_contains($layoutMigration,'ADD COLUMN IF NOT EXISTS layout JSON NULL'),'Responsive layout metadata uses an additive page-local JSON column');
$check(str_contains($repository,'settings=?,layout=?')&&str_contains($repository,"'layout'=>PageBuilder::sanitizeLayout"),'Repository persists and normalizes layout independently from shared section content');
$check(str_contains($view,'data-library-tab="layouts"')&&str_contains($view,'data-builder-layout-dialog'),'Builder exposes layout presets and per-section responsive settings');
$check(str_contains($view,'data-builder-view="live"')&&str_contains($view,'data-builder-live-frame')&&str_contains($view,'data-library-tab="inspector"'),'Builder exposes the inline Live Canvas and Core Inspector');
$check(str_contains($script,'function switchBuilderView')&&str_contains($script,'function renderInspector')&&str_contains($script,'sensecms-builder-select'),'Live Canvas selects theme-rendered sections and edits them through the standard Builder model');
$preview=(string)file_get_contents(dirname(__DIR__).'/.cms/source/public/theme/sensecms-builder-preview.js');
$check(str_contains($preview,'sensecms-builder-ready')&&str_contains($preview,'sensecms-builder-action'),'Core preview bridge supports selection and safe quick actions');
$public=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/Http/PublicController.php');
$check(str_contains($public,'function builderPreview')&&str_contains($public,'builderDraft($pageId, $userId)')&&str_contains($public,"header('Cache-Control: private, no-store')"),'Live preview is authenticated, private and sourced from the current editors recovery draft');
$workspace=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/workspace.php');
$check(str_contains($workspace,"/live-preview$#")&&str_contains($workspace,'$auth->id()'),'Workspace routes Live Canvas through the authenticated current user');
$front=(string)file_get_contents(dirname(__DIR__).'/.cms/source/public/index.php');
$check(str_contains($front,"#^/content/builder/[1-9][0-9]*/live-preview$#D")&&str_contains($front,'$sameOriginFrame ? "\'self\'" : "\'none\'"'),'Only the authenticated Live Canvas route permits same-origin framing');
$previewBlocks=PageBuilder::previewBlocks([$grouped[0]],'en','en');
$check(($previewBlocks[0]['uid']??'')===$layoutUid&&($previewBlocks[0]['payload']??[])===$catalog['text']['defaults']&&!empty($previewBlocks[0]['builder_preview']),'Core converts sanitized sections to the portable private preview contract');
$check(str_contains($script,'function applyLayoutPreset')&&str_contains($script,'function openLayout')&&str_contains($script,'function blockUnits'),'Layout groups use controlled presets, responsive settings and atomic reordering');
$appearance=PageBuilder::sanitizeAppearance(['variant'=>'card','surface'=>'soft','spacing'=>'unsafe','radius'=>'large','align'=>'center','css'=>'display:none']);
$check($appearance===['variant'=>'card','surface'=>'soft','spacing'=>'default','radius'=>'large','align'=>'center'],'Section appearance accepts only portable Core tokens and ignores arbitrary CSS');
$appearanceMigration=(string)file_get_contents(dirname(__DIR__).'/.cms/source/database/workspace/035_page_builder_appearance.sql');
$check(str_contains($appearanceMigration,'ADD COLUMN IF NOT EXISTS appearance JSON NULL'),'Section appearance uses an additive page-local JSON column');
$check(str_contains($repository,'layout=?,appearance=?')&&str_contains($repository,"'appearance'=>PageBuilder::sanitizeAppearance"),'Repository persists and normalizes appearance independently from content and layout');
$check(str_contains($view,"'appearance'=>\$builderAppearance")&&str_contains($script,'function appearanceGroup')&&str_contains($script,'Portable Core styles'),'Core Inspector exposes controlled portable section appearance');
$themeBlocks=(string)file_get_contents(dirname(__DIR__).'/.themes/sensecms/views/blocks.php');
$themeStyle=(string)file_get_contents(dirname(__DIR__).'/.themes/sensecms/assets/site.css');
$check(str_contains($themeBlocks,'PageBuilder::sanitizeAppearance')&&str_contains($themeStyle,'.sense-layout-item.sense-variant-card'),'Theme maps portable appearance tokens through its presentation layer');
$qualityBlock=$draftBlock;$qualityBlock['visible']=false;$qualityBlock['localized']['en']['image']='/media/quality.webp';$qualityBlock['localized']['en']['image_alt']='';
$qualityDraft=PageBuilder::sanitizeBlocks([$qualityBlock],$catalog,['en'],true);
$quality=PageBuilder::qualityReport($qualityDraft,$catalog,[['locale'=>'en','native_name'=>'English']],['translations'=>['en'=>['title'=>'','slug'=>'','seo_title'=>'','seo_description'=>'']],'media'=>['/media/quality.webp'=>['size_bytes'=>3_145_728,'mime_type'=>'image/webp']]]);
$qualityCodes=array_column($quality['issues'],'code');
$check(!$quality['ready']&&in_array('page-title',$qualityCodes,true)&&in_array('no-visible-sections',$qualityCodes,true)&&in_array('image-alt',$qualityCodes,true)&&in_array('heavy-image',$qualityCodes,true),'Quality Inspector finds blocking metadata, visibility, accessibility and media-performance issues');
$check(PageBuilder::mediaPaths($qualityDraft,$catalog)===['/media/quality.webp'],'Quality Inspector extracts only typed local media references for bounded metadata lookup');
$qualityReady=PageBuilder::qualityReport(PageBuilder::sanitizeBlocks([$layoutBlock($layoutUid,null)],$catalog,['en'],true),$catalog,[['locale'=>'en','native_name'=>'English']],['translations'=>['en'=>['title'=>'A concise page title','slug'=>'quality','seo_title'=>'A concise SEO title','seo_description'=>'A clear and useful search description.']]]);
$check($qualityReady['ready']&&$qualityReady['counts']['error']===0,'Quality Inspector keeps a complete portable draft publishable');
$check(str_contains($view,'data-library-tab="quality"')&&str_contains($view,'data-builder-quality-open')&&str_contains($script,'function loadQuality')&&str_contains($script,'function renderQuality'),'Builder exposes the live Core Quality Inspector and direct issue navigation');
$check(str_contains($controller,'function inspectPageBuilder')&&str_contains($workspace,"/(\\d+)/quality$#"),'Authenticated Builder route inspects the current unsaved draft without a database write');
$mediaLibrary=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/Core/MediaLibrary.php');
$check(str_contains($mediaLibrary,'function qualityMetadata')&&str_contains($mediaLibrary,"array_slice")&&str_contains($mediaLibrary,"m.status=\"active\""),'Media performance checks use bounded, scoped active-library metadata');
$guard=(string)file_get_contents(dirname(__DIR__).'/.cms/source/public/theme/sensecms-unsaved-guard.js');
$check(str_contains($guard,'confirmLeave:open')&&!str_contains($guard,'if(url.href===location.href)return')&&str_contains($script,'guard?.confirmLeave'),'Internal Page Builder navigation consistently uses the styled Core unsaved-changes dialog');
$collection=$catalog['news'];
$check($collection['label']==='Dynamic collection'&&array_column($collection['shared_fields'],'type')===['select','select','content-select','content-multiselect','select','number','select','checkbox','checkbox','checkbox'],'Legacy news identity now exposes the complete portable collection contract');
$collectionBlock=['uid'=>'72345678-1234-4234-8234-123456789abc','type'=>'news','visible'=>true,'shared'=>array_replace($collection['shared_defaults'],['selection'=>'selected','category_id'=>'12','selected_ids'=>[7,'7',-1,9,0]]),'localized'=>['en'=>$collection['defaults']]];
$collectionSaved=PageBuilder::sanitizeBlocks([$collectionBlock],$catalog,['en'])[0];
$check($collectionSaved['shared']['category_id']==='12'&&$collectionSaved['shared']['selected_ids']===[7,9],'Collection filters retain only bounded positive unique content identifiers');
$check(str_contains($repository,'function builderCollectionOptions')&&str_contains($repository,'function hydratePageCollections')&&str_contains($repository,"p.visibility='public'")&&str_contains($repository,"m.status='active'"),'Collection resolver is facility-scoped, publication-aware and uses active media only');
$check(str_contains($view,"'collection_options'=>\$builderCollections")&&str_contains($script,'function contentMultiselectNode')&&str_contains($script,"collectionOptions.sources?.[source]?.items"),'Builder exposes searchable source-aware collection selection without theme-owned data logic');
$check(str_contains($public,'hydratePageCollections')&&str_contains($themeBlocks,"\$block['collection']['items']")&&str_contains($themeStyle,'.sense-block-news.is-list'),'Public requests hydrate live collection data and the theme presents every supported layout');
$collaborationMigration=(string)file_get_contents(dirname(__DIR__).'/.cms/source/database/workspace/036_page_builder_collaboration.sql');
$check(str_contains($collaborationMigration,'page_builder_section_workflow')&&str_contains($collaborationMigration,'page_builder_section_comments')&&str_contains($collaborationMigration,'page_builder_section_locks'),'Collaboration schema separates workflow, durable discussion and expiring edit locks');
$check(str_contains($collaborationMigration,'content.pages.collaborate')&&str_contains($collaborationMigration,"('content-manager','editor','reviewer')"),'Editors and reviewers receive a dedicated least-privilege Builder collaboration permission');
$access=(string)file_get_contents(dirname(__DIR__).'/.cms/source/app/Core/AccessControl.php');
$check(str_contains($access,'function builderCollaborators')&&str_contains($access,"return'content.pages.collaborate'")&&str_contains($access,'revisions/compare'),'Builder collaboration is facility-scoped and routed separately from content editing');
$check(str_contains($repository,'function builderCollaboration')&&str_contains($repository,'function acquireBuilderSectionLock')&&str_contains($repository,"expires_at>NOW() FOR UPDATE")&&str_contains($repository,'DATE_ADD(NOW(),INTERVAL ')&&str_contains($repository,'is editing this section'),'Repository uses database-timed expiring section locks instead of cosmetic browser state or PHP timezone assumptions');
$check(str_contains($repository,'function addBuilderSectionComment')&&str_contains($repository,'function resolveBuilderSectionComment')&&str_contains($repository,'builder_assignment'),'Section discussions retain resolution history and assignments notify the selected collaborator');
$check(str_contains($controller,'function savePageBuilderSectionWorkflow')&&str_contains($controller,'Only a reviewer can approve a section')&&str_contains($controller,'function comparePageBuilderRevisions'),'Approval remains reviewer-gated and revision comparison is an authenticated Core endpoint');
$check(str_contains($workspace,'/collaboration$#')&&str_contains($workspace,'/sections/([a-f0-9-]+)/lock$#')&&str_contains($workspace,'/revisions/compare$#'),'Workspace exposes bounded collaboration, locking and comparison routes');
$check(str_contains($view,'data-library-tab="review"')&&str_contains($view,'data-builder-review')&&str_contains($view,'data-builder-compare'),'Builder provides a coherent Review workspace and two-version comparison UI');
$check(str_contains($script,'function renderReview()')&&str_contains($script,'function reserveSection')&&str_contains($script,'function syncCollaboration')&&str_contains($script,'function compareRevisions'),'Builder refreshes collaboration state, owns one expiring edit lock and compares revisions without reload');
$before=['blocks'=>[$layoutBlock($layoutUid,null),$layoutBlock('82345678-1234-4234-8234-123456789abc',null)]];
$after=$before;$after['blocks'][0]['localized']['en']['title']='Changed section title';$after['blocks']=[$after['blocks'][1],$after['blocks'][0],$layoutBlock('92345678-1234-4234-8234-123456789abc',null)];
$diff=PageBuilder::revisionDiff($before,$after,$catalog);
$check($diff['summary']['added']===1&&$diff['summary']['removed']===0&&$diff['summary']['moved']===2&&$diff['summary']['changed']===2&&!$diff['empty'],'Revision comparison reports added, moved and field-level changed sections by stable UID');
$detail=implode(' ',array_merge(...array_column($diff['changes'],'details')));
$check(str_contains($detail,'Position 1 → 2')&&str_contains($detail,'EN content: Headline'),'Revision history names precise position and localized field changes without exposing raw snapshots');
echo "$count builder preset/compatibility checks passed; no database or network writes.\n";
