<?php
declare(strict_types=1);

namespace SenseCMS\LinkedIn {
    function curl_init(string$url):object{return(object)['url'=>$url,'options'=>[],'status'=>0];}
    function curl_setopt_array(object$curl,array$options):bool{$curl->options=$options;return true;}
    function curl_exec(object$curl):bool{$GLOBALS['linkedin_requests'][]=$curl;$next=array_shift($GLOBALS['linkedin_responses']);if(!$next)throw new \RuntimeException('Unexpected LinkedIn request.');$curl->status=$next[0];foreach((array)($next[2]??[])as$name=>$value)($curl->options[CURLOPT_HEADERFUNCTION])($curl,$name.': '.$value."\r\n");$body=is_array($next[1])?json_encode($next[1]):$next[1];return($curl->options[CURLOPT_WRITEFUNCTION])($curl,$body)===strlen($body);}
    function curl_error(object$curl):string{return'';}
    function curl_getinfo(object$curl,int$kind):int{return$curl->status;}
    function curl_close(object$curl):void{}
}
namespace {
    $provider=require dirname(__DIR__).'/.plugins/linkedin-publisher/src/provider.php';$checks=0;
    function linkedinCheck(bool$ok,string$label):void{global$checks;if(!$ok)throw new RuntimeException($label);$checks++;echo"PASS $label\n";}
    function linkedinRejects(callable$fn,string$label,?int$code=null):void{try{$fn();}catch(RuntimeException$error){linkedinCheck($code===null||$error->getCode()===$code,$label);return;}throw new RuntimeException($label);}
    function linkedinResponses(array$items):void{$GLOBALS['linkedin_responses']=$items;$GLOBALS['linkedin_requests']=[];}
    $render=static function(array$provider):string{$linkedinProvider=$provider;$linkedinOAuthRevision=3;$linkedinOAuthOutcome='success';$csrf='fixture-csrf';ob_start();require dirname(__DIR__).'/.plugins/linkedin-publisher/views/linkedin.php';return(string)ob_get_clean();};
    $disconnected=$render([]);linkedinCheck(str_contains($disconnected,'action="/social-publishing/linkedin/connect"')&&str_contains($disconnected,'data-linkedin-connect'),'LinkedIn OAuth connect exposes focused popup hook');linkedinCheck(str_contains($disconnected,'data-linkedin-oauth-modal')&&str_contains($disconnected,'aria-modal="true"'),'LinkedIn OAuth progress dialog is accessible');
    $connected=$render(['connections'=>[['id'=>7,'enabled'=>true,'display_name'=>'Sense CMS Owner','external_account_id'=>'member_A1','last_verified_at'=>'now'],['id'=>8,'enabled'=>true,'display_name'=>'Second Profile','external_account_id'=>'member_B2','last_verified_at'=>'later']]]);linkedinCheck(str_contains($connected,'/social-publishing/linkedin/connections/7/disconnect')&&str_contains($connected,'/social-publishing/linkedin/connections/8/disconnect'),'each LinkedIn profile has an independent disconnect action');linkedinCheck(substr_count($connected,'class="social-account-card"')===2&&str_contains($connected,'Add LinkedIn profile'),'LinkedIn settings list multiple profiles and retain add action');
    $popup=(string)file_get_contents(dirname(__DIR__).'/.plugins/linkedin-publisher/assets/linkedin.js');linkedinCheck(str_contains($popup,"window.open('about:blank',popupName")&&str_contains($popup,"event.origin!==location.origin")&&str_contains($popup,"url.pathname!=='/api/social/linkedin/v1/authorize'"),'LinkedIn OAuth popup validates message origin and broker destination');linkedinCheck(str_contains($popup,"if(window.name!==popupName)return false")&&str_contains($popup,'if(window.opener&&!window.opener.closed)')&&str_contains($popup,'window.close()'),'LinkedIn OAuth popup closes after a provider-isolated return without requiring its opener');
    $credentials=['member_id'=>'member_A1','name'=>'Sense CMS Owner','access_token'=>'access-'.str_repeat('a',40),'expires_at'=>time()+3600];$payload=['message'=>'A reviewed professional story','title'=>'Article title','excerpt'=>'Article description','url'=>'https://example.test/en/posts/story','image_url'=>null];
    linkedinResponses([[200,['sub'=>'member_A1','name'=>'Sense CMS Owner']]]);$verified=$provider->verify($credentials);linkedinCheck($verified['external_id']==='member_A1'&&$verified['display_name']==='Sense CMS Owner','LinkedIn member identity verified');$request=$GLOBALS['linkedin_requests'][0];linkedinCheck($request->url==='https://api.linkedin.com/v2/userinfo'&&in_array('Authorization: Bearer '.$credentials['access_token'],$request->options[CURLOPT_HTTPHEADER],true),'LinkedIn identity uses fixed endpoint and bearer token');
    linkedinResponses([[201,[],['X-RestLi-Id'=>'urn:li:share:1987654321098765']]]);$published=$provider->publish($credentials,$payload);linkedinCheck($published['external_id']==='urn:li:share:1987654321098765'&&$published['external_url']==='https://www.linkedin.com/feed/update/urn:li:share:1987654321098765','LinkedIn publication identity and canonical URL accepted');$request=$GLOBALS['linkedin_requests'][0];$body=json_decode((string)$request->options[CURLOPT_POSTFIELDS],true);$content=$body['specificContent']['com.linkedin.ugc.ShareContent'];linkedinCheck($request->url==='https://api.linkedin.com/v2/ugcPosts'&&$body['author']==='urn:li:person:member_A1'&&$content['shareCommentary']['text']==='A reviewed professional story'&&$content['media'][0]['originalUrl']==='https://example.test/en/posts/story','LinkedIn article share contains reviewed message and canonical URL');linkedinCheck(in_array('X-Restli-Protocol-Version: 2.0.0',$request->options[CURLOPT_HTTPHEADER],true),'LinkedIn publication uses required Rest.li protocol header');
    linkedinResponses([]);linkedinRejects(fn()=>$provider->publish(array_replace($credentials,['member_id'=>'bad id']),$payload),'invalid LinkedIn credentials rejected before network');linkedinCheck(!$GLOBALS['linkedin_requests'],'invalid LinkedIn credentials send no request');linkedinRejects(fn()=>$provider->publish(array_replace($credentials,['expires_at'=>time()]),$payload),'expired LinkedIn credential fails closed');linkedinRejects(fn()=>$provider->publish($credentials,array_replace($payload,['url'=>'http://example.test/story'])),'non-HTTPS LinkedIn destination rejected');
    linkedinResponses([[429,['message'=>'limit']]]);linkedinRejects(fn()=>$provider->publish($credentials,$payload),'LinkedIn rate limit remains a failure',429);linkedinResponses([[201,[],['X-RestLi-Id'=>'unsafe/id']]]);linkedinRejects(fn()=>$provider->publish($credentials,$payload),'unexpected LinkedIn publication identity rejected');
    echo"$checks LinkedIn Publisher protocol checks passed; no live LinkedIn requests.\n";
}
