<?php
declare(strict_types=1);

namespace SenseCMS\Mastodon {
    function dns_get_record(string$host,int$type):array{return$GLOBALS['mastodon_dns'][$host]??[];}
    function curl_init(string$url):object{return(object)['url'=>$url,'options'=>[],'status'=>0];}
    function curl_setopt_array(object$curl,array$options):bool{$curl->options=$options;return true;}
    function curl_exec(object$curl):bool{$GLOBALS['mastodon_requests'][]=$curl;$next=array_shift($GLOBALS['mastodon_responses']);if(!$next)throw new \RuntimeException('Unexpected Mastodon request.');$curl->status=$next[0];$body=is_array($next[1])?json_encode($next[1],JSON_UNESCAPED_SLASHES):$next[1];return($curl->options[CURLOPT_WRITEFUNCTION])($curl,$body)===strlen($body);}
    function curl_error(object$curl):string{return'';}function curl_getinfo(object$curl,int$kind):int{return$curl->status;}function curl_close(object$curl):void{}
}

namespace {
    require dirname(__DIR__).'/.plugins/mastodon-publisher/src/MastodonClient.php';
    $client=new SenseCMS\Mastodon\MastodonClient();$provider=require dirname(__DIR__).'/.plugins/mastodon-publisher/src/provider.php';$checks=0;
    function mastodonCheck(bool$ok,string$label):void{global$checks;if(!$ok)throw new RuntimeException($label);$checks++;echo"PASS $label\n";}
    function mastodonRejects(callable$fn,string$label,?int$code=null):void{try{$fn();}catch(RuntimeException$error){mastodonCheck($code===null||$error->getCode()===$code,$label);return;}throw new RuntimeException($label);}
    function mastodonResponses(array$items):void{$GLOBALS['mastodon_responses']=$items;$GLOBALS['mastodon_requests']=[];}
    $GLOBALS['mastodon_dns']=['social.example'=>[['ip'=>'93.184.216.34']],'private.example'=>[['ip'=>'127.0.0.1']]];
    $manifest=json_decode((string)file_get_contents(dirname(__DIR__).'/.plugins/mastodon-publisher/plugin.json'),true,32,JSON_THROW_ON_ERROR);$license=(array)($manifest['license']??[]);mastodonCheck(($license['price']??null)===15&&($license['currency']??'')==='USD'&&($license['billing_period']??'')==='year','Mastodon subscription is USD 15 per year');mastodonCheck(($license['product_name']??'')==='Sense CMS Mastodon Publisher Plugin'&&($license['product_model']??'')==='Mastodon Publisher Plugin'&&($license['product_version']??'')==='1.0','Mastodon uses its own fixed licence identity');
    $render=static function(array$provider):string{$mastodonProvider=$provider;$mastodonOAuthRevision=3;$mastodonOAuthOutcome='success';$csrf='fixture-csrf';ob_start();require dirname(__DIR__).'/.plugins/mastodon-publisher/views/mastodon.php';return(string)ob_get_clean();};
    $disconnected=$render([]);mastodonCheck(str_contains($disconnected,'data-mastodon-connect')&&str_contains($disconnected,'name="instance"')&&str_contains($disconnected,'value="mastodon.social"')&&str_contains($disconnected,'data-mastodon-oauth-modal'),'Mastodon server form defaults to mastodon.social and renders the accessible OAuth progress dialog');
    $connected=$render(['connections'=>[['id'=>9,'enabled'=>true,'display_name'=>'@alice@social.example','external_account_id'=>'social.example:101','last_verified_at'=>'now'],['id'=>10,'enabled'=>true,'display_name'=>'@bob@other.example','external_account_id'=>'other.example:202','last_verified_at'=>'later']]]);mastodonCheck(substr_count($connected,'class="social-account-card"')===2&&str_contains($connected,'/connections/9/disconnect')&&str_contains($connected,'Add Mastodon account'),'Mastodon settings manage multiple accounts and servers');
    $popup=(string)file_get_contents(dirname(__DIR__).'/.plugins/mastodon-publisher/assets/mastodon.js');mastodonCheck(str_contains($popup,"url.pathname!=='/oauth/authorize'")&&str_contains($popup,'url.origin!==origin.origin'),'Mastodon popup accepts only the selected HTTPS instance authorization endpoint');mastodonCheck(str_contains($popup,"if(window.name!==popupName)return false")&&str_contains($popup,'if(window.opener&&!window.opener.closed)')&&str_contains($popup,'window.close()'),'Mastodon OAuth popup closes after an isolated provider return');
    mastodonResponses([[200,['client_id'=>'client-'.str_repeat('c',24),'client_secret'=>'secret-'.str_repeat('s',32)]]]);$start=$client->begin('social.example','https://www.sensecms.com/social-publishing/mastodon/callback','https://www.sensecms.com');mastodonCheck(str_starts_with($start['authorize_url'],'https://social.example/oauth/authorize?')&&$start['pending']['origin']==='https://social.example','Mastodon app registered at the selected instance');$registration=$GLOBALS['mastodon_requests'][0];parse_str((string)$registration->options[CURLOPT_POSTFIELDS],$registrationFields);mastodonCheck($registrationFields['scopes']==='read:accounts write:statuses'&&$registrationFields['redirect_uris']==='https://www.sensecms.com/social-publishing/mastodon/callback','Mastodon registration requests only account-read and status-write scopes');$query=[];parse_str((string)parse_url($start['authorize_url'],PHP_URL_QUERY),$query);mastodonCheck($query['code_challenge_method']==='S256'&&strlen((string)$query['code_challenge'])===43&&$query['state']===$start['state'],'Mastodon authorization uses state and PKCE S256');mastodonCheck($registration->options[CURLOPT_FOLLOWLOCATION]===false&&$registration->options[CURLOPT_SSL_VERIFYPEER]===true&&in_array('social.example:443:93.184.216.34',$registration->options[CURLOPT_RESOLVE],true),'Mastodon request pins public DNS and refuses redirects');
    mastodonResponses([[200,['access_token'=>'token-'.str_repeat('t',48),'token_type'=>'Bearer','scope'=>'read:accounts write:statuses']],[200,['id'=>'101','username'=>'alice','acct'=>'alice','url'=>'https://social.example/@alice']]]);$finished=$client->finish($start['pending'],'authorization-code-value','https://www.sensecms.com/social-publishing/mastodon/callback');mastodonCheck($finished['external_id']==='social.example:101'&&$finished['display_name']==='@alice@social.example'&&$finished['credentials']['account_id']==='101','Mastodon authorization exchanges and verifies the selected account');$tokenRequest=$GLOBALS['mastodon_requests'][0];parse_str((string)$tokenRequest->options[CURLOPT_POSTFIELDS],$tokenFields);mastodonCheck($tokenFields['code_verifier']===$start['pending']['verifier']&&$tokenFields['client_secret']===$start['pending']['client_secret'],'Mastodon token exchange binds the registered client and PKCE verifier');
    mastodonResponses([[200,['id'=>'101','username'=>'alice','acct'=>'alice','url'=>'https://social.example/@alice']]]);$verified=$provider->verify($finished['credentials']);mastodonCheck($verified['external_id']==='social.example:101'&&$verified['display_name']==='@alice@social.example','Mastodon stored identity verifies before use');
    $payload=['post_id'=>77,'message'=>'A reviewed Sense CMS story','url'=>'https://www.sensecms.com/news/story','title'=>'Story','excerpt'=>'Summary'];mastodonResponses([[200,['id'=>'114381884422001','url'=>'https://social.example/@alice/114381884422001']]]);$published=$provider->publish($finished['credentials'],$payload);mastodonCheck($published['external_id']==='114381884422001'&&$published['external_url']==='https://social.example/@alice/114381884422001','Mastodon publication identity and same-instance URL accepted');$publishRequest=$GLOBALS['mastodon_requests'][0];parse_str((string)$publishRequest->options[CURLOPT_POSTFIELDS],$statusFields);$headers=$publishRequest->options[CURLOPT_HTTPHEADER];mastodonCheck($statusFields['status']==="A reviewed Sense CMS story\n\nhttps://www.sensecms.com/news/story"&&$statusFields['visibility']==='public'&&array_any($headers,static fn(string$header):bool=>str_starts_with($header,'Idempotency-Key: ')),'Mastodon publication sends reviewed text with an idempotency key');
    foreach(['localhost','127.0.0.1','https://social.example/path','http://social.example','https://user@social.example']as$unsafe)mastodonRejects(fn()=>$client->begin($unsafe,'https://www.sensecms.com/social-publishing/mastodon/callback','https://www.sensecms.com'),'Unsafe Mastodon instance rejected before network');mastodonRejects(fn()=>$client->begin('private.example','https://www.sensecms.com/social-publishing/mastodon/callback','https://www.sensecms.com'),'Private Mastodon DNS result rejected before network');mastodonCheck(count($GLOBALS['mastodon_requests'])===1,'Unsafe Mastodon origins send no additional request');
    mastodonResponses([]);mastodonRejects(fn()=>$provider->publish(array_replace($finished['credentials'],['instance'=>'https://social.example.evil.test']),$payload),'Modified Mastodon instance credentials rejected before network');mastodonRejects(fn()=>$provider->publish($finished['credentials'],array_replace($payload,['url'=>'http://www.sensecms.com/story'])),'Non-HTTPS Mastodon destination rejected before network');mastodonCheck($GLOBALS['mastodon_requests']===[],'Invalid Mastodon publication data sends no request');mastodonResponses([[429,['error'=>'Too many requests']]]);mastodonRejects(fn()=>$provider->publish($finished['credentials'],$payload),'Mastodon rate limit remains a retryable failure',429);
    echo"$checks Mastodon Publisher protocol checks passed; no live Mastodon requests.\n";
}
