<?php
declare(strict_types=1);

namespace SenseCMS\Pinterest {
    function curl_init(string$url):object{return(object)['url'=>$url,'options'=>[],'status'=>0];}
    function curl_setopt_array(object$curl,array$options):bool{$curl->options=$options;return true;}
    function curl_exec(object$curl):bool{$GLOBALS['pinterest_requests'][]=$curl;$next=array_shift($GLOBALS['pinterest_responses']);if(!$next)throw new \RuntimeException('Unexpected Pinterest request.');$curl->status=$next[0];$body=is_array($next[1])?json_encode($next[1]):$next[1];return($curl->options[CURLOPT_WRITEFUNCTION])($curl,$body)===strlen($body);}
    function curl_error(object$curl):string{return'';}
    function curl_getinfo(object$curl,int$kind):int{return$curl->status;}
    function curl_close(object$curl):void{}
}
namespace {
    $provider=require dirname(__DIR__).'/.plugins/pinterest-publisher/src/provider.php';$checks=0;
    function pinterestCheck(bool$ok,string$label):void{global$checks;if(!$ok)throw new RuntimeException($label);$checks++;echo"PASS $label\n";}
    function pinterestRejects(callable$fn,string$label,?int$code=null):void{try{$fn();}catch(RuntimeException$error){pinterestCheck($code===null||$error->getCode()===$code,$label);return;}throw new RuntimeException($label);}
    function pinterestResponses(array$items):void{$GLOBALS['pinterest_responses']=$items;$GLOBALS['pinterest_requests']=[];}
    $manifest=json_decode((string)file_get_contents(dirname(__DIR__).'/.plugins/pinterest-publisher/plugin.json'),true,32,JSON_THROW_ON_ERROR);$license=(array)($manifest['license']??[]);pinterestCheck(($license['price']??null)===15&&($license['currency']??'')==='USD'&&($license['billing_period']??'')==='year','Pinterest subscription is USD 15 per year');pinterestCheck(($license['product_name']??'')==='Sense CMS Pinterest Publisher Plugin'&&($license['product_model']??'')==='Pinterest Publisher Plugin'&&($license['product_version']??'')==='1.0','Pinterest uses its own fixed licence identity');
    $render=static function(array$provider):string{$pinterestProvider=$provider;$pinterestOAuthRevision=3;$pinterestOAuthOutcome='success';$csrf='fixture-csrf';ob_start();require dirname(__DIR__).'/.plugins/pinterest-publisher/views/pinterest.php';return(string)ob_get_clean();};$disconnected=$render([]);pinterestCheck(str_contains($disconnected,'action="/social-publishing/pinterest/connect"')&&str_contains($disconnected,'data-pinterest-connect'),'Pinterest OAuth connect exposes focused popup hook');pinterestCheck(str_contains($disconnected,'data-pinterest-oauth-modal')&&str_contains($disconnected,'public HTTPS featured image is required'),'Pinterest screen explains popup flow and required image');pinterestCheck(str_contains($disconnected,'class="social-empty social-connect-empty"')&&str_contains($disconnected,'class="social-steps"')&&str_contains($disconnected,'class="social-panel-footer"'),'Pinterest settings reuse the shared Social Publishing empty, workflow and note components');$connected=$render(['connections'=>[['id'=>7,'display_name'=>'@sensecms · News','external_account_id'=>'9001','last_verified_at'=>'now'],['id'=>8,'display_name'=>'@second · Ideas','external_account_id'=>'9002','last_verified_at'=>'later']]]);pinterestCheck(substr_count($connected,'class="social-account-card"')===2&&substr_count($connected,'class="social-account-meta"')===2&&substr_count($connected,'class="btn social-disconnect"')===2&&str_contains($connected,'/connections/7/disconnect')&&str_contains($connected,'Add Pinterest board'),'Pinterest settings manage multiple boards with shared metadata and actions');
    $popup=(string)file_get_contents(dirname(__DIR__).'/.plugins/pinterest-publisher/assets/pinterest.js');pinterestCheck(str_contains($popup,"window.open('about:blank',popupName")&&str_contains($popup,"event.origin!==location.origin")&&str_contains($popup,"url.pathname!=='/api/social/pinterest/v1/authorize'"),'Pinterest OAuth popup validates message origin and broker destination');pinterestCheck(str_contains($popup,"if(window.name!==popupName)return false")&&str_contains($popup,'window.close()'),'Pinterest OAuth popup closes after provider return');
    $credentials=['user_id'=>'123456789','username'=>'sensecms','board_id'=>'9001','board_name'=>'News','access_token'=>'access-'.str_repeat('a',40),'refresh_token'=>'refresh-'.str_repeat('r',40),'expires_at'=>time()+3600,'refresh_expires_at'=>time()+86400];$payload=['message'=>'A reviewed visual story','title'=>'Article title','url'=>'https://example.test/en/posts/story','image_url'=>'https://example.test/storage/story.jpg'];
    pinterestResponses([[200,['id'=>'9001','name'=>'Sense CMS News','owner'=>['username'=>'sensecms']]]]);$verified=$provider->verify($credentials);pinterestCheck($verified['external_id']==='9001'&&$verified['display_name']==='@sensecms · Sense CMS News','Pinterest board identity verified');$request=$GLOBALS['pinterest_requests'][0];pinterestCheck($request->url==='https://api.pinterest.com/v5/boards/9001'&&in_array('Authorization: Bearer '.$credentials['access_token'],$request->options[CURLOPT_HTTPHEADER],true),'Pinterest identity uses fixed board endpoint and bearer token');
    pinterestResponses([[201,['id'=>'765432109876543210','board_id'=>'9001']]]);$published=$provider->publish($credentials,$payload);pinterestCheck($published['external_id']==='765432109876543210'&&$published['external_url']==='https://www.pinterest.com/pin/765432109876543210/','Pinterest publication identity and canonical URL accepted');$request=$GLOBALS['pinterest_requests'][0];$body=json_decode((string)$request->options[CURLOPT_POSTFIELDS],true);pinterestCheck($request->url==='https://api.pinterest.com/v5/pins'&&$body['board_id']==='9001'&&$body['title']==='Article title'&&$body['description']==='A reviewed visual story'&&$body['link']==='https://example.test/en/posts/story'&&$body['media_source']['source_type']==='image_url'&&$body['media_source']['url']==='https://example.test/storage/story.jpg','Pinterest image Pin contains board, reviewed content and canonical link');
    pinterestResponses([]);pinterestRejects(fn()=>$provider->publish(array_replace($credentials,['board_id'=>'bad']),$payload),'invalid Pinterest credentials rejected before network');pinterestCheck(!$GLOBALS['pinterest_requests'],'invalid Pinterest credentials send no request');pinterestRejects(fn()=>$provider->publish($credentials,array_replace($payload,['image_url'=>null])),'Pinterest post without public image fails closed');pinterestRejects(fn()=>$provider->publish($credentials,array_replace($payload,['url'=>'http://example.test/story'])),'non-HTTPS Pinterest destination rejected');pinterestRejects(fn()=>$provider->publish($credentials,array_replace($payload,['image_url'=>'https://user:pass@example.test/private.jpg'])),'credential-bearing Pinterest image URL rejected');pinterestResponses([[429,['message'=>'limit']]]);pinterestRejects(fn()=>$provider->publish($credentials,$payload),'Pinterest rate limit remains a failure',429);
    echo"$checks Pinterest Publisher protocol checks passed; no live Pinterest requests.\n";
}
