<?php

declare(strict_types=1);

require dirname(__DIR__).'/.cms/source/bootstrap.php';
require dirname(__DIR__).'/.src/PinterestBrokerService.php';
require dirname(__DIR__).'/.src/PinterestOAuthEndpoint.php';

use SenseCMS\Website\PinterestBrokerService;
use SenseCMS\Website\PinterestOAuthEndpoint;

$root=sys_get_temp_dir().'/sensecms-pinterest-test-'.bin2hex(random_bytes(8));if(!mkdir($root,0700))throw new RuntimeException('Cannot create private Pinterest fixture.');
$key=random_bytes(32);$access='access-'.str_repeat('a',40);$refresh='refresh-'.str_repeat('r',40);$calls=[];$count=0;$cfg=['client_id'=>'fixture-client-id','client_secret'=>'fixture-client-secret-'.str_repeat('s',20)];
$http=static function(string$method,string$url,array$headers,string$payload)use(&$calls,$access,$refresh):array{
    $calls[]=[$method,$url,$headers,$payload];
    if($url==='https://www.chivale.com/license/'){parse_str($payload,$form);if(($form['LicenseKey']??'')!==str_repeat('K',32))return[403,'{"error":true}'];return[200,json_encode(['error'=>false,'data'=>['product'=>['name'=>'Sense CMS','model'=>'Sense CMS System','version'=>'1.0'],'valid_from'=>null,'valid_to'=>null]])];}
    if($url==='https://api.pinterest.com/v5/oauth/token')return[200,json_encode(['access_token'=>$access,'refresh_token'=>$refresh,'token_type'=>'bearer','expires_in'=>2592000,'refresh_token_expires_in'=>5184000,'scope'=>'boards:read,pins:read,pins:write,user_accounts:read'])];
    if($url==='https://api.pinterest.com/v5/user_account')return[200,'{"id":"123456789","username":"sensecms"}'];
    if($url==='https://api.pinterest.com/v5/boards?page_size=250')return[200,'{"items":[{"id":"9001","name":"Sense CMS News"},{"id":"9002","name":"Product ideas"}],"bookmark":null}'];
    throw new RuntimeException('Unexpected fixture URL '.$url);
};
$broker=new PinterestBrokerService($root,$key,$cfg,$http);$server=['HTTP_AUTHORIZATION'=>'Bearer '.str_repeat('K',32),'HTTP_X_SENSECMS_DOMAIN'=>'https://tenant.example'];$other=array_replace($server,['HTTP_X_SENSECMS_DOMAIN'=>'https://other.example']);
$check=static function(bool$ok,string$label)use(&$count):void{if(!$ok)throw new RuntimeException($label);$count++;echo"PASS $label\n";};
$reject=static function(callable$fn,int$code,string$label)use($check):void{try{$fn();}catch(RuntimeException$error){$check($error->getCode()===$code&&!str_contains($error->getMessage(),'access-'),' '.$label);return;}throw new RuntimeException($label);};
$requestToken=static function(array$start):string{parse_str((string)parse_url($start['authorize_url'],PHP_URL_QUERY),$query);return(string)($query['request']??'');};
try{
    $check($broker->ready(),'configured Pinterest broker ready');$reject(fn()=>(new PinterestBrokerService($root,$key,[],$http))->start($server,[]),503,'missing Pinterest app credentials fail closed');
    $reject(fn()=>$broker->start([],['return_url'=>'https://tenant.example/social-publishing/pinterest/callback']),401,'installation licence required');$reject(fn()=>$broker->start($server,['return_url'=>'https://evil.example/social-publishing/pinterest/callback']),422,'return URL bound to installation');
    $start=$broker->start($server,['return_url'=>'https://tenant.example/social-publishing/pinterest/callback']);$request=$requestToken($start);$check(strlen($request)===43&&$start['expires_in']===600,'short-lived Pinterest authorization request');
    $authorize=$broker->authorize($request);parse_str((string)parse_url($authorize,PHP_URL_QUERY),$query);$check(str_starts_with($authorize,'https://www.pinterest.com/oauth/?')&&$query['client_id']===$cfg['client_id']&&$query['redirect_uri']==='https://www.sensecms.com/api/social/pinterest/v1/callback'&&$query['scope']==='boards:read,pins:read,pins:write,user_accounts:read'&&$query['state']===$request,'Pinterest authorization uses minimum board publishing scopes');
    $selectionUrl=$broker->callback(['state'=>$request,'code'=>'fixture-code']);parse_str((string)parse_url($selectionUrl,PHP_URL_QUERY),$selectionQuery);$selection=(string)($selectionQuery['request']??'');$check(str_starts_with($selectionUrl,'https://www.sensecms.com/api/social/pinterest/v1/select?request=')&&strlen($selection)===43,'Pinterest callback opens opaque board selection');$tokenCall=array_values(array_filter($calls,static fn(array$call):bool=>$call[1]==='https://api.pinterest.com/v5/oauth/token'))[0]??[];parse_str((string)($tokenCall[3]??''),$tokenForm);$check(($tokenForm['continuous_refresh']??'')==='true','Pinterest requests indefinitely refreshable continuous authorization');
    $reject(fn()=>$broker->callback(['state'=>$request,'code'=>'fixture-code']),410,'Pinterest OAuth state is single-use');$form=$broker->selectionForm($selection);$check(str_contains($form,'Sense CMS News')&&str_contains($form,'Product ideas')&&substr_count($form,'name="board_id"')===2,'Pinterest selection lists discovered boards without credentials');preg_match('/name="csrf" value="([A-Za-z0-9_-]{43})"/',$form,$csrf);$redirect=$broker->select(['request'=>$selection,'csrf'=>$csrf[1]??'','board_id'=>'9002']);parse_str((string)parse_url($redirect,PHP_URL_QUERY),$claimQuery);$claim=(string)($claimQuery['claim']??'');$check(str_starts_with($redirect,'https://tenant.example/social-publishing/pinterest/callback?claim=')&&strlen($claim)===43,'selected Pinterest board returns opaque installation claim');
    $reject(fn()=>$broker->claim($other,$claim),403,'Pinterest claim bound to licensed installation');$credential=$broker->claim($server,$claim);$check($credential['user_id']==='123456789'&&$credential['username']==='sensecms'&&$credential['board_id']==='9002'&&$credential['board_name']==='Product ideas'&&$credential['access_token']===$access&&$credential['refresh_token']===$refresh&&$credential['refresh_expires_at']>time(),'one-time Pinterest board credential claimed by correct installation');$reject(fn()=>$broker->claim($server,$claim),410,'claimed Pinterest credential is deleted');
    $tokens=$broker->refresh($server,$refresh);$check($tokens['access_token']===$access&&$tokens['refresh_token']===$refresh&&$tokens['expires_at']>time()&&$tokens['refresh_expires_at']>time(),'Pinterest refresh rotates a bounded credential pair');
    $cancel=$broker->start($server,['return_url'=>'https://tenant.example/social-publishing/pinterest/callback']);$cancelRequest=$requestToken($cancel);$check($broker->callback(['state'=>$cancelRequest,'error'=>'access_denied'])==='https://tenant.example/social-publishing/pinterest/callback','cancelled Pinterest login returns without claim');
    $raw='';foreach(glob($root.'/storage/*.json')?:[]as$file)$raw.=file_get_contents($file);$check(!str_contains($raw,$cfg['client_secret'])&&!str_contains($raw,$access)&&!str_contains($raw,$refresh)&&!str_contains($raw,str_repeat('K',32)),'Pinterest state encrypted without credentials or licence plaintext');
    $edge=['HTTPS'=>'on','HTTP_HOST'=>'www.sensecms.com','REQUEST_METHOD'=>'POST','REQUEST_URI'=>'/api/social/pinterest/v1/start','CONTENT_TYPE'=>'application/json']+$server;[$status,$headers,$body]=PinterestOAuthEndpoint::response($edge,json_encode(['return_url'=>'https://tenant.example/social-publishing/pinterest/callback']),$broker);$check($status===200&&($headers['Content-Type']??'')==='application/json; charset=utf-8'&&isset(json_decode($body,true)['authorize_url']),'Pinterest HTTP start returns broker URL');
    foreach([[array_replace($edge,['HTTPS'=>'off']),421],[array_replace($edge,['HTTP_HOST'=>'evil.example']),421],[array_replace($edge,['REQUEST_URI'=>'/api/social/pinterest/v1/unknown']),404],[array_replace($edge,['REQUEST_METHOD'=>'GET']),405],[array_replace($edge,['CONTENT_TYPE'=>'text/plain']),415],[array_replace($edge,['CONTENT_LENGTH'=>65537]),413]]as$idx=>[$unsafe,$expected])$check(PinterestOAuthEndpoint::response($unsafe,'{}',$broker)[0]===$expected,'Pinterest HTTP edge rejects unsafe request '.$idx);$check(PinterestOAuthEndpoint::response($edge,'broken',$broker)[0]===400,'Pinterest HTTP edge rejects invalid JSON');
    echo"$count Pinterest broker checks passed; isolated transport only.\n";
}finally{$broker=null;gc_collect_cycles();foreach(glob($root.'/storage/*.json')?:[]as$file)unlink($file);if(is_file($root.'/broker.lock'))unlink($root.'/broker.lock');if(is_dir($root.'/storage'))rmdir($root.'/storage');rmdir($root);}
