<?php
declare(strict_types=1);

require dirname(__DIR__).'/.cms/source/bootstrap.php';
require dirname(__DIR__).'/.plugins/telegram-channels-publisher/src/TelegramChannelsClient.php';

use App\Core\LicenseClient;
use App\Core\LicenseService;
use SenseCMS\TelegramChannels\TelegramChannelsClient;

$root=sys_get_temp_dir().'/sensecms-telegram-channel-client-'.bin2hex(random_bytes(8));$lic=$root.'/license';if(!mkdir($lic,0700,true))throw new RuntimeException('Cannot create private license fixture.');$secret=random_bytes(32);$key=str_repeat('K',32);$domain='https://www.sensecms.com';$data=['product'=>['name'=>'Sense CMS','model'=>'Sense CMS System','version'=>'1.0'],'valid_from'=>null,'valid_until'=>null];$plain=json_encode(['key'=>$key,'domain'=>$domain,'data'=>$data,'checked_at'=>time()],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);$nonce=random_bytes(24);file_put_contents($lic.'/key.bin',$secret);file_put_contents($lic.'/license.lic',"SENSECMS-LIC-1\n".base64_encode($nonce.sodium_crypto_secretbox($plain,$nonce,$secret)));chmod($lic.'/key.bin',0600);chmod($lic.'/license.lic',0600);$requests=[];$private=false;
$http=static function(string$url,array$headers,string$payload)use(&$requests,&$private):array{$body=json_decode($payload,true,16,JSON_THROW_ON_ERROR);$requests[]=[$url,$headers,$body];$identity=['channel_id'=>$private?'-1009876543210':'-1001234567890','title'=>$private?'Private Editorial':'Sense CMS News','username'=>$private?'':'sensecmsnews','bot_username'=>'SenseCMSBot'];if(str_ends_with($url,'/channels/publish'))$identity+=['message_id'=>91,'duplicate'=>false];return[200,json_encode($identity,JSON_THROW_ON_ERROR)];};
$service=new LicenseService($lic,new LicenseClient(['endpoint'=>'https://www.chivale.com/license/','product_name'=>'Sense CMS','product_model'=>'Sense CMS System','product_version'=>'1.0']));$client=new TelegramChannelsClient($service,'https://www.sensecms.com/api/telegram/v1',$domain,$http);$checks=0;
$check=static function(bool$ok,string$label)use(&$checks):void{if(!$ok)throw new RuntimeException($label);$checks++;echo"PASS $label\n";};$reject=static function(callable$fn,string$label)use($check):void{try{$fn();}catch(RuntimeException){$check(true,$label);return;}throw new RuntimeException($label);};
try{
    $manifest=json_decode((string)file_get_contents(dirname(__DIR__).'/.plugins/telegram-channels-publisher/plugin.json'),true,32,JSON_THROW_ON_ERROR);$license=(array)($manifest['license']??[]);$check(($license['price']??null)===15&&($license['currency']??'')==='USD'&&($license['billing_period']??'')==='year','Telegram Channels subscription is USD 15 per year');$check(($license['product_name']??'')==='Sense CMS Telegram Channels Plugin'&&($license['product_model']??'')==='Telegram Channels Plugin'&&($license['product_version']??'')==='1.0','Telegram Channels uses its own fixed licence identity');$check(($manifest['dependencies'][0]['version']??'')==='>=0.2.2 <1.0.0'&&($manifest['social_publisher']['max_message_length']??0)===3800,'Telegram Channels requires delivery-key capable Social Publishing');
    $render=static function(array$provider):string{$telegramChannelsProvider=$provider;$csrf='fixture-csrf';ob_start();require dirname(__DIR__).'/.plugins/telegram-channels-publisher/views/telegram-channels.php';return(string)ob_get_clean();};$empty=$render([]);$check(str_contains($empty,'https://t.me/SenseCMSBot?startchannel&amp;admin=post_messages')&&str_contains($empty,'name="channel"')&&str_contains($empty,'only the permission to post messages'),'Connection screen exposes minimal channel-admin deep link and no token field');$connected=$render(['connections'=>[['id'=>4,'display_name'=>'Sense CMS News (@sensecmsnews)','external_account_id'=>'-1001234567890','last_verified_at'=>'now'],['id'=>5,'display_name'=>'Private Editorial','external_account_id'=>'-1009876543210','last_verified_at'=>'later']]]);$check(substr_count($connected,'class="social-account-card"')===2&&str_contains($connected,'/connections/4/disconnect'),'Settings screen manages multiple Telegram channels');
    $verified=$client->verify('@sensecmsnews');$check($verified['channel_id']==='-1001234567890'&&$verified['username']==='sensecmsnews','Public channel verification accepts canonical broker identity');$check(array_any($requests[0][1],static fn(string$header):bool=>$header==='Authorization: Bearer '.str_repeat('K',32))&&$requests[0][2]['channel']==='@sensecmsnews','Broker request uses the installation licence without package-key exposure');
    $payload=['delivery_key'=>hash('sha256','delivery-1'),'message'=>'Reviewed story','url'=>'https://www.sensecms.com/en/posts/story'];$published=$client->publish($verified,$payload);$check($published['external_id']==='-1001234567890:91'&&$published['external_url']==='https://t.me/sensecmsnews/91','Public channel publication returns canonical Telegram URL');$check($requests[1][2]['text']==="Reviewed story\n\nhttps://www.sensecms.com/en/posts/story"&&$requests[1][2]['event_key']===$payload['delivery_key'],'Publication sends reviewed text, canonical link and stable delivery key');
    $private=true;$privateIdentity=$client->verify('-1009876543210');$privatePost=$client->publish($privateIdentity,array_replace($payload,['delivery_key'=>hash('sha256','delivery-2')]));$check($privatePost['external_url']==='https://t.me/c/9876543210/91','Private channel publication returns Telegram internal message URL');
    $reject(fn()=>$client->publish($verified,array_replace($payload,['delivery_key'=>'bad'])),'Malformed delivery key rejected before broker request');$reject(fn()=>$client->publish($verified,array_replace($payload,['url'=>'http://example.test'])),'Non-HTTPS canonical URL rejected before broker request');$reject(fn()=>new TelegramChannelsClient($service,'https://evil.example/api',$domain,$http),'Configurable third-party broker refused');
    echo"$checks Telegram Channels publisher checks passed; no live Telegram requests.\n";
}finally{foreach(glob($lic.'/*')?:[]as$file)unlink($file);rmdir($lic);rmdir($root);}
