<?php

declare(strict_types=1);

require dirname(__DIR__).'/.cms/source/bootstrap.php';
require dirname(__DIR__).'/.src/TikTokBrokerService.php';
require dirname(__DIR__).'/.src/TikTokOAuthEndpoint.php';

use SenseCMS\Website\TikTokBrokerService;
use SenseCMS\Website\TikTokOAuthEndpoint;

$root=sys_get_temp_dir().'/sensecms-tiktok-test-'.bin2hex(random_bytes(8));if(!mkdir($root,0700))throw new RuntimeException('Cannot create private TikTok fixture.');$key=random_bytes(32);$access='access-'.str_repeat('a',40);$refresh='refresh-'.str_repeat('r',40);$open='fixture_open_id';$calls=[];$count=0;$cfg=['client_key'=>'fixture-client-key','client_secret'=>'fixture-client-secret-'.str_repeat('s',20)];
$http=static function(string$method,string$url,array$headers,string$payload)use(&$calls,$access,$refresh,$open):array{$calls[]=[$method,$url,$headers,$payload];if($url==='https://www.chivale.com/license/'){parse_str($payload,$form);if(($form['LicenseKey']??'')!==str_repeat('K',32))return[403,'{"error":true}'];return[200,json_encode(['error'=>false,'data'=>['product'=>['name'=>'Sense CMS','model'=>'Sense CMS System','version'=>'1.0'],'valid_from'=>null,'valid_to'=>null]])];}if($url==='https://open.tiktokapis.com/v2/oauth/token/')return[200,json_encode(['access_token'=>$access,'refresh_token'=>$refresh,'open_id'=>$open,'expires_in'=>86400,'refresh_expires_in'=>31536000,'scope'=>'user.info.basic,video.publish,video.upload','token_type'=>'Bearer'])];if($url==='https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name')return[200,json_encode(['data'=>['user'=>['open_id'=>$open,'display_name'=>'sensecms']], 'error'=>['code'=>'ok']])];throw new RuntimeException('Unexpected fixture URL '.$url);};
$broker=new TikTokBrokerService($root,$key,$cfg,$http);$server=['HTTP_AUTHORIZATION'=>'Bearer '.str_repeat('K',32),'HTTP_X_SENSECMS_DOMAIN'=>'https://tenant.example'];$other=array_replace($server,['HTTP_X_SENSECMS_DOMAIN'=>'https://other.example']);$check=static function(bool$ok,string$label)use(&$count):void{if(!$ok)throw new RuntimeException($label);$count++;echo"PASS $label\n";};$reject=static function(callable$fn,int$code,string$label)use($check):void{try{$fn();}catch(RuntimeException$error){$check($error->getCode()===$code&&!str_contains($error->getMessage(),'access-'),$label);return;}throw new RuntimeException($label);};$requestToken=static function(array$start):string{parse_str((string)parse_url($start['authorize_url'],PHP_URL_QUERY),$query);return(string)($query['request']??'');};
try{
    $check($broker->ready(),'configured TikTok broker ready');$reject(fn()=>(new TikTokBrokerService($root,$key,[],$http))->start($server,[]),503,'missing TikTok app credentials fail closed');$reject(fn()=>$broker->start([],['return_url'=>'https://tenant.example/social-publishing/tiktok/callback']),401,'installation licence required');$reject(fn()=>$broker->start($server,['return_url'=>'https://evil.example/social-publishing/tiktok/callback']),422,'return URL bound to installation');
    $start=$broker->start($server,['return_url'=>'https://tenant.example/social-publishing/tiktok/callback']);$request=$requestToken($start);$check(strlen($request)===43&&$start['expires_in']===600,'short-lived TikTok authorization request');$authorize=$broker->authorize($request);parse_str((string)parse_url($authorize,PHP_URL_QUERY),$query);$check(str_starts_with($authorize,'https://www.tiktok.com/v2/auth/authorize/?')&&$query['client_key']===$cfg['client_key']&&$query['redirect_uri']==='https://www.sensecms.com/api/social/tiktok/v1/callback'&&$query['scope']==='user.info.basic,video.publish'&&$query['state']===$request,'TikTok authorization uses minimum direct-post scopes');
    $redirect=$broker->callback(['state'=>$request,'code'=>'fixture-code']);parse_str((string)parse_url($redirect,PHP_URL_QUERY),$claimQuery);$claim=(string)($claimQuery['claim']??'');$check(str_starts_with($redirect,'https://tenant.example/social-publishing/tiktok/callback?claim=')&&strlen($claim)===43,'TikTok callback returns opaque installation claim');$reject(fn()=>$broker->callback(['state'=>$request,'code'=>'fixture-code']),410,'TikTok OAuth state is single-use');$reject(fn()=>$broker->claim($other,$claim),403,'TikTok claim bound to licensed installation');$credential=$broker->claim($server,$claim);$check($credential['open_id']===$open&&$credential['display_name']==='sensecms'&&$credential['access_token']===$access&&$credential['refresh_token']===$refresh&&$credential['refresh_expires_at']>time(),'one-time TikTok credential claimed by correct installation');$reject(fn()=>$broker->claim($server,$claim),410,'claimed TikTok credential is deleted');$tokens=$broker->refresh($server,$refresh);$check($tokens['open_id']===$open&&$tokens['expires_at']>time()&&$tokens['refresh_expires_at']>time(),'TikTok refresh rotates a bounded credential pair');
    $image=imagecreatetruecolor(360,360);ob_start();imagepng($image);$png=(string)ob_get_clean();imagedestroy($image);$stage=$broker->stage($server,'image/png',$png,hash('sha256','delivery'));$check(preg_match('#^https://www\.sensecms\.com/api/social/tiktok/v1/media/[A-Za-z0-9_-]{43}\.png$#D',$stage['source_url'])===1&&$stage['expires_at']>time(),'TikTok image staged under verified Sense CMS domain');$token=basename((string)parse_url($stage['source_url'],PHP_URL_PATH),'.png');$media=$broker->media($token);$check($media['mime']==='image/png'&&hash_equals(hash('sha256',$png),$media['sha256'])&&$media['binary']===$png,'staged TikTok image preserves exact verified bytes');$same=$broker->stage($server,'image/png',$png,hash('sha256','delivery'));$check($same['source_url']===$stage['source_url'],'delivery-key staging is idempotent');
    $mediaEdge=['HTTPS'=>'on','HTTP_HOST'=>'www.sensecms.com','REQUEST_METHOD'=>'HEAD','REQUEST_URI'=>parse_url($stage['source_url'],PHP_URL_PATH)];[$status,$headers,$body]=TikTokOAuthEndpoint::response($mediaEdge,'',$broker);$check($status===200&&$headers['Content-Type']==='image/png'&&(int)$headers['Content-Length']===strlen($png)&&$body==='','TikTok media HEAD returns exact public metadata without a body');
    $edge=['HTTPS'=>'on','HTTP_HOST'=>'www.sensecms.com','REQUEST_METHOD'=>'POST','REQUEST_URI'=>'/api/social/tiktok/v1/start','CONTENT_TYPE'=>'application/json']+$server;[$status,$headers,$body]=TikTokOAuthEndpoint::response($edge,json_encode(['return_url'=>'https://tenant.example/social-publishing/tiktok/callback']),$broker);$check($status===200&&($headers['Content-Type']??'')==='application/json; charset=utf-8'&&isset(json_decode($body,true)['authorize_url']),'TikTok HTTP start returns broker URL');foreach([[array_replace($edge,['HTTPS'=>'off']),421],[array_replace($edge,['HTTP_HOST'=>'evil.example']),421],[array_replace($edge,['REQUEST_URI'=>'/api/social/tiktok/v1/unknown']),404],[array_replace($edge,['REQUEST_METHOD'=>'GET']),405],[array_replace($edge,['CONTENT_TYPE'=>'text/plain']),415],[array_replace($edge,['CONTENT_LENGTH'=>65537]),413]]as$idx=>[$unsafe,$expected])$check(TikTokOAuthEndpoint::response($unsafe,'{}',$broker)[0]===$expected,'TikTok HTTP edge rejects unsafe request '.$idx);$check(TikTokOAuthEndpoint::response($edge,'broken',$broker)[0]===400,'TikTok HTTP edge rejects invalid JSON');
    $raw='';foreach(glob($root.'/storage/*.json')?:[]as$file)$raw.=file_get_contents($file);$check(!str_contains($raw,$cfg['client_secret'])&&!str_contains($raw,$access)&&!str_contains($raw,$refresh)&&!str_contains($raw,str_repeat('K',32)),'TikTok state encrypted without credentials or licence plaintext');echo"$count TikTok broker checks passed; isolated transport only.\n";
}finally{$broker=null;gc_collect_cycles();foreach(glob($root.'/storage/*.json')?:[]as$file)unlink($file);foreach(glob($root.'/media/*.bin')?:[]as$file)unlink($file);if(is_file($root.'/broker.lock'))unlink($root.'/broker.lock');if(is_dir($root.'/media'))rmdir($root.'/media');if(is_dir($root.'/storage'))rmdir($root.'/storage');rmdir($root);}
