<?php
declare(strict_types=1);

namespace SenseCMS\TikTok {
    function curl_init(string$url):object{return(object)['url'=>$url,'options'=>[],'status'=>0];}
    function curl_setopt_array(object$curl,array$options):bool{$curl->options=$options;return true;}
    function curl_exec(object$curl):bool{$GLOBALS['tiktok_requests'][]=$curl;$next=array_shift($GLOBALS['tiktok_responses']);if(!$next)throw new \RuntimeException('Unexpected TikTok request.');$curl->status=$next[0];$body=is_array($next[1])?json_encode($next[1]):$next[1];return($curl->options[CURLOPT_WRITEFUNCTION])($curl,$body)===strlen($body);}
    function curl_error(object$curl):string{return'';}
    function curl_getinfo(object$curl,int$kind):int{return$curl->status;}
    function curl_close(object$curl):void{}
}
namespace {
    require dirname(__DIR__).'/.cms/source/bootstrap.php';$provider=require dirname(__DIR__).'/.plugins/tiktok-publisher/src/provider.php';$checks=0;function tiktokCheck(bool$ok,string$label):void{global$checks;if(!$ok)throw new RuntimeException($label);$checks++;echo"PASS $label\n";}function tiktokRejects(callable$fn,string$label):void{try{$fn();}catch(RuntimeException){tiktokCheck(true,$label);return;}throw new RuntimeException($label);}function tiktokResponses(array$items):void{$GLOBALS['tiktok_responses']=$items;$GLOBALS['tiktok_requests']=[];}
    $manifest=json_decode((string)file_get_contents(dirname(__DIR__).'/.plugins/tiktok-publisher/plugin.json'),true,32,JSON_THROW_ON_ERROR);$license=(array)($manifest['license']??[]);tiktokCheck(($manifest['dependencies'][0]['version']??'')==='>=0.3.0 <1.0.0'&&($manifest['social_publisher']['editor_options']??false)===true,'TikTok requires provider-option capable Social Publishing');tiktokCheck(($license['price']??null)===15&&($license['currency']??'')==='USD'&&($license['billing_period']??'')==='year','TikTok subscription is USD 15 per year');tiktokCheck(($license['product_name']??'')==='Sense CMS TikTok Publisher Plugin'&&($license['product_model']??'')==='TikTok Publisher Plugin'&&($license['product_version']??'')==='1.0','TikTok uses its own fixed licence identity');
    $render=static function(array$provider):string{$tiktokProvider=$provider;$tiktokOAuthRevision=3;$tiktokOAuthOutcome='success';$csrf='fixture-csrf';ob_start();require dirname(__DIR__).'/.plugins/tiktok-publisher/views/tiktok.php';return(string)ob_get_clean();};$disconnected=$render([]);tiktokCheck(str_contains($disconnected,'action="/social-publishing/tiktok/connect"')&&str_contains($disconnected,'data-tiktok-connect')&&str_contains($disconnected,'data-tiktok-oauth-modal'),'TikTok settings expose accessible focused OAuth flow');tiktokCheck(str_contains($disconnected,'class="social-empty social-connect-empty"')&&str_contains($disconnected,'class="social-steps"')&&str_contains($disconnected,'class="social-panel-footer"'),'TikTok settings reuse the shared Social Publishing empty, workflow and note components');$connected=$render(['connections'=>[['id'=>7,'display_name'=>'@sensecms','external_account_id'=>'open-1','last_verified_at'=>'now'],['id'=>8,'display_name'=>'@second','external_account_id'=>'open-2','last_verified_at'=>'later']]]);tiktokCheck(substr_count($connected,'class="social-account-card"')===2&&substr_count($connected,'class="social-account-meta"')===2&&substr_count($connected,'class="btn social-disconnect"')===2&&str_contains($connected,'/connections/7/disconnect')&&str_contains($connected,'Add TikTok account'),'TikTok settings manage multiple accounts with shared metadata and actions');$popup=(string)file_get_contents(dirname(__DIR__).'/.plugins/tiktok-publisher/assets/tiktok.js');tiktokCheck(str_contains($popup,"window.open('about:blank',popupName")&&str_contains($popup,"event.origin!==location.origin")&&str_contains($popup,"url.pathname!=='/api/social/tiktok/v1/authorize'")&&str_contains($popup,'window.close()'),'TikTok OAuth popup validates origin and closes after return');
    $credentials=['open_id'=>'fixture.open','display_name'=>'sensecms','access_token'=>'access-'.str_repeat('a',40),'refresh_token'=>'refresh-'.str_repeat('r',40),'expires_at'=>time()+3600,'refresh_expires_at'=>time()+86400];$user=['data'=>['user'=>['open_id'=>'fixture.open','display_name'=>'Sense CMS']], 'error'=>['code'=>'ok']];tiktokResponses([[200,$user]]);$verified=$provider->verify($credentials);tiktokCheck($verified['external_id']==='fixture.open'&&$verified['display_name']==='@Sense CMS','TikTok account identity verified');
    $creator=['data'=>['creator_username'=>'sensecms','creator_nickname'=>'Sense CMS','privacy_level_options'=>['PUBLIC_TO_EVERYONE','SELF_ONLY'],'comment_disabled'=>false,'duet_disabled'=>false,'stitch_disabled'=>false,'max_video_post_duration_sec'=>600],'error'=>['code'=>'ok']];tiktokResponses([[200,$creator]]);$editor=$provider->editor($credentials);tiktokCheck(count($editor['fields'])===7&&$editor['fields'][0]['name']==='privacy_level'&&$editor['fields'][0]['required']===true&&$editor['fields'][6]['name']==='music_consent'&&$editor['fields'][6]['required']===true,'TikTok editor exposes live privacy, disclosure, AI-label and consent controls');tiktokCheck($GLOBALS['tiktok_requests'][0]->options[CURLOPT_POSTFIELDS]==='{}','TikTok creator-information query sends the required empty JSON object');tiktokResponses([]);$cached=$provider->editor($editor['credentials']);tiktokCheck(count($cached['fields'])===7&&!$GLOBALS['tiktok_requests'],'TikTok editor reuses recently verified creator choices without another API request');tiktokResponses([[200,['error'=>['code'=>'internal_error']]],[200,$creator]]);$editor=$provider->editor($credentials);tiktokCheck(count($editor['fields'])===7&&count($GLOBALS['tiktok_requests'])===2,'TikTok editor recovers from one transient creator-information rejection');
    $valid=['privacy_level'=>'PUBLIC_TO_EVERYONE','allow_comment'=>'1','commercial_content'=>'1','your_brand'=>'1','music_consent'=>'1'];tiktokResponses([[200,$creator]]);$options=$provider->options($credentials,$valid)['options'];tiktokCheck($options['privacy_level']==='PUBLIC_TO_EVERYONE'&&$options['allow_comment']&&$options['your_brand']&&!$options['branded_content']&&$options['music_consent'],'TikTok publishing choices normalize explicitly');tiktokResponses([[200,$creator]]);tiktokRejects(fn()=>$provider->options($credentials,array_replace($valid,['music_consent'=>''])),'TikTok refuses publishing without music confirmation');tiktokResponses([[200,$creator]]);tiktokRejects(fn()=>$provider->options($credentials,['privacy_level'=>'SELF_ONLY','commercial_content'=>'1','branded_content'=>'1','music_consent'=>'1']),'TikTok refuses branded content with private visibility');
    tiktokResponses([[200,['data'=>['status'=>'PROCESSING_TO_PUBLISH'],'error'=>['code'=>'ok']]]]);$status=$provider->status($credentials,'v2.publish.123');tiktokCheck($status['status']==='processing','TikTok processing status remains asynchronous');tiktokResponses([[200,['data'=>['status'=>'PUBLISH_COMPLETE','publicaly_available_post_id'=>['123']],'error'=>['code'=>'ok']]]]);$status=$provider->status($credentials,'v2.publish.123');tiktokCheck($status['status']==='published','TikTok completion maps to published delivery');tiktokResponses([[200,['data'=>['status'=>'FAILED','fail_reason'=>'photo_pull_failed'],'error'=>['code'=>'ok']]]]);$status=$provider->status($credentials,'v2.publish.123');tiktokCheck($status['status']==='failed'&&str_contains($status['error'],'featured image'),'TikTok failure reason is reduced to safe actionable text');
    $source=(string)file_get_contents(dirname(__DIR__).'/.plugins/tiktok-publisher/src/provider.php');tiktokCheck(str_contains($source,"'media_type'=>'PHOTO'")&&str_contains($source,"'post_mode'=>'DIRECT_POST'")&&str_contains($source,"'source'=>'PULL_FROM_URL'")&&str_contains($source,"'status'=>'processing'")&&str_contains($source,'delivery_key'),'TikTok Direct Post uses verified staged photo source and tracked asynchronous identity');echo"$checks TikTok Publisher protocol checks passed; no live TikTok requests.\n";
}
