<?php

declare(strict_types=1);

if(PHP_SAPI!=='cli'||PHP_OS_FAMILY==='Windows'||$argc!==3){fwrite(STDERR,"Usage on private MariaDB host: php tests/youtube-social-release.php <release-directory> <trusted-public-keys.json>\n");exit(2);}set_error_handler(static function(int$level,string$message,string$file,int$line):never{throw new ErrorException($message,0,$level,$file,$line);});
$core=dirname(__DIR__).'/.cms/source';require$core.'/bootstrap.php';$release=realpath($argv[1]);$encoded=json_decode((string)file_get_contents($argv[2]),true,16,JSON_THROW_ON_ERROR);$keys=array_map(static fn(string$value):string=>base64_decode($value,true),$encoded);$count=0;$check=static function(bool$ok,string$label)use(&$count):void{if(!$ok)throw new RuntimeException($label);$count++;echo"PASS $label\n";};
$hashes=json_decode((string)file_get_contents($release.'/youtube-social-release.json'),true,16,JSON_THROW_ON_ERROR);$archives=[];foreach(['addon-social-publishing-0.5.1.zip','plugin-youtube-publisher-0.2.0.zip']as$file){$path=$release.'/'.$file;$manifest=App\Core\Packages\Archive::verify($path,$keys);$identity=App\Core\Packages\Manifest::identity($manifest);$check(hash_equals(hash_file('sha256',$path),(string)($hashes[$identity]??'')),'Exact signed archive '.$identity);$archives[$identity]=[$path,$manifest];}$check(array_keys($archives)===['addon:social-publishing','plugin:youtube-publisher'],'Dependency-ordered YouTube release set');
$dbName='senseyoutube_'.bin2hex(random_bytes(6));$testRoot=sys_get_temp_dir().'/sense-youtube-'.bin2hex(random_bytes(12));$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
try{
    $db->exec("CREATE DATABASE `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$db->exec("USE `$dbName`");foreach(explode(';',(string)file_get_contents($core.'/database/001_core.sql'))as$sql)if(trim($sql)!=='')$db->exec($sql);$db->prepare('INSERT INTO users (name,email,password,created_at) VALUES (?,?,?,UTC_TIMESTAMP())')->execute(['YouTube release QA','owner@example.test',password_hash(bin2hex(random_bytes(24)),PASSWORD_ARGON2ID)]);$db->exec("INSERT INTO roles (slug,name) VALUES ('owner','Owner'); INSERT INTO user_roles VALUES (1,1)");$db->prepare('INSERT INTO migrations (name,checksum,applied_at) VALUES (?,?,UTC_TIMESTAMP())')->execute(['001_core',hash_file('sha256',$core.'/database/001_core.sql')]);(new App\Installer\WorkspaceMigration($db,$core))->apply();mkdir($testRoot.'/config',0700,true);copy($core.'/config/product.php',$testRoot.'/config/product.php');$manager=new App\Core\PackageManager($db,$testRoot,'1.0.0');
    foreach($archives as[$path,$manifest]){$id=$manifest['publisher']['key_id'];$manager->trustPublisher($id,$manifest['publisher']['name'],'',$encoded[$id],1);$stage=$manager->stageLocalFile($path,1);$check($stage['signature']==='verified','Verified package staging '.$manifest['slug']);$installed=$manager->install($stage['token'],1);$check($installed['version']===$manifest['version'],'Installed YouTube social package '.$manifest['slug']);}
    $addon=$manager->package('addon','social-publishing');$plugin=$manager->package('plugin','youtube-publisher');$addonRuntime=json_decode((string)file_get_contents($testRoot.'/addons/social-publishing/addon.json'),true,32,JSON_THROW_ON_ERROR);$pluginRuntime=json_decode((string)file_get_contents($testRoot.'/plugins/youtube-publisher/plugin.json'),true,32,JSON_THROW_ON_ERROR);$license=(array)($pluginRuntime['license']??[]);$check($addon['version']==='0.5.1'&&in_array('/api/social-publishing/media',$addonRuntime['routes']??[],true),'Signed Social Publishing rich-media dependency active');$check($db->query("SHOW COLUMNS FROM social_post_targets LIKE 'options_json'")->fetchColumn()==='options_json','Social target options schema retained');$check($db->query("SHOW COLUMNS FROM posts LIKE 'audio_media_id'")->fetchColumn()==='audio_media_id'&&$db->query("SHOW COLUMNS FROM posts LIKE 'video_media_id'")->fetchColumn()==='video_media_id','Post audio and video migration applied in isolated MariaDB');$check($db->query("SHOW TABLES LIKE 'post_tags'")->fetchColumn()==='post_tags'&&$db->query("SHOW TABLES LIKE 'post_tag_map'")->fetchColumn()==='post_tag_map','Localized post tag schema applied in isolated MariaDB');$check($plugin['version']==='0.2.0'&&($pluginRuntime['social_publisher']['platform']??'')==='youtube'&&($pluginRuntime['social_publisher']['editor_options']??false)===true&&($pluginRuntime['social_publisher']['max_message_length']??0)===5000&&($license['price']??0)===15&&($license['product_name']??'')==='Sense CMS YouTube Publisher Plugin','Signed paid YouTube provider contract active');
    $db->exec("INSERT INTO social_connections (plugin_slug,external_account_id,display_name,encrypted_credentials,enabled,last_verified_at,created_at,updated_at) VALUES ('youtube-publisher','UCaaaaaaaaaaaaaaaaaaaaaa','Sense CMS','encrypted-channel-1',1,UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()),('youtube-publisher','UCbbbbbbbbbbbbbbbbbbbbbb','Second Channel','encrypted-channel-2',1,UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP())");$check((int)$db->query("SELECT COUNT(*) FROM social_connections WHERE plugin_slug='youtube-publisher'")->fetchColumn()===2,'Provider accepts multiple independent YouTube channels');
    $failed=false;try{$manager->uninstall('addon','social-publishing',1);}catch(RuntimeException){$failed=true;}$check($failed,'Active YouTube plugin blocks shared add-on removal');$manager->uninstall('plugin','youtube-publisher',1);$manager->uninstall('addon','social-publishing',1);$check(!is_dir($testRoot.'/plugins/youtube-publisher')&&!is_dir($testRoot.'/addons/social-publishing'),'YouTube packages removed in dependency order');$check($db->query("SHOW TABLES LIKE 'social_connections'")->fetchColumn()==='social_connections','Uninstall preserves social data tables');foreach($archives as[$path]){$stage=$manager->stageLocalFile($path,1);$manager->install($stage['token'],1);}$check($manager->package('plugin','youtube-publisher')['active']&&$manager->package('addon','social-publishing')['active'],'YouTube packages reinstall active with retained schema');echo"$count signed YouTube social package checks passed.\n";
}finally{if(!preg_match('/^senseyoutube_[a-f0-9]{12}$/D',$dbName))throw new RuntimeException('Unsafe QA database cleanup.');$db->exec("DROP DATABASE IF EXISTS `$dbName`");if(is_dir($testRoot)){if(!preg_match('#^'.preg_quote(sys_get_temp_dir(),'#').'/sense-youtube-[a-f0-9]{24}$#D',$testRoot))throw new RuntimeException('Unsafe QA directory cleanup.');foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($testRoot,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST)as$file)$file->isDir()&&!$file->isLink()?rmdir($file->getPathname()):unlink($file->getPathname());rmdir($testRoot);}}
