<?php

declare(strict_types=1);

use App\Core\ExtensionContext;
use App\Core\Runtime;
use SenseCMS\Social\SocialIntegrationManager;
use SenseCMS\TikTok\TikTokOnboardingClient;

require_once __DIR__.'/src/TikTokOnboardingClient.php';

return static function(string$method,string$path,ExtensionContext$context):bool{
    $disconnect=preg_match('#^/social-publishing/tiktok/connections/(\d+)/disconnect$#D',$path,$matches)===1;if(!in_array($path,['/social-publishing/tiktok','/social-publishing/tiktok/status','/social-publishing/tiktok/connect','/social-publishing/tiktok/callback'],true)&&!$disconnect)return false;if(!$context->auth->check()){header('Location: /login',true,302);exit;}$context->access->assert('social.settings.manage');$foundation=$context->root.'/addons/social-publishing/src/SocialIntegrationManager.php';if(!is_file($foundation))throw new RuntimeException('The Social Publishing add-on is required.');require_once$foundation;$manager=new SocialIntegrationManager($context->db,$context->root,(string)($context->config['secrets_key']??''));
    if($method==='GET'&&$path==='/social-publishing/tiktok'){$provider=null;foreach($manager->catalog()as$item)if($item['slug']==='tiktok-publisher'){$provider=$item;break;}$context->dashboard->extensionPage('TikTok Publisher',__DIR__.'/views/tiktok.php',['tiktokProvider'=>$provider,'tiktokOAuthRevision'=>(int)($_SESSION['tiktok_oauth_revision']??0),'tiktokOAuthOutcome'=>(string)($_SESSION['flash_type']??''),'csrf'=>$context->auth->csrf(),'extensionActive'=>'/social-publishing','extensionStyles'=>['/extension-assets/addon/social-publishing/social.css?v=0.4.1','/extension-assets/plugin/tiktok-publisher/tiktok.css?v=0.1.3'],'extensionScripts'=>['/extension-assets/plugin/tiktok-publisher/tiktok.js?v=0.1.3']]);}
    if($method==='GET'&&$path==='/social-publishing/tiktok/status'){$connections=[];foreach($manager->catalog()as$item)if($item['slug']==='tiktok-publisher'){$connections=(array)($item['connections']??[]);break;}header('Cache-Control: no-store');header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'data'=>['connected'=>$connections!==[],'connected_count'=>count($connections),'connection_ids'=>array_values(array_map(static fn(array$item):int=>(int)$item['id'],$connections)),'revision'=>(int)($_SESSION['tiktok_oauth_revision']??0)]],JSON_THROW_ON_ERROR);exit;}
    if($method==='POST'&&$path==='/social-publishing/tiktok/connect'){if(!$context->auth->verifyCsrf($_POST['csrf']??null))throw new RuntimeException('Your session token is invalid. Refresh and try again.',419);$base=(string)($context->config['integrations']['tiktok_social_broker_url']??'');$client=new TikTokOnboardingClient((new Runtime($context->root))->license(),$base,(string)$context->config['base_url']);$url=$client->start();if(str_contains((string)($_SERVER['HTTP_ACCEPT']??''),'application/json')){header('Cache-Control: no-store');header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'authorize_url'=>$url],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);exit;}header('Location: '.$url,true,302);exit;}
    if($method==='GET'&&$path==='/social-publishing/tiktok/callback'){try{if(!isset($_GET['claim']))throw new RuntimeException('TikTok authorization was cancelled.');$base=(string)($context->config['integrations']['tiktok_social_broker_url']??'');$client=new TikTokOnboardingClient((new Runtime($context->root))->license(),$base,(string)$context->config['base_url']);$data=$client->claim((string)$_GET['claim']);$manager->save('tiktok-publisher',(string)$data['open_id'],'@'.(string)$data['display_name'],['open_id'=>(string)$data['open_id'],'display_name'=>(string)$data['display_name'],'access_token'=>(string)$data['access_token'],'refresh_token'=>(string)$data['refresh_token'],'expires_at'=>(int)$data['expires_at'],'refresh_expires_at'=>(int)$data['refresh_expires_at']]);$_SESSION['tiktok_oauth_revision']=(int)($_SESSION['tiktok_oauth_revision']??0)+1;$_SESSION['flash']='TikTok account connected successfully.';$_SESSION['flash_type']='success';}catch(Throwable$error){error_log('TikTok connection failed: '.get_class($error));$_SESSION['flash']='TikTok could not be connected. Verify the Sandbox target account and application access.';$_SESSION['flash_type']='error';}header('Location: /social-publishing/tiktok',true,302);exit;}
    if($method==='POST'&&$disconnect){if(!$context->auth->verifyCsrf($_POST['csrf']??null))throw new RuntimeException('Your session token is invalid. Refresh and try again.',419);$manager->disconnect('tiktok-publisher',(int)$matches[1]);$_SESSION['flash']='TikTok account disconnected. Existing delivery history was preserved.';$_SESSION['flash_type']='success';header('Location: /social-publishing/tiktok',true,302);exit;}
    http_response_code(405);header('Allow: GET, POST');exit;
};
