<?php
declare(strict_types=1);
$provider=is_array($tiktokProvider??null)?$tiktokProvider:[];$connections=array_values(array_filter((array)($provider['connections']??[]),'is_array'));$connected=$connections!==[];$oauthRevision=(int)($tiktokOAuthRevision??0);$oauthOutcome=(string)($tiktokOAuthOutcome??'');$h=static fn(mixed$value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');$steps=[['file-pen-line','Prepare','Create and review a post with a featured image.'],['sliders-horizontal','Choose','Select the account, privacy, interactions and disclosures.'],['badge-check','Confirm','Accept TikTok’s Music Usage Confirmation for this post.'],['activity','Monitor','Track asynchronous processing and retry an explicit failure safely.']];
?>
<div class="sensecms-unified-workspace social-publishing-page social-tiktok-page" data-tiktok-page data-tiktok-oauth-revision="<?= $oauthRevision ?>" data-tiktok-oauth-outcome="<?= $h($oauthOutcome) ?>">
<header class="sensecms-section-hero social-publishing-hero is-tiktok"><div class="sensecms-section-hero-main"><span class="sensecms-section-hero-icon"><i data-lucide="music-2"></i></span><div><span class="sensecms-section-overline">Social Publishing provider</span><h2>TikTok accounts</h2><p>Connect one or more creator accounts and publish only image posts explicitly configured and confirmed by an editor.</p></div></div><div class="social-hero-actions"><?php if($connected): ?><span class="social-hero-summary"><i data-lucide="circle-check"></i><span><strong><?= count($connections) ?> connected</strong><small>TikTok <?= count($connections)===1?'account':'accounts' ?></small></span></span><?php endif; ?><a class="btn border-default-200" href="/social-publishing"><i data-lucide="arrow-left"></i>Social Publishing</a></div></header>
<section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="<?= $connected?'badge-check':'link' ?>"></i></span><div><h2 class="card-title"><?= $connected?'Connected accounts':'Connect TikTok' ?></h2><p><?= $connected?'Add multiple accounts, then choose every destination and setting per post.':'Sign in with an approved TikTok Sandbox target account.' ?></p></div></div><form method="post" action="/social-publishing/tiktok/connect" data-tiktok-connect><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn bg-primary text-white" type="submit" data-sensecms-native><i data-lucide="plus"></i><?= $connected?'Add TikTok account':'Connect with TikTok' ?></button></form></header><div class="card-body">
<?php if($connected): ?><div class="social-account-list"><?php foreach($connections as$connection): ?><article class="social-account-card"><div class="social-account-primary"><span class="social-provider-icon"><i data-lucide="music-2"></i></span><div><span class="social-account-kicker">TikTok account</span><strong><?= $h($connection['display_name']?:'TikTok account') ?></strong><small>Privacy and consent are selected independently for each post.</small></div></div><dl class="social-account-meta"><div><dt>Connection</dt><dd><span class="social-status is-connected"><i data-lucide="circle-check"></i>Connected</span></dd></div><div><dt>User ID</dt><dd><?= $h($connection['external_account_id']) ?></dd></div><div><dt>Last verified</dt><dd><?= $h($connection['last_verified_at']?:'Not available') ?></dd></div></dl><form class="social-account-actions" method="post" action="/social-publishing/tiktok/connections/<?= (int)$connection['id'] ?>/disconnect" data-sensecms-confirm="Disconnect this TikTok account? Existing delivery history will be preserved."><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn social-disconnect" type="submit" data-sensecms-native><i data-lucide="unlink"></i>Disconnect</button></form></article><?php endforeach; ?></div><?php else: ?><div class="social-empty social-connect-empty"><span><i data-lucide="music-2"></i></span><strong>No TikTok account connected</strong><p>The official service exchanges authorization securely. The TikTok Client Secret is never copied into this CMS installation.</p></div><?php endif; ?>
</div></section>
<section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="route"></i></span><div><h2 class="card-title">How publishing works</h2><p>TikTok requires live creator settings and explicit consent immediately before publishing.</p></div></div></header><div class="card-body"><ol class="social-steps"><?php foreach($steps as$i=>$step): ?><li><span class="social-step-number"><?= $i+1 ?></span><span class="social-step-icon"><i data-lucide="<?= $step[0] ?>"></i></span><div><strong><?= $h($step[1]) ?></strong><p><?= $h($step[2]) ?></p></div></li><?php endforeach; ?></ol></div><footer class="social-panel-footer"><i data-lucide="shield-check"></i><span><strong>Development Preview uses TikTok Sandbox limits.</strong> Production access remains subject to TikTok review. No post is sent until an editor chooses privacy, disclosures and confirms music usage.</span></footer></section>
<div class="tiktok-oauth-modal" data-tiktok-oauth-modal role="dialog" aria-modal="true" aria-labelledby="tiktok-oauth-title" hidden><section><span class="tiktok-oauth-icon"><i data-lucide="music-2"></i></span><h2 id="tiktok-oauth-title">Connecting TikTok</h2><p data-tiktok-oauth-status>Complete authorization in the TikTok window. This page will update automatically.</p><button class="btn border-default-200" type="button" data-tiktok-oauth-cancel>Cancel</button></section></div>
</div>
