<?php

declare(strict_types=1);

use App\Core\ExtensionContext;
use App\Core\Runtime;
use SenseCMS\Social\SocialIntegrationManager;
use SenseCMS\YouTube\YouTubeOnboardingClient;

require_once __DIR__.'/src/YouTubeOnboardingClient.php';

return static function(string$method,string$path,ExtensionContext$context):bool{
    $disconnect=preg_match('#^/social-publishing/youtube/connections/(\d+)/disconnect$#D',$path,$matches)===1;if(!in_array($path,['/social-publishing/youtube','/social-publishing/youtube/status','/social-publishing/youtube/connect','/social-publishing/youtube/callback'],true)&&!$disconnect)return false;if(!$context->auth->check()){header('Location: /login',true,302);exit;}$context->access->assert('social.settings.manage');$foundation=$context->root.'/addons/social-publishing/src/SocialIntegrationManager.php';if(!is_file($foundation))throw new RuntimeException('The Social Publishing add-on is required.');require_once$foundation;$manager=new SocialIntegrationManager($context->db,$context->root,(string)($context->config['secrets_key']??''));
    if($method==='GET'&&$path==='/social-publishing/youtube'){$provider=null;foreach($manager->catalog()as$item)if($item['slug']==='youtube-publisher'){$provider=$item;break;}$context->dashboard->extensionPage('YouTube Publisher',__DIR__.'/views/youtube.php',['youtubeProvider'=>$provider,'youtubeOAuthRevision'=>(int)($_SESSION['youtube_oauth_revision']??0),'youtubeOAuthOutcome'=>(string)($_SESSION['flash_type']??''),'csrf'=>$context->auth->csrf(),'extensionActive'=>'/social-publishing','extensionStyles'=>['/extension-assets/addon/social-publishing/social.css?v=0.5.0','/extension-assets/plugin/youtube-publisher/youtube.css?v=0.2.0'],'extensionScripts'=>['/extension-assets/plugin/youtube-publisher/youtube.js?v=0.2.0']]);}
    if($method==='GET'&&$path==='/social-publishing/youtube/status'){$connections=[];foreach($manager->catalog()as$item)if($item['slug']==='youtube-publisher'){$connections=(array)($item['connections']??[]);break;}header('Cache-Control: no-store');header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'data'=>['connected'=>$connections!==[],'connected_count'=>count($connections),'connection_ids'=>array_values(array_map(static fn(array$item):int=>(int)$item['id'],$connections)),'revision'=>(int)($_SESSION['youtube_oauth_revision']??0)]],JSON_THROW_ON_ERROR);exit;}
    if($method==='POST'&&$path==='/social-publishing/youtube/connect'){if(!$context->auth->verifyCsrf($_POST['csrf']??null))throw new RuntimeException('Your session token is invalid. Refresh and try again.',419);$client=new YouTubeOnboardingClient((new Runtime($context->root))->license(),(string)($context->config['integrations']['youtube_social_broker_url']??''),(string)$context->config['base_url']);$url=$client->start();if(str_contains((string)($_SERVER['HTTP_ACCEPT']??''),'application/json')){header('Cache-Control: no-store');header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'authorize_url'=>$url],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);exit;}header('Location: '.$url,true,302);exit;}
    if($method==='GET'&&$path==='/social-publishing/youtube/callback'){try{if(!isset($_GET['claim']))throw new RuntimeException('YouTube authorization was cancelled.');$client=new YouTubeOnboardingClient((new Runtime($context->root))->license(),(string)($context->config['integrations']['youtube_social_broker_url']??''),(string)$context->config['base_url']);$data=$client->claim((string)$_GET['claim']);$manager->save('youtube-publisher',(string)$data['channel_id'],(string)$data['channel_title'],['channel_id'=>(string)$data['channel_id'],'channel_title'=>(string)$data['channel_title'],'access_token'=>(string)$data['access_token'],'refresh_token'=>(string)$data['refresh_token'],'expires_at'=>(int)$data['expires_at'],'public_uploads'=>(bool)($data['public_uploads']??false)]);$_SESSION['youtube_oauth_revision']=(int)($_SESSION['youtube_oauth_revision']??0)+1;$_SESSION['flash']='YouTube channel connected successfully.';$_SESSION['flash_type']='success';}catch(Throwable$error){error_log('YouTube connection failed: '.get_class($error));$_SESSION['flash']='YouTube could not be connected. Verify the Google application and channel access.';$_SESSION['flash_type']='error';}header('Location: /social-publishing/youtube',true,302);exit;}
    if($method==='POST'&&$disconnect){if(!$context->auth->verifyCsrf($_POST['csrf']??null))throw new RuntimeException('Your session token is invalid. Refresh and try again.',419);$manager->disconnect('youtube-publisher',(int)$matches[1]);$_SESSION['flash']='YouTube channel disconnected. Existing delivery history was preserved.';$_SESSION['flash_type']='success';header('Location: /social-publishing/youtube',true,302);exit;}
    http_response_code(405);header('Allow: GET, POST');exit;
};
