<?php
declare(strict_types=1);
$provider=is_array($youtubeProvider??null)?$youtubeProvider:[];$connections=array_values(array_filter((array)($provider['connections']??[]),'is_array'));$connected=$connections!==[];$oauthRevision=(int)($youtubeOAuthRevision??0);$oauthOutcome=(string)($youtubeOAuthOutcome??'');$h=static fn(mixed$value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');$steps=[['file-video','Prepare','Upload an MP4 or WebM video to the Media Library and create a reviewed post.'],['sliders-horizontal','Choose','Select the channel, video, privacy and audience settings.'],['upload-cloud','Upload','Publish now or on schedule through one idempotent delivery.'],['activity','Monitor','Open the resulting YouTube video or retry a failed delivery safely.']];
?>
<div class="sensecms-unified-workspace social-publishing-page social-youtube-page" data-youtube-page data-youtube-oauth-revision="<?= $oauthRevision ?>" data-youtube-oauth-outcome="<?= $h($oauthOutcome) ?>">
<header class="sensecms-section-hero social-publishing-hero is-youtube"><div class="sensecms-section-hero-main"><span class="sensecms-section-hero-icon"><i data-lucide="youtube"></i></span><div><span class="sensecms-section-overline">Social Publishing provider</span><h2>YouTube channels</h2><p>Connect one or more channels and upload only videos explicitly selected and reviewed by an editor.</p></div></div><div class="social-hero-actions"><?php if($connected): ?><span class="social-hero-summary"><i data-lucide="circle-check"></i><span><strong><?= count($connections) ?> connected</strong><small>YouTube <?= count($connections)===1?'channel':'channels' ?></small></span></span><?php endif; ?><a class="btn border-default-200" href="/social-publishing"><i data-lucide="arrow-left"></i>Social Publishing</a></div></header>
<section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="<?= $connected?'badge-check':'link' ?>"></i></span><div><h2 class="card-title"><?= $connected?'Connected channels':'Connect YouTube' ?></h2><p><?= $connected?'Add multiple channels, then choose every destination and upload setting per post.':'Sign in with Google and choose the YouTube channel that Sense CMS may upload to.' ?></p></div></div><form method="post" action="/social-publishing/youtube/connect" data-youtube-connect><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn bg-primary text-white" type="submit" data-sensecms-native><i data-lucide="plus"></i><?= $connected?'Add YouTube channel':'Connect with YouTube' ?></button></form></header><div class="card-body">
<?php if($connected): ?><div class="social-account-list"><?php foreach($connections as$connection): ?><article class="social-account-card"><div class="social-account-primary"><span class="social-provider-icon"><i data-lucide="youtube"></i></span><div><span class="social-account-kicker">YouTube channel</span><strong><?= $h($connection['display_name']?:'YouTube channel') ?></strong><small>A video and audience setting are selected independently for each post.</small></div></div><dl class="social-account-meta"><div><dt>Connection</dt><dd><span class="social-status is-connected"><i data-lucide="circle-check"></i>Connected</span></dd></div><div><dt>Channel ID</dt><dd><?= $h($connection['external_account_id']) ?></dd></div><div><dt>Last verified</dt><dd><?= $h($connection['last_verified_at']?:'Not available') ?></dd></div></dl><form class="social-account-actions" method="post" action="/social-publishing/youtube/connections/<?= (int)$connection['id'] ?>/disconnect" data-sensecms-confirm="Disconnect this YouTube channel? Existing delivery history will be preserved."><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn social-disconnect" type="submit" data-sensecms-native><i data-lucide="unlink"></i>Disconnect</button></form></article><?php endforeach; ?></div><?php else: ?><div class="social-empty social-connect-empty"><span><i data-lucide="youtube"></i></span><strong>No YouTube channel connected</strong><p>The official service exchanges authorization securely. The Google Client Secret is never copied into this CMS installation.</p></div><?php endif; ?>
</div></section>
<section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="route"></i></span><div><h2 class="card-title">How publishing works</h2><p>A controlled video-upload workflow from the Media Library to one or more channels.</p></div></div></header><div class="card-body"><ol class="social-steps"><?php foreach($steps as$i=>$step): ?><li><span class="social-step-number"><?= $i+1 ?></span><span class="social-step-icon"><i data-lucide="<?= $step[0] ?>"></i></span><div><strong><?= $h($step[1]) ?></strong><p><?= $h($step[2]) ?></p></div></li><?php endforeach; ?></ol></div><footer class="social-panel-footer"><i data-lucide="shield-check"></i><span><strong>Development Preview starts with private uploads.</strong> Public and unlisted publishing become available only after the official Sense CMS Google project passes YouTube API compliance review.</span></footer></section>
<div class="youtube-oauth-modal" data-youtube-oauth-modal role="dialog" aria-modal="true" aria-labelledby="youtube-oauth-title" hidden><section><span class="youtube-oauth-icon"><i data-lucide="youtube"></i></span><h2 id="youtube-oauth-title">Connecting YouTube</h2><p data-youtube-oauth-status>Complete authorization in the Google window. This page will update automatically.</p><button class="btn border-default-200" type="button" data-youtube-oauth-cancel>Cancel</button></section></div>
</div>
