<?php

declare(strict_types=1);

use App\Core\ExtensionContext;
use App\Core\Secrets;
use SenseCMS\Mastodon\MastodonClient;
use SenseCMS\Social\SocialIntegrationManager;

require_once __DIR__.'/src/MastodonClient.php';

return static function(string$method,string$path,ExtensionContext$context):bool{
    $disconnect=preg_match('#^/social-publishing/mastodon/connections/(\d+)/disconnect$#D',$path,$matches)===1;
    if(!in_array($path,['/social-publishing/mastodon','/social-publishing/mastodon/status','/social-publishing/mastodon/connect','/social-publishing/mastodon/callback'],true)&&!$disconnect)return false;
    if(!$context->auth->check()){header('Location: /login',true,302);exit;}$context->access->assert('social.settings.manage');$foundation=$context->root.'/addons/social-publishing/src/SocialIntegrationManager.php';if(!is_file($foundation))throw new RuntimeException('The Social Publishing add-on is required.');
    require_once$foundation;$manager=new SocialIntegrationManager($context->db,$context->root,(string)($context->config['secrets_key']??''));$client=new MastodonClient();
    if($method==='GET'&&$path==='/social-publishing/mastodon'){$provider=null;foreach($manager->catalog()as$item)if($item['slug']==='mastodon-publisher'){$provider=$item;break;}$context->dashboard->extensionPage('Mastodon Publisher',__DIR__.'/views/mastodon.php',['mastodonProvider'=>$provider,'mastodonOAuthRevision'=>(int)($_SESSION['mastodon_oauth_revision']??0),'mastodonOAuthOutcome'=>(string)($_SESSION['flash_type']??''),'csrf'=>$context->auth->csrf(),'extensionActive'=>'/social-publishing','extensionStyles'=>['/extension-assets/addon/social-publishing/social.css?v=0.2.2','/extension-assets/plugin/mastodon-publisher/mastodon.css?v=0.1.1'],'extensionScripts'=>['/extension-assets/plugin/mastodon-publisher/mastodon.js?v=0.1.1']]);}
    if($method==='GET'&&$path==='/social-publishing/mastodon/status'){$connections=[];foreach($manager->catalog()as$item)if($item['slug']==='mastodon-publisher'){$connections=(array)($item['connections']??[]);break;}header('Cache-Control: no-store');header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'data'=>['connected'=>$connections!==[],'connected_count'=>count($connections),'connection_ids'=>array_values(array_map(static fn(array$item):int=>(int)$item['id'],$connections)),'revision'=>(int)($_SESSION['mastodon_oauth_revision']??0)]],JSON_THROW_ON_ERROR);exit;}
    if($method==='POST'&&$path==='/social-publishing/mastodon/connect'){
        header('Cache-Control: no-store');$json=str_contains((string)($_SERVER['HTTP_ACCEPT']??''),'application/json');
        try{if(!$context->auth->verifyCsrf($_POST['csrf']??null))throw new RuntimeException('Your session token is invalid. Refresh and try again.',419);$base=rtrim((string)($context->config['base_url']??''),'/');$result=$client->begin((string)($_POST['instance']??''),$base.'/social-publishing/mastodon/callback',$base);$secrets=new Secrets((string)($context->config['secrets_key']??''));$pending=is_array($_SESSION['mastodon_oauth']??null)?$_SESSION['mastodon_oauth']:[];$now=time();foreach($pending as$key=>$item)if(!is_array($item)||(int)($item['expires_at']??0)<$now)unset($pending[$key]);if(count($pending)>=5)array_shift($pending);$pending[$result['state']]=['expires_at'=>(int)$result['pending']['expires_at'],'cipher'=>$secrets->encrypt(json_encode($result['pending'],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR))];$_SESSION['mastodon_oauth']=$pending;if($json){header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'authorize_url'=>$result['authorize_url'],'instance_origin'=>$result['pending']['origin']],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);exit;}header('Location: '.$result['authorize_url'],true,302);exit;}
        catch(Throwable$error){if(!$json)throw$error;http_response_code(in_array($error->getCode(),[419,422],true)?$error->getCode():502);header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>false,'message'=>$error->getCode()===419?$error->getMessage():'The Mastodon connection could not be started. Verify the server address and try again.'],JSON_THROW_ON_ERROR);exit;}
    }
    if($method==='GET'&&$path==='/social-publishing/mastodon/callback'){
        try{$state=(string)($_GET['state']??'');if(!preg_match('/^[A-Za-z0-9_-]{43}$/D',$state)||isset($_GET['error'])||!isset($_GET['code']))throw new RuntimeException('Mastodon authorization was cancelled.');$pending=is_array($_SESSION['mastodon_oauth']??null)?$_SESSION['mastodon_oauth']:[];$saved=$pending[$state]??null;unset($pending[$state]);$_SESSION['mastodon_oauth']=$pending;if(!is_array($saved)||(int)($saved['expires_at']??0)<time()||!is_string($saved['cipher']??null))throw new RuntimeException('The Mastodon authorization session expired.');$plain=(new Secrets((string)($context->config['secrets_key']??'')))->decrypt($saved['cipher']);$flow=json_decode($plain,true,16,JSON_THROW_ON_ERROR);if(!is_array($flow))throw new RuntimeException('The Mastodon authorization session is invalid.');$base=rtrim((string)($context->config['base_url']??''),'/');$data=$client->finish($flow,(string)$_GET['code'],$base.'/social-publishing/mastodon/callback');$manager->save('mastodon-publisher',(string)$data['external_id'],(string)$data['display_name'],(array)$data['credentials']);$_SESSION['mastodon_oauth_revision']=(int)($_SESSION['mastodon_oauth_revision']??0)+1;$_SESSION['flash']='Mastodon account connected successfully.';$_SESSION['flash_type']='success';}
        catch(Throwable$error){error_log('Mastodon connection failed: '.get_class($error));$_SESSION['flash']='Mastodon could not be connected. Verify the server authorization and try again.';$_SESSION['flash_type']='error';}header('Location: /social-publishing/mastodon',true,302);exit;
    }
    if($method==='POST'&&$disconnect){if(!$context->auth->verifyCsrf($_POST['csrf']??null))throw new RuntimeException('Your session token is invalid. Refresh and try again.',419);$manager->disconnect('mastodon-publisher',(int)$matches[1]);$_SESSION['flash']='Mastodon account disconnected. Existing delivery history was preserved.';$_SESSION['flash_type']='success';header('Location: /social-publishing/mastodon',true,302);exit;}
    http_response_code(405);header('Allow: GET, POST');exit;
};
