<?php
declare(strict_types=1);

$provider=is_array($xProvider??null)?$xProvider:[];$connections=array_values(array_filter((array)($provider['connections']??[]),'is_array'));$connected=$connections!==[];$oauthRevision=(int)($xOAuthRevision??0);$oauthOutcome=(string)($xOAuthOutcome??'');
$h=static fn(mixed$value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$steps=[['file-pen-line','Prepare','Create and review the post in Sense CMS.'],['list-checks','Choose','Select an X account and customize its message.'],['calendar-clock','Publish','Send now or schedule one idempotent delivery.'],['activity','Monitor','Inspect the result and retry a failed delivery safely.']];
?>
<div class="sensecms-unified-workspace social-publishing-page social-x-page" data-x-page data-x-oauth-revision="<?= $oauthRevision ?>" data-x-oauth-outcome="<?= $h($oauthOutcome) ?>">
    <header class="sensecms-section-hero social-publishing-hero is-x"><div class="sensecms-section-hero-main"><span class="sensecms-section-hero-icon"><i data-lucide="twitter"></i></span><div><span class="sensecms-section-overline">Social Publishing provider</span><h2>X account</h2><p>Connect one or more X accounts through the official Sense CMS application and publish only posts explicitly selected by an editor.</p></div></div><div class="social-hero-actions"><?php if($connected): ?><span class="social-hero-summary"><i data-lucide="circle-check"></i><span><strong><?= count($connections) ?> connected</strong><small>X <?= count($connections)===1?'account':'accounts' ?></small></span></span><?php endif; ?><a class="btn border-default-200" href="/social-publishing"><i data-lucide="arrow-left"></i>Social Publishing</a></div></header>
    <section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="<?= $connected?'badge-check':'link' ?>"></i></span><div><h2 class="card-title"><?= $connected?'Connected accounts':'Connect X' ?></h2><p><?= $connected?'Connect and manage multiple X accounts, then choose destinations per post.':'Sign in at X and approve the minimum publishing permissions.' ?></p></div></div><form method="post" action="/social-publishing/x/connect" data-x-connect><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn bg-primary text-white" type="submit" data-sensecms-native><i data-lucide="plus"></i><?= $connected?'Add X account':'Connect with X' ?></button></form></header><div class="card-body">
    <?php if($connected): ?><div class="social-account-list"><?php foreach($connections as$connection): ?><article class="social-account-card"><div class="social-account-primary"><span class="social-provider-icon"><i data-lucide="twitter"></i></span><div><span class="social-account-kicker">X account</span><strong><?= $h($connection['display_name']?:'X account') ?></strong><small>An editor can select this destination independently.</small></div></div><dl class="social-account-meta"><div><dt>Connection</dt><dd><span class="social-status is-connected"><i data-lucide="circle-check"></i>Connected</span></dd></div><div><dt>User ID</dt><dd><?= $h($connection['external_account_id']) ?></dd></div><div><dt>Last verified</dt><dd><?= $h($connection['last_verified_at']?:'Not available') ?></dd></div></dl><form class="social-account-actions" method="post" action="/social-publishing/x/connections/<?= (int)$connection['id'] ?>/disconnect"><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn social-disconnect" type="submit" data-sensecms-native><i data-lucide="unlink"></i>Disconnect</button></form></article><?php endforeach; ?></div>
    <?php else: ?><div class="social-empty social-connect-empty"><span><i data-lucide="twitter"></i></span><strong>No X account connected</strong><p>OAuth tokens are encrypted inside this installation. The X application secret remains on the official Sense CMS service.</p></div><?php endif; ?>
    </div></section>
    <section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="route"></i></span><div><h2 class="card-title">How publishing works</h2><p>A controlled four-step flow from review to delivery.</p></div></div></header><div class="card-body"><ol class="social-steps"><?php foreach($steps as$index=>[$icon,$title,$description]): ?><li><span class="social-step-number"><?= $index+1 ?></span><span class="social-step-icon"><i data-lucide="<?= $h($icon) ?>"></i></span><div><strong><?= $h($title) ?></strong><p><?= $h($description) ?></p></div></li><?php endforeach; ?></ol></div></section>
    <div class="x-oauth-modal" data-x-oauth-modal hidden><section role="dialog" aria-modal="true" aria-labelledby="x-oauth-title"><div class="x-oauth-icon"><i data-lucide="twitter"></i></div><h2 id="x-oauth-title">Connect X</h2><p data-x-oauth-status aria-live="polite">Continue securely in the X window. This page will update automatically when you finish.</p><button class="btn border-default-200" type="button" data-x-oauth-cancel>Cancel</button></section></div>
</div>
