<?php declare(strict_types=1); $nav = ['/platform' => 'Platform', '/extensions' => 'Extensions', '/docs' => 'Documentation']; ?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= $e($page['title']) ?> · Sense CMS</title><meta name="description" content="<?= $e($page['description']) ?>">
<?php if ($status === 200): ?><link rel="canonical" href="<?= $e($baseUrl . $path) ?>"><?php else: ?><meta name="robots" content="noindex"><?php endif; ?>
<meta name="theme-color" content="#f7f9fc"><meta property="og:title" content="<?= $e($page['title']) ?> · Sense CMS"><meta property="og:description" content="<?= $e($page['description']) ?>"><meta property="og:type" content="website"><meta property="og:url" content="<?= $e($baseUrl . ($status === 200 ? $path : '/')) ?>">
<link rel="icon" href="/theme-assets/logo.svg" type="image/svg+xml"><link rel="stylesheet" href="/theme-assets/site.css"><script src="/theme-assets/site.js" defer></script>
</head>
<body><a class="skip" href="#main">Skip to content</a>
<header class="header"><div class="container header-inner"><a class="brand" href="/" aria-label="Sense CMS home"><img src="/theme-assets/logo.svg" width="34" height="38" alt=""><span>Sense<span class="brand-light">CMS</span><span class="brand-dot">.</span></span></a>
<button class="menu-button" aria-expanded="false" aria-controls="navigation" type="button">Menu <span aria-hidden="true">☰</span></button>
<nav id="navigation" aria-label="Main navigation"><?php foreach ($nav as $url => $label): ?><a href="<?= $url ?>"<?= str_starts_with($path, $url) ? ' aria-current="page"' : '' ?>><?= $label ?></a><?php endforeach; ?><a href="/contact"<?= $path === '/contact' ? ' aria-current="page"' : '' ?>>Contact</a><a class="button small" href="/download">Get Sense CMS <span aria-hidden="true">↗</span></a></nav></div></header>
<main id="main">
<?php if ($page['kind'] === 'home'): ?>
<section class="hero container"><div class="hero-copy"><a class="release-tag" href="/download"><span class="status-dot"></span> Building Sense CMS · Development preview <span aria-hidden="true">↗</span></a><h1>Make room<br>for <span class="blue">what’s next.</span></h1><p class="intro">A clear foundation for your website.<br>A system you can make your own.</p><p class="hero-detail">A modular PHP CMS with independent themes, a dedicated workspace and room for the features your project needs.</p><div class="actions"><a class="button" href="/platform">Explore the platform <span aria-hidden="true">↗</span></a><a class="text-link" href="/docs">Read the documentation <span aria-hidden="true">→</span></a></div><div class="hero-notes"><span>PHP 8.5+</span><span>Your infrastructure</span><span>Modular by design</span></div></div>
<div class="architecture" aria-label="Sense CMS architecture: independent theme above Core, with modules, plugins and addons"><div class="architecture-top"><span class="eyebrow">A SYSTEM THAT FITS TOGETHER</span><span class="tiny-label">01 / Architecture</span></div><div class="architecture-surface"><span class="tile-icon" aria-hidden="true">↗</span><div><span class="tiny-label">THE EXPERIENCE</span><h2>Your website.<br>Your identity.</h2></div><a href="/extensions#themes" class="architecture-link">Independent themes <span aria-hidden="true">→</span></a></div><div class="connector" aria-hidden="true"></div><div class="core-block"><img src="/theme-assets/logo.svg" width="38" height="44" alt=""><div><span class="tiny-label">THE FOUNDATION</span><strong>Sense CMS Core</strong><span>Workspace · Identity · Licensing</span></div><span class="core-mark" aria-hidden="true">+</span></div><div class="extension-row"><a href="/extensions#modules"><span aria-hidden="true">◫</span>Modules</a><a href="/extensions#plugins"><span aria-hidden="true">⇄</span>Plugins</a><a href="/extensions#addons"><span aria-hidden="true">+</span>Addons</a></div><p class="diagram-caption">One Core. Separate responsibilities. Your choice of extensions.</p></div></section>
<div class="principles-strip"><div class="container"><span>BUILT AROUND CLEAR BOUNDARIES</span><strong>Content ≠ presentation</strong><strong>Core ≠ optional features</strong><strong>Your site ≠ a locked platform</strong></div></div>
<section class="section container"><div class="section-heading"><div><span class="eyebrow">LESS COUPLING. MORE POSSIBILITIES.</span><h2>Start with the essentials.<br>Build in your direction.</h2></div><p>Keep the foundation focused. Give each part of your website a clear place to belong.</p></div><div class="feature-grid"><article><span class="number">01</span><h3>A workspace of its own</h3><p>Administration belongs to Core. Changing the public theme does not mean replacing the place where you manage your website.</p><a class="text-link" href="/platform#workspace">Meet the workspace →</a></article><article><span class="number">02</span><h3>Extensions with a purpose</h3><p>Modules, plugins, addons and themes have distinct roles, explicit compatibility and signed package inventories.</p><a class="text-link" href="/extensions">Understand the packages →</a></article><article><span class="number">03</span><h3>Your infrastructure</h3><p>PHP and a relational database on your own server. Public files stay separate from private configuration and installation keys.</p><a class="text-link" href="/docs/server">See server requirements →</a></article></div></section>
<section class="container foundation-banner"><div><span class="eyebrow">A THOUGHTFUL FIRST STEP</span><h2>Good foundations<br>start before the homepage.</h2><p>Installation begins with a verified license. Then come server checks, your database and the owner account.</p><a class="button inverse" href="/docs/installation">Follow the installation guide ↗</a></div><ol class="install-steps"><li><span>01</span><div><strong>Verify the license</strong><p>Bound to your canonical domain.</p></div></li><li><span>02</span><div><strong>Check your environment</strong><p>Know what the server needs.</p></div></li><li><span>03</span><div><strong>Create your workspace</strong><p>An empty database. A named owner.</p></div></li></ol></section>
<section class="section container closing"><span class="eyebrow">FOLLOW THE BUILD</span><h2>A clear view of where we are.</h2><p>Sense CMS is in active development. Explore the implemented foundation, read the technical documentation and check release availability.</p><a class="button" href="/download">View release status ↗</a></section>
<?php elseif ($page['kind'] === 'article'): ?>
<div class="container docs-layout"><aside class="docs-nav"><a href="/docs" class="eyebrow">DOCUMENTATION</a><nav aria-label="Documentation"><?php foreach (['/docs/installation' => 'Installation', '/docs/licensing' => 'Licensing', '/docs/packages' => 'Package contract', '/docs/server' => 'Server configuration'] as $url => $label): ?><a href="<?= $url ?>"<?= $path === $url ? ' aria-current="page"' : '' ?>><?= $label ?></a><?php endforeach; ?></nav><p>Documentation for the current development Core.</p></aside><article class="article"><a class="back" href="/docs">← All documentation</a><h1><?= $e($page['title']) ?></h1><p class="intro"><?= $e($page['description']) ?></p><?php foreach ($page['sections'] as $i => $section): ?><section id="section-<?= $i + 1 ?>"><h2><?= $e($section[0]) ?></h2><p><?= $e($section[1]) ?></p><?php if (isset($section[2])): ?><pre><code><?= $e($section[2]) ?></code></pre><?php endif; ?></section><?php endforeach; ?><div class="article-footer">Have a question? <a href="/contact">Contact Sense CMS →</a></div></article></div>
<?php else: ?>
<section class="page-hero container"><span class="eyebrow"><?= $e(['platform' => 'THE PLATFORM', 'extensions' => 'THE EXTENSION SYSTEM', 'docs' => 'DOCUMENTATION', 'download' => 'RELEASES & DOWNLOADS', 'contact' => 'GET IN TOUCH', '404' => '404 / NOT FOUND'][$page['kind']]) ?></span><h1><?= $e($page['title']) ?></h1><p class="intro"><?= $e($page['description']) ?></p></section>
<?php if ($page['kind'] === 'platform'): ?>
<section class="container split-section" id="workspace"><div><span class="eyebrow">01 / CORE WORKSPACE</span><h2>One place to manage.<br>Any direction to build.</h2><p>The administrative workspace is independent of the public theme. The current Core includes owner authentication, site settings, license management and an activity log.</p><p>Content editing, media management and the full extension lifecycle are the next layers. They are not presented as finished features.</p><a class="text-link" href="/download">See what is ready →</a></div><div class="definition-list"><div><strong>Identity</strong><span>Owner account, role checks and private sessions.</span></div><div><strong>Configuration</strong><span>Shared site settings outside the public theme.</span></div><div><strong>Licensing</strong><span>Domain validation and encrypted local storage.</span></div><div><strong>Activity</strong><span>Recorded installation, sign-in and settings events.</span></div></div></section>
<section class="section container"><div class="section-heading"><h2>Clear boundaries.<br>Less to untangle.</h2><p>A general-purpose system, not a specialist application with its labels changed.</p></div><div class="feature-grid"><article><span class="number">01</span><h3>Portable Core</h3><p>A clean installation does not carry another website’s database, customer data, credentials or runtime keys.</p></article><article><span class="number">02</span><h3>Independent presentation</h3><p>A public theme owns the website’s visual experience, while administration remains a Core responsibility.</p></article><article><span class="number">03</span><h3>Explicit trust</h3><p>Signed packages must match trusted publisher keys and declared compatibility. A signature is verified, not assumed.</p></article></div></section>
<?php elseif ($page['kind'] === 'extensions'): ?>
<section class="container extension-list"><?php foreach ([['modules','01','Modules','Application capabilities','Give a feature its own routes, data and lifecycle. Content and media management belong here rather than becoming mandatory Core services.'],['plugins','02','Plugins','Connections and integrations','Connect external services or respond to application events without making the integration part of every installation.'],['addons','03','Addons','Optional workspace tools','Extend administrative and operational workflows while keeping the base workspace focused.'],['themes','04','Themes','Your public identity','Shape public pages and their visual language independently of administration. This website is being built as the Sense CMS product theme.']] as [$id,$n,$label,$subtitle,$text]): ?><article id="<?= $id ?>"><span class="number"><?= $n ?></span><div><h2><?= $label ?></h2><span class="eyebrow"><?= $subtitle ?></span></div><p><?= $text ?></p></article><?php endforeach; ?></section><section class="container notice"><h2>Package architecture, not an open marketplace yet.</h2><p>The archive builder, signature verifier and dependency planner are implemented. Signed themes can be installed and rolled back with the operator CLI. The full module lifecycle and package-management interface are in development. There are no publicly released extension packages to download today.</p><a class="text-link" href="/docs/packages">Read the package contract →</a></section>
<?php elseif ($page['kind'] === 'docs'): ?>
<section class="container docs-grid"><?php foreach ([['/docs/installation','01','Installation','From server preparation to your first owner account.'],['/docs/licensing','02','Licensing','Domain binding, encrypted storage and validation.'],['/docs/packages','03','Package contract','Package types, compatibility and publisher trust.'],['/docs/server','04','Server configuration','HTTPS, public roots, Nginx and Apache.']] as [$url,$n,$label,$text]): ?><a href="<?= $url ?>" class="doc-card"><span class="number"><?= $n ?></span><h2><?= $label ?> <span aria-hidden="true">↗</span></h2><p><?= $text ?></p></a><?php endforeach; ?></section>
<?php elseif ($page['kind'] === 'download'): ?>
<section class="container release-panel"><div><span class="release-tag"><span class="status-dot"></span> Development · Core 0.1.0</span><h2>Not a stable release.<br>No surprises.</h2><p>The current build is being tested in isolated environments. A public installation download will appear here only when the complete release passes installation, update and recovery checks.</p><p>No payment, download or release date is being offered on this page.</p><a class="button" href="/docs/installation">Review the installation guide ↗</a></div><div class="release-checklist"><h3>Current readiness</h3><?php foreach ([['Implemented','License-first installation'],['Implemented','Owner login and basic Workspace'],['Implemented','Signed archives and dependency planning'],['Implemented','Operator CLI for signed themes and rollback'],['In development','Full package-management interface'],['In development','Content and media modules'],['Not released','Public stable distribution']] as [$state,$feature]): ?><div><span><?= $feature ?></span><strong class="<?= $state === 'Implemented' ? 'ready' : 'pending' ?>"><?= $state ?></strong></div><?php endforeach; ?></div></section>
<?php elseif ($page['kind'] === 'contact'): ?>
<section class="container contact-layout"><a class="contact-card" href="mailto:info@SenseCMS.com"><span class="eyebrow">EMAIL SENSE CMS</span><h2>info@SenseCMS.com <span aria-hidden="true">↗</span></h2><p>Platform questions, licensing enquiries or a conversation about your project.</p><span class="text-link">Open your email application →</span></a><div><h2>Help us understand your question.</h2><p>For a technical enquiry, include your PHP version, Core version and a short description of the problem.</p><p>Do not email passwords, license keys, private encryption keys or database credentials.</p><a class="text-link" href="/docs">You may find the answer in the docs →</a></div></section>
<?php else: ?><section class="container closing"><p>The address may have changed. Start from the homepage or browse the documentation.</p><div class="actions"><a class="button" href="/">Back to the homepage →</a><a href="/docs" class="text-link">Documentation →</a></div></section><?php endif; ?>
<?php endif; ?>
</main><footer class="footer"><div class="container footer-top"><div><a class="brand" href="/"><img src="/theme-assets/logo.svg" width="30" height="34" alt=""><span>Sense<span class="brand-light">CMS</span><span class="brand-dot">.</span></span></a><p>A clear foundation.<br>A system of your own.</p></div><div><h2>Explore</h2><a href="/platform">Platform</a><a href="/extensions">Extensions</a><a href="/download">Release status</a></div><div><h2>Build</h2><a href="/docs">Documentation</a><a href="/docs/installation">Installation</a><a href="/docs/packages">Package contract</a></div><div><h2>Connect</h2><a href="/contact">Contact</a><a href="mailto:info@SenseCMS.com">info@SenseCMS.com</a></div></div><div class="container footer-bottom"><span>© <?= date('Y') ?> Sense CMS · QUANT Software House Limited</span><span>Independent by design.</span></div></footer>
</body></html>
