<?php

declare(strict_types=1);

return [
    '/privacy-policy' => [
        'title' => 'Privacy Policy',
        'description' => 'How QUANT Software House Limited collects, uses, protects and retains personal information in connection with Sense CMS and this website.',
        'sections' => [
            ['Who we are', 'QUANT Software House Limited (company number 16902352) is the controller for this website and the central Sense CMS services it operates. Our registered office is 71-75 Shelton Street, Covent Garden, London, United Kingdom, WC2H 9JQ. Privacy enquiries and data-rights requests may be sent to info@SenseCMS.com. A customer operating an independent Sense CMS installation is normally the controller for information collected through that installation, while we act only in the role agreed with that customer.'],
            ['Scope', 'This policy covers www.sensecms.com, licensing and package-distribution services, contact forms, live chat, and central connection services used by Sense CMS social-publishing integrations. It does not replace the privacy notice of an independently operated customer website or the privacy terms of a connected third-party platform.'],
            ['Information we collect', 'Depending on how you use the services, we may process your name, business contact details, enquiry or chat content, account and licence records, canonical website domain, product and package identifiers, download and delivery records, and technical information such as the server-observed IP address, approximate country, request time, requested address, browser or device information and security events. Contact forms use a keyed one-way visitor hash for abuse prevention rather than storing the submitted IP address with the form entry.'],
            ['Contact forms and live chat', 'We use contact-form and live-chat information to answer enquiries, provide support, route conversations, prevent abuse and maintain a reliable record of the exchange. Authorised operators can see the IP address observed by our server and an approximate country derived locally for a live-chat conversation; these details are not returned in public chat state and are erased when the conversation is deleted. Do not send passwords, licence keys, private encryption keys, access tokens or unnecessary sensitive information.'],
            ['Licensing and downloads', 'When a licence is verified or a protected package is requested, we process the licence and product identifiers, the canonical domain, validation result, time and limited security metadata needed to provide the service, enforce entitlement, prevent fraud and investigate failures. Licence keys are not placed in public URLs or intentionally written to public logs. Customer installations keep local licence information encrypted with an installation-specific key.'],
            ['Connected social platforms', 'The available Sense CMS integrations include Facebook Pages, X, LinkedIn, Bluesky, Mastodon, Telegram Channels, TikTok and YouTube. If an authorised administrator connects one of these services, we or the customer installation may process an account, profile, Page, channel or board identifier and display name; granted permissions; encrypted access or refresh credentials; selected publication targets; reviewed text and media references; publication time; provider response identifiers; and delivery status. Depending on the provider, a central Sense CMS broker may also process short-lived authorisation state and a single-use connection claim. We never ask for a social-platform password.'],
            ['Meta and Facebook data', 'For Facebook, Meta may provide an app-scoped account identifier, the identifiers and names of Pages the administrator can manage, Page permissions and a Page access token. The central broker validates the calling CMS licence, completes Meta authorisation and transfers the selected Page credential through a short-lived, single-use encrypted claim. Pending broker records expire after ten minutes and are removed after a successful claim. The reusable Page credential is then held encrypted by the customer installation until an authorised user disconnects the account. Publishing sends the reviewed content and necessary credential to Meta through its Graph API.'],
            ['Google and YouTube API data', 'The YouTube Publisher requests youtube.upload to upload videos selected by an editor and youtube.readonly only to read the identifier and title of the currently authenticated channel so the editor can confirm the destination. After an administrator chooses to connect Google, Google provides that channel information, an access token, a refresh token and token expiry information. The central Sense CMS broker keeps the Google client secret in private storage, uses encrypted authorisation state and transfers the channel credential to the licensed installation through a short-lived, single-use claim. The installation stores that credential encrypted until the channel is disconnected, access is revoked or the credential is replaced. When an editor explicitly publishes, Sense CMS sends Google the selected MP4 file, title, description, privacy and audience settings, applicable synthetic-media disclosure and subscriber-notification choice. We store the returned YouTube video identifier, link and delivery result. The integration does not request email, contacts, comments, subscribers or analytics, and does not read, edit or delete existing videos. Google data is used and transferred only to provide and secure the user-requested connection and upload, consistently with the Google API Services User Data Policy, including its Limited Use requirements.'],
            ['Google and YouTube choices', 'An authorised administrator can disconnect a YouTube channel in Sense CMS, which deletes the installation’s stored channel credential and prevents new uploads through that connection. The Google account holder can also revoke Sense CMS access from the security settings of their Google Account. A user may request deletion of related central support or security records by contacting info@SenseCMS.com, subject to legal or fraud-prevention retention requirements. Revocation or disconnection does not delete videos already uploaded to YouTube; those remain controlled through the connected YouTube account.'],
            ['Pending and future integrations', 'Instagram and Threads are awaiting Meta platform access. Pinterest account connection remains unavailable while Pinterest trial access is pending. We do not process connection credentials or publish through an integration merely because it is listed here: processing begins only when the feature is available and an authorised administrator actively connects the relevant account. This policy will be reviewed before a materially different integration goes live.'],
            ['Purposes and lawful bases', 'We process information to provide requested website, support, licensing, download and integration services; take steps before entering into a contract; administer contracts; secure systems; prevent abuse, fraud, replay and duplicate delivery; diagnose faults; improve reliability; and meet legal obligations. The applicable lawful bases are performance of a contract or pre-contractual steps, our legitimate interests in operating and protecting the services, compliance with legal obligations and, where required, consent. We do not sell personal information.'],
            ['Sharing and international transfers', 'We share information only as needed with hosting, email, security and professional-service providers, with a connected platform chosen by the authorised user, with a customer that controls its own Sense CMS installation, or where law requires it. Connected providers such as Meta, X, LinkedIn, Google or other platform operators may process information outside the United Kingdom under their own terms. Where we make a restricted international transfer, we use an applicable adequacy regulation, contractual safeguards or another lawful transfer mechanism and can provide further information on request.'],
            ['Retention', 'Current website settings retain stored contact-form submissions for up to 365 days and live-chat conversations for up to 30 days, unless they are deleted earlier or must be retained for a legal or security reason. Unclaimed central connection claims, including Google and YouTube claims, expire after ten minutes and are removed after successful use. Connected-platform credentials remain encrypted in the relevant installation until disconnection, revocation or replacement. YouTube delivery records retain the uploaded video identifier, link, requested settings and result for operational history, duplicate prevention and audit, but not a second copy of the Google credential. Consent choices for optional analytics are remembered for up to 180 days. Contract, licence, delivery and security records are kept only for the period reasonably required for service delivery, audit, dispute handling, duplicate prevention, legal compliance and the establishment, exercise or defence of claims.'],
            ['Security', 'We use access controls, HTTPS, encryption for sensitive stored credentials, private runtime storage, short-lived connection state, least-privilege permissions and logging designed to avoid secrets. No internet service can be guaranteed completely secure. Customers remain responsible for protecting their own Sense CMS accounts, server, database, backups and connected-platform permissions.'],
            ['Your rights and choices', 'Subject to applicable law, you may ask for access, correction, erasure, restriction, portability or objection and may withdraw consent at any time without affecting earlier lawful processing. Rights depend on the processing context and lawful basis. Contact info@SenseCMS.com; we may verify identity and authority before acting. You may also complain to the UK Information Commissioner’s Office at ico.org.uk or to another competent supervisory authority.'],
            ['Changes', 'We review this policy when services, integrations or legal requirements change. Material changes will be brought to users’ attention where required. Last updated: 20 September 2026.'],
        ],
    ],
    '/terms-and-conditions' => [
        'title' => 'Terms & Conditions',
        'description' => 'Terms governing access to the Sense CMS website, central services, documentation, downloads and connected integrations.',
        'sections' => [
            ['About these terms', 'These terms govern use of www.sensecms.com and central services operated by QUANT Software House Limited, company number 16902352, with registered office at 71-75 Shelton Street, Covent Garden, London, United Kingdom, WC2H 9JQ. By using the website or a central service, you agree to these terms. If you act for an organisation, you confirm that you have authority to bind it. Contact us at info@SenseCMS.com.'],
            ['Separate product and order terms', 'Sense CMS Core, themes, plugins, addons, modules, licences, subscriptions, professional services and customer-operated installations may be governed by a separate licence, quotation, order form, service agreement or package terms. Those specific terms take priority for the relevant product or service if they conflict with these website terms. A price or package description on the website is information, not acceptance of an order, unless an ordering flow expressly states otherwise.'],
            ['Permitted use', 'You may browse the website, use documentation and use services made available to you for lawful business or personal purposes. You must follow applicable law, the relevant product licence and third-party platform rules. You are responsible for the content, media rights, audience, timing, disclosures and records associated with anything you choose to publish.'],
            ['Accounts, licences and security', 'You must provide accurate information, protect accounts and licence keys, apply least privilege, keep your software and server reasonably secure and notify us promptly of suspected unauthorised access. A licence is limited to its stated product, model, validity and canonical domain. You must not share, resell, alter, bypass or use a key for another product or installation unless the applicable agreement expressly permits it.'],
            ['Acceptable use', 'You must not use the website or services for unlawful, deceptive, infringing, abusive or unauthorised activity; introduce malicious code; probe or bypass security or rate limits; interfere with other users; scrape protected services; misuse another installation or connection claim; collect credentials; impersonate another person; or use an integration without authority over the connected account, Page, profile, board or channel.'],
            ['Social-publishing integrations', 'Active integrations may support Facebook Pages, X, LinkedIn, Bluesky, Mastodon, Telegram Channels, TikTok and YouTube. TikTok and YouTube remain Development Preview integrations subject to their platform review, scope, quota and publication restrictions. Instagram, Threads and Pinterest remain subject to platform access or production enablement. Availability, permissions and behaviour can change because each connected platform controls its own API, review, policies, rate limits and outages. No affiliation or endorsement by those platforms is implied.'],
            ['Review and delivery', 'Social publishing is review-first: an authorised user decides what to publish and where. A successful request does not guarantee reach, display format or continued availability on a third-party platform. When a delivery result is ambiguous, Sense CMS may hold it for review rather than risk an accidental duplicate. You must promptly disconnect an account when access is no longer authorised.'],
            ['Intellectual property', 'The website, Sense CMS name and branding, documentation, software and original content are owned by or licensed to QUANT Software House Limited and are protected by applicable intellectual-property laws. No ownership is transferred by access to the website. Product source code and packages may be used only under their applicable licences. Third-party names, marks, content and software remain the property of their respective owners.'],
            ['Availability and changes', 'We may maintain, secure, change, suspend or discontinue a website feature or central service, including where required by security, law, abuse prevention or a third-party platform change. We aim to act reasonably and give notice where practicable, but continuous or error-free availability is not guaranteed. Preview, development or pending features must not be relied on as production commitments.'],
            ['Liability', 'Nothing in these terms excludes liability that cannot lawfully be excluded, including liability for fraud or fraudulent misrepresentation and death or personal injury caused by negligence. Subject to that rule and any specific paid agreement, we are not liable for loss caused by unauthorised use, customer-controlled infrastructure or content, third-party platforms, events outside reasonable control, or indirect or consequential loss. Statutory rights that apply to consumers are not affected.'],
            ['Suspension and termination', 'You may stop using a central integration by disconnecting the relevant account and may stop using the website at any time. We may restrict or suspend access where reasonably necessary to address unlawful use, material breach, non-payment under an applicable agreement, security risk, platform requirements or legal obligations. Terms concerning ownership, responsibility, liability, records and dispute resolution survive where their nature requires it.'],
            ['Governing law', 'These terms are governed by the law of England and Wales. The courts of England and Wales have jurisdiction, except that a consumer may also have mandatory rights to bring a claim in the part of the United Kingdom or country where they live. We encourage you to contact info@SenseCMS.com first so that a concern can be addressed directly.'],
            ['Changes', 'We may update these terms to reflect service, legal or security changes. The current version is published at this address, and material changes will be communicated where required. Last updated: 20 September 2026.'],
        ],
    ],
    '/cookies' => [
        'title' => 'Cookies',
        'description' => 'Information about cookies and similar browser storage used by the Sense CMS website and how to control optional analytics.',
        'sections' => [
            ['What cookies are', 'Cookies are small text records stored by a browser. Similar technologies, including local storage, can remember a preference without creating a traditional cookie. We use these technologies only for the purposes described below and do not use advertising cookies.'],
            ['Strictly necessary session cookie', 'The first-party sensecms_session cookie supports security controls, contact-form CSRF protection, abuse prevention and live-chat continuity. It contains a random session identifier rather than the content of your message. It is marked Secure and HttpOnly, is restricted to same-site requests, and is a session cookie that normally expires when the browser session ends. Because it is required to provide these interactive and security functions, it is not controlled by the optional analytics choice.'],
            ['Analytics preference', 'If Google Analytics is configured, the website displays an analytics preference panel before making any request to Google. Your granted or denied choice is stored in first-party local storage under a key beginning sensecms:analytics: for up to 180 days. This preference record contains the choice and expiry time, not an advertising identifier. You can reopen Analytics settings from the on-page button and change your choice.'],
            ['Optional analytics cookies', 'Only after you actively accept analytics may Google Analytics load and set first-party cookies whose names begin sensega_ga. They distinguish browser activity for aggregated website-usage measurement. Advertising storage, Google Signals and advertising personalisation remain disabled, and page-view addresses exclude query strings. Rejecting or withdrawing analytics prevents further loading and removes matching analytics cookies that the website can access. Google may receive technical usage information as an independent service provider under its own privacy terms.'],
            ['Current and future integrations', 'Connecting Facebook, Instagram, X, LinkedIn, Threads, Bluesky, Mastodon, Telegram Channels, Pinterest, TikTok or YouTube is an authenticated administrator action, not a tracking cookie placed on ordinary website visitors. Pending or future integrations do not set cookies merely because they are listed on the website. A third-party platform may use its own cookies when you deliberately follow a link to it or complete authorisation on its domain; its own notice then applies.'],
            ['Your controls', 'You can reject optional analytics without losing ordinary access to the website. You can later change the analytics choice using the visible Analytics settings control when analytics is configured, and you can clear cookies or local storage in your browser. Blocking the necessary session cookie may prevent contact forms, live chat or protected account functions from working correctly.'],
            ['Changes and contact', 'We review this notice when browser storage or integrations change. For questions, contact info@SenseCMS.com. Last updated: 20 September 2026.'],
        ],
    ],
];
