ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS subject_type VARCHAR(100) NULL;
ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS subject_id BIGINT UNSIGNED NULL;
ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS context JSON NULL;
