ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(80) NULL AFTER name;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(80) NULL AFTER first_name;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address VARCHAR(500) NULL AFTER last_name;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500) NULL AFTER address;
