ALTER TABLE forms ADD COLUMN IF NOT EXISTS block_uid CHAR(36) NULL AFTER id;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS recipient VARCHAR(190) NULL AFTER active;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS settings JSON NULL AFTER recipient;
ALTER TABLE forms ADD UNIQUE INDEX IF NOT EXISTS form_block_uid (block_uid);
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS uid CHAR(36) NULL AFTER id;
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS page_id BIGINT UNSIGNED NULL AFTER form_id;
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS block_uid CHAR(36) NULL AFTER page_id;
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS locale VARCHAR(20) NULL AFTER block_uid;
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS visitor_hash CHAR(64) NULL AFTER locale;
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL AFTER created_at;
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS handled_at DATETIME NULL AFTER updated_at;
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS notified_at DATETIME NULL AFTER handled_at;
ALTER TABLE form_submissions ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL AFTER notified_at;
UPDATE form_submissions SET uid=UUID() WHERE uid IS NULL OR uid='';
UPDATE form_submissions SET updated_at=created_at WHERE updated_at IS NULL;
ALTER TABLE form_submissions MODIFY uid CHAR(36) NOT NULL;
ALTER TABLE form_submissions MODIFY updated_at DATETIME NOT NULL;
ALTER TABLE form_submissions ADD UNIQUE INDEX IF NOT EXISTS submission_uid (uid);
ALTER TABLE form_submissions ADD INDEX IF NOT EXISTS submission_inbox (deleted_at,status,created_at);
ALTER TABLE form_submissions ADD INDEX IF NOT EXISTS submission_block (block_uid,created_at);
UPDATE content_blocks SET source_theme='core' WHERE type IN ('hero','gallery','admissions') AND archived_at IS NULL;
INSERT IGNORE INTO settings (`key`,value) VALUES ('form_retention_days','365');
