<?php
declare(strict_types=1);
$provider=is_array($telegramChannelsProvider??null)?$telegramChannelsProvider:[];$connections=array_values(array_filter((array)($provider['connections']??[]),'is_array'));$connected=$connections!==[];$h=static fn(mixed$value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');$steps=[['bot','Authorize','Add @SenseCMSBot as a channel administrator allowed to post messages.'],['link','Connect','Enter the public @username or numeric channel ID and verify access.'],['list-checks','Choose','Select each connected channel while reviewing a post.'],['send','Publish','Send now or schedule one idempotent delivery.']];
?>
<div class="sensecms-unified-workspace social-publishing-page social-telegram-channels-page">
<header class="sensecms-section-hero social-publishing-hero is-telegram-channels"><div class="sensecms-section-hero-main"><span class="sensecms-section-hero-icon"><i data-lucide="send"></i></span><div><span class="sensecms-section-overline">Social Publishing provider</span><h2>Telegram Channels</h2><p>Connect one or more channels through the official Sense CMS bot and publish only posts explicitly selected by an editor.</p></div></div><div class="social-hero-actions"><?php if($connected): ?><span class="social-hero-summary"><i data-lucide="circle-check"></i><span><strong><?= count($connections) ?> connected</strong><small>Telegram <?= count($connections)===1?'channel':'channels' ?></small></span></span><?php endif; ?><a class="btn border-default-200" href="/social-publishing"><i data-lucide="arrow-left"></i>Social Publishing</a></div></header>
<section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="<?= $connected?'badge-check':'link' ?>"></i></span><div><h2 class="card-title"><?= $connected?'Connected channels':'Connect Telegram channel' ?></h2><p><?= $connected?'Manage multiple channels and choose destinations independently per post.':'First authorize the official bot in Telegram, then enter the channel address below.' ?></p></div></div><form class="telegram-channel-connect-form" method="post" action="/social-publishing/telegram-channels/connect"><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><label><span>Telegram channel</span><input class="form-control" type="text" name="channel" autocomplete="off" maxlength="64" placeholder="@yourchannel" required></label><button class="btn bg-primary text-white" type="submit" data-sensecms-native><i data-lucide="plus"></i><?= $connected?'Add Telegram channel':'Connect channel' ?></button></form></header><div class="card-body">
<aside class="telegram-bot-notice"><span><i data-lucide="shield-check"></i></span><div><strong>Authorize the official bot</strong><p>Add <strong>@SenseCMSBot</strong> with only the permission to post messages. The bot token stays on the official Sense CMS service and is never copied into this installation.</p><a class="btn border-default-200" href="https://t.me/SenseCMSBot?startchannel&amp;admin=post_messages" target="_blank" rel="noopener noreferrer"><i data-lucide="external-link"></i>Choose channel in Telegram</a></div></aside>
<?php if($connected): ?><div class="social-account-list"><?php foreach($connections as$connection): ?><article class="social-account-card"><div class="social-account-primary"><span class="social-provider-icon telegram-channel-provider-icon"><i data-lucide="send"></i></span><div><span class="social-account-kicker">Telegram channel</span><strong><?= $h($connection['display_name']?:'Telegram channel') ?></strong><small>An editor can select this destination independently.</small></div></div><dl class="social-account-meta"><div><dt>Connection</dt><dd><span class="social-status is-connected"><i data-lucide="circle-check"></i>Connected</span></dd></div><div><dt>Channel ID</dt><dd class="telegram-channel-id"><?= $h($connection['external_account_id']) ?></dd></div><div><dt>Last verified</dt><dd><?= $h($connection['last_verified_at']?:'Not available') ?></dd></div></dl><form class="social-account-actions" method="post" action="/social-publishing/telegram-channels/connections/<?= (int)$connection['id'] ?>/disconnect"><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn social-disconnect" type="submit" data-sensecms-native><i data-lucide="unlink"></i>Disconnect</button></form></article><?php endforeach; ?></div>
<?php else: ?><div class="social-empty social-connect-empty"><span class="telegram-channel-provider-icon"><i data-lucide="send"></i></span><strong>No Telegram channel connected</strong><p>Public channels can use <code>@username</code> or a <code>t.me</code> address. Private channels can use their numeric <code>-100…</code> channel ID.</p></div><?php endif; ?>
</div></section>
<section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="route"></i></span><div><h2 class="card-title">How publishing works</h2><p>A controlled four-step flow from channel authorization to delivery.</p></div></div></header><div class="card-body"><ol class="social-steps"><?php foreach($steps as$index=>[$icon,$title,$description]): ?><li><span class="social-step-number"><?= $index+1 ?></span><span class="social-step-icon"><i data-lucide="<?= $h($icon) ?>"></i></span><div><strong><?= $h($title) ?></strong><p><?= $h($description) ?></p></div></li><?php endforeach; ?></ol></div></section>
</div>
