<?php
declare(strict_types=1);

$provider=is_array($pinterestProvider??null)?$pinterestProvider:[];$connections=array_values(array_filter((array)($provider['connections']??[]),'is_array'));$connected=$connections!==[];$oauthRevision=(int)($pinterestOAuthRevision??0);$oauthOutcome=(string)($pinterestOAuthOutcome??'');
$h=static fn(mixed$value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$steps=[['file-pen-line','Prepare','Create and review a post with a public featured image.'],['layout-grid','Choose','Select a Pinterest board and customize its description.'],['calendar-clock','Publish','Send now or schedule one idempotent image Pin.'],['activity','Monitor','Inspect the result and retry a failed delivery safely.']];
?>
<div class="sensecms-unified-workspace social-publishing-page social-pinterest-page" data-pinterest-page data-pinterest-oauth-revision="<?= $oauthRevision ?>" data-pinterest-oauth-outcome="<?= $h($oauthOutcome) ?>">
    <header class="sensecms-section-hero social-publishing-hero is-pinterest"><div class="sensecms-section-hero-main"><span class="sensecms-section-hero-icon"><i data-lucide="pin"></i></span><div><span class="sensecms-section-overline">Social Publishing provider</span><h2>Pinterest boards</h2><p>Connect one or more boards through the official Sense CMS application and publish only image posts explicitly selected by an editor.</p></div></div><div class="social-hero-actions"><?php if($connected): ?><span class="social-hero-summary"><i data-lucide="circle-check"></i><span><strong><?= count($connections) ?> connected</strong><small>Pinterest <?= count($connections)===1?'board':'boards' ?></small></span></span><?php endif; ?><a class="btn border-default-200" href="/social-publishing"><i data-lucide="arrow-left"></i>Social Publishing</a></div></header>
    <section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="<?= $connected?'badge-check':'link' ?>"></i></span><div><h2 class="card-title"><?= $connected?'Connected boards':'Connect Pinterest' ?></h2><p><?= $connected?'Connect multiple accounts or boards, then choose destinations per post.':'Sign in with a Pinterest Business account and choose one board to connect.' ?></p></div></div><form method="post" action="/social-publishing/pinterest/connect" data-pinterest-connect><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn bg-primary text-white" type="submit" data-sensecms-native><i data-lucide="plus"></i><?= $connected?'Add Pinterest board':'Connect with Pinterest' ?></button></form></header><div class="card-body">
    <?php if($connected): ?><div class="social-account-list"><?php foreach($connections as$connection): ?><article class="social-account-card"><div class="social-account-primary"><span class="social-provider-icon"><i data-lucide="pin"></i></span><div><span class="social-account-kicker">Pinterest board</span><strong><?= $h($connection['display_name']?:'Pinterest board') ?></strong><small>An editor can select this destination independently.</small></div></div><dl class="social-account-meta"><div><dt>Connection</dt><dd><span class="social-status is-connected"><i data-lucide="circle-check"></i>Connected</span></dd></div><div><dt>Board ID</dt><dd><?= $h($connection['external_account_id']) ?></dd></div><div><dt>Last verified</dt><dd><?= $h($connection['last_verified_at']?:'Not available') ?></dd></div></dl><form class="social-account-actions" method="post" action="/social-publishing/pinterest/connections/<?= (int)$connection['id'] ?>/disconnect" data-sensecms-confirm="Disconnect this Pinterest board? Existing delivery history will be preserved."><input type="hidden" name="csrf" value="<?= $h($csrf) ?>"><button class="btn social-disconnect" type="submit" data-sensecms-native><i data-lucide="unlink"></i>Disconnect</button></form></article><?php endforeach; ?></div><?php else: ?><div class="social-empty social-connect-empty"><span><i data-lucide="pin"></i></span><strong>No Pinterest board connected</strong><p>The central service exchanges authorization securely. The Pinterest App Secret is never copied into this CMS installation.</p></div><?php endif; ?>
    </div></section>
    <section class="card social-panel"><header class="card-header social-panel-header"><div class="social-panel-title"><span><i data-lucide="route"></i></span><div><h2 class="card-title">How publishing works</h2><p>Every destination remains review-first, traceable and independently disconnectable.</p></div></div></header><div class="card-body"><ol class="social-steps"><?php foreach($steps as$i=>$step): ?><li><span class="social-step-number"><?= $i+1 ?></span><span class="social-step-icon"><i data-lucide="<?= $step[0] ?>"></i></span><div><strong><?= $h($step[1]) ?></strong><p><?= $h($step[2]) ?></p></div></li><?php endforeach; ?></ol></div><footer class="social-panel-footer"><i data-lucide="image"></i><span><strong>A public HTTPS featured image is required.</strong> Pinterest creates image Pins in this first release. The Pin links back to the canonical Sense CMS post.</span></footer></section>
    <div class="pinterest-oauth-modal" data-pinterest-oauth-modal role="dialog" aria-modal="true" aria-labelledby="pinterest-oauth-title" hidden><section><span class="pinterest-oauth-icon"><i data-lucide="pin"></i></span><h2 id="pinterest-oauth-title">Connecting Pinterest</h2><p data-pinterest-oauth-status>Complete authorization and choose a board in the Pinterest window. This page will update automatically.</p><button class="btn border-default-200" type="button" data-pinterest-oauth-cancel>Cancel</button></section></div>
</div>
