<?php

declare(strict_types=1);

namespace App\Core;

use PDOException;
use RuntimeException;

final class AiContentService
{
    public function __construct(private readonly AiRepository$repository,private readonly Secrets$secrets,private readonly AiProviderClient$client=new AiProviderClient()){}

    public function saveProvider(array$input,int$userId=0):int
    {
        $drivers=AiProviderClient::drivers();$id=max(0,(int)($input['id']??0));$name=mb_substr(trim((string)($input['name']??'')),0,120);$slug=strtolower(trim((string)($input['slug']??'')));$driver=AiProviderClient::driver((string)($input['driver']??''));$model=mb_substr(trim((string)($input['default_model']??'')),0,150);$base=rtrim(trim((string)($input['base_url']??'')),'/');$key=trim((string)($input['api_key']??''));
        if($name===''||$driver===''||$model==='')throw new RuntimeException('Provider name, driver and model are required.');if(!preg_match('/^[a-z][a-z0-9-]{1,79}$/',$slug))throw new RuntimeException('Provider slug must use lowercase letters, numbers and hyphens.');if(!preg_match('/^[A-Za-z0-9._:\/-]+$/',$model))throw new RuntimeException('The model identifier is invalid.');
        if($base==='')$base=(string)($drivers[$driver]['default_url']??'');$parts=parse_url($base);if(!is_array($parts)||strtolower((string)($parts['scheme']??''))!=='https'||empty($parts['host'])||isset($parts['user'])||isset($parts['pass'])||isset($parts['query'])||isset($parts['fragment']))throw new RuntimeException('The provider base URL must be a clean HTTPS address without credentials or query parameters.');
        $purposes=array_values(array_intersect((array)($input['purposes']??[]),['builder','posts','chat']));if(!$purposes)$purposes=['builder'];$data=['id'=>$id,'slug'=>$slug,'name'=>$name,'driver'=>$driver,'base_url'=>$base,'default_model'=>$model,'enabled'=>!empty($input['enabled']),'priority'=>max(1,min(999,(int)($input['priority']??100))),'options'=>['purposes'=>$purposes,'limits'=>self::limits($input)]];
        if($key!==''){$data['api_key_encrypted']=$this->secrets->encrypt($key);}elseif(!empty($data['enabled'])&&(!$id||empty($this->repository->providerById($id)['api_key_encrypted'])))throw new RuntimeException('Enter an API key before enabling this provider.');
        try{$saved=$this->repository->saveProvider($data);}catch(PDOException){throw new RuntimeException('The provider slug already exists or the configuration is invalid.');}$this->repository->auditProvider($userId,$saved,$id?'ai.provider.updated':'ai.provider.created',['driver'=>$driver,'purposes'=>$purposes,'enabled'=>$data['enabled']]);return$saved;
    }

    public function verifyProvider(int$id,int$userId=0):array
    {
        $provider=$this->repository->providerById($id);if(!$provider||empty($provider['api_key_encrypted']))throw new RuntimeException('Configure an API key before testing this provider.');
        $system='You are a connection health check.';$prompt='Reply with exactly: Sense CMS ready';$usage=0;
        try{$usage=$this->repository->beginUsage($provider,'verification',$userId,mb_strlen($system)+mb_strlen($prompt),24);$result=$this->client->generate($provider,$this->secrets->decrypt((string)$provider['api_key_encrypted']),$system,$prompt,false,24);$ok=stripos($result['text'],'Sense CMS ready')!==false;if(!$ok)throw new RuntimeException('The provider returned an unexpected verification response.');$this->repository->finishUsage($usage,true,$result['usage']);$this->repository->providerVerification($id,true);$this->repository->auditProvider($userId,$id,'ai.provider.verified',['driver'=>$provider['driver']]);return['verified_at'=>(new \DateTimeImmutable())->format('Y-m-d H:i:s')];}
        catch(\Throwable$error){if($usage)$this->repository->finishUsage($usage,false,null,$error->getCode()===429?'usage_limit':'provider_error');$this->repository->providerVerification($id,false,$error->getMessage());$this->repository->auditProvider($userId,$id,'ai.provider.verification_failed',['driver'=>$provider['driver'],'code'=>$error->getCode()===429?'usage_limit':'provider_error']);throw$error;}
    }

    public function propose(int$pageId,int$facilityId,int$userId,array$input,array$blocks,array$catalog,array$languages,array$actions,array$quality=[]):array
    {
        $provider=$this->repository->provider((string)($input['provider']??''));if(!$provider||empty($provider['api_key_encrypted']))throw new RuntimeException('Choose an enabled and configured AI provider.');$purposes=(array)($provider['options']['purposes']??[]);if($purposes&&!in_array('builder',$purposes,true))throw new RuntimeException('This AI provider is not enabled for Page Builder.');
        $action=(string)($input['action']??'');$definition=$actions[$action]??null;if(!is_array($definition))throw new RuntimeException('Choose an available AI action.');$scope=in_array($input['scope']??'',(array)$definition['scope'],true)?(string)$input['scope']:(string)($definition['scope'][0]??'page');$locales=array_values(array_map(static fn(array$l):string=>(string)$l['locale'],$languages));$locale=in_array($input['locale']??'',$locales,true)?(string)$input['locale']:($locales[0]??'en');$defaultLocale=$locale;foreach($languages as$language)if(!empty($language['is_default'])){$defaultLocale=(string)$language['locale'];break;}
        $uid=strtolower(trim((string)($input['section_uid']??'')));if($scope==='section'&&!preg_match('/^[a-f0-9-]{36}$/',$uid))throw new RuntimeException('Select a section before requesting this AI action.');$instructions=mb_substr(trim((string)($input['instructions']??'')),0,2000);$audience=mb_substr(trim((string)($input['audience']??'')),0,120);$tone=mb_substr(trim((string)($input['tone']??'')),0,80);
        $context=$this->context($blocks,$catalog,$scope,$uid,$locale,$defaultLocale,$quality);$schema=$this->schema($catalog);$system='You are the controlled Page Builder copilot inside Sense CMS. Return JSON only. Never invent facts, prices, dates, policies, testimonials, certifications or service availability. Never return HTML scripts, event handlers, data URLs, executable URLs or unsupported section types. Preserve supplied links, names and factual details. Your output is only a proposal and will be validated by Core.';
        $user=json_encode(['task'=>(string)$definition['instruction'],'scope'=>$scope,'target_locale'=>$locale,'source_locale'=>$defaultLocale,'audience'=>$audience,'tone'=>$tone,'editor_instructions'=>$instructions,'allowed_sections'=>$schema,'current_document'=>$context,'response_schema'=>['summary'=>'Plain text up to 240 characters','sections'=>[['uid'=>'Existing UID for edits; omit for new sections','type'=>'Allowed section type','content'=>'Object containing only allowed localized fields']]]],JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
        if(strlen($user)>180000)throw new RuntimeException('The selected page is too large for one AI request. Choose a section or reduce the content.');$run=$this->repository->beginBuilderRun($pageId,$facilityId,$userId,$provider,$action,$scope,$locale,mb_strlen($user));$usage=0;
        try{$usage=$this->repository->beginUsage($provider,'builder',$userId,mb_strlen($system)+mb_strlen($user),3600);$response=$this->client->generate($provider,$this->secrets->decrypt((string)$provider['api_key_encrypted']),$system,$user,true,3600);$decoded=self::decodeProposal($response['text']);$after=self::applyProposal($blocks,$decoded,$action,$scope,$uid,$locale,$locales,$catalog);$diff=PageBuilder::revisionDiff(['blocks'=>$blocks],['blocks'=>$after],$catalog);$summary=mb_substr(trim((string)($decoded['summary']??'AI proposal ready for review.')),0,240);$this->repository->finishUsage($usage,true,$response['usage']);$this->repository->finishBuilderRun($run,true,mb_strlen($response['text']),$response['usage']);return['summary'=>$summary!==''?$summary:'AI proposal ready for review.','blocks'=>$after,'diff'=>$diff,'provider'=>['slug'=>$provider['slug'],'name'=>$provider['name'],'model'=>$provider['default_model']],'action'=>$action,'scope'=>$scope,'locale'=>$locale,'usage'=>$response['usage']];}
        catch(\Throwable$error){if($usage)$this->repository->finishUsage($usage,false,null,$error->getCode()===429?'usage_limit':'provider_error');$this->repository->finishBuilderRun($run,false,0,null,$error->getCode()===429?'usage_limit':'provider_error');throw$error;}
    }

    public static function postActions():array
    {
        return[
            'generate-draft'=>['label'=>'Generate article draft','description'=>'Create a complete draft from an editorial brief.','icon'=>'file-sparkles','scopes'=>['document'],'instruction'=>'Create a complete article draft from the supplied brief. Include a useful title, excerpt, structured article body, SEO metadata and focused tags.'],
            'rewrite'=>['label'=>'Improve writing','description'=>'Improve clarity and flow while preserving facts.','icon'=>'wand-sparkles','scopes'=>['content','selection'],'instruction'=>'Improve clarity, flow and readability. Preserve every supplied fact, name, link and meaning.'],
            'shorten'=>['label'=>'Make concise','description'=>'Remove repetition while preserving the essential message.','icon'=>'shrink','scopes'=>['content','selection'],'instruction'=>'Shorten the supplied writing substantially. Preserve its essential meaning, factual details, names and links.'],
            'expand'=>['label'=>'Expand article','description'=>'Add useful structure without inventing information.','icon'=>'expand','scopes'=>['content','selection'],'instruction'=>'Expand the supplied writing with useful structure and explanation. Do not invent facts, quotations, dates, prices, policies or claims.'],
            'seo'=>['label'=>'Prepare SEO metadata','description'=>'Propose an SEO title, description and focused keywords.','icon'=>'search-check','scopes'=>['metadata'],'instruction'=>'Create accurate search metadata from the supplied article. Avoid clickbait and unsupported claims.'],
            'translate'=>['label'=>'Translate article','description'=>'Translate the default-language article into the selected language.','icon'=>'languages','scopes'=>['document'],'instruction'=>'Translate the source article naturally into the target language. Preserve meaning, names, links, markup structure and factual details.'],
        ];
    }

    public function proposePost(int$userId,array$input,array$languages):array
    {
        $provider=$this->repository->provider((string)($input['provider']??''));if(!$provider||empty($provider['api_key_encrypted']))throw new RuntimeException('Choose an enabled and configured AI provider.');$purposes=(array)($provider['options']['purposes']??[]);if($purposes&&!in_array('posts',$purposes,true))throw new RuntimeException('This AI provider is not enabled for Posts.');
        $actions=self::postActions();$action=(string)($input['action']??'');$definition=$actions[$action]??null;if(!is_array($definition))throw new RuntimeException('Choose an available post AI action.');$scope=in_array($input['scope']??'',(array)$definition['scopes'],true)?(string)$input['scope']:(string)$definition['scopes'][0];
        $locales=array_values(array_filter(array_map(static fn(array$l):string=>(string)($l['locale']??''),$languages)));$locale=in_array($input['locale']??'',$locales,true)?(string)$input['locale']:($locales[0]??'en');$sourceLocale=in_array($input['source_locale']??'',$locales,true)?(string)$input['source_locale']:($locales[0]??'en');foreach($languages as$language)if(!empty($language['is_default'])){$sourceLocale=(string)$language['locale'];break;}if($action==='translate'&&$locale===$sourceLocale)throw new RuntimeException('Choose a target language different from the default language.');
        $current=self::sanitizePostFields((array)($input['current']??[]));$source=self::sanitizePostFields((array)($input['source']??[]));$selection=mb_substr(trim((string)($input['selection']??'')),0,20000);if($scope==='selection'&&mb_strlen($selection)<2)throw new RuntimeException('Select a passage in the article before using this action.');$instructions=mb_substr(trim((string)($input['instructions']??'')),0,2000);$audience=mb_substr(trim((string)($input['audience']??'')),0,120);$tone=mb_substr(trim((string)($input['tone']??'')),0,80);if($action==='generate-draft'&&$instructions===''&&self::postEmpty($current))throw new RuntimeException('Add an editorial brief before generating a new article.');
        $system='You are the controlled Posts copilot inside Sense CMS. Return JSON only. Never invent facts, quotations, names, dates, prices, policies, credentials, testimonials or claims. Preserve supplied links and factual details. Use safe semantic article HTML only: headings, paragraphs, lists, emphasis, blockquotes and links. Never return scripts, event handlers, forms, embeds, data URLs or executable URLs. Your output is only a proposal and must be reviewed by a human before saving or publishing.';
        $context=$scope==='selection'?['title'=>$current['title']]:($action==='translate'?$source:$current);$schema=$scope==='selection'?['summary'=>'Plain text up to 240 characters','selection'=>'Replacement plain text for the selected passage']:['summary'=>'Plain text up to 240 characters','fields'=>['title'=>'Plain text up to 255 characters','excerpt'=>'Plain text up to 1200 characters','content'=>'Safe semantic HTML up to 100000 characters','seo_title'=>'Plain text up to 255 characters','seo_description'=>'Plain text up to 500 characters','tags'=>['Up to 30 focused tags, each up to 100 characters']]];
        $prompt=json_encode(['task'=>$definition['instruction'],'action'=>$action,'scope'=>$scope,'target_locale'=>$locale,'source_locale'=>$sourceLocale,'audience'=>$audience,'tone'=>$tone,'editor_instructions'=>$instructions,'current_post'=>$context,'selected_text'=>$scope==='selection'?$selection:null,'response_schema'=>$schema],JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if(strlen($prompt)>160000)throw new RuntimeException('The article is too large for one AI request. Select a passage or shorten the content.');$usage=0;
        try{$usage=$this->repository->beginUsage($provider,'posts',$userId,mb_strlen($system)+mb_strlen($prompt),$scope==='selection'?1200:3600);$response=$this->client->generate($provider,$this->secrets->decrypt((string)$provider['api_key_encrypted']),$system,$prompt,true,$scope==='selection'?1200:3600);$decoded=self::decodePostProposal($response['text']);$proposal=self::applyPostProposal($current,$decoded,$action,$scope);if($scope==='selection'){$proposal['before']['selection']=$selection;$proposal['changes'][0]['before']=$selection;}$this->repository->finishUsage($usage,true,$response['usage']);return$proposal+['provider'=>['slug'=>$provider['slug'],'name'=>$provider['name'],'model'=>$provider['default_model']],'action'=>$action,'scope'=>$scope,'locale'=>$locale,'source_locale'=>$sourceLocale,'usage'=>$response['usage']];}
        catch(\Throwable$error){if($usage)$this->repository->finishUsage($usage,false,null,$error->getCode()===429?'usage_limit':'provider_error');throw$error;}
    }

    public static function decodePostProposal(string$text):array
    {
        $text=trim(preg_replace('/^```(?:json)?\s*|\s*```$/i','',$text)??$text);$start=strpos($text,'{');$end=strrpos($text,'}');if($start===false||$end===false||$end<$start)throw new RuntimeException('The AI provider did not return a structured post proposal.');$decoded=json_decode(substr($text,$start,$end-$start+1),true);if(!is_array($decoded))throw new RuntimeException('The AI post proposal has an invalid structure.');return$decoded;
    }

    public static function applyPostProposal(array$current,array$proposal,string$action,string$scope):array
    {
        $current=self::sanitizePostFields($current);$summary=mb_substr(trim((string)($proposal['summary']??'AI proposal ready for review.')),0,240);if($scope==='selection'){$selection=mb_substr(trim(strip_tags((string)($proposal['selection']??''))),0,20000);if($selection==='')throw new RuntimeException('The AI proposal did not contain a usable replacement.');return['summary'=>$summary?:'AI proposal ready for review.','before'=>['selection'=>''],'after'=>['selection'=>$selection],'changes'=>[['field'=>'selection','label'=>'Selected passage','before'=>'','after'=>$selection]]];}
        $allowed=match($action){'generate-draft','translate'=>['title','excerpt','content','seo_title','seo_description','tags'],'rewrite'=>['title','excerpt','content'],'shorten'=>['excerpt','content'],'expand'=>['excerpt','content'],'seo'=>['seo_title','seo_description','tags'],default=>[]};$fields=is_array($proposal['fields']??null)?$proposal['fields']:[];$candidate=$current;foreach($allowed as$key)if(array_key_exists($key,$fields))$candidate[$key]=$fields[$key];$candidate=self::sanitizePostFields($candidate);$labels=['title'=>'Post title','excerpt'=>'Excerpt','content'=>'Article content','seo_title'=>'SEO title','seo_description'=>'SEO description','tags'=>'Tags / keywords'];$changes=[];foreach($allowed as$key){$before=$current[$key]??'';$after=$candidate[$key]??'';if($before===$after)continue;$changes[]=['field'=>$key,'label'=>$labels[$key],'before'=>$before,'after'=>$after];}if(!$changes)throw new RuntimeException('The AI proposal did not contain applicable changes.');return['summary'=>$summary?:'AI proposal ready for review.','before'=>$current,'after'=>$candidate,'changes'=>$changes];
    }

    public static function sanitizePostFields(array$fields):array
    {
        $plain=static fn(string$key,int$max):string=>mb_substr(trim(strip_tags((string)($fields[$key]??''))),0,$max);$tags=is_array($fields['tags']??null)?$fields['tags']:(preg_split('/[,;\r\n]+/u',(string)($fields['tags']??''))?:[]);$clean=[];foreach($tags as$tag){$tag=mb_substr(trim(strip_tags((string)$tag)),0,100);if($tag!==''&&!in_array(mb_strtolower($tag),array_map('mb_strtolower',$clean),true))$clean[]=$tag;if(count($clean)>=30)break;}return['title'=>$plain('title',255),'excerpt'=>$plain('excerpt',1200),'content'=>mb_substr(HtmlSanitizer::sanitize((string)($fields['content']??'')),0,100000),'seo_title'=>$plain('seo_title',255),'seo_description'=>$plain('seo_description',500),'tags'=>$clean];
    }

    private static function postEmpty(array$fields):bool{return trim((string)($fields['title']??''))===''&&trim(strip_tags((string)($fields['content']??'')))==='';}

    public static function limits(array$input):array
    {
        $int=static fn(string$key,int$max):int=>max(0,min($max,(int)($input[$key]??0)));$decimal=static function(string$key,float$max)use($input):string{$value=trim((string)($input[$key]??'0'));if($value===''||!is_numeric($value))$value='0';return number_format(max(0,min($max,(float)$value)),6,'.','');};
        $limits=['daily_requests'=>$int('daily_request_limit',1000000),'monthly_requests'=>$int('monthly_request_limit',10000000),'daily_tokens'=>$int('daily_token_limit',2000000000),'monthly_tokens'=>$int('monthly_token_limit',4000000000),'daily_cost_usd'=>$decimal('daily_cost_limit',1000000),'monthly_cost_usd'=>$decimal('monthly_cost_limit',10000000),'input_cost_per_million'=>$decimal('input_cost_per_million',1000000),'output_cost_per_million'=>$decimal('output_cost_per_million',1000000),'warning_percent'=>max(50,min(100,(int)($input['warning_percent']??80)))];
        if(((float)$limits['daily_cost_usd']>0||(float)$limits['monthly_cost_usd']>0)&&(float)$limits['input_cost_per_million']<=0&&(float)$limits['output_cost_per_million']<=0)throw new RuntimeException('Configure token pricing before enabling a cost budget.');return$limits;
    }

    public static function decodeProposal(string$text):array
    {
        $text=trim(preg_replace('/^```(?:json)?\s*|\s*```$/i','',$text)??$text);$start=strpos($text,'{');$end=strrpos($text,'}');if($start===false||$end===false||$end<$start)throw new RuntimeException('The AI provider did not return a structured proposal.');$decoded=json_decode(substr($text,$start,$end-$start+1),true);if(!is_array($decoded)||!is_array($decoded['sections']??null)||count($decoded['sections'])>30)throw new RuntimeException('The AI proposal has an invalid structure.');return$decoded;
    }

    public static function applyProposal(array$current,array$proposal,string$action,string$scope,string$uid,string$locale,array$locales,array$catalog):array
    {
        $generated=(array)($proposal['sections']??[]);if(in_array($action,['generate-page','add-sections'],true)){$new=[];$singletons=[];if($action==='add-sections')foreach($current as$block)if(!empty($catalog[$block['type']]['singleton']))$singletons[$block['type']]=true;foreach($generated as$item){if(!is_array($item)||!isset($catalog[(string)($item['type']??'')]))continue;$type=(string)$item['type'];if(!empty($catalog[$type]['singleton'])&&isset($singletons[$type]))continue;$singletons[$type]=true;$new[]=self::newBlock($type,(array)($item['content']??[]),$locale,$locales,$catalog[$type]);}if(!$new)throw new RuntimeException('The AI proposal did not contain any usable sections.');$candidate=$action==='generate-page'?$new:array_merge($current,$new);return PageBuilder::sanitizeBlocks($candidate,$catalog,$locales,true);}
        $byUid=[];foreach($generated as$item)if(is_array($item)&&preg_match('/^[a-f0-9-]{36}$/',(string)($item['uid']??'')))$byUid[(string)$item['uid']]=$item;$changed=false;$candidate=$current;
        foreach($candidate as&$block){$blockUid=(string)($block['uid']??'');if($scope==='section'&&$blockUid!==$uid)continue;$item=$byUid[$blockUid]??($scope==='section'&&count($generated)===1?$generated[0]:null);if(!is_array($item)||(isset($item['type'])&&(string)$item['type']!==(string)$block['type']))continue;$allowed=array_column((array)($catalog[$block['type']]['fields']??[]),'key');$content=array_intersect_key((array)($item['content']??[]),array_flip($allowed));if(!$content)continue;$block['localized'][$locale]=array_replace((array)($block['localized'][$locale]??[]),$content);$changed=true;}unset($block);if(!$changed)throw new RuntimeException('The AI proposal did not contain applicable changes.');return PageBuilder::sanitizeBlocks($candidate,$catalog,$locales,true);
    }

    private function context(array$blocks,array$catalog,string$scope,string$uid,string$locale,string$sourceLocale,array$quality):array
    {
        $result=[];foreach($blocks as$block){if($scope==='section'&&($block['uid']??'')!==$uid)continue;$fields=array_column((array)($catalog[$block['type']]['fields']??[]),'key');$result[]=['uid'=>$block['uid'],'type'=>$block['type'],'target_content'=>array_intersect_key((array)($block['localized'][$locale]??[]),array_flip($fields)),'source_content'=>array_intersect_key((array)($block['localized'][$sourceLocale]??[]),array_flip($fields))];}$issues=[];foreach(array_slice((array)($quality['issues']??[]),0,20)as$issue)if(($scope!=='section'||($issue['block_uid']??'')===$uid)&&(empty($issue['locale'])||$issue['locale']===$locale))$issues[]=['severity'=>$issue['severity']??'advice','message'=>$issue['message']??'','field'=>$issue['field']??''];return['sections'=>$result,'quality_issues'=>$issues];
    }
    private function schema(array$catalog):array{$result=[];foreach($catalog as$type=>$definition){$fields=[];foreach((array)($definition['fields']??[])as$field)$fields[]=['key'=>$field['key'],'type'=>$field['type'],'label'=>$field['label'],'required'=>$field['required']];$result[]=['type'=>$type,'label'=>$definition['label'],'singleton'=>$definition['singleton'],'fields'=>$fields];}return$result;}
    private static function newBlock(string$type,array$content,string$locale,array$locales,array$definition):array{$localized=[];foreach($locales as$item)$localized[$item]=array_replace((array)($definition['defaults']??[]),(array)($definition['localized_defaults'][$item]??[]));$allowed=array_column((array)($definition['fields']??[]),'key');$localized[$locale]=array_replace($localized[$locale]??[],array_intersect_key($content,array_flip($allowed)));return['uid'=>self::uuid(),'type'=>$type,'source'=>$definition['source'],'visible'=>true,'visible_from'=>null,'visible_until'=>null,'layout'=>PageBuilder::defaultLayout(),'appearance'=>PageBuilder::defaultAppearance(),'shared'=>$definition['shared_defaults']??[],'localized'=>$localized];}
    private static function uuid():string{$bytes=random_bytes(16);$bytes[6]=chr((ord($bytes[6])&0x0f)|0x40);$bytes[8]=chr((ord($bytes[8])&0x3f)|0x80);$hex=bin2hex($bytes);return substr($hex,0,8).'-'.substr($hex,8,4).'-'.substr($hex,12,4).'-'.substr($hex,16,4).'-'.substr($hex,20);}
}
