<?php

declare(strict_types=1);

namespace App\Core;

use PDO;
use RuntimeException;

final class MarketplaceGovernance
{
    public function __construct(private readonly PDO$db){}

    public function overview():array
    {
        $sources=$this->db->query('SELECT id,name,catalog_url,publisher_key_id,enabled,last_synced_at,last_error FROM marketplace_sources ORDER BY name')->fetchAll();$submissions=$this->db->query("SELECT s.id,s.type,s.slug,s.version,s.publisher_key_id,s.status,s.review_note,s.submitted_at,s.reviewed_at,COALESCE(u.name,'System') submitter FROM marketplace_submissions s LEFT JOIN users u ON u.id=s.submitted_by ORDER BY FIELD(s.status,'submitted','approved','rejected'),s.id DESC LIMIT 100")->fetchAll();
        return['sources'=>$sources,'submissions'=>$submissions,'counts'=>['sources'=>count($sources),'published'=>(int)$this->db->query("SELECT COUNT(*) FROM marketplace_entries WHERE status='published'")->fetchColumn(),'pending'=>count(array_filter($submissions,static fn(array$row):bool=>$row['status']==='submitted'))]];
    }

    public function publishedEntries():array
    {
        $rows=$this->db->query("SELECT e.*,p.name publisher,p.website publisher_url FROM marketplace_entries e INNER JOIN extension_publishers p ON p.key_id=e.publisher_key_id AND p.active=1 WHERE e.status='published' ORDER BY e.verified_at DESC")->fetchAll();foreach($rows as&$row){$manifest=json_decode((string)$row['manifest'],true);$row['manifest']=is_array($manifest)?$manifest:[];}unset($row);return$rows;
    }

    public function addSource(string$name,string$url,string$keyId,int$userId):array
    {
        $name=mb_substr(trim($name),0,150);$url=trim($url);$keyId=strtolower(trim($keyId));if(mb_strlen($name)<2||!$this->https($url))throw new RuntimeException('Provide a source name and a valid HTTPS catalog URL.');$publisher=$this->publisher($keyId);if(!$publisher)throw new RuntimeException('The catalog publisher key must be trusted and active first.');$this->db->prepare('INSERT INTO marketplace_sources (name,catalog_url,publisher_key_id,enabled,created_by,created_at,updated_at) VALUES (?,?,?,1,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),publisher_key_id=VALUES(publisher_key_id),enabled=1,updated_at=NOW()')->execute([$name,$url,$keyId,$userId?:null]);$id=(int)$this->db->lastInsertId();if(!$id){$statement=$this->db->prepare('SELECT id FROM marketplace_sources WHERE catalog_url=?');$statement->execute([$url]);$id=(int)$statement->fetchColumn();}$this->audit($userId,'marketplace.source.saved','marketplace_source',$id,['url_host'=>parse_url($url,PHP_URL_HOST),'publisher_key_id'=>$keyId]);return['id'=>$id,'name'=>$name];
    }

    public function sync(int$id,int$userId):array
    {
        $statement=$this->db->prepare('SELECT * FROM marketplace_sources WHERE id=? AND enabled=1');$statement->execute([$id]);$source=$statement->fetch();if(!$source)throw new RuntimeException('The catalog source is unavailable.');try{$envelope=json_decode($this->fetch((string)$source['catalog_url']),true,32,JSON_THROW_ON_ERROR);$signed=base64_decode((string)($envelope['signed_payload']??''),true);$signature=base64_decode((string)($envelope['signature']??''),true);$publisher=$this->publisher((string)$source['publisher_key_id']);$key=base64_decode((string)($publisher['public_key']??''),true);if(!is_string($signed)||!is_string($signature)||!is_string($key)||strlen($signature)!==SODIUM_CRYPTO_SIGN_BYTES||!sodium_crypto_sign_verify_detached($signature,$signed,$key))throw new RuntimeException('Remote catalog signature verification failed.');$payload=json_decode($signed,true,64,JSON_THROW_ON_ERROR);if((int)($payload['schema']??0)!==1||!is_array($payload['entries']??null)||count($payload['entries'])>2000)throw new RuntimeException('Remote catalog payload is invalid.');$count=0;$upsert=$this->db->prepare("INSERT INTO marketplace_entries (source_id,type,slug,version,release_channel,publisher_key_id,package_url,package_checksum,manifest,status,verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'published',NOW(),NOW(),NOW()) ON DUPLICATE KEY UPDATE package_url=VALUES(package_url),package_checksum=VALUES(package_checksum),manifest=VALUES(manifest),status='published',verified_at=NOW(),updated_at=NOW()");foreach($payload['entries']as$entry){$clean=$this->entry($entry,(string)$source['publisher_key_id']);$upsert->execute([$id,$clean['type'],$clean['slug'],$clean['version'],$clean['release_channel'],$source['publisher_key_id'],$clean['package_url'],$clean['package_checksum'],json_encode($clean['manifest'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);$count++;}$this->db->prepare('UPDATE marketplace_sources SET last_synced_at=NOW(),last_error=NULL,updated_at=NOW() WHERE id=?')->execute([$id]);$this->audit($userId,'marketplace.source.synced','marketplace_source',$id,['entries'=>$count]);return['entries'=>$count];}catch(\Throwable$error){$this->db->prepare('UPDATE marketplace_sources SET last_error=?,updated_at=NOW() WHERE id=?')->execute([mb_substr($error->getMessage(),0,500),$id]);throw$error;}
    }

    public function submit(array$staged,string$archive,int$userId):array
    {
        $key=(string)($staged['publisher']['key_id']??'');if(!$this->publisher($key))throw new RuntimeException('Only packages signed by an active trusted publisher can enter moderation.');$manifest=['name'=>$staged['name'],'description'=>$staged['description'],'engine'=>$staged['engine'],'publisher'=>$staged['publisher'],'permissions'=>$staged['permissions'],'dependencies'=>$staged['dependencies'],'release_channel'=>$staged['release_channel']??'stable'];$this->db->prepare("INSERT INTO marketplace_submissions (type,slug,version,publisher_key_id,archive_path,package_checksum,manifest,status,submitted_by,submitted_at,updated_at) VALUES (?,?,?,?,?,?,?,'submitted',?,NOW(),NOW()) ON DUPLICATE KEY UPDATE archive_path=VALUES(archive_path),package_checksum=VALUES(package_checksum),manifest=VALUES(manifest),status='submitted',review_note=NULL,submitted_by=VALUES(submitted_by),submitted_at=NOW(),reviewed_by=NULL,reviewed_at=NULL,updated_at=NOW()")->execute([$staged['type'],$staged['slug'],$staged['version'],$key,$archive,$staged['checksum'],json_encode($manifest,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$userId?:null]);$id=(int)$this->db->lastInsertId();if(!$id){$query=$this->db->prepare('SELECT id FROM marketplace_submissions WHERE type=? AND slug=? AND version=? AND publisher_key_id=?');$query->execute([$staged['type'],$staged['slug'],$staged['version'],$key]);$id=(int)$query->fetchColumn();}$this->audit($userId,'marketplace.submission.created','marketplace_submission',$id,['identity'=>$staged['type'].':'.$staged['slug'],'version'=>$staged['version']]);return['id'=>$id];
    }

    public function moderate(int$id,string$status,string$note,int$userId):void
    {
        if(!in_array($status,['approved','rejected'],true))throw new RuntimeException('Choose a valid moderation outcome.');$note=mb_substr(trim($note),0,1000);$statement=$this->db->prepare("UPDATE marketplace_submissions SET status=?,review_note=?,reviewed_by=?,reviewed_at=NOW(),updated_at=NOW() WHERE id=? AND status='submitted'");$statement->execute([$status,$note?:null,$userId?:null,$id]);if(!$statement->rowCount())throw new RuntimeException('The submission is no longer awaiting moderation.');$this->audit($userId,'marketplace.submission.'.$status,'marketplace_submission',$id,['note'=>$note]);
    }

    public function entryForInstall(int$id):array{$statement=$this->db->prepare("SELECT * FROM marketplace_entries WHERE id=? AND status='published'");$statement->execute([$id]);$row=$statement->fetch();if(!$row)throw new RuntimeException('The verified catalog release was not found.');return$row;}
    public function submissionForInstall(int$id):array{$statement=$this->db->prepare("SELECT * FROM marketplace_submissions WHERE id=? AND status='approved'");$statement->execute([$id]);$row=$statement->fetch();if(!$row)throw new RuntimeException('The approved submission was not found.');return$row;}

    private function entry(array$entry,string$keyId):array{$type=(string)($entry['type']??'');$slug=(string)($entry['slug']??'');$version=(string)($entry['version']??'');$channel=(string)($entry['release_channel']??'stable');$url=(string)($entry['package_url']??'');$checksum=(string)($entry['package_checksum']??'');if(!in_array($type,['theme','plugin','addon'],true)||!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$slug)||!preg_match('/^\d+\.\d+(?:\.\d+)?(?:-[0-9A-Za-z.-]+)?$/',$version)||!in_array($channel,['stable','beta','preview'],true)||!$this->https($url)||!preg_match('/^[a-f0-9]{64}$/',$checksum))throw new RuntimeException('A remote catalog entry is invalid.');$manifest=is_array($entry['manifest']??null)?$entry['manifest']:[];$manifest=array_replace($manifest,['slug'=>$slug,'version'=>$version,'release_channel'=>$channel,'publisher_key_id'=>$keyId]);return['type'=>$type,'slug'=>$slug,'version'=>$version,'release_channel'=>$channel,'package_url'=>$url,'package_checksum'=>$checksum,'manifest'=>$manifest];}
    private function publisher(string$keyId):?array{$statement=$this->db->prepare('SELECT * FROM extension_publishers WHERE key_id=? AND active=1');$statement->execute([$keyId]);$row=$statement->fetch();return$row?:null;}
    private function fetch(string$url):string{if(!$this->https($url))throw new RuntimeException('Catalog sources must use HTTPS.');$host=(string)parse_url($url,PHP_URL_HOST);$records=dns_get_record($host,DNS_A);$addresses=array_values(array_unique(array_filter(array_column($records?:[],'ip'))));if(!$addresses)throw new RuntimeException('Catalog host has no IPv4 address.');foreach($addresses as$address)if(!filter_var($address,FILTER_VALIDATE_IP,FILTER_FLAG_IPV4|FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))throw new RuntimeException('Catalog host resolves to a private or reserved address.');$port=(int)(parse_url($url,PHP_URL_PORT)?:443);$buffer='';$handle=curl_init($url);curl_setopt_array($handle,[CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>6,CURLOPT_TIMEOUT=>15,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS,CURLOPT_IPRESOLVE=>CURL_IPRESOLVE_V4,CURLOPT_RESOLVE=>[$host.':'.$port.':'.$addresses[0]],CURLOPT_WRITEFUNCTION=>static function($_handle,string$chunk)use(&$buffer):int{if(strlen($buffer)+strlen($chunk)>5242880)return 0;$buffer.=$chunk;return strlen($chunk);},CURLOPT_USERAGENT=>'SenseCMS-Marketplace/1.0']);$ok=curl_exec($handle);$code=(int)curl_getinfo($handle,CURLINFO_RESPONSE_CODE);$error=curl_error($handle);curl_close($handle);if($ok===false||$code<200||$code>=300)throw new RuntimeException('Catalog download failed'.($error!==''?': '.$error:'.'));return$buffer;}
    private function https(string$url):bool{return filter_var($url,FILTER_VALIDATE_URL)!==false&&strtolower((string)parse_url($url,PHP_URL_SCHEME))==='https'&&parse_url($url,PHP_URL_USER)===null&&parse_url($url,PHP_URL_PASS)===null;}
    private function audit(int$userId,string$event,string$type,int$id,array$context):void{$this->db->prepare('INSERT INTO activity_log (user_id,event,subject_type,subject_id,context,created_at) VALUES (?,?,?,?,?,NOW())')->execute([$userId?:null,$event,$type,$id,json_encode($context,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);}
}
