<?php

declare(strict_types=1);

namespace App\Core;

use RuntimeException;
use ZipArchive;

final class SurveyExport
{
    public static function csv(array$rows):string
    {
        $stream=fopen('php://temp','w+b');if(!$stream)throw new RuntimeException('CSV export could not be created.');fwrite($stream,"\xEF\xBB\xBF");$headers=$rows?array_keys($rows[0]):['Response ID','Status','Language','Facility','Started','Completed','Name','Email'];fputcsv($stream,$headers);foreach($rows as$row)fputcsv($stream,array_map(static fn($value)=>is_scalar($value)||$value===null?$value:json_encode($value,JSON_UNESCAPED_UNICODE),$row));rewind($stream);$output=stream_get_contents($stream);fclose($stream);return(string)$output;
    }

    public static function xlsx(array$rows,array$summary,string$title):string
    {
        if(!class_exists(ZipArchive::class))throw new RuntimeException('XLSX export requires the PHP ZIP extension.');$path=tempnam(sys_get_temp_dir(),'sensecms-survey-');if(!$path)throw new RuntimeException('XLSX workspace could not be created.');$zip=new ZipArchive();if($zip->open($path,ZipArchive::OVERWRITE)!==true){@unlink($path);throw new RuntimeException('XLSX archive could not be created.');}
        $headers=$rows?array_keys($rows[0]):['Response ID','Status','Language','Facility','Started','Completed','Name','Email'];$responseData=[$headers];foreach($rows as$row)$responseData[]=array_values($row);$summaryData=[['Survey report',$title],['Generated',gmdate('Y-m-d H:i:s').' UTC'],['Started',(int)($summary['started']??0)],['Completed',(int)($summary['completed']??0)],['Completion rate',(float)($summary['completion_rate']??0)/100],['NPS',$summary['nps']??''],['CSAT',$summary['csat']!==null?((float)$summary['csat']/100):'']];
        $files=['[Content_Types].xml'=>self::contentTypes(),'_rels/.rels'=>self::rels(),'xl/workbook.xml'=>self::workbook(),'xl/_rels/workbook.xml.rels'=>self::workbookRels(),'xl/styles.xml'=>self::styles(),'docProps/core.xml'=>self::core($title),'docProps/app.xml'=>self::app(),'xl/worksheets/sheet1.xml'=>self::sheet($summaryData,[5=>9,7=>9]),'xl/worksheets/sheet2.xml'=>self::sheet($responseData,[])];foreach($files as$name=>$content)$zip->addFromString($name,$content);$zip->close();$binary=file_get_contents($path);@unlink($path);if($binary===false)throw new RuntimeException('XLSX export could not be finalized.');return$binary;
    }

    public static function pdf(array$summary,array$questions,string$title):string
    {
        $lines=[];$lines[]=['title',self::ascii($title)?:'Survey report'];$lines[]=['meta','Generated '.gmdate('Y-m-d H:i:s').' UTC'];$lines[]=['section','Executive summary'];$lines[]=['body','Started responses: '.(int)($summary['started']??0)];$lines[]=['body','Completed responses: '.(int)($summary['completed']??0)];$lines[]=['body','Completion rate: '.number_format((float)($summary['completion_rate']??0),1).'%'];if(($summary['nps']??null)!==null)$lines[]=['body','Net Promoter Score: '.number_format((float)$summary['nps'],1)];if(($summary['csat']??null)!==null)$lines[]=['body','Customer Satisfaction: '.number_format((float)$summary['csat'],1).'%'];$lines[]=['section','Question performance'];foreach(array_slice($questions,0,40)as$question){$label=self::ascii((string)($question['label']??'Question'));$score=array_key_exists('score',$question)?' - score '.number_format((float)$question['score'],1):'';$lines[]=['body',self::wrap($label.' - '.(int)($question['responses']??0).' responses'.$score,92)];}
        return self::document($lines);
    }

    private static function sheet(array$rows,array$percentRows):string{$xml='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView showGridLines="0" workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>';for($i=1,$max=max(1,count($rows[0]??[]));$i<=$max;$i++)$xml.='<col min="'.$i.'" max="'.$i.'" width="'.($i<=8?20:28).'" customWidth="1"/>';$xml.='</cols><sheetData>';foreach($rows as$r=>$row){$xml.='<row r="'.($r+1).'"'.($r===0?' ht="24" customHeight="1"':'').'>';foreach(array_values($row)as$c=>$value){$ref=self::column($c+1).($r+1);$style=$r===0?1:(isset($percentRows[$r+1])?2:0);if(is_int($value)||is_float($value))$xml.='<c r="'.$ref.'" s="'.$style.'"><v>'.$value.'</v></c>';else$xml.='<c r="'.$ref.'" s="'.$style.'" t="inlineStr"><is><t xml:space="preserve">'.self::xml((string)$value).'</t></is></c>';}$xml.='</row>';}$last=self::column(max(1,count($rows[0]??[]))).max(1,count($rows));return$xml.'</sheetData><autoFilter ref="A1:'.$last.'"/><pageMargins left="0.4" right="0.4" top="0.5" bottom="0.5" header="0.2" footer="0.2"/></worksheet>';}
    private static function contentTypes():string{return'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>';}
    private static function rels():string{return'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>';}
    private static function workbook():string{return'<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Summary" sheetId="1" r:id="rId1"/><sheet name="Responses" sheetId="2" r:id="rId2"/></sheets></workbook>';}
    private static function workbookRels():string{return'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>';}
    private static function styles():string{return'<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Aptos"/><color rgb="FF223B57"/></font><font><b/><sz val="10"/><name val="Aptos Display"/><color rgb="FFFFFFFF"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF123F75"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><numFmts count="1"><numFmt numFmtId="164" formatCode="0.0%"/></numFmts><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment vertical="center"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>';}
    private static function core(string$title):string{return'<?xml version="1.0" encoding="UTF-8"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>'.self::xml($title).'</dc:title><dc:creator>SenseCMS</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">'.gmdate('Y-m-d\TH:i:s\Z').'</dcterms:created></cp:coreProperties>';}
    private static function app():string{return'<?xml version="1.0" encoding="UTF-8"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>SenseCMS</Application></Properties>';}
    private static function document(array$lines):string{$content="q\n";$y=790;foreach($lines as[$kind,$line]){$size=$kind==='title'?20:($kind==='section'?13:9);$font=$kind==='body'?'F1':'F2';if($kind==='section')$y-=12;foreach(explode("\n",(string)$line)as$part){$safe=str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$part);$content.="BT /$font $size Tf 50 $y Td ($safe) Tj ET\n";$y-=$kind==='title'?28:($kind==='section'?20:14);if($y<55)break 2;}}$content.="Q\n";$objects=[];$objects[]='<< /Type /Catalog /Pages 2 0 R >>';$objects[]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';$objects[]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>';$objects[]='<< /Length '.strlen($content).' >> stream' . "\n".$content.'endstream';$objects[]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';$objects[]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';$pdf="%PDF-1.4\n";$offsets=[0];foreach($objects as$i=>$object){$offsets[]=strlen($pdf);$pdf.=($i+1)." 0 obj\n$object\nendobj\n";}$xref=strlen($pdf);$pdf.="xref\n0 ".(count($objects)+1)."\n0000000000 65535 f \n";for($i=1;$i<=count($objects);$i++)$pdf.=sprintf('%010d 00000 n ',$offsets[$i])."\n";return$pdf.'trailer << /Size '.(count($objects)+1).' /Root 1 0 R >>'."\nstartxref\n$xref\n%%EOF";}
    private static function wrap(string$text,int$width):string{return wordwrap($text,$width,"\n",true);}
    private static function ascii(string$value):string{$ascii=@iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$value);return trim(preg_replace('/[^\x20-\x7E]/','',(string)$ascii)??'');}
    private static function xml(string$value):string{return htmlspecialchars($value,ENT_XML1|ENT_QUOTES,'UTF-8');}
    private static function column(int$number):string{$name='';while($number>0){$number--;$name=chr(65+$number%26).$name;$number=intdiv($number,26);}return$name;}
}
