<?php

declare(strict_types=1);

namespace App\Core;

use DateTimeImmutable;
use PDO;
use RuntimeException;
use Throwable;

final class SurveyRepository
{
    private const TYPES=['single','multiple','matrix','scale','nps','csat','text','date','consent'];
    public function __construct(private readonly PDO $db,private readonly string $secret='sensecms-surveys'){}

    public function listing(array$filters,?array$scope,int$page=1,int$perPage=20):array
    {
        $page=max(1,$page);$perPage=max(5,min(50,$perPage));$where=['s.archived_at IS NULL'];$params=[];
        $q=mb_substr(trim((string)($filters['q']??'')),0,120);if($q!==''){$where[]='(s.slug LIKE ? OR EXISTS(SELECT 1 FROM survey_translations st WHERE st.survey_id=s.id AND st.title LIKE ?))';$params[]='%'.$q.'%';$params[]='%'.$q.'%';}
        $status=(string)($filters['status']??'all');if(in_array($status,['draft','scheduled','published','closed'],true)){$where[]='s.status=?';$params[]=$status;}
        $facility=max(0,(int)($filters['facility_id']??0));if($facility){$where[]='EXISTS(SELECT 1 FROM survey_facilities sc WHERE sc.survey_id=s.id AND sc.facility_id=?)';$params[]=$facility;}
        $scopeSql=$this->scopeSql('s',$scope);$where[]=$scopeSql['sql'];$params=array_merge($params,$scopeSql['params']);$clause=implode(' AND ',$where);
        $count=$this->db->prepare('SELECT COUNT(*) FROM surveys s WHERE '.$clause);$count->execute($params);$total=(int)$count->fetchColumn();$offset=($page-1)*$perPage;
        $sql='SELECT s.*,COALESCE(t.title,s.slug) title,(SELECT COUNT(*) FROM survey_questions q WHERE q.survey_id=s.id) question_count,(SELECT COUNT(*) FROM survey_responses r WHERE r.survey_id=s.id AND r.status="completed") response_count,(SELECT COUNT(*) FROM survey_facilities c WHERE c.survey_id=s.id) facility_count FROM surveys s LEFT JOIN survey_translations t ON t.survey_id=s.id AND t.locale=(SELECT locale FROM languages WHERE enabled=1 ORDER BY is_default DESC,sort_order,id LIMIT 1) WHERE '.$clause.' ORDER BY s.updated_at DESC,s.id DESC LIMIT '.$perPage.' OFFSET '.$offset;
        $statement=$this->db->prepare($sql);$statement->execute($params);$items=$statement->fetchAll();foreach($items as&$item)$item['effective_status']=$this->effectiveStatus($item);unset($item);
        return['items'=>$items,'pagination'=>['page'=>$page,'pages'=>max(1,(int)ceil($total/$perPage)),'total'=>$total,'per_page'=>$perPage],'summary'=>$this->summary($scope)];
    }

    public function detail(int$id,?array$scope):array
    {
        $survey=$this->survey($id,$scope);$translations=[];$statement=$this->db->prepare('SELECT * FROM survey_translations WHERE survey_id=?');$statement->execute([$id]);foreach($statement->fetchAll()as$row)$translations[$row['locale']]=$row;
        $pages=[];$statement=$this->db->prepare('SELECT * FROM survey_pages WHERE survey_id=? ORDER BY sort_order,id');$statement->execute([$id]);foreach($statement->fetchAll()as$page){$page['translations']=[];$copy=$this->db->prepare('SELECT * FROM survey_page_translations WHERE page_id=?');$copy->execute([$page['id']]);foreach($copy->fetchAll()as$row)$page['translations'][$row['locale']]=$row;$questions=$this->db->prepare('SELECT * FROM survey_questions WHERE page_id=? ORDER BY sort_order,id');$questions->execute([$page['id']]);$page['questions']=[];foreach($questions->fetchAll()as$question){$question['settings']=$this->json($question['settings'],[]);$question['translations']=[];$copy=$this->db->prepare('SELECT * FROM survey_question_translations WHERE question_id=?');$copy->execute([$question['id']]);foreach($copy->fetchAll()as$row){$row['options']=$this->json($row['options'],[]);$question['translations'][$row['locale']]=$row;}$page['questions'][]=$question;}$pages[]=$page;}
        $rules=[];$statement=$this->db->prepare('SELECT r.*,sq.uid source_question_uid,tq.uid target_question_uid,tp.uid target_page_uid FROM survey_logic_rules r INNER JOIN survey_questions sq ON sq.id=r.source_question_id LEFT JOIN survey_questions tq ON tq.id=r.target_question_id LEFT JOIN survey_pages tp ON tp.id=r.target_page_id WHERE r.survey_id=? ORDER BY r.sort_order,r.id');$statement->execute([$id]);$rules=$statement->fetchAll();
        $facilities=$this->ids('SELECT facility_id FROM survey_facilities WHERE survey_id=?',[$id]);$targetPages=$this->ids('SELECT page_id FROM survey_target_pages WHERE survey_id=?',[$id]);
        return$survey+['translations'=>$translations,'pages'=>$pages,'logic'=>$rules,'facility_ids'=>$facilities,'target_page_ids'=>$targetPages,'effective_status'=>$this->effectiveStatus($survey)];
    }

    public function save(array$input,int$userId,?array$scope,bool$canPublish):array
    {
        $id=max(0,(int)($input['id']??0));$existing=$id?$this->survey($id,$scope):null;$slug=$this->slug((string)($input['slug']??''));if(mb_strlen($slug)<2)throw new RuntimeException('Survey slug must contain at least two URL-safe characters.');
        $status=in_array($input['status']??'draft',['draft','scheduled','published','closed'],true)?(string)$input['status']:'draft';if(in_array($status,['scheduled','published','closed'],true)&&!$canPublish)throw new RuntimeException('You do not have permission to publish or close surveys.',403);
        $opens=$this->date($input['opens_at']??null,'Opening date is invalid.');$closes=$this->date($input['closes_at']??null,'Closing date is invalid.');if($opens&&$closes&&$opens>=$closes)throw new RuntimeException('Closing date must be later than opening date.');if($status==='scheduled'&&!$opens)throw new RuntimeException('A scheduled survey requires an opening date.');
        $mode=in_array($input['response_mode']??'anonymous',['anonymous','identified'],true)?(string)$input['response_mode']:'anonymous';$rate=max(1,min(30,(int)($input['rate_limit']??5)));$retention=max(30,min(3650,(int)($input['retention_days']??365)));$anonymize=max(1,min($retention,(int)($input['anonymize_after_days']??90)));
        $facilities=array_values(array_unique(array_filter(array_map('intval',(array)($input['facility_ids']??[])))));if($scope!==null){foreach($facilities as$facility)if(!in_array($facility,$scope,true))throw new RuntimeException('A selected facility is outside your access scope.',403);if(!$facilities)throw new RuntimeException('Choose at least one facility within your access scope.');}$this->assertFacilities($facilities);
        $targetPages=array_values(array_unique(array_filter(array_map('intval',(array)($input['target_page_ids']??[])))));$this->assertTargetPages($targetPages,$facilities,$scope);
        $locales=$this->activeLocales();$translations=$this->translations((array)($input['translations']??[]),$locales);$pages=$this->sanitizePages((array)($input['pages']??[]),$locales);if(!$pages)throw new RuntimeException('Add at least one survey page.');
        $uid=$existing['uid']??$this->uuid();$this->db->beginTransaction();try{
            if($id){$statement=$this->db->prepare('UPDATE surveys SET slug=?,status=?,response_mode=?,one_response=?,captcha_enabled=?,rate_limit=?,opens_at=?,closes_at=?,retention_days=?,anonymize_after_days=?,updated_by=?,published_at=IF(?="published" AND published_at IS NULL,NOW(),published_at),updated_at=NOW() WHERE id=?');$statement->execute([$slug,$status,$mode,!empty($input['one_response'])?1:0,!empty($input['captcha_enabled'])?1:0,$rate,$opens,$closes,$retention,$anonymize,$userId,$status,$id]);}else{$statement=$this->db->prepare('INSERT INTO surveys (uid,slug,status,response_mode,one_response,captcha_enabled,rate_limit,opens_at,closes_at,retention_days,anonymize_after_days,created_by,updated_by,published_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,IF(?="published",NOW(),NULL),NOW(),NOW())');$statement->execute([$uid,$slug,$status,$mode,!empty($input['one_response'])?1:0,!empty($input['captcha_enabled'])?1:0,$rate,$opens,$closes,$retention,$anonymize,$userId,$userId,$status]);$id=(int)$this->db->lastInsertId();}
            $this->replaceTranslations($id,$translations);$this->db->prepare('DELETE FROM survey_logic_rules WHERE survey_id=?')->execute([$id]);
            $defaultLocale=$this->defaultLocale();$oldPages=[];$statement=$this->db->prepare('SELECT id,uid FROM survey_pages WHERE survey_id=?');$statement->execute([$id]);foreach($statement->fetchAll()as$row)$oldPages[$row['uid']]=(int)$row['id'];$oldQuestions=[];$statement=$this->db->prepare('SELECT q.id,q.uid,q.type,q.settings,qt.options FROM survey_questions q LEFT JOIN survey_question_translations qt ON qt.question_id=q.id AND qt.locale=? WHERE q.survey_id=?');$statement->execute([$defaultLocale,$id]);foreach($statement->fetchAll()as$row){$row['id']=(int)$row['id'];$row['settings']=$this->json($row['settings'],[]);$row['options']=$this->json($row['options'],[]);$oldQuestions[$row['uid']]=$row;}$answered=[];if($oldQuestions){$ids=array_column($oldQuestions,'id');$marks=implode(',',array_fill(0,count($ids),'?'));$statement=$this->db->prepare('SELECT DISTINCT question_id FROM survey_answers WHERE question_id IN ('.$marks.')');$statement->execute($ids);$answered=array_fill_keys(array_map('intval',$statement->fetchAll(PDO::FETCH_COLUMN)),true);}
            $pageMap=[];$questionMap=[];foreach($pages as$pageOrder=>$page){$pageId=$oldPages[$page['uid']]??0;if($pageId){$this->db->prepare('UPDATE survey_pages SET sort_order=? WHERE id=? AND survey_id=?')->execute([$pageOrder,$pageId,$id]);}else{$statement=$this->db->prepare('INSERT INTO survey_pages (survey_id,uid,sort_order) VALUES (?,?,?)');$statement->execute([$id,$page['uid'],$pageOrder]);$pageId=(int)$this->db->lastInsertId();}$pageMap[$page['uid']]=$pageId;$this->db->prepare('DELETE FROM survey_page_translations WHERE page_id=?')->execute([$pageId]);foreach($page['translations']as$locale=>$copy)$this->db->prepare('INSERT INTO survey_page_translations (page_id,locale,title,description) VALUES (?,?,?,?)')->execute([$pageId,$locale,$copy['title'],$copy['description']]);foreach($page['questions']as$order=>$question){$old=$oldQuestions[$question['uid']]??null;$questionId=(int)($old['id']??0);if($questionId&&!empty($answered[$questionId])&&$this->semanticSpec((string)$old['type'],(array)$old['settings'],(array)$old['options'])!==$this->semanticSpec($question['type'],$question['settings'],$question['translations'][$defaultLocale]['options']??[]))throw new RuntimeException('Questions with recorded responses cannot change type, scale or option values. Duplicate the survey to create a new structure.');if($questionId){$this->db->prepare('UPDATE survey_questions SET page_id=?,type=?,required=?,sort_order=?,settings=? WHERE id=? AND survey_id=?')->execute([$pageId,$question['type'],$question['required']?1:0,$order,$this->encode($question['settings']),$questionId,$id]);}else{$statement=$this->db->prepare('INSERT INTO survey_questions (survey_id,page_id,uid,type,required,sort_order,settings) VALUES (?,?,?,?,?,?,?)');$statement->execute([$id,$pageId,$question['uid'],$question['type'],$question['required']?1:0,$order,$this->encode($question['settings'])]);$questionId=(int)$this->db->lastInsertId();}$questionMap[$question['uid']]=$questionId;$this->db->prepare('DELETE FROM survey_question_translations WHERE question_id=?')->execute([$questionId]);foreach($question['translations']as$locale=>$copy)$this->db->prepare('INSERT INTO survey_question_translations (question_id,locale,label,help_text,options) VALUES (?,?,?,?,?)')->execute([$questionId,$locale,$copy['label'],$copy['help_text'],$this->encode($copy['options'])]);}}
            $removedQuestions=array_values(array_diff(array_column($oldQuestions,'id'),array_values($questionMap)));foreach($removedQuestions as$questionId)if(!empty($answered[(int)$questionId]))throw new RuntimeException('Questions with recorded responses cannot be removed. Duplicate the survey to create a new structure.');if($removedQuestions){$marks=implode(',',array_fill(0,count($removedQuestions),'?'));$this->db->prepare('DELETE FROM survey_question_translations WHERE question_id IN ('.$marks.')')->execute($removedQuestions);$this->db->prepare('DELETE FROM survey_questions WHERE id IN ('.$marks.')')->execute($removedQuestions);}$removedPages=array_values(array_diff(array_values($oldPages),array_values($pageMap)));if($removedPages){$marks=implode(',',array_fill(0,count($removedPages),'?'));$this->db->prepare('DELETE FROM survey_page_translations WHERE page_id IN ('.$marks.')')->execute($removedPages);$this->db->prepare('DELETE FROM survey_pages WHERE id IN ('.$marks.')')->execute($removedPages);}
            $rules=$this->sanitizeRules((array)($input['logic']??[]),$questionMap,$pageMap);foreach($rules as$order=>$rule)$this->db->prepare('INSERT INTO survey_logic_rules (survey_id,source_question_id,operator,compare_value,action,target_question_id,target_page_id,sort_order) VALUES (?,?,?,?,?,?,?,?)')->execute([$id,$rule['source'],$rule['operator'],$rule['value'],$rule['action'],$rule['target_question'],$rule['target_page'],$order]);
            $this->db->prepare('DELETE FROM survey_facilities WHERE survey_id=?')->execute([$id]);foreach($facilities as$facility)$this->db->prepare('INSERT INTO survey_facilities (survey_id,facility_id) VALUES (?,?)')->execute([$id,$facility]);$this->db->prepare('DELETE FROM survey_target_pages WHERE survey_id=?')->execute([$id]);foreach($targetPages as$pageId)$this->db->prepare('INSERT INTO survey_target_pages (survey_id,page_id) VALUES (?,?)')->execute([$id,$pageId]);
            $this->audit($userId,$existing?'survey.updated':'survey.created',$id,['status'=>$status,'questions'=>count($questionMap),'facilities'=>$facilities]);$this->db->commit();
        }catch(Throwable$error){if($this->db->inTransaction())$this->db->rollBack();if($error instanceof \PDOException&&str_contains(strtolower($error->getMessage()),'duplicate'))throw new RuntimeException('This survey slug is already in use.',0,$error);throw$error;}
        return$this->detail($id,$scope);
    }

    public function action(int$id,string$action,int$userId,?array$scope,bool$canPublish):array
    {
        $survey=$this->survey($id,$scope);if(!in_array($action,['archive','restore','duplicate','close'],true))throw new RuntimeException('Unknown survey action.');if(in_array($action,['archive','restore','close'],true)&&!$canPublish)throw new RuntimeException('You do not have permission to change survey publication.',403);
        if($action==='duplicate'){$copy=$this->detail($id,$scope);$copy['id']=0;$copy['slug']=$this->cloneSlug((string)$copy['slug']);$copy['status']='draft';$pageUids=[];$questionUids=[];foreach($copy['pages']as&$page){$oldPage=$page['uid'];$page['uid']=$this->uuid();$pageUids[$oldPage]=$page['uid'];foreach($page['questions']as&$question){$oldQuestion=$question['uid'];$question['uid']=$this->uuid();$questionUids[$oldQuestion]=$question['uid'];}unset($question);}unset($page);foreach($copy['logic']as&$rule){$rule['source_question_uid']=$questionUids[$rule['source_question_uid']]??'';$rule['target_question_uid']=$questionUids[$rule['target_question_uid']]??'';$rule['target_page_uid']=$pageUids[$rule['target_page_uid']]??'';}unset($rule);return$this->save($copy,$userId,$scope,false);}
        $status=match($action){'archive'=>'archived','restore'=>'draft','close'=>'closed'};$archived=$action==='archive'?date('Y-m-d H:i:s'):null;$this->db->prepare('UPDATE surveys SET status=?,archived_at=?,updated_by=?,updated_at=NOW() WHERE id=?')->execute([$status,$archived,$userId,$id]);$this->audit($userId,'survey.'.$action,$id,['from'=>$survey['status'],'to'=>$status]);return$this->detail($id,$scope);
    }

    public function publicSurvey(string$slug,string$locale,?int$facilityId=null,bool$preview=false):?array
    {
        $statement=$this->db->prepare('SELECT * FROM surveys WHERE slug=? AND archived_at IS NULL LIMIT 1');$statement->execute([$slug]);$survey=$statement->fetch();if(!$survey)return null;if(!$preview&&!$this->isPublic($survey))return null;$targets=$this->ids('SELECT facility_id FROM survey_facilities WHERE survey_id=?',[(int)$survey['id']]);if($facilityId&&$targets&&!in_array($facilityId,$targets,true))return null;if(!$facilityId&&count($targets)===1)$facilityId=$targets[0];$detail=$this->detail((int)$survey['id'],null);$fallback=$this->defaultLocale();$detail['copy']=$detail['translations'][$locale]??$detail['translations'][$fallback]??reset($detail['translations']);foreach($detail['pages']as&$page){$page['copy']=$page['translations'][$locale]??$page['translations'][$fallback]??reset($page['translations']);foreach($page['questions']as&$question)$question['copy']=$question['translations'][$locale]??$question['translations'][$fallback]??reset($question['translations']);unset($question);}unset($page);$detail['locale']=$locale;$detail['facility_id']=$facilityId;return$detail;
    }

    public function publicSurveyByUid(string$uid,string$locale,?int$facilityId=null):?array
    {
        if(!$this->validUuid($uid))return null;$statement=$this->db->prepare('SELECT slug FROM surveys WHERE uid=? LIMIT 1');$statement->execute([$uid]);$slug=$statement->fetchColumn();return$slug?$this->publicSurvey((string)$slug,$locale,$facilityId):null;
    }

    public function responseContext(string$uid):?array
    {
        if(!$this->validUuid($uid))return null;$statement=$this->db->prepare('SELECT s.uid survey_uid,s.captcha_enabled,r.locale FROM survey_responses r INNER JOIN surveys s ON s.id=r.survey_id WHERE r.uid=? LIMIT 1');$statement->execute([$uid]);return$statement->fetch()?:null;
    }

    public function start(int$surveyId,string$locale,?int$facilityId,string$visitorHash,array$metadata=[]):array
    {
        $survey=$this->survey($surveyId,null);if(!$this->isPublic($survey))throw new RuntimeException('This survey is not accepting responses.');$targets=$this->ids('SELECT facility_id FROM survey_facilities WHERE survey_id=?',[$surveyId]);if($targets&&(!$facilityId||!in_array($facilityId,$targets,true)))throw new RuntimeException('Choose an eligible facility for this survey.');$since=(new DateTimeImmutable('-15 minutes'))->format('Y-m-d H:i:s');$rate=$this->db->prepare('SELECT COUNT(*) FROM survey_responses WHERE survey_id=? AND visitor_hash=? AND started_at>=?');$rate->execute([$surveyId,$visitorHash,$since]);if((int)$rate->fetchColumn()>=(int)$survey['rate_limit'])throw new RuntimeException('Too many attempts. Please try again later.',429);if($survey['one_response']){$once=$this->db->prepare('SELECT 1 FROM survey_responses WHERE survey_id=? AND visitor_hash=? AND status="completed" LIMIT 1');$once->execute([$surveyId,$visitorHash]);if($once->fetchColumn())throw new RuntimeException('A response has already been submitted from this browser.',409);}
        $uid=$this->uuid();$token=bin2hex(random_bytes(24));$statement=$this->db->prepare('INSERT INTO survey_responses (uid,survey_id,facility_id,locale,status,token_hash,visitor_hash,metadata,started_at) VALUES (?,?,?,? ,"started",?,?,?,NOW())');$statement->execute([$uid,$surveyId,$facilityId,$locale,hash('sha256',$token),$visitorHash,$this->encode($metadata)]);return['uid'=>$uid,'token'=>$token];
    }

    public function submit(string$uid,string$token,array$input):array
    {
        $statement=$this->db->prepare('SELECT r.*,s.response_mode,s.status survey_status,s.one_response,s.opens_at,s.closes_at FROM survey_responses r INNER JOIN surveys s ON s.id=r.survey_id WHERE r.uid=? LIMIT 1');$statement->execute([$uid]);$response=$statement->fetch();if(!$response||!hash_equals((string)$response['token_hash'],hash('sha256',$token)))throw new RuntimeException('Survey response session is invalid.',419);if($response['status']!=='started')throw new RuntimeException('This response has already been completed.',409);if(!$this->isPublic($response,'survey_status'))throw new RuntimeException('This survey is no longer accepting responses.');
        $detail=$this->detail((int)$response['survey_id'],null);$answers=is_array($input['answers']??null)?$input['answers']:[];$visible=$this->visibleQuestions($detail,$answers);$validated=[];foreach($detail['pages']as$page)foreach($page['questions']as$question){$key=$question['uid'];if(!isset($visible[$key]))continue;$value=$answers[$key]??null;$validated[(int)$question['id']]=$this->answer($question,$value);}
        $name=mb_substr(trim((string)($input['name']??'')),0,190);$email=mb_substr(trim((string)($input['email']??'')),0,190);if($response['response_mode']==='identified'){if(mb_strlen($name)<2)throw new RuntimeException('Enter your name.');if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a valid email address.');}else{$name='';$email='';}
        $this->db->beginTransaction();try{foreach($validated as$questionId=>$value){$text=is_array($value)?implode(', ',array_map('strval',$value)):(is_bool($value)?($value?'Yes':'No'):(string)$value);$numeric=is_numeric($value)?(float)$value:null;$this->db->prepare('INSERT INTO survey_answers (response_id,question_id,value,text_value,numeric_value,created_at) VALUES (?,?,?,?,?,NOW())')->execute([$response['id'],$questionId,$this->encode($value),mb_substr($text,0,10000),$numeric]);}$this->db->prepare('UPDATE survey_responses SET status="completed",respondent_name=?,respondent_email=?,completed_at=NOW() WHERE id=? AND status="started"')->execute([$name?:null,$email?:null,$response['id']]);$this->db->prepare('INSERT INTO activity_log (user_id,event,subject_type,subject_id,context,created_at) VALUES (NULL,"survey.response.completed","survey",?,?,NOW())')->execute([$response['survey_id'],$this->encode(['response_uid'=>$uid,'facility_id'=>$response['facility_id'],'locale'=>$response['locale']])]);$this->db->commit();}catch(Throwable$error){if($this->db->inTransaction())$this->db->rollBack();throw$error;}return['response_uid'=>$uid,'completed'=>true];
    }

    public function responses(int$id,array$filters,?array$scope,int$page=1,int$perPage=30):array
    {
        $this->survey($id,$scope);$page=max(1,$page);$where=['r.survey_id=?'];$params=[$id];$status=(string)($filters['status']??'all');if(in_array($status,['started','completed','abandoned','disqualified'],true)){$where[]='r.status=?';$params[]=$status;}$facility=max(0,(int)($filters['facility_id']??0));if($facility){$where[]='r.facility_id=?';$params[]=$facility;}$from=$this->date($filters['from']??null,'Invalid start date.',true);if($from){$where[]='r.started_at>=?';$params[]=$from;}$to=$this->date($filters['to']??null,'Invalid end date.',true);if($to){$where[]='r.started_at<=?';$params[]=$to;}$clause=implode(' AND ',$where);$count=$this->db->prepare('SELECT COUNT(*) FROM survey_responses r WHERE '.$clause);$count->execute($params);$total=(int)$count->fetchColumn();$statement=$this->db->prepare('SELECT r.*,c.city_slug,c.facility_slug,COALESCE(ct.name,c.facility_slug) facility_name FROM survey_responses r LEFT JOIN facilities c ON c.id=r.facility_id LEFT JOIN facility_translations ct ON ct.facility_id=c.id AND ct.locale=r.locale WHERE '.$clause.' ORDER BY r.started_at DESC LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage));$statement->execute($params);return['items'=>$statement->fetchAll(),'pagination'=>['page'=>$page,'pages'=>max(1,(int)ceil($total/$perPage)),'total'=>$total]];
    }

    public function response(int$surveyId,string$uid,?array$scope):array
    {
        $detail=$this->detail($surveyId,$scope);$statement=$this->db->prepare('SELECT r.*,c.city_slug,c.facility_slug FROM survey_responses r LEFT JOIN facilities c ON c.id=r.facility_id WHERE r.survey_id=? AND r.uid=? LIMIT 1');$statement->execute([$surveyId,$uid]);$response=$statement->fetch();if(!$response)throw new RuntimeException('Survey response was not found.',404);$labels=[];foreach($detail['pages']as$page)foreach($page['questions']as$question){$copy=$question['translations'][$response['locale']]??$question['translations'][$this->defaultLocale()]??reset($question['translations']);$labels[(int)$question['id']]=['label'=>$copy['label']??$question['uid'],'type'=>$question['type']];}$answers=$this->db->prepare('SELECT question_id,value,text_value,numeric_value FROM survey_answers WHERE response_id=? ORDER BY id');$answers->execute([$response['id']]);$response['answers']=[];foreach($answers->fetchAll()as$answer)if(isset($labels[(int)$answer['question_id']]))$response['answers'][]=$labels[(int)$answer['question_id']]+['value'=>$this->json($answer['value'],$answer['text_value']),'text_value'=>$answer['text_value'],'numeric_value'=>$answer['numeric_value']];return$response;
    }

    public function anonymizeNow(int$id,int$userId,?array$scope):int
    {
        $this->survey($id,$scope);$statement=$this->db->prepare('UPDATE survey_responses SET respondent_name=NULL,respondent_email=NULL,token_hash=NULL,visitor_hash=NULL,metadata=JSON_OBJECT(),anonymized_at=NOW() WHERE survey_id=? AND status="completed" AND anonymized_at IS NULL');$statement->execute([$id]);$count=$statement->rowCount();$this->audit($userId,'survey.responses.anonymized',$id,['responses'=>$count]);return$count;
    }

    public function statistics(int$id,array$filters,?array$scope):array
    {
        $detail=$this->detail($id,$scope);$where=['r.survey_id=?'];$params=[$id];$facility=max(0,(int)($filters['facility_id']??0));if($facility){$where[]='r.facility_id=?';$params[]=$facility;}$clause=implode(' AND ',$where);$statement=$this->db->prepare('SELECT COUNT(*) started,SUM(status="completed") completed,SUM(status="abandoned") abandoned,AVG(TIMESTAMPDIFF(SECOND,started_at,completed_at)) avg_seconds FROM survey_responses r WHERE '.$clause);$statement->execute($params);$summary=$statement->fetch()?:[];$summary=array_map(static fn($v)=>(float)$v,$summary);$summary['completion_rate']=$summary['started']?round($summary['completed']/$summary['started']*100,1):0;
        $questions=[];$nps=[];$csat=[];foreach($detail['pages']as$page)foreach($page['questions']as$question){$copy=$question['translations'][$this->defaultLocale()]??reset($question['translations']);$row=['uid'=>$question['uid'],'type'=>$question['type'],'label'=>$copy['label']??$question['uid'],'responses'=>0,'distribution'=>[]];$answers=$this->db->prepare('SELECT a.text_value,a.numeric_value,COUNT(*) total FROM survey_answers a INNER JOIN survey_responses r ON r.id=a.response_id WHERE a.question_id=? AND r.status="completed"'.($facility?' AND r.facility_id=?':'').' GROUP BY a.text_value,a.numeric_value ORDER BY total DESC');$answers->execute($facility?[$question['id'],$facility]:[$question['id']]);foreach($answers->fetchAll()as$answer){$row['responses']+=(int)$answer['total'];$row['distribution'][]=['value'=>$answer['text_value'],'numeric'=>$answer['numeric_value']!==null?(float)$answer['numeric_value']:null,'count'=>(int)$answer['total']];}$values=[];foreach($row['distribution']as$item)for($i=0;$i<$item['count'];$i++)if($item['numeric']!==null)$values[]=$item['numeric'];if($question['type']==='nps'&&$values){$promoters=count(array_filter($values,fn($v)=>$v>=9));$detractors=count(array_filter($values,fn($v)=>$v<=6));$row['score']=round(($promoters-$detractors)/count($values)*100,1);$nps[]=$row['score'];}if($question['type']==='csat'&&$values){$positive=count(array_filter($values,fn($v)=>$v>=4));$row['score']=round($positive/count($values)*100,1);$csat[]=$row['score'];}$questions[]=$row;}
        $funnel=[];foreach($detail['pages']as$page){$ids=array_map(fn($q)=>(int)$q['id'],$page['questions']);$reached=0;if($ids){$marks=implode(',',array_fill(0,count($ids),'?'));$query=$this->db->prepare('SELECT COUNT(DISTINCT a.response_id) FROM survey_answers a INNER JOIN survey_responses r ON r.id=a.response_id WHERE a.question_id IN ('.$marks.') AND r.survey_id=?'.($facility?' AND r.facility_id=?':''));$query->execute(array_merge($ids,[$id],$facility?[$facility]:[]));$reached=(int)$query->fetchColumn();}$copy=$page['translations'][$this->defaultLocale()]??reset($page['translations']);$funnel[]=['uid'=>$page['uid'],'title'=>$copy['title']??'Survey page','reached'=>$reached];}
        return['summary'=>$summary+['nps'=>$nps?round(array_sum($nps)/count($nps),1):null,'csat'=>$csat?round(array_sum($csat)/count($csat),1):null],'questions'=>$questions,'funnel'=>$funnel,'trend'=>$this->trend($id,$facility),'cross_tab'=>$this->crossTab($detail,$facility)];
    }

    public function exportRows(int$id,?array$scope):array
    {
        $detail=$this->detail($id,$scope);$questions=[];foreach($detail['pages']as$page)foreach($page['questions']as$question){$copy=$question['translations'][$this->defaultLocale()]??reset($question['translations']);$questions[(int)$question['id']]=['uid'=>$question['uid'],'label'=>$copy['label']??$question['uid']];}$statement=$this->db->prepare('SELECT r.*,c.city_slug,c.facility_slug FROM survey_responses r LEFT JOIN facilities c ON c.id=r.facility_id WHERE r.survey_id=? ORDER BY r.started_at');$statement->execute([$id]);$rows=[];foreach($statement->fetchAll()as$response){$row=['Response ID'=>$response['uid'],'Status'=>$response['status'],'Language'=>$response['locale'],'Facility'=>trim((string)$response['city_slug'].' / '.(string)$response['facility_slug']),'Started'=>$response['started_at'],'Completed'=>$response['completed_at'],'Name'=>$response['respondent_name'],'Email'=>$response['respondent_email']];$answers=$this->db->prepare('SELECT question_id,text_value FROM survey_answers WHERE response_id=?');$answers->execute([$response['id']]);foreach($questions as$question)$row[$question['label']]='';foreach($answers->fetchAll()as$answer)if(isset($questions[(int)$answer['question_id']]))$row[$questions[(int)$answer['question_id']]['label']]=$answer['text_value'];$rows[]=$row;}return['survey'=>$detail,'rows'=>$rows];
    }

    public function maintain(int$limit=500):array
    {
        $opened=$this->db->exec("UPDATE surveys SET status='published',published_at=COALESCE(published_at,NOW()),updated_at=NOW() WHERE status='scheduled' AND opens_at<=NOW() AND (closes_at IS NULL OR closes_at>NOW())");$closed=$this->db->exec("UPDATE surveys SET status='closed',updated_at=NOW() WHERE status IN ('scheduled','published') AND closes_at IS NOT NULL AND closes_at<=NOW()");$surveys=$this->db->query('SELECT id,retention_days,anonymize_after_days FROM surveys')->fetchAll();$anonymized=0;$deleted=0;foreach($surveys as$survey){$cut=(new DateTimeImmutable())->modify('-'.(int)$survey['anonymize_after_days'].' days')->format('Y-m-d H:i:s');$statement=$this->db->prepare('UPDATE survey_responses SET respondent_name=NULL,respondent_email=NULL,token_hash=NULL,visitor_hash=NULL,metadata=JSON_OBJECT(),anonymized_at=NOW() WHERE survey_id=? AND status="completed" AND anonymized_at IS NULL AND completed_at<? LIMIT '.$limit);$statement->execute([$survey['id'],$cut]);$anonymized+=$statement->rowCount();$retention=(new DateTimeImmutable())->modify('-'.(int)$survey['retention_days'].' days')->format('Y-m-d H:i:s');$ids=$this->ids('SELECT id FROM survey_responses WHERE survey_id=? AND COALESCE(completed_at,started_at)<? LIMIT '.$limit,[$survey['id'],$retention]);if($ids){$marks=implode(',',array_fill(0,count($ids),'?'));$this->db->prepare('DELETE FROM survey_answers WHERE response_id IN ('.$marks.')')->execute($ids);$this->db->prepare('DELETE FROM survey_responses WHERE id IN ('.$marks.')')->execute($ids);$deleted+=count($ids);}}return['ok'=>true,'opened'=>$opened,'closed'=>$closed,'anonymized'=>$anonymized,'deleted'=>$deleted];
    }

    public function visitorHash(string$ip,string$userAgent):string{return hash_hmac('sha256',$ip.'|'.mb_substr($userAgent,0,300),$this->secret?:'sensecms-surveys');}
    public function recentCompletedCount(?array$scope):int{$scopeSql=$this->scopeSql('s',$scope);$statement=$this->db->prepare('SELECT COUNT(*) FROM survey_responses r INNER JOIN surveys s ON s.id=r.survey_id WHERE r.status="completed" AND r.completed_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND '.$scopeSql['sql']);$statement->execute($scopeSql['params']);return(int)$statement->fetchColumn();}

    private function sanitizePages(array$input,array$locales):array
    {
        if(count($input)>20)throw new RuntimeException('A survey can contain up to 20 pages.');$pages=[];$uids=[];$questionUids=[];$total=0;foreach($input as$page){if(!is_array($page))continue;$uid=$this->validUuid((string)($page['uid']??''))?(string)$page['uid']:$this->uuid();if(isset($uids[$uid]))throw new RuntimeException('Survey page identifiers must be unique.');$uids[$uid]=true;$translations=[];foreach($locales as$locale){$copy=(array)($page['translations'][$locale]??[]);$translations[$locale]=['title'=>mb_substr(trim((string)($copy['title']??'')),0,255),'description'=>mb_substr(trim((string)($copy['description']??'')),0,1000)];}$questions=[];foreach((array)($page['questions']??[])as$question){if(!is_array($question))continue;if(++$total>100)throw new RuntimeException('A survey can contain up to 100 questions.');$qUid=$this->validUuid((string)($question['uid']??''))?(string)$question['uid']:$this->uuid();if(isset($questionUids[$qUid]))throw new RuntimeException('Question identifiers must be unique.');$questionUids[$qUid]=true;$type=in_array($question['type']??'',self::TYPES,true)?(string)$question['type']:'text';$settings=$this->settings($type,(array)($question['settings']??[]));$copy=[];foreach($locales as$locale){$translation=(array)($question['translations'][$locale]??[]);$label=mb_substr(trim((string)($translation['label']??'')),0,500);if($label==='')throw new RuntimeException('Every question requires a label in '.$locale.'.');$options=$this->options($type,$translation['options']??[],$locale);$copy[$locale]=['label'=>$label,'help_text'=>mb_substr(trim((string)($translation['help_text']??'')),0,1000),'options'=>$options];}if(in_array($type,['single','multiple','matrix'],true)){$baseLocale=$this->defaultLocale();if(!isset($copy[$baseLocale]))$baseLocale=$locales[0];foreach(['choices','rows']as$group){$base=$copy[$baseLocale]['options'][$group]??[];foreach($copy as$locale=>&$translation){$items=$translation['options'][$group]??[];if(count($items)!==count($base))throw new RuntimeException('Translated option counts must match for '.$locale.'.');foreach($items as$index=>&$item)$item['value']=$base[$index]['value'];unset($item);$translation['options'][$group]=$items;}unset($translation);}}$questions[]=['uid'=>$qUid,'type'=>$type,'required'=>!empty($question['required']),'settings'=>$settings,'translations'=>$copy];}$pages[]=['uid'=>$uid,'translations'=>$translations,'questions'=>$questions];}return$pages;
    }

    private function translations(array$input,array$locales):array{$result=[];foreach($locales as$locale){$copy=(array)($input[$locale]??[]);$title=mb_substr(trim((string)($copy['title']??'')),0,255);if($title==='')throw new RuntimeException('Survey title is required in '.$locale.'.');$result[$locale]=['title'=>$title,'introduction'=>mb_substr(trim((string)($copy['introduction']??'')),0,10000),'success_message'=>mb_substr(trim((string)($copy['success_message']??'')),0,1000),'closed_message'=>mb_substr(trim((string)($copy['closed_message']??'')),0,1000)];}return$result;}
    private function replaceTranslations(int$id,array$translations):void{$this->db->prepare('DELETE FROM survey_translations WHERE survey_id=?')->execute([$id]);foreach($translations as$locale=>$copy)$this->db->prepare('INSERT INTO survey_translations (survey_id,locale,title,introduction,success_message,closed_message) VALUES (?,?,?,?,?,?)')->execute([$id,$locale,$copy['title'],$copy['introduction'],$copy['success_message'],$copy['closed_message']]);}
    private function settings(string$type,array$input):array{$settings=['min'=>max(0,min(100,(int)($input['min']??($type==='nps'?0:1)))),'max'=>max(1,min(100,(int)($input['max']??($type==='nps'?10:5)))),'max_length'=>max(50,min(10000,(int)($input['max_length']??2000))),'allow_other'=>!empty($input['allow_other'])];if($settings['max']<=$settings['min'])$settings['max']=$settings['min']+1;return$settings;}
    private function options(string$type,mixed$input,string$locale):array{if(!in_array($type,['single','multiple','matrix'],true))return[];$input=is_array($input)?$input:[];$clean=[];foreach(['choices','rows']as$group){$items=[];foreach(array_slice((array)($input[$group]??($group==='choices'?$input:[])),0,50)as$item){$item=is_array($item)?$item:['label'=>$item];$label=mb_substr(trim((string)($item['label']??'')),0,255);if($label==='')continue;$value=$this->slug((string)($item['value']??$label));if($value==='')$value='option-'.(count($items)+1);$items[]=['value'=>$value,'label'=>$label];}$clean[$group]=$items;}if(!$clean['choices'])throw new RuntimeException('Choice questions require options in '.$locale.'.');if($type==='matrix'&&!$clean['rows'])throw new RuntimeException('Matrix questions require rows in '.$locale.'.');return$clean;}
    private function sanitizeRules(array$input,array$questions,array$pages):array{$rules=[];foreach(array_slice($input,0,100)as$rule){if(!is_array($rule))continue;$source=$questions[(string)($rule['source_question_uid']??'')]??0;$action=in_array($rule['action']??'',['show','hide','skip_page','end'],true)?(string)$rule['action']:'';$operator=in_array($rule['operator']??'',['equals','not_equals','contains','greater_than','less_than','answered','not_answered'],true)?(string)$rule['operator']:'';$targetQuestion=$questions[(string)($rule['target_question_uid']??'')]??null;$targetPage=$pages[(string)($rule['target_page_uid']??'')]??null;if(!$source||!$action||!$operator)continue;if(in_array($action,['show','hide'],true)&&!$targetQuestion)continue;if($action==='skip_page'&&!$targetPage)continue;$rules[]=['source'=>$source,'operator'=>$operator,'value'=>mb_substr(trim((string)($rule['compare_value']??'')),0,500),'action'=>$action,'target_question'=>$targetQuestion,'target_page'=>$targetPage];}return$rules;}
    private function answer(array$question,mixed$value):mixed{$type=$question['type'];$required=(bool)$question['required'];$copy=$question['translations'][$this->defaultLocale()]??reset($question['translations']);$options=(array)($copy['options']??[]);$choices=array_values(array_map(static fn(array$item):string=>(string)($item['value']??''),array_filter((array)($options['choices']??[]),'is_array')));if($type==='multiple'){$value=is_array($value)?array_values(array_unique(array_map('strval',$value))):[];if($required&&!$value)throw new RuntimeException('A required question has not been answered.');if(array_diff($value,$choices))throw new RuntimeException('A choice answer is invalid.');return array_slice($value,0,50);}if($type==='matrix'){$value=is_array($value)?array_map('strval',$value):[];$rows=array_values(array_map(static fn(array$item):string=>(string)($item['value']??''),array_filter((array)($options['rows']??[]),'is_array')));if($required&&array_diff($rows,array_keys($value)))throw new RuntimeException('Complete every required matrix question.');if(array_diff(array_keys($value),$rows)||array_diff(array_values($value),$choices))throw new RuntimeException('A matrix answer is invalid.');return$value;}if($type==='consent'){$value=filter_var($value,FILTER_VALIDATE_BOOL);if($required&&!$value)throw new RuntimeException('Required consent must be accepted.');return$value;}$value=is_array($value)?'':trim((string)$value);if($required&&$value==='')throw new RuntimeException('A required question has not been answered.');if($type==='single'&&$value!==''&&!in_array($value,$choices,true))throw new RuntimeException('A choice answer is invalid.');if($type==='date'&&$value!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$value))throw new RuntimeException('Enter a valid date.');if(in_array($type,['scale','nps','csat'],true)&&$value!==''){$number=(float)$value;$min=(float)$question['settings']['min'];$max=(float)$question['settings']['max'];if(!is_numeric($value)||$number<$min||$number>$max)throw new RuntimeException('A rating is outside the allowed scale.');return$number;}if(mb_strlen($value)>(int)$question['settings']['max_length'])throw new RuntimeException('An answer exceeds its character limit.');return$value;}
    private function visibleQuestions(array$detail,array$answers):array{$visible=[];$pageById=[];foreach($detail['pages']as$page){$pageById[(int)$page['id']]=$page;foreach($page['questions']as$q)$visible[$q['uid']]=true;}foreach($detail['logic']as$rule)if($rule['action']==='show')unset($visible[$rule['target_question_uid']]);foreach($detail['logic']as$rule){$value=$answers[$rule['source_question_uid']]??null;if(!$this->condition($value,$rule['operator'],$rule['compare_value']))continue;if($rule['action']==='show')$visible[$rule['target_question_uid']]=true;if($rule['action']==='hide')unset($visible[$rule['target_question_uid']]);if($rule['action']==='skip_page'&&isset($pageById[(int)$rule['target_page_id']]))foreach($pageById[(int)$rule['target_page_id']]['questions']as$q)unset($visible[$q['uid']]);if($rule['action']==='end'){foreach($detail['pages']as$page){$after=false;foreach($page['questions']as$q){if($after)unset($visible[$q['uid']]);if($q['uid']===$rule['source_question_uid'])$after=true;}}}}return$visible;}
    private function condition(mixed$value,string$operator,string$compare):bool{$values=is_array($value)?array_map('strval',$value):[(string)$value];$text=implode(' ',$values);return match($operator){'equals'=>in_array($compare,$values,true),'not_equals'=>!in_array($compare,$values,true),'contains'=>str_contains(mb_strtolower($text),mb_strtolower($compare)),'greater_than'=>is_numeric($text)&&(float)$text>(float)$compare,'less_than'=>is_numeric($text)&&(float)$text<(float)$compare,'answered'=>$text!=='','not_answered'=>$text==='',default=>false};}
    private function trend(int$id,int$facility):array{$sql='SELECT DATE(completed_at) day,COUNT(*) total FROM survey_responses WHERE survey_id=? AND status="completed" AND completed_at>=DATE_SUB(CURDATE(),INTERVAL 29 DAY)'.($facility?' AND facility_id=?':'').' GROUP BY DATE(completed_at) ORDER BY day';$statement=$this->db->prepare($sql);$statement->execute($facility?[$id,$facility]:[$id]);return$statement->fetchAll();}
    private function crossTab(array$detail,int$facility):array{$choices=[];foreach($detail['pages']as$page)foreach($page['questions']as$q)if(in_array($q['type'],['single','scale','nps','csat'],true))$choices[]=$q;if(count($choices)<2)return[];[$a,$b]=$choices;$sql='SELECT aa.text_value row_value,ab.text_value column_value,COUNT(*) total FROM survey_answers aa INNER JOIN survey_answers ab ON ab.response_id=aa.response_id INNER JOIN survey_responses r ON r.id=aa.response_id WHERE aa.question_id=? AND ab.question_id=? AND r.status="completed"'.($facility?' AND r.facility_id=?':'').' GROUP BY aa.text_value,ab.text_value ORDER BY aa.text_value,ab.text_value';$statement=$this->db->prepare($sql);$statement->execute($facility?[$a['id'],$b['id'],$facility]:[$a['id'],$b['id']]);return['row_question'=>$a['uid'],'column_question'=>$b['uid'],'cells'=>$statement->fetchAll()];}
    private function survey(int$id,?array$scope):array{$scopeSql=$this->scopeSql('s',$scope);$statement=$this->db->prepare('SELECT s.* FROM surveys s WHERE s.id=? AND '.$scopeSql['sql'].' LIMIT 1');$statement->execute(array_merge([$id],$scopeSql['params']));$row=$statement->fetch();if(!$row)throw new RuntimeException('Survey was not found or is outside your facility scope.',404);return$row;}
    private function scopeSql(string$alias,?array$scope):array{if($scope===null)return['sql'=>'1=1','params'=>[]];$scope=array_values(array_unique(array_map('intval',$scope)));if(!$scope)return['sql'=>'NOT EXISTS(SELECT 1 FROM survey_facilities sx WHERE sx.survey_id='.$alias.'.id)','params'=>[]];return['sql'=>'(NOT EXISTS(SELECT 1 FROM survey_facilities sx WHERE sx.survey_id='.$alias.'.id) OR EXISTS(SELECT 1 FROM survey_facilities sx WHERE sx.survey_id='.$alias.'.id AND sx.facility_id IN ('.implode(',',array_fill(0,count($scope),'?')).')))','params'=>$scope];}
    private function summary(?array$scope):array{$scopeSql=$this->scopeSql('s',$scope);$statement=$this->db->prepare('SELECT COUNT(*) total,SUM(s.status="published") published,SUM(s.status="scheduled") scheduled,(SELECT COUNT(*) FROM survey_responses r INNER JOIN surveys sr ON sr.id=r.survey_id WHERE r.status="completed" AND '.$this->scopeSql('sr',$scope)['sql'].') responses FROM surveys s WHERE s.archived_at IS NULL AND '.$scopeSql['sql']);$params=array_merge($this->scopeSql('sr',$scope)['params'],$scopeSql['params']);$statement->execute($params);return array_map('intval',$statement->fetch()?:[]);}
    private function assertFacilities(array$ids):void{if(!$ids)return;$marks=implode(',',array_fill(0,count($ids),'?'));$statement=$this->db->prepare('SELECT COUNT(*) FROM facilities WHERE id IN ('.$marks.') AND status="active"');$statement->execute($ids);if((int)$statement->fetchColumn()!==count($ids))throw new RuntimeException('Choose valid active facilities.');}
    private function assertTargetPages(array$ids,array$facilities,?array$scope):void{if(!$ids)return;$marks=implode(',',array_fill(0,count($ids),'?'));$statement=$this->db->prepare('SELECT facility_id FROM pages WHERE id IN ('.$marks.') AND status<>"archived"');$statement->execute($ids);$found=array_map('intval',$statement->fetchAll(PDO::FETCH_COLUMN));if(count($found)!==count($ids))throw new RuntimeException('One or more target pages are unavailable.');foreach($found as$facility)if(($facilities&&!in_array($facility,$facilities,true))||($scope!==null&&!in_array($facility,$scope,true)))throw new RuntimeException('Target pages must belong to selected accessible facilities.');}
    private function activeLocales():array{return array_map('strval',$this->db->query('SELECT locale FROM languages WHERE enabled=1 ORDER BY sort_order,id')->fetchAll(PDO::FETCH_COLUMN));}
    private function defaultLocale():string{return(string)($this->db->query('SELECT locale FROM languages WHERE enabled=1 ORDER BY is_default DESC,sort_order,id LIMIT 1')->fetchColumn()?:'en');}
    private function semanticSpec(string$type,array$settings,array$options):array{$result=['type'=>$type];if(in_array($type,['scale','nps','csat'],true)){$result['min']=(int)($settings['min']??0);$result['max']=(int)($settings['max']??0);}if(in_array($type,['single','multiple','matrix'],true))foreach(['choices','rows']as$group)$result[$group]=array_values(array_map(static fn(array$item):string=>(string)($item['value']??''),array_filter((array)($options[$group]??[]),'is_array')));return$result;}
    private function cloneSlug(string$slug):string{$base=mb_substr($slug,0,170).'-copy';$candidate=$base;$index=2;$statement=$this->db->prepare('SELECT 1 FROM surveys WHERE slug=? LIMIT 1');while(true){$statement->execute([$candidate]);if(!$statement->fetchColumn())return$candidate;$candidate=$base.'-'.$index++;}}
    private function isPublic(array$row,string$statusKey='status'):bool{$status=(string)($row[$statusKey]??'');$now=date('Y-m-d H:i:s');return in_array($status,['published','scheduled'],true)&&(!$row['opens_at']||$row['opens_at']<=$now)&&(!$row['closes_at']||$row['closes_at']>$now);}
    private function effectiveStatus(array$row):string{if($row['status']==='scheduled'&&$row['opens_at']&&$row['opens_at']<=date('Y-m-d H:i:s')&&(!$row['closes_at']||$row['closes_at']>date('Y-m-d H:i:s')))return'published';if(in_array($row['status'],['scheduled','published'],true)&&$row['closes_at']&&$row['closes_at']<=date('Y-m-d H:i:s'))return'closed';return(string)$row['status'];}
    private function date(mixed$value,string$message,bool$dateOnly=false):?string{$value=trim((string)$value);if($value==='')return null;$pattern=$dateOnly?'/^(\d{4})-(\d{2})-(\d{2})(?: 00:00:00)?$/':'/^(\d{4})-(\d{2})-(\d{2})(?:(?:T| )(\d{2}):(\d{2})(?::(\d{2}))?)?$/';if(!preg_match($pattern,$value,$parts)||(int)$parts[1]<1000||(int)$parts[1]>9999)throw new RuntimeException($message);foreach($dateOnly?['!Y-m-d','!Y-m-d H:i:s']:['!Y-m-d\TH:i','!Y-m-d H:i:s','!Y-m-d']as$format){$date=DateTimeImmutable::createFromFormat($format,$value);if($date!==false&&DateTimeImmutable::getLastErrors()===false)return$date->format('Y-m-d H:i:s');}throw new RuntimeException($message);}
    private function slug(string$value):string{$ascii=@iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$value)?:$value;return trim(preg_replace('/[^a-z0-9]+/','-',strtolower($ascii))??'','-');}
    private function validUuid(string$value):bool{return(bool)preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i',$value);}
    private function uuid():string{$data=random_bytes(16);$data[6]=chr((ord($data[6])&15)|64);$data[8]=chr((ord($data[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($data),4));}
    private function ids(string$sql,array$params):array{$statement=$this->db->prepare($sql);$statement->execute($params);return array_values(array_map('intval',$statement->fetchAll(PDO::FETCH_COLUMN)));}
    private function json(mixed$value,mixed$fallback):mixed{if(is_array($value))return$value;$decoded=json_decode((string)$value,true);return json_last_error()===JSON_ERROR_NONE?$decoded:$fallback;}
    private function encode(mixed$value):string{return(string)json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE);}
    private function audit(int$userId,string$event,int$id,array$context):void{$this->db->prepare('INSERT INTO activity_log (user_id,event,subject_type,subject_id,context,created_at) VALUES (?,?,?,?,?,NOW())')->execute([$userId?:null,$event,'survey',$id,$this->encode($context)]);}
}
