<?php

declare(strict_types=1);

use App\Core\Auth;
use App\Core\AiChatService;
use App\Core\AiLicenseService;
use App\Core\AiRepository;
use App\Core\CmsRepository;
use App\Core\EventBus;
use App\Core\ExtensionContext;
use App\Core\ExtensionRuntime;
use App\Core\LicenseException;
use App\Core\LicenseService;
use App\Core\ManifestRegistry;
use App\Core\PackageManager;
use App\Core\Secrets;
use App\Core\FacilityRepository;
use App\Core\AccessControl;
use App\Core\EmailSystem;
use App\Core\WorkflowRepository;
use App\Core\MediaLibrary;
use App\Core\SurveyRepository;
use App\Core\MarketplaceGovernance;
use App\Core\ConsoleSearchIndex;
use App\Http\AiChatController;
use App\Http\DashboardController;
use App\Http\AuthController;
use App\Http\LicenseController;
use App\Http\LiveChatController;
use App\Http\PublicController;
use App\Http\PublicSearchController;
use App\Http\FormController;
use App\Http\PublicFacilityController;
use App\Http\SurveyController;
use App\Http\ThemeAssetController;
use App\Http\ExtensionAssetController;

// Loaded only after Core host/session checks and a completed Workspace migration.
$config = require $root . '/config/workspace.php';
$license = $runtime->license();
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
if ($method === 'HEAD') $method = 'GET';
if (!in_array($path, ['/login', '/license', '/forgot-password', '/reset-password', '/set-password', '/captcha/login.png', '/captcha/recovery.png'], true)) {
    try { $license->enforce($baseUrl); }
    catch (LicenseException) { $reply(['redirect' => '/license'], 423); }
}
$events = new EventBus();
$cms = new CmsRepository($db, $events, $runtime);
$emailSystem = new EmailSystem($db,$cms,new Secrets((string)$config['secrets_key']),$config,(string)$config['base_url']);
$facilities = new FacilityRepository($db);
$auth = new Auth($db);
$access = new AccessControl($db,$auth);
$workflow = new WorkflowRepository($db,$access);
$media = new MediaLibrary($db,$root.'/public');
$surveys = new SurveyRepository($db,(string)($config['secrets_key']??'sensecms-surveys'));
$themes = new ManifestRegistry($root . '/themes', 'theme.json', 'theme', (new App\Core\Packages\ThemeManager($runtime))->activePath());
$plugins = new ManifestRegistry($root . '/plugins', 'plugin.json');
$addons = new ManifestRegistry($root . '/addons', 'addon.json');
$marketplaceConfig = (array) ($config['marketplace'] ?? []);
$marketplaceConfig['installation_url'] = (string) $config['base_url'];
$marketplaceConfig['headers'] = [];
$packages = new PackageManager($db, $root, (string) $config['engine_version'], $marketplaceConfig);
$marketplaceGovernance=new MarketplaceGovernance($db);
$consoleSearch = new ConsoleSearchIndex($cms, $themes, $plugins, $addons, $packages);
$public = new PublicController($cms, $facilities, $themes, $plugins, $addons, $config);
$publicSearch = new PublicSearchController($cms, $facilities, $config);
$publicFacilities = new PublicFacilityController($facilities,$cms,$config);
$aiRepository = new AiRepository($db);
$dashboard = new DashboardController($auth, $access, $workflow, $media, $surveys, $cms, $facilities, $themes, $plugins, $addons, $packages, $marketplaceGovernance, $consoleSearch, $aiRepository, $license, new App\Core\SystemUpdate($db,$root,$config),$emailSystem);
$aiChat = new AiChatController(new AiChatService($aiRepository, new Secrets($config['secrets_key']), $cms));
$liveChat = new LiveChatController($auth, $aiRepository);
$login = new AuthController($auth, $cms, (string) $config['base_url'], (array) ($config['demo'] ?? []),$emailSystem);
$licenseController = new LicenseController($auth, $license, $config, $cms);
$forms = new FormController($cms, $config, $emailSystem);
$surveyController = new SurveyController($surveys,$cms,$config);
$access->enforceRequest($method,$path);
if ($path==='/system/update' && in_array($method,['GET','POST'],true)) (new App\Http\SystemUpdateController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->handle($method);
if ($path==='/system/notifications/whatsapp/connect' && $method==='POST') (new App\Http\NotificationController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->connect();
if ($path==='/system/notifications/whatsapp' && $method==='GET') (new App\Http\NotificationController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->callback();
if ($path==='/system/notifications/telegram/profile-photo' && $method==='GET') (new App\Http\NotificationController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->telegramPhoto();
if ($path==='/system/notifications/telegram/profile-photo' && $method==='POST') (new App\Http\NotificationController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->telegramProfile('set');
if ($path==='/system/notifications/telegram/profile-photo/remove' && $method==='POST') (new App\Http\NotificationController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->telegramProfile('remove');
if ($path==='/system/notifications' && in_array($method,['GET','POST'],true)) (new App\Http\NotificationController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->handle($method);
if ($path==='/api/telegram-connection' && in_array($method,['GET','POST'],true)) (new App\Http\TelegramConnectionController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->handle($method);
if ($path==='/api/web-push' && in_array($method,['GET','POST'],true)) (new App\Http\WebPushController(new ExtensionContext($db,$auth,$access,$dashboard,$config,$root)))->handle($method);
$extensionRuntime = new ExtensionRuntime($db, $root);
if ($extensionRuntime->dispatch($method, $path, new ExtensionContext($db, $auth, $access, $dashboard, $config, $root))) exit;

if ($method === 'GET' && $path === '/dashboard') $dashboard->dashboard();
if ($method === 'GET' && $path === '/profile') $dashboard->profile();
if ($method === 'POST' && $path === '/profile') $dashboard->saveProfile();
if ($method === 'GET' && $path === '/settings') $dashboard->settings();
if ($method === 'POST' && $path === '/settings') $dashboard->saveSettings();
if ($method === 'POST' && $path === '/settings/password') $dashboard->changePassword();
if ($method === 'GET' && $path === '/login') $login->login();
if ($method === 'POST' && $path === '/login') $login->attempt();
if ($method === 'GET' && $path === '/captcha/login.png') $login->captcha();
if ($method === 'GET' && $path === '/forgot-password') $login->forgotPassword();
if ($method === 'POST' && $path === '/forgot-password') $login->requestPasswordReset();
if ($method === 'GET' && in_array($path,['/set-password','/reset-password'],true)) $login->passwordForm();
if ($method === 'POST' && $path === '/set-password') $login->setPassword();
if ($method === 'GET' && $path === '/captcha/recovery.png') $login->recoveryCaptcha();
if ($method === 'GET' && preg_match('#^/captcha/forms/([a-f0-9-]{36})\.png$#i', $path, $matches)) $forms->captcha($matches[1]);
if ($method === 'POST' && preg_match('#^/api/forms/([a-f0-9-]{36})/submit$#i', $path, $matches)) $forms->submit($matches[1]);
if ($method === 'GET' && preg_match('#^/captcha/surveys/([a-f0-9-]{36})\.png$#i', $path, $matches)) $surveyController->captcha($matches[1]);
if ($method === 'POST' && preg_match('#^/api/surveys/([a-f0-9-]{36})/start$#i', $path, $matches)) $surveyController->start($matches[1]);
if ($method === 'POST' && preg_match('#^/api/survey-responses/([a-f0-9-]{36})/submit$#i', $path, $matches)) $surveyController->submit($matches[1]);
if ($method === 'POST' && $path === '/logout') { if (!$auth->verifyCsrf($_POST['csrf'] ?? null)) { http_response_code(419); if (str_contains((string) ($_SERVER['HTTP_ACCEPT'] ?? ''), 'application/json') || (($_SERVER['HTTP_X_SENSECMS_REQUEST'] ?? '') === '1')) { header('Content-Type: application/json; charset=utf-8'); echo json_encode(['ok' => false, 'message' => 'Your session token is invalid. Refresh and try again.']); exit; } exit('Invalid request token'); } $login->logout(); }
if ($method === 'GET' && $path === '/content/pages') $dashboard->pages();
if ($method === 'GET' && $path === '/content/pages/new') $dashboard->pageForm();
if ($method === 'GET' && preg_match('#^/content/pages/(\d+)/edit$#', $path, $matches)) $dashboard->pageForm((int) $matches[1]);
if ($method === 'POST' && $path === '/content/pages') $dashboard->savePage();
if ($method === 'POST' && preg_match('#^/content/pages/(\d+)/(archive|restore|duplicate|delete)$#', $path, $matches)) $dashboard->pageAction((int) $matches[1], $matches[2]);
if ($method === 'POST' && $path === '/content/pages/trash/empty') $dashboard->emptyPageTrash();
if ($method === 'GET' && $path === '/content/workflow') $dashboard->workflow();
if ($method === 'POST' && preg_match('#^/content/workflow/(page|post)/(\d+)/(submit|approve|request-changes|publish|withdraw|assign)$#', $path, $matches)) $dashboard->workflowAction($matches[1],(int)$matches[2],$matches[3]);
if ($method === 'GET' && $path === '/content/facilities') $dashboard->facilities();
if ($method === 'POST' && $path === '/content/facilities') $dashboard->saveFacility();
if ($method === 'POST' && $path === '/content/facilities/geolocation') $dashboard->saveFacilityGeolocation();
if ($method === 'POST' && preg_match('#^/content/facilities/(\d+)/(archive|restore|primary)$#', $path, $matches)) $dashboard->facilityAction((int)$matches[1],$matches[2]);
if ($method === 'GET' && $path === '/content/builder') $dashboard->pageBuilder();
if ($method === 'POST' && preg_match('#^/content/builder/(\d+)$#', $path, $matches)) $dashboard->savePageBuilder((int) $matches[1]);
if ($method === 'POST' && $path === '/content/builder/media') $dashboard->uploadPageBuilderMedia();
if ($method === 'GET' && $path === '/api/content/builder/media') $dashboard->pageBuilderMedia();
if ($method === 'GET' && $path === '/content/media') $dashboard->mediaLibrary();
if ($method === 'GET' && $path === '/api/media') $dashboard->mediaData();
if ($method === 'GET' && preg_match('#^/api/media/(\d+)$#', $path, $matches)) $dashboard->mediaDetail((int)$matches[1]);
if ($method === 'POST' && $path === '/content/media/upload') $dashboard->uploadMedia();
if ($method === 'POST' && preg_match('#^/content/media/(\d+)$#', $path, $matches)) $dashboard->saveMedia((int)$matches[1]);
if ($method === 'POST' && $path === '/content/media/folders') $dashboard->saveMediaFolder();
if ($method === 'POST' && preg_match('#^/content/media/folders/(\d+)/delete$#', $path, $matches)) $dashboard->deleteMediaFolder((int)$matches[1]);
if ($method === 'POST' && preg_match('#^/content/media/(\d+)/(trash|restore|regenerate)$#', $path, $matches)) $dashboard->mediaAction((int)$matches[1],$matches[2]);
if ($method === 'POST' && preg_match('#^/content/media/(\d+)/delete$#', $path, $matches)) $dashboard->deleteMedia((int)$matches[1]);
if ($method === 'POST' && $path === '/content/media/trash/empty') $dashboard->emptyMediaTrash();
if ($method === 'GET' && $path === '/surveys') $dashboard->surveys();
if ($method === 'GET' && $path === '/api/surveys') $dashboard->surveyData();
if ($method === 'GET' && preg_match('#^/api/surveys/(\d+)$#', $path, $matches)) $dashboard->surveyDetail((int)$matches[1]);
if ($method === 'POST' && $path === '/surveys') $dashboard->saveSurvey();
if ($method === 'POST' && preg_match('#^/surveys/(\d+)/(archive|restore|duplicate|close)$#', $path, $matches)) $dashboard->surveyAction((int)$matches[1],$matches[2]);
if ($method === 'GET' && preg_match('#^/api/surveys/(\d+)/statistics$#', $path, $matches)) $dashboard->surveyStatistics((int)$matches[1]);
if ($method === 'GET' && preg_match('#^/api/surveys/(\d+)/responses$#', $path, $matches)) $dashboard->surveyResponses((int)$matches[1]);
if ($method === 'GET' && preg_match('#^/api/surveys/(\d+)/responses/([a-f0-9-]{36})$#i', $path, $matches)) $dashboard->surveyResponse((int)$matches[1],$matches[2]);
if ($method === 'POST' && preg_match('#^/surveys/(\d+)/anonymize$#', $path, $matches)) $dashboard->anonymizeSurvey((int)$matches[1]);
if ($method === 'GET' && preg_match('#^/surveys/(\d+)/export\.(csv|xlsx|pdf)$#', $path, $matches)) $dashboard->exportSurvey((int)$matches[1],$matches[2]);
if ($method === 'POST' && $path === '/content/builder/globals') $dashboard->createPageBuilderGlobal();
if ($method === 'POST' && preg_match('#^/content/builder/globals/(\d+)/rename$#', $path, $matches)) $dashboard->renamePageBuilderGlobal((int) $matches[1]);
if ($method === 'POST' && preg_match('#^/content/builder/globals/(\d+)/archive$#', $path, $matches)) $dashboard->archivePageBuilderGlobal((int) $matches[1]);
if ($method === 'POST' && preg_match('#^/content/builder/(\d+)/revisions/(\d+)/restore$#', $path, $matches)) $dashboard->restorePageBuilderRevision((int) $matches[1], (int) $matches[2]);
if ($method === 'GET' && $path === '/seo') $dashboard->seo();
if ($method === 'POST' && $path === '/seo/global') $dashboard->saveSeoGlobal();
if ($method === 'POST' && $path === '/seo/page') $dashboard->saveSeoPage();
if ($method === 'GET' && $path === '/content/home') $dashboard->home();
if ($method === 'POST' && $path === '/content/home') $dashboard->saveHome();
if ($method === 'GET' && $path === '/system/extensions/popups') $dashboard->popups();
if ($method === 'POST' && $path === '/system/extensions/popups') $dashboard->saveHome();
if ($method === 'GET' && $path === '/content/navigation') $dashboard->navigation();
if ($method === 'POST' && $path === '/content/navigation') $dashboard->saveNavigation();
if ($method === 'POST' && $path === '/content/site-chrome') $dashboard->saveSiteChrome();
if ($method === 'GET' && $path === '/content/posts') $dashboard->posts();
if ($method === 'GET' && $path === '/content/posts/new') $dashboard->postForm();
if ($method === 'GET' && preg_match('#^/content/posts/(\d+)/edit$#', $path, $matches)) $dashboard->postForm((int) $matches[1]);
if ($method === 'POST' && $path === '/content/posts') $dashboard->savePost();
if ($method === 'POST' && preg_match('#^/content/posts/(\d+)/(archive|restore|duplicate)$#', $path, $matches)) $dashboard->postAction((int) $matches[1], $matches[2]);
if ($method === 'GET' && $path === '/content/categories') $dashboard->categories();
if ($method === 'POST' && $path === '/content/categories') $dashboard->saveCategory();
if ($method === 'POST' && preg_match('#^/content/categories/(\d+)/(archive|restore)$#', $path, $matches)) $dashboard->categoryAction((int) $matches[1], $matches[2]);
if ($method === 'GET' && $path === '/appearance/themes') $dashboard->themes();
if ($method === 'GET' && $path === '/marketplace') $dashboard->marketplace();
if ($method === 'GET' && $path === '/api/marketplace') $dashboard->marketplaceData();
if ($method === 'POST' && $path === '/marketplace/sources') $dashboard->saveMarketplaceSource();
if ($method === 'POST' && preg_match('#^/marketplace/sources/(\d+)/sync$#',$path,$matches)) $dashboard->syncMarketplaceSource((int)$matches[1]);
if ($method === 'POST' && $path === '/marketplace/submissions') $dashboard->submitMarketplacePackage();
if ($method === 'POST' && preg_match('#^/marketplace/submissions/(\d+)/(approve|reject)$#',$path,$matches)) $dashboard->moderateMarketplaceSubmission((int)$matches[1],$matches[2]);
if ($method === 'POST' && preg_match('#^/marketplace/catalog/(\d+)/stage$#',$path,$matches)) $dashboard->stageMarketplaceEntry((int)$matches[1]);
if ($method === 'POST' && preg_match('#^/marketplace/official/([a-f0-9]{32})/stage$#',$path,$matches)) $dashboard->stageOfficialMarketplaceProduct($matches[1]);
if ($method === 'POST' && preg_match('#^/marketplace/packages/(theme|plugin|addon)/([a-z0-9-]+)/uninstall$#',$path,$matches)) $dashboard->uninstallMarketplacePackage($matches[1],$matches[2]);
if ($method === 'POST' && preg_match('#^/marketplace/submissions/(\d+)/stage$#',$path,$matches)) $dashboard->stageMarketplaceSubmission((int)$matches[1]);
if ($method === 'GET' && $path === '/appearance') $dashboard->appearance();
if ($method === 'POST' && $path === '/appearance') $dashboard->saveAppearance();
if ($method === 'POST' && $path === '/appearance/releases/activate') $dashboard->changeThemeRelease();
if ($method === 'POST' && $path === '/appearance/releases/rollback') $dashboard->changeThemeRelease(true);
if ($method === 'POST' && preg_match('#^/appearance/themes/([a-z0-9-]+)/activate$#', $path, $matches)) $dashboard->activateTheme($matches[1]);
if ($method === 'POST' && preg_match('#^/appearance/themes/([a-z0-9-]+)/draft$#', $path, $matches)) $dashboard->saveThemeDraft($matches[1]);
if ($method === 'POST' && preg_match('#^/appearance/themes/([a-z0-9-]+)/publish$#', $path, $matches)) $dashboard->publishThemeDraft($matches[1]);
if ($method === 'POST' && preg_match('#^/appearance/themes/([a-z0-9-]+)/discard$#', $path, $matches)) $dashboard->discardThemeDraft($matches[1]);
if ($method === 'GET' && preg_match('#^/appearance/themes/([a-z0-9-]+)/preview$#', $path, $matches)) $dashboard->previewTheme($matches[1]);
if ($method === 'GET' && $path === '/system/extensions') $dashboard->plugins();
if ($method === 'POST' && preg_match('#^/system/extensions/(addon|plugin)/([a-z0-9-]+)/toggle$#', $path, $matches)) $dashboard->toggleExtension($matches[1], $matches[2]);
if ($method === 'POST' && $path === '/system/extensions/packages/inspect') $dashboard->inspectPackage();
if ($method === 'POST' && $path === '/system/extensions/packages/install') $dashboard->installPackage();
if ($method === 'POST' && $path === '/system/extensions/packages/updates/check') $dashboard->checkPackageUpdates();
if ($method === 'POST' && preg_match('#^/system/extensions/packages/(theme|plugin|addon)/([a-z0-9-]+)/update$#', $path, $matches)) $dashboard->stagePackageUpdate($matches[1], $matches[2]);
if ($method === 'POST' && preg_match('#^/system/extensions/packages/(theme|plugin|addon)/([a-z0-9-]+)/rollback$#', $path, $matches)) $dashboard->rollbackPackage($matches[1], $matches[2]);
if ($method === 'POST' && $path === '/system/extensions/publishers') $dashboard->trustPublisher();
if ($method === 'POST' && preg_match('#^/system/extensions/publishers/([a-z0-9._-]+)/toggle$#', $path, $matches)) $dashboard->togglePublisher($matches[1]);
if ($method === 'GET' && $path === '/system/access') $dashboard->accessControl();
if ($method === 'POST' && $path === '/system/access/users') $dashboard->saveAccessUser();
if ($method === 'POST' && preg_match('#^/system/access/users/(\d+)/welcome$#',$path,$matches)) $dashboard->resendWelcome((int)$matches[1]);
if ($method === 'POST' && $path === '/system/access/teams') $dashboard->saveAccessTeam();
if ($method === 'POST' && $path === '/system/access/roles') $dashboard->saveAccessRole();
if ($method === 'GET' && $path === '/api/notifications') $dashboard->notifications();
if ($method === 'POST' && $path === '/api/notifications/read') $dashboard->readNotifications();
if ($method === 'GET' && $path === '/api/console-search') $dashboard->consoleSearch();
if ($method === 'GET' && $path === '/forms/submissions') $dashboard->formInbox();
if ($method === 'GET' && $path === '/api/forms/submissions') $dashboard->formInboxData();
if ($method === 'GET' && preg_match('#^/api/forms/submissions/(\d+)$#', $path, $matches)) $dashboard->formSubmissionDetail((int)$matches[1]);
if ($method === 'POST' && preg_match('#^/api/forms/submissions/(\d+)/status$#', $path, $matches)) $dashboard->updateFormSubmission((int)$matches[1]);
if ($method === 'POST' && preg_match('#^/api/forms/submissions/(\d+)/delete$#', $path, $matches)) $dashboard->deleteFormSubmission((int)$matches[1]);
if ($method === 'GET' && $path === '/forms/submissions/export') $dashboard->exportFormSubmissions();
if ($method === 'GET' && $path === '/system/cache') $dashboard->cache();
if ($method === 'GET' && $path === '/system/email') $dashboard->email();
if ($method === 'POST' && $path === '/system/email/server') $dashboard->saveEmailServer();
if ($method === 'POST' && $path === '/system/email/appearance') $dashboard->saveEmailAppearance();
if ($method === 'POST' && $path === '/system/email/templates') $dashboard->saveEmailTemplates();
if ($method === 'POST' && $path === '/system/email/test') $dashboard->testEmail();
if ($method === 'GET' && $path === '/system/search-index') $dashboard->searchIndex();
if ($method === 'POST' && $path === '/system/search-index/rebuild') $dashboard->rebuildSearchIndex();
if ($method === 'POST' && $path === '/system/cache') $dashboard->saveCache();
if ($method === 'POST' && $path === '/system/cache/clear') $dashboard->clearCache();
if ($method === 'POST' && $path === '/system/cache/reset') $dashboard->resetCache();
if ($method === 'GET' && $path === '/system/sounds') $dashboard->sounds();
if ($method === 'POST' && $path === '/system/sounds') $dashboard->saveSounds();
if ($method === 'POST' && $path === '/system/sounds/reset') $dashboard->resetSounds();
if ($method === 'GET' && $path === '/system/captcha') $dashboard->captcha();
if ($method === 'POST' && $path === '/system/captcha') $dashboard->saveCaptcha();
if ($method === 'GET' && $path === '/system/languages') $dashboard->languages();
if ($method === 'POST' && $path === '/system/languages') $dashboard->saveLanguage();
if ($method === 'GET' && $path === '/ai') $dashboard->ai();
if ($method === 'GET' && $path === '/conversations') $dashboard->conversations();
if ($method === 'GET' && $path === '/conversations/configuration') $dashboard->liveChatConfiguration();
if ($method === 'POST' && $path === '/conversations/configuration') $dashboard->saveLiveChatConfiguration();
if ($method === 'POST' && preg_match('#^/conversations/([a-f0-9-]{36})/messages$#i', $path, $matches)) $dashboard->sendConversationMessage($matches[1]);
if ($method === 'POST' && preg_match('#^/conversations/([a-f0-9-]{36})/delete$#i', $path, $matches)) $dashboard->deleteConversation($matches[1]);
if ($method === 'POST' && preg_match('#^/conversations/([a-f0-9-]{36})/transfer$#i', $path, $matches)) $dashboard->transferConversation($matches[1]);
if ($method === 'GET' && preg_match('#^/conversations/([a-f0-9-]{36})/transcript$#i', $path, $matches)) $dashboard->exportConversation($matches[1]);
if ($method === 'GET' && $path === '/api/operator/chat-events') $liveChat->events();
if ($method === 'POST' && preg_match('#^/api/operator/conversations/([a-f0-9-]{36})/connect$#i', $path, $matches)) $liveChat->connect($matches[1]);
if ($method === 'GET' && preg_match('#^/api/operator/conversations/([a-f0-9-]{36})$#i', $path, $matches)) $liveChat->conversation($matches[1]);
if ($method === 'POST' && preg_match('#^/api/operator/conversations/([a-f0-9-]{36})/read$#i', $path, $matches)) $liveChat->read($matches[1]);
if ($method === 'GET' && $path === '/license') $dashboard->license();
if ($method === 'POST' && $path === '/license') $licenseController->upload();
if ($method === 'POST' && $path === '/system/license/hosting-credit') $dashboard->saveHostingCredit();
if ($method === 'POST' && $path === '/api/ai/chat') {
    $forceHuman = false;
    try { (new AiLicenseService('https://www.chivale.com/license/', $root . '/storage/license/ai-status.json'))->validate((string) getenv('AI_CHAT_LICENSE_KEY'), $config['base_url']); }
    catch (LicenseException) { $forceHuman = true; }
    $aiChat->reply($forceHuman);
}
if ($method === 'GET' && $path === '/api/chat/state') $aiChat->state();
if ($method === 'GET' && $path === '/api/search') $publicSearch->search();
if ($method === 'GET' && $path === '/api/facilities') $publicFacilities->index();
if ($method === 'GET' && $path === '/robots.txt') $public->robots();
if ($method === 'GET' && $path === '/sitemap.xml') $public->sitemap();
if ($method === 'GET' && $publicPage !== null) $public->showPageAtPath($publicPage);
if ($method === 'GET' && $path === '/') {
    header('Vary: Accept-Language, Sec-CH-UA-Lang, X-System-Language, CF-IPCountry');
    header('Location: /' . $public->preferredLocale() . '/home', true, 302);
    exit;
}
if ($method === 'GET' && preg_match('#^/([a-z]{2,5})/posts/([a-z0-9-]+)$#', $path, $matches)) $public->showPost($matches[1],$matches[2]);
if ($method === 'GET' && preg_match('#^/([a-z]{2,5})/facilities/([a-z0-9-]+)/([a-z0-9-]+)/posts/([a-z0-9-]+)$#', $path, $matches)) $public->showFacilityPost($matches[1],$matches[2],$matches[3],$matches[4]);
if ($method === 'GET' && preg_match('#^/([a-z]{2,5})/facilities/([a-z0-9-]+)/([a-z0-9-]+)(?:/([a-z0-9-]+))?$#', $path, $matches)) $public->showFacility($matches[1],$matches[2],$matches[3],$matches[4]??null);
if ($method === 'GET' && preg_match('#^/([a-z]{2,5})/surveys/([a-z0-9-]+)$#', $path, $matches)) $surveyController->show($matches[1],$matches[2]);
if ($method === 'GET' && preg_match('#^/([a-z]{2,5})(?:/([a-z0-9-]+))?$#', $path, $matches)) $public->show($matches[1], $matches[2] ?? 'home');
header('Content-Type: text/plain; charset=utf-8', true, 404);
echo "Not found";
