<?php
declare(strict_types=1);

if(PHP_SAPI!=='cli'||$argc!==4||!in_array($argv[2],['--apply','--rollback'],true))exit("Usage: php publish-telegram-channels-extension.php <installation> --apply|--rollback <private-backup>\n");
umask(0077);$root=realpath($argv[1]);$backup=realpath($argv[3]);if(!$root||!$backup||!str_starts_with($backup,'/root/'))throw new RuntimeException('Private existing operator paths required.');require$root.'/bootstrap.php';$runtime=new App\Core\Runtime($root);$runtime->license()->enforce($runtime->baseUrl());$db=App\Core\Runtime::connect($runtime->read('installed')['database']);$cms=new App\Core\CmsRepository($db,new App\Core\EventBus(),$runtime);$owner=(int)$db->query("SELECT ur.user_id FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN users u ON u.id=ur.user_id WHERE r.slug='owner' AND u.active=1 ORDER BY ur.user_id LIMIT 1")->fetchColumn();if(!$owner||$cms->defaultLocale()!=='en')throw new RuntimeException('Expected licensed English product website.');$theme=(new App\Core\Packages\ThemeManager($runtime))->activePath();$catalog=App\Core\PageBuilder::catalog(json_decode((string)file_get_contents($theme.'/theme.json'),true,32,JSON_THROW_ON_ERROR));$journal=$backup.'/telegram-channels-extension-before.json';$lock=fopen($backup.'/telegram-channels-extension.lock','c+b');if(!$lock||!flock($lock,LOCK_EX|LOCK_NB))throw new RuntimeException('Telegram Channels publication already running.');
$uuid=static function():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);$h=bin2hex($b);return substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20);};
$save=static function(array$doc,array$blocks)use($cms,$catalog,$owner):void{$current=$cms->builderDocument((int)$doc['id']);if(!$current)throw new RuntimeException('Marketplace page disappeared.');$cms->saveBuilderDocument((int)$doc['id'],(int)$current['builder_version'],$owner,'sensecms',App\Core\PageBuilder::sanitizeBlocks($blocks,$catalog,array_keys($doc['translations'])),array_keys($catalog));};
$rollback=static function(array$state)use($cms,$save,$owner):void{foreach($state['pages']??[]as$doc)$save($doc,$doc['blocks']);if(!empty($state['detail_id']))$cms->setPageStatus((int)$state['detail_id'],'archived',$owner);if(!empty($state['global_id']))$cms->archiveGlobalSection((int)$state['global_id'],$owner);};
if($argv[2]==='--rollback'){$state=json_decode((string)file_get_contents($journal),true,64,JSON_THROW_ON_ERROR);$rollback($state);echo"Telegram Channels Publisher marketplace entry withdrawn; original catalogue pages restored.\n";exit;}
if(file_exists($journal))throw new RuntimeException('Existing Telegram Channels publication journal; inspect before rerun.');$path='/extensions/catalog/plugin/telegram-channels-publisher';$query=$db->prepare('SELECT p.id,p.status FROM pages p JOIN page_translations t ON t.page_id=p.id WHERE t.locale=? AND t.slug=? ORDER BY p.id DESC LIMIT 1');$query->execute(['en','extensions-catalog-plugin-telegram-channels-publisher']);$existing=$query->fetch();$existingDetail=0;if($existing){if(($existing['status']??'')!=='archived')throw new RuntimeException('Telegram Channels detail route already exists.');$existingDetail=(int)$existing['id'];}foreach($cms->globalSections()as$section)if(($section['name']??'')==='Marketplace: Telegram Channels Publisher')throw new RuntimeException('Telegram Channels shared section already exists.');
$state=['pages'=>[],'global_id'=>null,'detail_id'=>null];foreach(['/extensions'=>18,'/extensions/catalog'=>18,'/extensions/catalog/plugin'=>13]as$url=>$expected){$page=$cms->pageAtPath($url);if(!$page)throw new RuntimeException('Missing marketplace route: '.$url);$doc=$cms->builderDocument((int)$page['id']);$actual=0;foreach($doc['blocks']as$block){$cta=(string)($block['localized']['en']['cta_url']??'');if(preg_match('~^/extensions/catalog/(system|theme|plugin|addon|module|application)/[a-z0-9-]+$~D',$cta))$actual++;if($cta===$path)throw new RuntimeException('Telegram Channels is already linked.');}if($actual!==$expected)throw new RuntimeException('Marketplace baseline changed: '.$url);$state['pages'][]=$doc;}file_put_contents($journal,json_encode($state,JSON_THROW_ON_ERROR),LOCK_EX);
try{
    $card=App\Core\PageBuilder::sanitizeBlocks([['uid'=>$uuid(),'type'=>'text','visible'=>true,'shared'=>[],'localized'=>['en'=>['title'=>'Telegram Channels Publisher','text'=>'<p><strong>USD 15 / year</strong> · Plugins</p><p>Publish reviewed Sense CMS posts to one or more Telegram channels through the official Sense CMS bot.</p><p>Signed Development Preview 0.1.0 available</p>','cta_label'=>'View package →','cta_url'=>$path]]]],$catalog,['en'])[0];$global=$cms->createGlobalSection('Marketplace: Telegram Channels Publisher',$card,$owner);$state['global_id']=(int)$global['id'];file_put_contents($journal,json_encode($state,JSON_THROW_ON_ERROR),LOCK_EX);$card['global_section_id']=(int)$global['id'];$card['global_version']=0;foreach($state['pages']as$doc){$item=$card;$item['uid']=$uuid();$save($doc,array_merge($doc['blocks'],[$item]));}
    $facility=(new App\Core\FacilityRepository($db))->primary('en','en');if(!$facility)throw new RuntimeException('Primary facility unavailable.');$description='Publish reviewed Sense CMS posts to multiple Telegram channels through the official Sense CMS bot.';$input=['id'=>$existingDetail,'facility_id'=>(int)$facility['id'],'template'=>'default','status'=>'draft','visibility'=>'public','published_at'=>null,'public_path'=>null];$translations=['en'=>['title'=>'Telegram Channels Publisher','slug'=>'extensions-catalog-plugin-telegram-channels-publisher','excerpt'=>$description,'seo_title'=>'Telegram Channels Publisher for Sense CMS','seo_description'=>$description]];$id=$cms->savePage($input,$translations,$owner);$state['detail_id']=$id;file_put_contents($journal,json_encode($state,JSON_THROW_ON_ERROR),LOCK_EX);
    $sections=[['USD 15 / year','<p>This paid plugin requires its own product licence. The Sense CMS Core key and keys for other extensions do not authorize it.</p><p>Licence identity: <strong>Sense CMS Telegram Channels Plugin</strong> / <strong>Telegram Channels Plugin</strong>. The 32-character key, installation domain, start date and expiry date are validated independently.</p>'],['Development Preview 0.1.0','<p>The exact signed development package is available from the Extensions marketplace and requires the installed Sense CMS Social Publishing addon.</p><p>The standard Telegram Bot API does not require a paid Telegram API plan. The annual Sense CMS fee funds extension development, compatibility maintenance and monitoring.</p>','Open Extensions →','/extensions'],['Multiple channels','<p>Connect multiple public or private Telegram channels and select every destination independently while reviewing a post.</p><p>Public channels use an <code>@username</code> or <code>t.me</code> address; private channels use their numeric channel ID.</p>'],['Minimal bot permission','<p>Add <strong>@SenseCMSBot</strong> as a channel administrator with only <code>post_messages</code>. The bot token remains on the official Sense CMS service and is never copied into the customer installation.</p>'],['Reliable publishing','<p>Every reviewed message includes the canonical Sense CMS link. A revision-bound delivery key and an encrypted broker tombstone prevent duplicate sends during safe retries, including after an ambiguous Telegram response.</p><p>The initial release publishes text and links; media albums, polls and paid high-throughput broadcasts are outside this release.</p>'],['Explore the ecosystem','<p>Compare themes, plugins, addons and applications with clear pricing and release availability.</p>','All extensions →','/extensions']];$blocks=[];foreach($sections as$section)$blocks[]=['uid'=>$uuid(),'type'=>'text','visible'=>true,'shared'=>[],'localized'=>['en'=>['title'=>$section[0],'text'=>$section[1],'cta_label'=>$section[2]??'','cta_url'=>$section[3]??'']]];$doc=$cms->builderDocument($id);$cms->saveBuilderDocument($id,(int)$doc['builder_version'],$owner,'sensecms',App\Core\PageBuilder::sanitizeBlocks($blocks,$catalog,['en']),array_keys($catalog));$cms->savePage(array_replace($input,['id'=>$id,'status'=>'published','public_path'=>$path]),$translations,$owner);
}catch(Throwable$error){$rollback($state);throw$error;}
echo"Published paid Telegram Channels Publisher Development Preview across three marketplace collections.\n";
