<?php

declare(strict_types=1);

use App\Core\PageBuilder;
use App\Core\SeoMeta;

if(PHP_SAPI!=='cli'||$argc!==4||!in_array($argv[2],['--apply','--rollback'],true))exit("Usage: php publish-ai-product-pages.php <installation> --apply|--rollback <private-backup>\n");
umask(0077);$root=realpath($argv[1]);$backup=realpath($argv[3]);
if(!$root||!is_file($root.'/bootstrap.php')||!$backup||!str_starts_with(str_replace('\\','/',$backup),'/root/'))throw new RuntimeException('Existing installation and private operator backup paths are required.');
require $root.'/bootstrap.php';
$runtime=new App\Core\Runtime($root);$runtime->license()->enforce($runtime->baseUrl());$db=App\Core\Runtime::connect($runtime->read('installed')['database']);$events=new App\Core\EventBus();$cms=new App\Core\CmsRepository($db,$events,$runtime);
$owner=(int)$db->query("SELECT ur.user_id FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN users u ON u.id=ur.user_id WHERE r.slug='owner' AND u.active=1 ORDER BY ur.user_id LIMIT 1")->fetchColumn();$facility=(new App\Core\FacilityRepository($db))->primary('en','en');$manager=new App\Core\Packages\ThemeManager($runtime);$theme=$manager->active();
if(!$owner||!$facility||$cms->defaultLocale()!=='en'||($theme['slug']??'')!=='sensecms')throw new RuntimeException('Expected the licensed English Sense CMS product website.');
$descriptor=json_decode((string)file_get_contents($manager->activePath().'/theme.json'),true,64,JSON_THROW_ON_ERROR);$catalog=PageBuilder::catalog($descriptor);$locales=array_column($cms->languages(),'locale');$journal=$backup.'/site-ai-pages.json';
$write=static function(array$state)use($journal):void{$json=json_encode($state,JSON_THROW_ON_ERROR|JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";if(file_put_contents($journal,$json,LOCK_EX)!==strlen($json)||!chmod($journal,0600))throw new RuntimeException('Cannot write the AI product-page recovery journal.');};
$uuid=static function():string{$bytes=random_bytes(16);$bytes[6]=chr((ord($bytes[6])&15)|64);$bytes[8]=chr((ord($bytes[8])&63)|128);$hex=bin2hex($bytes);return substr($hex,0,8).'-'.substr($hex,8,4).'-'.substr($hex,12,4).'-'.substr($hex,16,4).'-'.substr($hex,20);};
$block=static function(string$title,string$text,string$cta='',string$url='')use($uuid,$catalog):array{return PageBuilder::sanitizeBlocks([['uid'=>$uuid(),'type'=>'text','visible'=>true,'shared'=>[],'localized'=>['en'=>['title'=>$title,'text'=>'<p>'.htmlspecialchars($text,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</p>','cta_label'=>$cta,'cta_url'=>$url]]]],$catalog,['en'])[0];};
$input=static fn(array$page):array=>['id'=>(int)$page['id'],'parent_id'=>(int)($page['parent_id']??0)?:null,'facility_id'=>(int)$page['facility_id'],'assigned_user_id'=>(int)($page['assigned_user_id']??0)?:null,'editorial_note'=>(string)($page['editorial_note']??''),'public_path'=>$page['public_path']??null,'template'=>(string)($page['template']??'default'),'status'=>(string)$page['status'],'visibility'=>(string)$page['visibility'],'published_at'=>$page['published_at']??null];
$translations=static function(array$rows):array{$result=[];foreach($rows as$locale=>$row)$result[(string)$locale]=['title'=>(string)$row['title'],'slug'=>(string)$row['slug'],'excerpt'=>(string)($row['excerpt']??''),'seo_title'=>(string)($row['seo_title']??''),'seo_description'=>(string)($row['seo_description']??'')];return$result;};
$setting=static function(string$key)use($db):array{$statement=$db->prepare('SELECT value FROM settings WHERE `key`=?');$statement->execute([$key]);$raw=$statement->fetchColumn();return['exists'=>$raw!==false,'raw'=>$raw===false?null:(string)$raw];};
$restoreSetting=static function(string$key,array$state)use($db):void{if(!empty($state['exists']))$db->prepare('INSERT INTO settings (`key`,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)')->execute([$key,$state['raw']]);else$db->prepare('DELETE FROM settings WHERE `key`=?')->execute([$key]);};

if($argv[2]==='--rollback'){
    if(!is_file($journal))throw new RuntimeException('AI product-page recovery journal is missing.');$state=json_decode((string)file_get_contents($journal),true,64,JSON_THROW_ON_ERROR);
    foreach(array_reverse((array)($state['updated']??[]),true)as$path=>$saved){$page=$cms->pageAtPath((string)$path);$document=$page?$cms->builderDocument((int)$page['id']):null;if(!$page||!$document||(int)$document['builder_version']!==(int)$saved['applied_version'])throw new RuntimeException('An updated page changed; rollback stopped: '.$path);$before=PageBuilder::sanitizeBlocks((array)$saved['document']['blocks'],$catalog,$locales);$cms->saveBuilderDocument((int)$page['id'],(int)$document['builder_version'],$owner,'sensecms',$before,array_keys($catalog));$cms->savePage($input($saved['page']),$translations($saved['page']['translations']),$owner);}
    foreach(array_reverse((array)($state['created']??[]),true)as$path=>$created){$page=$cms->pageAtPath((string)$path);$document=$page?$cms->builderDocument((int)$page['id']):null;if(!$page||!$document||(int)$page['id']!==(int)$created['id']||(int)$document['builder_version']!==(int)$created['version'])throw new RuntimeException('The created AI page changed; rollback stopped.');$cms->setPageStatus((int)$page['id'],'archived',$owner);$cms->deletePagePermanently((int)$page['id'],$owner);}
    foreach((array)($state['settings']??[])as$key=>$saved)$restoreSetting((string)$key,(array)$saved);$state['status']='rolled-back';$write($state);echo "Restored product pages and AI SEO metadata.\n";exit;
}

if(file_exists($journal))throw new RuntimeException('Existing AI product-page journal requires review.');foreach(['/','/platform']as$path)if(!$cms->pageAtPath($path))throw new RuntimeException('Required managed product page is missing: '.$path);if($cms->pageAtPath('/platform/ai'))throw new RuntimeException('The AI product page already exists and requires review.');
$slug='platform-ai';$check=$db->prepare('SELECT 1 FROM page_translations WHERE facility_id=? AND locale="en" AND slug=?');$check->execute([(int)$facility['id'],$slug]);if($check->fetchColumn())throw new RuntimeException('The AI page slug is already in use.');
$state=['status'=>'applying','updated'=>[],'created'=>[],'settings'=>[]];$write($state);
$promotions=[
    '/'=>['AI that keeps editors in control','Draft and refine Page Builder sections and posts, maintain a governed Knowledge Base for RAG, and choose your own configured AI provider. Human review stays in the publishing flow.','Explore Sense CMS AI →'],
    '/platform'=>['Provider-neutral AI in Core','Sense CMS combines editorial AI, per-provider budgets, a controlled RAG index and evaluation-ready training data. Themes still own presentation; Core owns content, permissions and review.','Discover the AI platform →'],
];
foreach($promotions as$path=>[$title,$text,$label]){$page=$cms->pageAtPath($path);$id=(int)$page['id'];$before=$cms->pageAdmin($id);$document=$cms->builderDocument($id);if(!$before||!$document)throw new RuntimeException('Cannot load managed page: '.$path);$state['updated'][$path]=['page'=>$before,'document'=>$document,'applied_version'=>null];$write($state);$blocks=PageBuilder::sanitizeBlocks((array)$document['blocks'],$catalog,$locales);$blocks[]=$block($title,$text,$label,'/platform/ai');$version=$cms->saveBuilderDocument($id,(int)$document['builder_version'],$owner,'sensecms',$blocks,array_keys($catalog));$state['updated'][$path]['applied_version']=$version;$write($state);}
$description='Provider-neutral AI for Page Builder and posts, a controlled Knowledge Base with RAG, budget guardrails, human review and local training-data preparation.';
$pageTranslations=['en'=>['title'=>'AI content management, built into Sense CMS','slug'=>$slug,'excerpt'=>$description,'seo_title'=>'AI Content Management, RAG & Editorial Assistance | Sense CMS','seo_description'=>'Use review-first AI in Sense CMS for Page Builder and posts, with a controlled Knowledge Base, RAG, provider budgets and human approval.']];
$id=$cms->savePage(['id'=>0,'facility_id'=>(int)$facility['id'],'public_path'=>'/platform/ai','template'=>'product','status'=>'draft','visibility'=>'public','published_at'=>null],$pageTranslations,$owner);$state['created']['/platform/ai']=['id'=>$id,'version'=>0];$write($state);
$sections=[
    ['AI for structured editorial work','Generate or improve drafts inside Page Builder and Posts without bypassing editorial review. Suggestions remain editable and publication stays a deliberate human action.'],
    ['One Core, multiple AI providers','Configure OpenAI Responses, compatible APIs, Anthropic or Google Gemini independently. Encrypted credentials, priorities and request, token and budget guardrails keep provider choice under installation control.'],
    ['Knowledge Base and RAG','Combine approved website content, manual knowledge and private text documents in a local, traceable retrieval index. Sources can be included, corrected, disabled or deleted independently.'],
    ['Automatic knowledge synchronization','Published pages and posts are queued for local reindexing when their content or publication state changes. Future, draft, private and excluded content stays out of retrieval.'],
    ['Training data without surprise costs','Curate reviewed examples and evaluation cases, then prepare checksum-locked JSONL packages locally. Paid provider fine-tuning remains disabled until a current estimate and separate confirmation are available.'],
    ['A foundation for visitor assistance','The same governed knowledge and provider controls prepare Sense CMS for a future visitor assistant with source-aware answers. Public visitor generation is not enabled on this website yet.'],
];$blocks=[];foreach($sections as[$title,$text])$blocks[]=$block($title,$text);$version=$cms->saveBuilderDocument($id,0,$owner,'sensecms',$blocks,array_keys($catalog));$state['created']['/platform/ai']['version']=$version;$write($state);$cms->savePage(['id'=>$id,'facility_id'=>(int)$facility['id'],'public_path'=>'/platform/ai','template'=>'product','status'=>'published','visibility'=>'public','published_at'=>null],$pageTranslations,$owner);
$key='seo_page_'.$id.'_en';$state['settings'][$key]=$setting($key);$write($state);$seo=SeoMeta::sanitizeDocument(['title'=>$pageTranslations['en']['seo_title'],'description'=>$pageTranslations['en']['seo_description'],'keywords'=>'AI content management, AI CMS, RAG CMS, AI Page Builder, AI writing assistant, provider-neutral AI, knowledge base CMS','canonical'=>'/platform/ai','robots'=>'index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1','schema_type'=>'CollectionPage','og_type'=>'website','og_title'=>'AI Content Management in Sense CMS','og_description'=>$description,'twitter_card'=>'summary_large_image','twitter_title'=>'AI Content Management in Sense CMS','twitter_description'=>$description],'page');$cms->saveSetting($key,$seo);
$state['status']='applied';$write($state);echo "Published /platform/ai, promoted AI on two product pages, and saved structured SEO metadata.\n";
