<?php
declare(strict_types=1);

if(PHP_SAPI!=='cli'||$argc!==4||!in_array($argv[2],['--apply','--rollback'],true))exit("Usage: php update-social-hotfix-marketplace.php <installation> --apply|--rollback <private-backup>\n");
umask(0077);$root=realpath($argv[1]);$backup=realpath($argv[3]);if(!$root||!$backup||!str_starts_with($backup,'/root/'))throw new RuntimeException('Private existing operator paths required.');require$root.'/bootstrap.php';$runtime=new App\Core\Runtime($root);$runtime->license()->enforce($runtime->baseUrl());$db=App\Core\Runtime::connect($runtime->read('installed')['database']);$cms=new App\Core\CmsRepository($db,new App\Core\EventBus(),$runtime);$owner=(int)$db->query("SELECT ur.user_id FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN users u ON u.id=ur.user_id WHERE r.slug='owner' AND u.active=1 ORDER BY ur.user_id LIMIT 1")->fetchColumn();if(!$owner||$cms->defaultLocale()!=='en')throw new RuntimeException('Expected licensed English product website.');$theme=(new App\Core\Packages\ThemeManager($runtime))->activePath();$catalog=App\Core\PageBuilder::catalog(json_decode((string)file_get_contents($theme.'/theme.json'),true,32,JSON_THROW_ON_ERROR));$journal=$backup.'/social-hotfix-marketplace-before.json';$lock=fopen($backup.'/social-hotfix-marketplace.lock','c+b');if(!$lock||!flock($lock,LOCK_EX|LOCK_NB))throw new RuntimeException('Social hotfix marketplace update already running.');
$document=static function(string$path)use($cms):array{$page=$cms->pageAtPath($path);$doc=$page?$cms->builderDocument((int)$page['id']):null;if(!$doc)throw new RuntimeException('Expected marketplace page is unavailable: '.$path);return$doc;};
$save=static function(array$before)use($cms,$catalog,$owner):void{$current=$cms->builderDocument((int)$before['id']);if(!$current)throw new RuntimeException('A marketplace page disappeared during update.');$versions=[];foreach($current['blocks']as$block)if(!empty($block['global_section_id']))$versions[(int)$block['global_section_id']]=(int)$block['global_version'];foreach($before['blocks']as&$block)if(!empty($block['global_section_id'])&&isset($versions[(int)$block['global_section_id']]))$block['global_version']=$versions[(int)$block['global_section_id']];unset($block);$cms->saveBuilderDocument((int)$before['id'],(int)$current['builder_version'],$owner,'sensecms',App\Core\PageBuilder::sanitizeBlocks($before['blocks'],$catalog,array_keys($before['translations'])),array_keys($catalog));};
$replace=static function(mixed&$value,string$old,string$new,int&$count)use(&$replace):void{if(is_array($value)){foreach($value as&$item)$replace($item,$old,$new,$count);unset($item);}elseif(is_string($value)){$value=str_replace($old,$new,$value,$changed);$count+=$changed;}};
$replaceCard=static function(array&$blocks,string$path,string$old,string$new,int&$count)use($replace):void{foreach($blocks as&$block){if(($block['localized']['en']['cta_url']??'')!==$path)continue;$replace($block,$old,$new,$count);}unset($block);};
$restore=static function(array$state)use($save):void{foreach(array_reverse($state['documents'])as$doc)$save($doc);};
if($argv[2]==='--rollback'){$state=json_decode((string)file_get_contents($journal),true,64,JSON_THROW_ON_ERROR);$restore($state);echo"Social hotfix marketplace versions restored.\n";exit;}
if(file_exists($journal))throw new RuntimeException('Existing Social hotfix marketplace journal; inspect before rerun.');$collections=['/extensions','/extensions/catalog','/extensions/catalog/plugin'];$details=['/extensions/catalog/plugin/bluesky-publisher','/extensions/catalog/plugin/x-publisher','/extensions/catalog/plugin/tiktok-publisher','/extensions/catalog/plugin/youtube-publisher'];$paths=array_merge($collections,$details);$state=['documents'=>array_map($document,$paths)];if(file_put_contents($journal,json_encode($state,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES),LOCK_EX)===false)throw new RuntimeException('Cannot save marketplace recovery journal.');
$versions=['/extensions/catalog/plugin/bluesky-publisher'=>['Development Preview 0.1.3','Development Preview 0.1.4'],'/extensions/catalog/plugin/x-publisher'=>['Development Preview 0.1.1','Development Preview 0.1.2'],'/extensions/catalog/plugin/tiktok-publisher'=>['Development Preview 0.1.1','Development Preview 0.1.3'],'/extensions/catalog/plugin/youtube-publisher'=>['Development Preview 0.1.0','Development Preview 0.1.1']];
try{$candidate=$state;$changes=array_fill(0,count($paths),0);foreach(array_keys($collections)as$index)foreach($versions as$path=>[$old,$new])$replaceCard($candidate['documents'][$index]['blocks'],$path,$old,$new,$changes[$index]);foreach($details as$offset=>$path){$index=count($collections)+$offset;[$old,$new]=$versions[$path];if($path==='/extensions/catalog/plugin/x-publisher'){$old='Version 0.1.1 is installed';$new='Version 0.1.2 is installed';}$replace($candidate['documents'][$index]['blocks'],$old,$new,$changes[$index]);if($path==='/extensions/catalog/plugin/youtube-publisher')$replace($candidate['documents'][$index]['blocks'],'Social Publishing 0.4.0','Social Publishing 0.4.1',$changes[$index]);}foreach($changes as$index=>$count){$expected=$index<3?3:($index===6?2:1);if($count!==$expected)throw new RuntimeException('Unexpected marketplace version baseline at '.$paths[$index].': '.$count);}foreach($candidate['documents']as$doc)$save($doc);foreach($details as$path){$rendered=json_encode($document($path)['blocks'],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);$needle=$path==='/extensions/catalog/plugin/x-publisher'?'Version 0.1.2 is installed':$versions[$path][1];if(!str_contains($rendered,$needle))throw new RuntimeException('Marketplace version verification failed: '.$path);}}catch(Throwable$error){$restore($state);throw$error;}
echo"Bluesky, X, TikTok and YouTube marketplace versions updated.\n";
