<?php

declare(strict_types=1);

use App\Core\EventBus;
use App\Core\PageBuilder;
use App\Core\Runtime;
use App\Core\SeoMeta;

if(PHP_SAPI!=='cli'||$argc!==4||!in_array($argv[2],['--apply','--rollback'],true))exit("Usage: php update-ai-visitor-product-page.php <installation> --apply|--rollback <private-backup>\n");
umask(0077);$root=realpath($argv[1]);$backup=realpath($argv[3]);if(!$root||!is_file($root.'/bootstrap.php')||!$backup||!str_starts_with(str_replace('\\','/',$backup),'/root/'))throw new RuntimeException('Existing installation and private operator backup paths are required.');
require $root.'/bootstrap.php';$runtime=new Runtime($root);$runtime->license()->enforce($runtime->baseUrl());$db=Runtime::connect($runtime->read('installed')['database']);$cms=new App\Core\CmsRepository($db,new EventBus(),$runtime);$owner=(int)$db->query("SELECT ur.user_id FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN users u ON u.id=ur.user_id WHERE r.slug='owner' AND u.active=1 ORDER BY ur.user_id LIMIT 1")->fetchColumn();$theme=(new App\Core\Packages\ThemeManager($runtime))->activePath();$catalog=PageBuilder::catalog(json_decode((string)file_get_contents($theme.'/theme.json'),true,64,JSON_THROW_ON_ERROR));$page=$cms->pageAtPath('/platform/ai');if(!$owner||!$page)throw new RuntimeException('Expected the Sense CMS AI product page and active owner.');$id=(int)$page['id'];$journal=$backup.'/ai-visitor-product-page.json';
$write=static function(array$state)use($journal):void{$json=json_encode($state,JSON_THROW_ON_ERROR|JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";if(file_put_contents($journal,$json,LOCK_EX)!==strlen($json)||!chmod($journal,0600))throw new RuntimeException('Cannot write the AI visitor page recovery journal.');};
$forSave=static function(array$blocks):array{foreach($blocks as&$item)if(!isset($item['source']))$item['source']=(string)($item['source_theme']??'sensecms');unset($item);return$blocks;};
$input=static fn(array$row):array=>['id'=>(int)$row['id'],'parent_id'=>(int)($row['parent_id']??0)?:null,'facility_id'=>(int)$row['facility_id'],'assigned_user_id'=>(int)($row['assigned_user_id']??0)?:null,'editorial_note'=>(string)($row['editorial_note']??''),'public_path'=>$row['public_path']??null,'template'=>(string)($row['template']??'default'),'status'=>(string)$row['status'],'visibility'=>(string)$row['visibility'],'published_at'=>$row['published_at']??null];
$translations=static function(array$rows):array{$result=[];foreach($rows as$locale=>$row)$result[(string)$locale]=['title'=>(string)$row['title'],'slug'=>(string)$row['slug'],'excerpt'=>(string)($row['excerpt']??''),'seo_title'=>(string)($row['seo_title']??''),'seo_description'=>(string)($row['seo_description']??'')];return$result;};
$settingKey='seo_page_'.$id.'_en';$setting=static function()use($db,$settingKey):array{$query=$db->prepare('SELECT value FROM settings WHERE `key`=?');$query->execute([$settingKey]);$raw=$query->fetchColumn();return['exists'=>$raw!==false,'raw'=>$raw===false?null:(string)$raw];};
if($argv[2]==='--rollback'){$state=is_file($journal)?json_decode((string)file_get_contents($journal),true,64,JSON_THROW_ON_ERROR):null;if(!is_array($state))throw new RuntimeException('AI visitor page recovery journal is missing.');$document=$cms->builderDocument($id);if(!$document||(int)$document['builder_version']!==(int)$state['applied_version'])throw new RuntimeException('The AI page changed after deployment; rollback stopped.');$cms->saveBuilderDocument($id,(int)$document['builder_version'],$owner,'sensecms',$forSave($state['document']['blocks']),array_keys($catalog));$cms->savePage($input($state['page']),$translations($state['page']['translations']),$owner);if($state['seo']['exists'])$db->prepare('INSERT INTO settings (`key`,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)')->execute([$settingKey,$state['seo']['raw']]);else$db->prepare('DELETE FROM settings WHERE `key`=?')->execute([$settingKey]);$state['status']='rolled-back';$write($state);echo"Restored the previous AI product page.\n";exit;}
if(file_exists($journal))throw new RuntimeException('Existing AI visitor page journal requires review.');$before=$cms->pageAdmin($id);$document=$cms->builderDocument($id);if(!$before||!$document)throw new RuntimeException('The AI product page could not be loaded.');$state=['status'=>'applying','page'=>$before,'document'=>$document,'seo'=>$setting(),'applied_version'=>null];$write($state);$blocks=$forSave($document['blocks']);$found=0;$text='Answer visitor questions from approved, indexed website knowledge, show verified source links and transfer the conversation to a person when the available context is insufficient. Daily reply and output limits keep usage controlled.';foreach($blocks as&$block){$localized=&$block['localized']['en'];if(($localized['title']??'')==='A foundation for visitor assistance'||($localized['title']??'')==='RAG visitor assistant with human handoff'){$localized['title']='RAG visitor assistant with human handoff';$localized['text']='<p>'.htmlspecialchars($text,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</p>';$found++;}}unset($block,$localized);if($found!==1)throw new RuntimeException('The reviewed visitor-assistant product section was not found exactly once.');$blocks=$forSave(PageBuilder::sanitizeBlocks($blocks,$catalog,array_keys($before['translations'])));$version=$cms->saveBuilderDocument($id,(int)$document['builder_version'],$owner,'sensecms',$blocks,array_keys($catalog));$state['applied_version']=$version;$write($state);$description='Provider-neutral editorial AI, controlled RAG, a source-aware visitor assistant, budget guardrails, human handoff and local training-data preparation.';$rows=$before['translations'];$rows['en']['excerpt']=$description;$rows['en']['seo_description']='Use Sense CMS AI for Page Builder, posts and a source-aware RAG visitor assistant with provider budgets, verified links and human handoff.';$cms->savePage($input($before),$translations($rows),$owner);$seo=SeoMeta::sanitizeDocument(array_replace((array)$cms->setting($settingKey,[]),['description'=>$rows['en']['seo_description'],'og_description'=>$description,'twitter_description'=>$description]),'page');$cms->saveSetting($settingKey,$seo);$state['status']='applied';$write($state);echo"Updated the AI product page for the Core RAG visitor assistant.\n";
