<?php
$facts = array_pad(array_slice((array) ($popup['facts'] ?? []), 0, 3), 3, []);
$activeLocale = (string) ($_GET['lang'] ?? ($languages[0]['locale'] ?? 'en'));
$popupDefaultLanguage = array_values(array_filter((array) $languages, static fn(array $language): bool => (bool) ($language['is_default'] ?? false)))[0] ?? ($languages[0] ?? ['locale' => 'en']);
$popupSelectedPage = null;
foreach ($pages as $page) {
    if ((int) ($page['id'] ?? 0) === (int) $selected) {
        $popupSelectedPage = $page;
        break;
    }
}
$popupSelectedPage ??= $pages[0] ?? ['slug' => ''];
$contentWorkspace = [
    'pages' => $pages,
    'selected' => $selected,
    'select' => 'popup',
    'form' => 'page-popup-form',
    'icon' => 'panel-top-open',
    'label' => 'Target page',
    'status' => 'Saved',
    'action' => 'Save pop-up',
    'preview_url' => '/' . rawurlencode((string) $popupDefaultLanguage['locale']) . '/' . rawurlencode((string) ($popupSelectedPage['slug'] ?? '')),
];
require __DIR__ . '/console-content-workspace-header.php';
?>
<form id="page-popup-form" data-content-form method="post" action="/system/extensions/popups" enctype="multipart/form-data" class="grid gap-5 xl:grid-cols-3"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="page_id" value="<?= (int)$selected ?>"><input type="hidden" name="ui_locale" value="<?= $escape($activeLocale) ?>" data-ui-locale>
<section class="card xl:col-span-2"><div class="card-header"><div><h6 class="card-title">Campaign content</h6><p class="mt-1 text-sm text-default-500">Only installed and active languages are available.</p></div><label class="sensecms-switch"><input name="popup_enabled" type="checkbox" value="1" <?= !empty($popup['enabled'])?'checked':'' ?>><span></span><b>Enabled</b></label></div><?php $localeTabsId='popup-locales';$localeTabsActive=$activeLocale;require __DIR__.'/console-language-tabs.php'; ?><div class="card-body"><?php foreach($languages as$language):$locale=(string)$language['locale'];$localized=array_replace(['eyebrow'=>$popup['eyebrow']??'','title'=>$popup['title']??'','text'=>$popup['text']??'','cta_label'=>$popup['cta_label']??'','image_url'=>$popup['image_url']??''],(array)($popup['localized'][$locale]??[])); ?><section class="sensecms-language-panel" data-language-panel="<?= $escape($locale) ?>" <?= $locale!==$activeLocale?'hidden':'' ?>><div class="grid gap-4 md:grid-cols-2"><label><span>Eyebrow</span><input class="form-input" name="popup_localized[<?= $escape($locale) ?>][eyebrow]" maxlength="80" value="<?= $escape($localized['eyebrow']) ?>"></label><label><span>Language image URL</span><input class="form-input" name="popup_localized[<?= $escape($locale) ?>][image_url]" value="<?= $escape($localized['image_url']) ?>"></label><label class="md:col-span-2"><span>Headline</span><input class="form-input" name="popup_localized[<?= $escape($locale) ?>][title]" maxlength="160" value="<?= $escape($localized['title']) ?>"></label><label class="md:col-span-2"><span>Message</span><textarea class="form-input" rows="4" name="popup_localized[<?= $escape($locale) ?>][text]" maxlength="700"><?= $escape($localized['text']) ?></textarea></label><label><span>Action label</span><input class="form-input" name="popup_localized[<?= $escape($locale) ?>][cta_label]" maxlength="60" value="<?= $escape($localized['cta_label']) ?>"></label></div></section><?php endforeach; ?><section class="sensecms-shared-settings"><header><span>SHARED SETTINGS</span><h4>Behaviour and destination</h4></header><div class="grid gap-4 md:grid-cols-2"><label><span>Action URL</span><input class="form-input" name="popup_cta_url" value="<?= $escape($popup['cta_url']??'') ?>"></label><label><span>Display frequency</span><select class="form-input" name="popup_frequency"><?php foreach(['session'=>'Once per browser session','once'=>'Once per browser','always'=>'Every visit']as$value=>$label): ?><option value="<?= $value ?>" <?= ($popup['frequency']??'session')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><label><span>Show from</span><input class="form-input" type="datetime-local" name="popup_start_at" value="<?= $escape($popup['start_at']??'') ?>"></label><label><span>Show until</span><input class="form-input" type="datetime-local" name="popup_end_at" value="<?= $escape($popup['end_at']??'') ?>"></label></div></section></div></section>
<aside class="grid gap-5 h-fit"><section class="card"><div class="card-header"><h6 class="card-title">Responsive dimensions</h6><span class="sensecms-status is-system">Current design</span></div><div class="card-body"><div class="sensecms-dimension-grid"><?php foreach(['width'=>['Modal width','1040','720','1440'],'image_width'=>['Image column','390','260','640'],'height'=>['Desktop height','645','440','900']]as$key=>[$label,$fallback,$min,$max]): ?><label><span><?= $label ?><small>px</small></span><input class="form-input" type="number" min="<?= $min ?>" max="<?= $max ?>" name="popup_<?= $key ?>" value="<?= (int)($popup[$key]??$fallback) ?>"></label><?php endforeach; ?></div><p class="sensecms-field-note"><i data-lucide="smartphone"></i>On tablets and phones the layout collapses automatically and never exceeds the viewport.</p></div></section><section class="card"><div class="card-header"><h6 class="card-title">Visual design</h6></div><div class="card-body grid gap-4"><label><span>Fallback campaign image</span><input class="form-input" type="file" name="popup_image" accept="image/png,image/jpeg,image/webp"><small>PNG, JPG or WebP · max. 5 MB</small></label><label><span>Fallback image URL</span><input class="form-input" name="popup_image_url" value="<?= $escape($popup['image_url']??'') ?>"></label><div class="grid grid-cols-2 gap-3"><?php foreach(['background_color'=>'Background','accent_color'=>'Accent','text_color'=>'Text','icon_color'=>'Icons']as$key=>$label): ?><label><span><?= $label ?></span><input class="sensecms-color" type="color" name="popup_<?= $key ?>" value="<?= $escape($popup[$key]??'#ffffff') ?>"></label><?php endforeach; ?></div></div></section></aside>
<section class="card xl:col-span-3"><div class="card-header"><div><h6 class="card-title">Highlight items</h6><p class="mt-1 text-sm text-default-500">Shared icon structure with concise campaign benefits.</p></div></div><div class="card-body"><div class="grid gap-4 md:grid-cols-3"><?php foreach($facts as$fact): ?><article class="sensecms-highlight-card"><label><span>Icon</span><select class="form-input" name="popup_fact_icon[]"><?php foreach(['graduation-cap'=>'Graduation','globe'=>'Globe','heart'=>'Heart','sparkles'=>'Sparkles','shield-check'=>'Shield']as$value=>$label): ?><option value="<?= $value ?>" <?= ($fact['icon']??'sparkles')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><label><span>Fallback title</span><input class="form-input" name="popup_fact_title[]" value="<?= $escape($fact['title']??'') ?>"></label><label><span>Fallback text</span><textarea class="form-input" rows="3" name="popup_fact_text[]"><?= $escape($fact['text']??'') ?></textarea></label></article><?php endforeach; ?></div><div class="sensecms-form-actions sensecms-form-actions-note"><span><i data-lucide="info"></i>The selected page has its own independent campaign.</span></div></div></section></form>
