<?php
$seoLanguages=array_values($languages??[]);$seoDefaultLanguage=array_values(array_filter($seoLanguages,static fn(array$language):bool=>(bool)($language['is_default']??false)))[0]??($seoLanguages[0]??['locale'=>'en']);
$seoActiveLocale=(string)($_GET['lang']??($seoLanguages[0]['locale']??'en'));if(!in_array($seoActiveLocale,array_column($seoLanguages,'locale'),true))$seoActiveLocale=(string)($seoLanguages[0]['locale']??'en');
$seoSelectedDocument=null;foreach($documents as$document)if((int)($document['id']??0)===(int)$selected){$seoSelectedDocument=$document;break;}$seoSelectedDocument??=$documents[0]??['id'=>0,'title'=>'No documents','slug'=>''];
$seoPreviewUrl='';if(!empty($seoSelectedDocument['id'])){$seoLocale=rawurlencode((string)$seoDefaultLanguage['locale']);$seoBase=!empty($seoSelectedDocument['is_primary'])?'/'.$seoLocale:'/'.$seoLocale.'/facilities/'.rawurlencode((string)($seoSelectedDocument['city_slug']??'')).'/'.rawurlencode((string)($seoSelectedDocument['facility_slug']??''));if($documentType==='post')$seoPreviewUrl=$seoBase.'/posts/'.rawurlencode((string)($seoSelectedDocument['slug']??''));else{$seoHome=(int)($seoSelectedDocument['homepage_page_id']??0)===(int)($seoSelectedDocument['id']??0);$seoPreviewUrl=$seoHome?($seoBase.(!empty($seoSelectedDocument['is_primary'])?'/home':'')):$seoBase.'/'.rawurlencode((string)($seoSelectedDocument['slug']??''));}}
$contentWorkspace=['pages'=>$documents,'selected'=>$selected,'select'=>'seo','seo_type'=>$documentType,'form'=>'document-seo-form','icon'=>'search-check','label'=>'Editing '.($documentType==='post'?'post':'page'),'status'=>'Saved','action'=>'Save metadata','preview_url'=>$seoPreviewUrl];require __DIR__.'/console-content-workspace-header.php';
$globalLocalized=(array)($seoGlobal['localized']??[]);
?>
<nav class="sensecms-seo-document-tabs" aria-label="SEO content type"><a href="/seo?type=page" class="<?= $documentType==='page'?'is-active':'' ?>"><i data-lucide="files"></i>Pages</a><a href="/seo?type=post" class="<?= $documentType==='post'?'is-active':'' ?>"><i data-lucide="newspaper"></i>Posts</a></nav>
<section class="card sensecms-seo-global-card">
    <div class="card-header sensecms-seo-header"><div><span class="sensecms-overline">SITE-WIDE SEARCH FOUNDATION</span><h6 class="card-title">Global SEO, identity and social defaults</h6><p>Used whenever a page or post does not provide its own localized override.</p></div><span class="sensecms-seo-health"><i data-lucide="shield-check"></i>Standards-ready</span></div>
    <form method="post" action="/seo/global" data-content-form class="card-body"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="ui_locale" value="<?= $escape($seoActiveLocale) ?>" data-ui-locale>
        <div class="sensecms-seo-global-grid">
            <div class="sensecms-seo-section"><h4>Site identity</h4><div class="grid gap-4 md:grid-cols-2">
                <label><span>Site name</span><input class="form-input" name="site_name" maxlength="255" value="<?= $escape($seoGlobal['site_name']??'') ?>" required></label><label><span>Alternate site name</span><input class="form-input" name="alternate_name" maxlength="255" value="<?= $escape($seoGlobal['alternate_name']??'') ?>"></label>
                <label><span>Canonical site URL <small>HTTPS</small></span><input class="form-input" type="url" name="site_url" value="<?= $escape($seoGlobal['site_url']??'') ?>" placeholder="https://example.com" required></label><label><span>Organization schema</span><select class="form-input" name="organization_type"><?php foreach(['EducationalOrganization','School','CollegeOrUniversity','Organization']as$value): ?><option value="<?= $value ?>" <?= ($seoGlobal['organization_type']??'')===$value?'selected':'' ?>><?= $value ?></option><?php endforeach; ?></select></label>
                <label class="md:col-span-2"><span>Organization description</span><textarea class="form-input" rows="3" maxlength="1000" name="organization_description"><?= $escape($seoGlobal['organization_description']??'') ?></textarea></label><label><span>Organization logo URL</span><input class="form-input" name="organization_logo" value="<?= $escape($seoGlobal['organization_logo']??'') ?>" placeholder="/path/logo.svg"></label><label><span>Country code <small>ISO 3166-1</small></span><input class="form-input" name="country_code" maxlength="2" value="<?= $escape($seoGlobal['country_code']??'') ?>" placeholder="GB"></label>
                <label><span>Default author</span><input class="form-input" name="author" value="<?= $escape($seoGlobal['author']??'') ?>"></label><label><span>Publisher</span><input class="form-input" name="publisher" value="<?= $escape($seoGlobal['publisher']??'') ?>"></label>
            </div></div>
            <div class="sensecms-seo-section"><h4>Default social image</h4><div class="grid gap-4 md:grid-cols-2">
                <label class="md:col-span-2"><span>Image URL or local path</span><input class="form-input" name="default_social_image" value="<?= $escape($seoGlobal['default_social_image']??'') ?>"></label><label class="md:col-span-2"><span>Image alternative text</span><input class="form-input" name="default_social_image_alt" maxlength="420" value="<?= $escape($seoGlobal['default_social_image_alt']??'') ?>"></label>
                <label><span>Width</span><input class="form-input" type="number" min="1" max="10000" name="default_image_width" value="<?= (int)($seoGlobal['default_image_width']??1200) ?>"></label><label><span>Height</span><input class="form-input" type="number" min="1" max="10000" name="default_image_height" value="<?= (int)($seoGlobal['default_image_height']??630) ?>"></label><label><span>MIME type</span><select class="form-input" name="default_image_type"><?php foreach(['image/webp','image/jpeg','image/png','image/gif']as$value): ?><option value="<?= $value ?>" <?= ($seoGlobal['default_image_type']??'')===$value?'selected':'' ?>><?= $value ?></option><?php endforeach; ?></select></label>
                <label><span>Default robots</span><select class="form-input" name="robots"><?php foreach(['index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1','index,follow','noindex,follow','noindex,nofollow']as$value): ?><option value="<?= $value ?>" <?= ($seoGlobal['robots']??'')===$value?'selected':'' ?>><?= $value ?></option><?php endforeach; ?></select></label>
            </div></div>
        </div>
        <details class="sensecms-seo-advanced"><summary><i data-lucide="share-2"></i><span><b>Social profiles and ownership</b><small>X cards, Facebook and structured organization links</small></span><i data-lucide="chevron-down"></i></summary><div class="grid gap-4 md:grid-cols-2"><?php foreach(['twitter_site'=>'X site handle','twitter_creator'=>'Default X creator','facebook_app_id'=>'Facebook App ID','facebook_url'=>'Facebook URL','instagram_url'=>'Instagram URL','linkedin_url'=>'LinkedIn URL','youtube_url'=>'YouTube URL']as$key=>$label): ?><label><span><?= $label ?></span><input class="form-input" name="<?= $key ?>" value="<?= $escape($seoGlobal[$key]??'') ?>"></label><?php endforeach; ?></div></details>
        <details class="sensecms-seo-advanced"><summary><i data-lucide="badge-check"></i><span><b>Search engine verification</b><small>Ownership tokens only - never paste complete HTML tags</small></span><i data-lucide="chevron-down"></i></summary><div class="grid gap-4 md:grid-cols-2"><?php foreach(['google_site_verification'=>'Google verification token','bing_site_verification'=>'Bing verification token','yandex_verification'=>'Yandex verification token','pinterest_domain_verify'=>'Pinterest verification token']as$key=>$label): ?><label><span><?= $label ?></span><input class="form-input" name="<?= $key ?>" maxlength="255" value="<?= $escape($seoGlobal[$key]??'') ?>"></label><?php endforeach; ?></div></details>
        <div class="sensecms-seo-section sensecms-seo-localized"><h4>Localized site defaults</h4><p>Use <code>%title%</code> and <code>%site_name%</code> in the title template.</p><?php $localeTabsId='seo-global-locales';$localeTabsActive=$seoActiveLocale;require __DIR__.'/console-language-tabs.php'; ?><div class="sensecms-seo-localized-body"><?php foreach($seoLanguages as$language):$locale=(string)$language['locale'];$data=(array)($globalLocalized[$locale]??[]); ?><section class="sensecms-language-panel" data-language-panel="<?= $escape($locale) ?>" <?= $locale!==$seoActiveLocale?'hidden':'' ?>><div class="grid gap-4 md:grid-cols-2"><label><span>Title template</span><input class="form-input" name="localized[<?= $escape($locale) ?>][title_template]" value="<?= $escape($data['title_template']??'%title%') ?>"></label><label><span>Default page title</span><input class="form-input" name="localized[<?= $escape($locale) ?>][default_title]" value="<?= $escape($data['default_title']??'') ?>"></label><label class="md:col-span-2"><span>Default description</span><textarea class="form-input" rows="3" name="localized[<?= $escape($locale) ?>][default_description]"><?= $escape($data['default_description']??'') ?></textarea></label><label class="md:col-span-2"><span>Default keywords <small>compatibility only</small></span><input class="form-input" name="localized[<?= $escape($locale) ?>][default_keywords]" value="<?= $escape($data['default_keywords']??'') ?>"></label><label class="md:col-span-2"><span>Default social image alt text</span><input class="form-input" name="localized[<?= $escape($locale) ?>][default_social_image_alt]" value="<?= $escape($data['default_social_image_alt']??'') ?>"></label></div></section><?php endforeach; ?></div></div>
        <div class="sensecms-form-actions"><span><i data-lucide="layers-3"></i>Global values provide safe fallbacks for every active language.</span><button class="btn bg-primary text-white" type="submit"><i data-lucide="save"></i>Save global SEO</button></div>
    </form>
</section>
<section class="card sensecms-seo-document-card"><div class="card-header sensecms-seo-header"><div><span class="sensecms-overline">LOCALIZED DOCUMENT METADATA</span><h6 class="card-title"><?= $documentType==='post'?'Post':'Page' ?> SEO and social preview</h6><p>Blank fields inherit the strongest available document or site-wide value.</p></div></div>
<?php if(empty($seoSelectedDocument['id'])): ?><div class="card-body"><p>No <?= $documentType==='post'?'posts':'pages' ?> are available in your facility scope.</p></div><?php else: ?><form id="document-seo-form" data-content-form method="post" action="/seo/page"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="document_type" value="<?= $escape($documentType) ?>"><input type="hidden" name="document_id" value="<?= (int)$selected ?>"><input type="hidden" name="ui_locale" value="<?= $escape($seoActiveLocale) ?>" data-ui-locale>
<?php $localeTabsId='seo-document-locales';$localeTabsActive=$seoActiveLocale;require __DIR__.'/console-language-tabs.php'; ?><div class="card-body"><?php foreach($seoLanguages as$language):$locale=(string)$language['locale'];$data=(array)($documentSeo[$locale]??[]); ?><section class="sensecms-language-panel" data-language-panel="<?= $escape($locale) ?>" <?= $locale!==$seoActiveLocale?'hidden':'' ?>>
<div class="sensecms-seo-section"><h4>Search result and indexing</h4><div class="grid gap-4 md:grid-cols-2"><label><span>SEO title</span><input class="form-input" maxlength="255" name="seo[<?= $escape($locale) ?>][title]" value="<?= $escape($data['title']??'') ?>"></label><label><span>Canonical URL</span><input class="form-input" name="seo[<?= $escape($locale) ?>][canonical]" value="<?= $escape($data['canonical']??'') ?>"></label><label class="md:col-span-2"><span>Meta description</span><textarea class="form-input" rows="3" maxlength="500" name="seo[<?= $escape($locale) ?>][description]"><?= $escape($data['description']??'') ?></textarea></label><label class="md:col-span-2"><span>Keywords <small>legacy compatibility; not a ranking signal</small></span><input class="form-input" maxlength="500" name="seo[<?= $escape($locale) ?>][keywords]" value="<?= $escape($data['keywords']??'') ?>"></label><label><span>Robots directives</span><select class="form-input" name="seo[<?= $escape($locale) ?>][robots]"><?php foreach(['index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1','index,follow','noindex,follow','noindex,nofollow']as$value): ?><option value="<?= $value ?>" <?= ($data['robots']??'')===$value?'selected':'' ?>><?= $value ?></option><?php endforeach; ?></select></label><label><span>Structured data type</span><select class="form-input" name="seo[<?= $escape($locale) ?>][schema_type]"><?php $schemaTypes=$documentType==='post'?['Article','BlogPosting','NewsArticle']:['WebPage','AboutPage','ContactPage','CollectionPage'];foreach($schemaTypes as$value): ?><option value="<?= $value ?>" <?= ($data['schema_type']??'')===$value?'selected':'' ?>><?= $value ?></option><?php endforeach; ?></select></label><label><span>Author</span><input class="form-input" name="seo[<?= $escape($locale) ?>][author]" value="<?= $escape($data['author']??'') ?>"></label></div></div>
<div class="sensecms-seo-section"><h4>Open Graph</h4><div class="grid gap-4 md:grid-cols-2"><label><span>Content type</span><select class="form-input" name="seo[<?= $escape($locale) ?>][og_type]"><?php foreach(['website','article']as$value): ?><option value="<?= $value ?>" <?= ($data['og_type']??'')===$value?'selected':'' ?>><?= $value ?></option><?php endforeach; ?></select></label><label><span>OG title</span><input class="form-input" name="seo[<?= $escape($locale) ?>][og_title]" value="<?= $escape($data['og_title']??'') ?>"></label><label class="md:col-span-2"><span>OG description</span><textarea class="form-input" rows="3" name="seo[<?= $escape($locale) ?>][og_description]"><?= $escape($data['og_description']??'') ?></textarea></label><label class="md:col-span-2"><span>OG image URL or local path</span><input class="form-input" name="seo[<?= $escape($locale) ?>][og_image]" value="<?= $escape($data['og_image']??'') ?>"></label><label class="md:col-span-2"><span>OG image alternative text</span><input class="form-input" name="seo[<?= $escape($locale) ?>][og_image_alt]" value="<?= $escape($data['og_image_alt']??'') ?>"></label><label><span>Image width</span><input class="form-input" type="number" min="0" max="10000" name="seo[<?= $escape($locale) ?>][og_image_width]" value="<?= (int)($data['og_image_width']??0) ?>"></label><label><span>Image height</span><input class="form-input" type="number" min="0" max="10000" name="seo[<?= $escape($locale) ?>][og_image_height]" value="<?= (int)($data['og_image_height']??0) ?>"></label><label><span>Image MIME type</span><input class="form-input" name="seo[<?= $escape($locale) ?>][og_image_type]" value="<?= $escape($data['og_image_type']??'') ?>" placeholder="image/webp"></label></div></div>
<div class="sensecms-seo-section"><h4>X / Twitter Card</h4><div class="grid gap-4 md:grid-cols-2"><label><span>Card format</span><select class="form-input" name="seo[<?= $escape($locale) ?>][twitter_card]"><?php foreach(['summary_large_image','summary']as$value): ?><option value="<?= $value ?>" <?= ($data['twitter_card']??'')===$value?'selected':'' ?>><?= $value ?></option><?php endforeach; ?></select></label><label><span>Creator handle</span><input class="form-input" name="seo[<?= $escape($locale) ?>][twitter_creator]" value="<?= $escape($data['twitter_creator']??'') ?>"></label><label><span>X title</span><input class="form-input" name="seo[<?= $escape($locale) ?>][twitter_title]" value="<?= $escape($data['twitter_title']??'') ?>"></label><label class="md:col-span-2"><span>X description</span><textarea class="form-input" rows="3" name="seo[<?= $escape($locale) ?>][twitter_description]"><?= $escape($data['twitter_description']??'') ?></textarea></label><label class="md:col-span-2"><span>X image URL or local path</span><input class="form-input" name="seo[<?= $escape($locale) ?>][twitter_image]" value="<?= $escape($data['twitter_image']??'') ?>"></label><label class="md:col-span-2"><span>X image alternative text</span><input class="form-input" name="seo[<?= $escape($locale) ?>][twitter_image_alt]" value="<?= $escape($data['twitter_image_alt']??'') ?>"></label></div></div>
</section><?php endforeach; ?></div><div class="sensecms-form-actions sensecms-form-actions-note"><span><i data-lucide="languages"></i>All active language variants are saved together.</span></div></form><?php endif; ?></section>
