<?php
$canManageUsers=in_array('system.owner',$accessPermissions,true)||in_array('users.manage',$accessPermissions,true);$canManageRoles=in_array('system.owner',$accessPermissions,true)||in_array('roles.manage',$accessPermissions,true);$canAudit=in_array('system.owner',$accessPermissions,true)||in_array('audit.view',$accessPermissions,true);
$tabs=['users'=>['users-round','Users'],'teams'=>['network','Teams'],'roles'=>['shield-check','Roles']];if($canAudit)$tabs['audit']=['scroll-text','Audit log'];
?>
<section class="sensecms-access-shell">
    <?php $sectionHero=['overline'=>'SYSTEM · IDENTITY & GOVERNANCE','title'=>'Access control','description'=>'Assign responsibilities, facility boundaries and precise capabilities without coupling administration to the active website theme.','icon'=>'shield-user','status'=>count($accessUsers).' user accounts','status_detail'=>count($accessTeams).' operational teams'];require __DIR__.'/console-section-hero.php'; ?>
    <nav class="sensecms-access-tabs" aria-label="Access control sections"><?php foreach($tabs as$key=>[$icon,$label]): ?><a href="/system/access?tab=<?= $key ?>" class="<?= $accessTab===$key?'is-active':'' ?>"><i data-lucide="<?= $icon ?>"></i><?= $label ?></a><?php endforeach; ?></nav>
    <?php if($accessTab==='users'): ?>
    <div class="sensecms-access-layout"><section class="card sensecms-access-list"><header class="sensecms-access-list-head"><div><h3>Platform users</h3><span><?= count($accessUsers) ?> accounts</span></div><?php if($canManageUsers): ?><a class="btn btn-sm bg-primary text-white" href="/system/access?tab=users"><i data-lucide="user-plus"></i>New user</a><?php endif; ?></header><?php foreach($accessUsers as$item):$initials=implode('',array_map(static fn(string$part):string=>mb_substr($part,0,1),array_slice(preg_split('/\s+/',trim((string)$item['name']))?:[],0,2))); ?><article class="sensecms-person"><div class="sensecms-person-main"><span class="sensecms-avatar"><?= $escape(mb_strtoupper($initials?:'U')) ?></span><div><strong><?= $escape($item['name']) ?></strong><small><?= $escape($item['job_title']?:$item['email']) ?></small><div class="sensecms-access-meta"><span class="sensecms-state-dot <?= $item['active']?'':'is-off' ?>"><?= $item['active']?'Active':'Disabled' ?></span><?php if($item['role_names']): ?><span class="sensecms-access-chip"><i></i><?= $escape($item['role_names']) ?></span><?php endif; ?><?php if($item['facility_names']): ?><span class="sensecms-access-chip"><i style="--chip:#0f9f6e"></i><?= $escape($item['facility_names']) ?></span><?php endif; ?></div></div></div><?php if($canManageUsers): ?><a class="sensecms-access-edit" href="/system/access?tab=users&edit_user=<?= (int)$item['id'] ?>" aria-label="Edit <?= $escape($item['name']) ?>"><i data-lucide="pencil"></i></a><?php endif; ?></article><?php endforeach; ?></section>
    <?php if($canManageUsers):$edit=$accessUser??[];$selectedRole=(int)($edit['role_ids'][0]??0); ?>
    <form class="card sensecms-access-form" method="post" action="/system/access/users">
        <input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>">
        <header class="card-header"><div><span class="sensecms-overline"><?= $edit?'EDIT ACCOUNT':'NEW ACCOUNT' ?></span><h3><?= $edit?'User access':'Invite a platform user' ?></h3></div></header>
        <div class="card-body">
            <label><span>Display name</span><input class="form-input" name="name" maxlength="120" required value="<?= $escape($edit['name']??'') ?>"></label>
            <label><span>E-mail address</span><input class="form-input" type="email" name="email" maxlength="190" required value="<?= $escape($edit['email']??'') ?>"></label>
            <label><span>Job title</span><input class="form-input" name="job_title" maxlength="120" value="<?= $escape($edit['job_title']??'') ?>"></label>
            <label><span><?= $edit?'New password - leave blank to keep current':'Optional initial password' ?></span><input class="form-input" type="password" name="password" minlength="14" autocomplete="new-password"><small class="sensecms-access-help"><?= $edit?'Enter at least 14 characters only when changing the password manually.':'Leave blank to send a secure one-time link that lets the user create a private password.' ?></small></label>
            <div><span class="sensecms-permission-title">Primary role</span><div class="sensecms-check-grid"><?php foreach($accessRoles as$role): ?><label class="sensecms-check"><input class="form-radio" type="radio" name="role_id" value="<?= (int)$role['id'] ?>" <?= $selectedRole===(int)$role['id']?'checked':'' ?> required><span><b><?= $escape($role['name']) ?></b><small><?= $escape($role['description']??'') ?></small></span></label><?php endforeach; ?></div><small class="sensecms-access-help">Choose one role. Saving replaces all earlier role assignments for this account.</small></div>
            <label class="sensecms-check sensecms-demo-option"><input class="form-checkbox" type="checkbox" name="is_demo" <?= !empty($edit['is_demo'])?'checked':'' ?>><span><b>Demo User</b><small>Grants access to every area in read-only mode. Changes, uploads, messages and all other write operations are blocked.</small></span><i data-lucide="lock-keyhole"></i></label>
            <div><span class="sensecms-permission-title">Direct facility scope</span><div class="sensecms-check-grid"><?php foreach($accessFacilities as$facility): ?><label class="sensecms-check"><input class="form-checkbox" type="checkbox" name="facility_ids[]" value="<?= (int)$facility['id'] ?>" <?= in_array((int)$facility['id'],(array)($edit['facility_ids']??[]),true)?'checked':'' ?>><span><b><?= $escape(($facility['city_name']??$facility['city_slug']).' · '.($facility['name']??$facility['facility_slug'])) ?></b></span></label><?php endforeach; ?></div><small class="sensecms-access-help">Owner and Demo User have global visibility. Other users receive the union of direct and team facility scopes.</small></div>
            <label class="sensecms-check"><input class="form-checkbox" type="checkbox" name="active" <?= !isset($edit['active'])||$edit['active']?'checked':'' ?>><span><b>Active account</b><small>Disabled accounts cannot sign in.</small></span></label>
            <div class="sensecms-access-submit"><?php if($edit): ?><button class="btn bg-default-150 text-default-700" type="submit" formaction="/system/access/users/<?= (int)$edit['id'] ?>/welcome" formnovalidate><i data-lucide="mail-plus"></i>Resend welcome e-mail</button><?php endif; ?><button class="btn bg-primary text-white" type="submit"><i data-lucide="save"></i>Save user access</button></div>
        </div>
    </form><?php endif; ?></div>
    <?php elseif($accessTab==='teams'): ?>
    <div class="sensecms-access-layout"><section class="card sensecms-access-list"><header class="sensecms-access-list-head"><div><h3>Operational teams</h3><span><?= count($accessTeams) ?> teams</span></div><?php if($canManageUsers): ?><a class="btn btn-sm bg-primary text-white" href="/system/access?tab=teams"><i data-lucide="plus"></i>New team</a><?php endif; ?></header><?php foreach($accessTeams as$item): ?><article class="sensecms-team"><div><strong><span style="color:<?= $escape($item['color']) ?>">●</span> <?= $escape($item['name']) ?></strong><small><?= $escape($item['description']?:'Shared operational responsibility') ?></small><div class="sensecms-access-meta"><span class="sensecms-access-chip"><?= (int)$item['user_count'] ?> users</span><span class="sensecms-access-chip"><?= (int)$item['facility_count'] ?> facilities</span><span class="sensecms-state-dot <?= $item['active']?'':'is-off' ?>"><?= $item['active']?'Active':'Disabled' ?></span></div></div><?php if($canManageUsers): ?><a class="sensecms-access-edit" href="/system/access?tab=teams&edit_team=<?= (int)$item['id'] ?>"><i data-lucide="pencil"></i></a><?php endif; ?></article><?php endforeach; ?></section>
    <?php if($canManageUsers):$edit=$accessTeam??[]; ?><form class="card sensecms-access-form" method="post" action="/system/access/teams"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><header class="card-header"><div><span class="sensecms-overline"><?= $edit?'EDIT TEAM':'NEW TEAM' ?></span><h3><?= $edit?'Team scope':'Create an operational team' ?></h3></div></header><div class="card-body"><label><span>Team name</span><input class="form-input" name="name" maxlength="120" required value="<?= $escape($edit['name']??'') ?>"></label><label><span>Slug</span><input class="form-input" name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="<?= $escape($edit['slug']??'') ?>" placeholder="generated-from-name"></label><label><span>Description</span><textarea class="form-input" rows="3" maxlength="500" name="description"><?= $escape($edit['description']??'') ?></textarea></label><label><span>Colour</span><input class="form-input" type="color" name="color" value="<?= $escape($edit['color']??'#2563eb') ?>"></label><div><span class="sensecms-permission-title">Members</span><div class="sensecms-check-grid"><?php foreach($accessUsers as$userOption): ?><label class="sensecms-check"><input class="form-checkbox" type="checkbox" name="user_ids[]" value="<?= (int)$userOption['id'] ?>" <?= in_array((int)$userOption['id'],(array)($edit['user_ids']??[]),true)?'checked':'' ?>><span><b><?= $escape($userOption['name']) ?></b><small><?= $escape($userOption['email']) ?></small></span></label><?php endforeach; ?></div></div><div><span class="sensecms-permission-title">Facility responsibility</span><div class="sensecms-check-grid"><?php foreach($accessFacilities as$facility): ?><label class="sensecms-check"><input class="form-checkbox" type="checkbox" name="facility_ids[]" value="<?= (int)$facility['id'] ?>" <?= in_array((int)$facility['id'],(array)($edit['facility_ids']??[]),true)?'checked':'' ?>><span><b><?= $escape(($facility['city_name']??$facility['city_slug']).' · '.($facility['name']??$facility['facility_slug'])) ?></b></span></label><?php endforeach; ?></div></div><label class="sensecms-check"><input class="form-checkbox" type="checkbox" name="active" <?= !isset($edit['active'])||$edit['active']?'checked':'' ?>><span><b>Active team</b></span></label><button class="btn bg-primary text-white" type="submit"><i data-lucide="save"></i>Save team</button></div></form><?php endif; ?></div>
    <?php elseif($accessTab==='roles'): ?>
    <div class="sensecms-access-layout"><section class="card sensecms-access-list"><header class="sensecms-access-list-head"><div><h3>Permission roles</h3><span><?= count($accessRoles) ?> roles</span></div><?php if($canManageRoles): ?><a class="btn btn-sm bg-primary text-white" href="/system/access?tab=roles"><i data-lucide="plus"></i>New role</a><?php endif; ?></header><?php foreach($accessRoles as$item): ?><article class="sensecms-role-row"><div><strong><span style="color:<?= $escape($item['color']) ?>">●</span> <?= $escape($item['name']) ?> <?= $item['is_system']?'<small style="display:inline">SYSTEM</small>':'' ?></strong><small><?= $escape($item['description']??'') ?></small><div class="sensecms-access-meta"><span class="sensecms-access-chip"><?= (int)$item['user_count'] ?> users</span><span class="sensecms-access-chip"><?= (int)$item['permission_count'] ?> permissions</span></div></div><?php if($canManageRoles&&$item['slug']!=='owner'): ?><a class="sensecms-access-edit" href="/system/access?tab=roles&edit_role=<?= (int)$item['id'] ?>"><i data-lucide="pencil"></i></a><?php endif; ?></article><?php endforeach; ?></section>
    <?php if($canManageRoles):$edit=$accessRole??[];$protected=($edit['slug']??'')==='owner'; ?><form class="card sensecms-access-form" method="post" action="/system/access/roles"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><header class="card-header"><div><span class="sensecms-overline"><?= $edit?'EDIT ROLE':'NEW ROLE' ?></span><h3><?= $edit?'Capabilities':'Create a permission role' ?></h3></div></header><div class="card-body"><label><span>Role name</span><input class="form-input" name="name" maxlength="100" required value="<?= $escape($edit['name']??'') ?>"></label><label><span>Slug</span><input class="form-input" name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="<?= $escape($edit['slug']??'') ?>"></label><label><span>Description</span><textarea class="form-input" rows="3" maxlength="500" name="description"><?= $escape($edit['description']??'') ?></textarea></label><label><span>Colour</span><input class="form-input" type="color" name="color" value="<?= $escape($edit['color']??'#2563eb') ?>"></label><div class="sensecms-permission-groups"><?php foreach($permissionGroups as$group=>$permissions): ?><section class="sensecms-permission-group"><strong><?= $escape($group) ?></strong><?php foreach($permissions as$permission): ?><label class="sensecms-check"><input class="form-checkbox" type="checkbox" name="permission_ids[]" value="<?= (int)$permission['id'] ?>" <?= in_array($permission['slug'],(array)($edit['permissions']??[]),true)?'checked':'' ?>><span><b><?= $escape($permission['name']) ?></b><small><?= $escape($permission['description']) ?></small></span></label><?php endforeach; ?></section><?php endforeach; ?></div><label class="sensecms-check"><input class="form-checkbox" type="checkbox" name="active" <?= !isset($edit['active'])||$edit['active']?'checked':'' ?>><span><b>Active role</b></span></label><button class="btn bg-primary text-white" type="submit"><i data-lucide="save"></i>Save role</button></div></form><?php endif; ?></div>
    <?php else: ?><section class="card sensecms-access-list"><header class="sensecms-access-list-head"><div><h3>Security and editorial activity</h3><span>Most recent <?= count($accessAudit) ?> events</span></div></header><?php foreach($accessAudit as$item): ?><article class="sensecms-audit-row"><b><?= $escape($item['actor_name']) ?></b><span><?= $escape(str_replace('.',' · ',(string)$item['event'])) ?> · <?= $escape($item['subject_type']) ?> #<?= (int)$item['subject_id'] ?></span><span><?= $escape(date('M j, Y · H:i',strtotime((string)$item['created_at']))) ?></span></article><?php endforeach; ?></section><?php endif; ?>
</section>
