<?php
$official=$officialMarketplace??[];$catalog=$official['products']??[];
$code=strtolower(substr((string)($_GET['lang']??$_SERVER['HTTP_ACCEPT_LANGUAGE']??'en'),0,2));if(!in_array($code,['en','de','zh','vi','th','lo','pl'],true))$code='en';
?>
<section class="sensecms-official"><header><div><span class="sensecms-update-kicker">DIRECT FROM SENSECMS.COM</span><h2>Official Marketplace</h2><p>Core system, themes, educational tools and integrations. Licensed downloads are verified on the official Marketplace.</p></div><a class="btn bg-default-150" href="https://www.sensecms.com/<?= $code ?>/marketplace/" target="_blank" rel="noopener noreferrer">Open Marketplace <i data-lucide="external-link"></i></a></header>
<?php if(!$catalog): ?><p role="status">The official catalog has not been synchronized yet. The server worker will download it automatically. <a href="/system/update">Check update status</a>.</p><?php endif; ?>
<div class="sensecms-official-grid"><?php foreach($catalog as $product): $copy=$product['copy'][$code]??$product['copy']['en']; ?>
<article><div class="sensecms-official-top"><span class="sensecms-update-symbol"><i data-lucide="<?= $escape($product['icon']==='devices'?'monitor-smartphone':$product['icon']) ?>"></i></span><span><?= $escape(ucfirst($product['type'])) ?></span></div><h3><?= $escape($product['name']) ?></h3><p><?= $escape($copy['description']) ?></p><div class="sensecms-official-meta"><span>v<?= $escape($product['version']) ?></span><span><?= $escape(ucfirst($product['channel'])) ?></span><?php foreach($copy['meta'] as $label): ?><span><?= $escape($label) ?></span><?php endforeach; ?></div><a class="btn <?= $product['licensed']?'bg-default-150':'bg-primary text-white' ?>" href="https://www.sensecms.com/<?= $code ?>/marketplace/#package-<?= $escape($product['id']) ?>" target="_blank" rel="noopener noreferrer"><?= $product['licensed']?'Download package':'Download on Marketplace' ?><i data-lucide="<?= $product['licensed']?'lock-keyhole':'external-link' ?>"></i></a></article>
<?php endforeach; ?></div></section>
