<?php $items=(array)($pageList['items']??[]);$pagination=(array)($pageList['pagination']??[]);$counts=(array)($pageList['counts']??[]); ?>
<section class="sensecms-content-index" data-content-index="pages">
    <?php $sectionHero=['overline'=>'CONTENT · PAGE MANAGEMENT','title'=>'Pages','description'=>'Manage lifecycle, translations and page structure from one professional workspace.','icon'=>'files','action_url'=>'/content/pages/new','action_label'=>'Create page','action_icon'=>'file-plus-2'];require __DIR__.'/console-section-hero.php'; ?>
    <?php if(($contentStatus??'all')==='archived'&&(int)($counts['archived']??0)>0): ?><div class="sensecms-index-utility"><form method="post" action="/content/pages/trash/empty" data-sensecms-confirm="Permanently delete every page in the trash? This removes their translations, sections and revision history and cannot be undone."><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button class="btn sensecms-empty-trash" type="submit"><i data-lucide="trash-2"></i>Empty trash</button></form></div><?php endif; ?>
    <nav class="sensecms-index-filters" aria-label="Page status"><?php foreach(['all'=>'All','published'=>'Published','draft'=>'Drafts','scheduled'=>'Scheduled','private'=>'Private','archived'=>'Archived']as$value=>$label): ?><a href="/content/pages?status=<?= $value ?>&facility=<?= (int)($facilityFilter??0) ?>" data-content-link class="<?= ($contentStatus??'all')===$value?'is-active':'' ?>"><?= $label ?><span><?= (int)($counts[$value]??0) ?></span></a><?php endforeach; ?></nav>
    <form class="sensecms-index-search sensecms-facility-filter" data-content-filter action="/content/pages"><input type="hidden" name="status" value="<?= $escape($contentStatus??'all') ?>"><i data-lucide="search"></i><input name="q" type="search" value="<?= $escape($contentQuery??'') ?>" placeholder="Search pages by title, slug or excerpt…"><select name="facility" aria-label="Filter by facility"><option value="0">All facilities</option><?php foreach($facilities as$facilityOption): ?><option value="<?= (int)$facilityOption['id'] ?>" <?= (int)($facilityFilter??0)===(int)$facilityOption['id']?'selected':'' ?>><?= $escape(($facilityOption['city_name']??$facilityOption['city_slug']).' · '.($facilityOption['name']??$facilityOption['facility_slug'])) ?></option><?php endforeach; ?></select><button type="submit">Search</button></form>
    <div class="sensecms-content-table card">
        <div class="sensecms-content-table-head"><span>Page</span><span>Content</span><span>Publication</span><span>Actions</span></div>
        <div class="sensecms-content-table-body"><?php foreach($items as$item):$archived=($item['status']??'')==='archived';$locale=(string)($item['locale']??'en');$isHome=(int)($item['homepage_page_id']??0)===(int)$item['id'];$preview=!empty($item['is_primary'])?'/'.rawurlencode($locale).'/'.rawurlencode((string)($item['slug']??'')):'/'.rawurlencode($locale).'/facilities/'.rawurlencode((string)$item['city_slug']).'/'.rawurlencode((string)$item['facility_slug']).($isHome?'':'/'.rawurlencode((string)($item['slug']??''))); $preview=(string)($item['public_path']??$preview); ?><article class="sensecms-content-row">
            <div class="sensecms-content-identity"><i data-lucide="file-text"></i><span><strong><?= $escape($item['title']??'Untitled page') ?></strong><small><?= $escape(($item['facility_name']??'Facility').' · '.$preview) ?></small></span></div>
            <div class="sensecms-content-metrics"><span><b><?= (int)($item['block_count']??0) ?></b> sections</span><span><b><?= (int)($item['translation_count']??0) ?></b> languages</span></div>
            <div><span class="sensecms-lifecycle is-<?= $escape((string)($item['status']??'draft')) ?>"><i data-lucide="<?= $archived?'archive':(($item['status']??'')==='published'?'circle-check':'clock-3') ?>"></i><?= $escape(ucfirst((string)($item['status']??'draft'))) ?></span><?php if(!empty($item['published_at'])): ?><small class="sensecms-date"><?= $escape(date('M j, Y · H:i',strtotime((string)$item['published_at']))) ?></small><?php endif; ?></div>
            <div class="sensecms-row-actions"><a href="/content/pages/<?= (int)$item['id'] ?>/edit" data-content-link aria-label="Edit page"><i data-lucide="pencil"></i></a><?php if(!$archived): ?><a href="/content/builder?document=<?= (int)$item['id'] ?>" data-content-link aria-label="Open Page Builder"><i data-lucide="panels-top-left"></i></a><a href="<?= $escape($preview) ?>" target="_blank" rel="noopener" aria-label="Preview page"><i data-lucide="external-link"></i></a><form method="post" action="/content/pages/<?= (int)$item['id'] ?>/duplicate"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button aria-label="Duplicate page"><i data-lucide="copy"></i></button></form><?php endif; ?><form method="post" action="/content/pages/<?= (int)$item['id'] ?>/<?= $archived?'restore':'archive' ?>" data-sensecms-confirm="<?= $archived?'Restore this page as a draft?':'Move this page to the trash without deleting its content?' ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button class="<?= $archived?'is-restore':'is-danger' ?>" aria-label="<?= $archived?'Restore':'Move to trash' ?> page"><i data-lucide="<?= $archived?'archive-restore':'archive' ?>"></i></button></form><?php if($archived): ?><form method="post" action="/content/pages/<?= (int)$item['id'] ?>/delete" data-sensecms-confirm="Permanently delete this page, all translations, sections and revision history? This cannot be undone."><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button class="is-delete" aria-label="Permanently delete page"><i data-lucide="trash-2"></i></button></form><?php endif; ?></div>
        </article><?php endforeach; ?><?php if(!$items): ?><div class="sensecms-content-empty"><i data-lucide="<?= ($contentStatus??'all')==='archived'?'trash-2':'files' ?>"></i><strong><?= ($contentStatus??'all')==='archived'?'The page trash is empty':'No pages found' ?></strong><span><?= ($contentStatus??'all')==='archived'?'Archived pages remain recoverable here until permanently deleted.':'Adjust the filters or create a new page.' ?></span></div><?php endif; ?></div>
        <footer class="sensecms-index-pagination"><span><?= (int)($pagination['total']??0) ?> pages</span><div><a data-content-link class="<?= ($pagination['page']??1)<=1?'is-disabled':'' ?>" href="/content/pages?status=<?= $escape($contentStatus??'all') ?>&facility=<?= (int)($facilityFilter??0) ?>&q=<?= rawurlencode((string)($contentQuery??'')) ?>&page=<?= max(1,(int)($pagination['page']??1)-1) ?>"><i data-lucide="chevron-left"></i></a><b><?= (int)($pagination['page']??1) ?> / <?= (int)($pagination['pages']??1) ?></b><a data-content-link class="<?= ($pagination['page']??1)>=($pagination['pages']??1)?'is-disabled':'' ?>" href="/content/pages?status=<?= $escape($contentStatus??'all') ?>&facility=<?= (int)($facilityFilter??0) ?>&q=<?= rawurlencode((string)($contentQuery??'')) ?>&page=<?= min((int)($pagination['pages']??1),(int)($pagination['page']??1)+1) ?>"><i data-lucide="chevron-right"></i></a></div></footer>
    </div>
</section>
