<?php
$surveyBoot=['data'=>$surveyData,'filters'=>$surveyFilters,'languages'=>array_values($languages),'facilities'=>array_values($facilities),'pages'=>array_values($surveyPages),'permissions'=>$surveyPermissions,'csrf'=>$csrf];
?>
<section class="sensecms-surveys" data-surveys-root>
    <?php $sectionHero=['overline'=>'ENGAGEMENT · PROFESSIONAL SURVEYS','title'=>'Research, feedback and measurable experience','description'=>'Build multilingual campaigns, route respondents with conditional logic and turn trusted feedback into facility-aware decisions.','icon'=>'clipboard-list','action_button'=>empty($surveyPermissions['manage'])?'':'data-survey-new','action_label'=>'Create survey','action_icon'=>'plus'];require __DIR__.'/console-section-hero.php'; ?>
    <section class="sensecms-survey-summary" data-survey-summary></section>
    <section class="sensecms-survey-list-view" data-survey-list-view>
        <div class="sensecms-survey-toolbar"><label><i data-lucide="search"></i><input class="form-input" type="search" placeholder="Search surveys..." data-survey-filter="q" value="<?= $escape($surveyFilters['q']??'') ?>"></label><select class="form-input" data-survey-filter="status"><option value="all">Every status</option><?php foreach(['draft'=>'Draft','scheduled'=>'Scheduled','published'=>'Published','closed'=>'Closed']as$value=>$label):?><option value="<?= $value ?>" <?= ($surveyFilters['status']??'all')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select><select class="form-input" data-survey-filter="facility_id"><option value="0">Every facility</option><?php foreach($facilities as$facility):?><option value="<?= (int)$facility['id'] ?>" <?= (int)($surveyFilters['facility_id']??0)===(int)$facility['id']?'selected':'' ?>><?= $escape(($facility['city_name']??$facility['city_slug']).' · '.($facility['name']??$facility['facility_slug'])) ?></option><?php endforeach;?></select></div>
        <div class="sensecms-survey-grid" data-survey-grid></div><nav class="sensecms-survey-pagination" data-survey-pagination></nav>
    </section>
    <section class="sensecms-survey-workspace" data-survey-workspace hidden>
        <header class="sensecms-content-workspace-header"><div class="sensecms-content-workspace-center"><i><i data-lucide="clipboard-check"></i></i><div><span>EDITING SURVEY</span><strong data-survey-workspace-title>Untitled survey</strong></div><b data-survey-workspace-status>Draft</b></div><div class="sensecms-content-workspace-actions"><span class="sensecms-content-save-state" data-survey-save-state><i></i>All changes saved</span><button class="btn bg-default-150" type="button" data-survey-back-list><i data-lucide="arrow-left"></i>All surveys</button><button class="btn bg-primary text-white" type="button" data-survey-save <?= empty($surveyPermissions['manage'])?'hidden':'' ?>><i data-lucide="save"></i>Save survey</button></div></header>
        <nav class="sensecms-survey-tabs" aria-label="Survey workspace"><button class="is-active" type="button" data-survey-tab="builder"><i data-lucide="blocks"></i>Builder</button><button type="button" data-survey-tab="logic"><i data-lucide="git-branch"></i>Logic</button><button type="button" data-survey-tab="publishing"><i data-lucide="send"></i>Publishing</button><button type="button" data-survey-tab="results"><i data-lucide="chart-no-axes-combined"></i>Statistics</button><button type="button" data-survey-tab="responses"><i data-lucide="rows-3"></i>Responses</button></nav>
        <div data-survey-panel="builder"><nav class="sensecms-language-tabs" data-survey-languages></nav><div class="sensecms-survey-builder-layout"><div><section class="sensecms-survey-settings-card" data-survey-copy></section><section class="sensecms-survey-pages" data-survey-pages></section></div><aside class="sensecms-survey-palette"><header><span>QUESTION LIBRARY</span><strong>9 professional field types</strong></header><div data-survey-palette></div><button type="button" data-survey-add-page><i data-lucide="file-plus-2"></i>Add survey page</button></aside></div></div>
        <div data-survey-panel="logic" hidden><section class="sensecms-survey-panel-head"><div><span>CONDITIONAL EXPERIENCE</span><h3>Route every respondent intelligently.</h3><p>Rules are evaluated in order. Show or hide questions, skip a page or finish a path early.</p></div><button class="btn bg-primary text-white" type="button" data-survey-add-rule><i data-lucide="plus"></i>Add rule</button></section><div class="sensecms-survey-rules" data-survey-rules></div></div>
        <div data-survey-panel="publishing" hidden><div class="sensecms-survey-publish-grid" data-survey-publishing></div></div>
        <div data-survey-panel="results" hidden><section class="sensecms-survey-results-toolbar"><div><span>LIVE ANALYTICS</span><h3>Decisions backed by clear evidence.</h3></div><select class="form-input" data-results-facility><option value="0">All targeted facilities</option></select><div class="sensecms-survey-export" data-survey-export></div></section><div data-survey-results></div></div>
        <div data-survey-panel="responses" hidden><section class="sensecms-survey-response-toolbar"><select class="form-input" data-response-status><option value="all">Every response</option><option value="completed">Completed</option><option value="started">Started</option><option value="abandoned">Abandoned</option></select><input class="form-input" type="date" data-response-from><input class="form-input" type="date" data-response-to></section><div data-survey-responses></div></div>
    </section>
    <div class="sensecms-survey-drawer" data-survey-response-drawer hidden><section><header><div><span>RESPONSE DETAIL</span><h3 data-response-title>Response</h3></div><button type="button" data-response-close aria-label="Close"><i data-lucide="x"></i></button></header><div data-response-body></div></section></div>
</section>
<script nonce="<?= htmlspecialchars((string) ($_SERVER['SENSE_CSP_NONCE'] ?? ''), ENT_QUOTES, 'UTF-8') ?>">window.SenseCMSSurveys=<?= json_encode($surveyBoot,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;</script>
