<?php
$tab=in_array($_GET['tab']??'sources',['sources','content','index','training'],true)?(string)$_GET['tab']:'sources';
$summary=(array)$knowledgeSummary;$documents=(array)($knowledgeDocuments['items']??[]);$pagination=(array)($knowledgeDocuments['pagination']??[]);$editing=(array)($knowledgeEdit??[]);
$training=(array)($knowledgeTrainingWorkspace??[]);$datasets=(array)($training['datasets']??[]);$examples=(array)($training['examples']??[]);$evaluations=(array)($training['evaluations']??[]);$providers=(array)($knowledgeProviders??[]);
$sectionHero=['overline'=>'CORE AI · RETRIEVAL','title'=>'Knowledge Base','description'=>'Control the approved knowledge used by the visitor assistant. Sources remain editable, removable and independent of any single AI provider.','icon'=>'brain-circuit','status'=>(int)($summary['ready']??0).' ready sources','status_detail'=>(int)($summary['chunks']??0).' indexed retrieval chunks','status_icon'=>empty($summary['failed'])?'circle-check':'triangle-alert'];
$tabs=['sources'=>['library-big','Sources','Manual knowledge and private files'],'content'=>['files','Website content','Pages and posts included in RAG'],'index'=>['database-zap','RAG index','Build status and controlled rebuild'],'training'=>['flask-conical','Training & evals','Curated data before fine-tuning']];
$formatBytes=static function(int$bytes):string{if($bytes<1024)return$bytes.' B';if($bytes<1048576)return number_format($bytes/1024,1).' KiB';return number_format($bytes/1048576,1).' MiB';};
?>
<section class="sensecms-unified-workspace" data-ai-knowledge data-csrf="<?= $escape($csrf) ?>">
    <?php require __DIR__.'/console-section-hero.php'; ?>
    <?php $aiActive='knowledge';require __DIR__.'/console-ai-navigation.php'; ?>
    <div class="sensecms-ai-summary">
        <?php foreach([['Approved sources',$summary['active']??0],['Indexed chunks',$summary['chunks']??0],['Included content',$summary['included_content']??0],['Private files',$formatBytes((int)($summary['bytes']??0))]]as[$label,$value]): ?><article><span><?= $escape($label) ?></span><strong><?= $escape((string)$value) ?></strong></article><?php endforeach; ?>
    </div>
    <nav class="sensecms-knowledge-tabs" aria-label="Knowledge Base sections"><?php foreach($tabs as$key=>$definition):[$icon,$label,$detail]=$definition; ?><a href="/ai/knowledge?tab=<?= $key ?>" class="<?= $tab===$key?'is-active':'' ?>"><i data-lucide="<?= $icon ?>"></i><span><b><?= $escape($label) ?></b><small><?= $escape($detail) ?></small></span></a><?php endforeach; ?></nav>

    <?php if($tab==='sources'): ?>
    <div class="sensecms-knowledge-layout">
        <section class="card sensecms-knowledge-editor">
            <div class="card-header"><div><span class="sensecms-overline"><?= $editing?'EDIT SOURCE':'ADD KNOWLEDGE' ?></span><h6 class="card-title"><?= $editing?$escape((string)$editing['title']):'New source' ?></h6><p>Write approved knowledge directly or upload a document. Originals are stored outside the public web root.</p></div></div>
            <form method="post" action="/ai/knowledge/documents" enctype="multipart/form-data" class="card-body" data-knowledge-form>
                <input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="id" value="<?= (int)($editing['id']??0) ?>">
                <div class="sensecms-source-kind" <?= $editing?'hidden':'' ?>><label><input type="radio" name="source_kind" value="manual" checked><span><i data-lucide="text-cursor-input"></i><b>Write text</b><small>Create editable knowledge</small></span></label><label><input type="radio" name="source_kind" value="file"><span><i data-lucide="file-up"></i><b>Upload file</b><small>TXT, PDF, RTF, DOC or DOCX</small></span></label></div>
                <label><span>Source title</span><input class="form-input" name="title" maxlength="255" required value="<?= $escape($editing['title']??'') ?>" placeholder="e.g. Returns and refunds"></label>
                <label><span>Language</span><select class="form-input" name="locale"><option value="">All languages</option><?php foreach($languages as$language): ?><option value="<?= $escape($language['locale']) ?>" <?= ($editing['locale']??'')===$language['locale']?'selected':'' ?>><?= $escape($language['native_name']?:$language['name']) ?></option><?php endforeach; ?></select></label>
                <label data-knowledge-manual><span>Knowledge text</span><textarea class="form-input" name="body" rows="14" maxlength="2000000" placeholder="Write the complete, approved information the assistant may use…"><?= $escape($editing['body']??'') ?></textarea><small>Corrections are reindexed immediately after saving.</small></label>
                <label class="sensecms-knowledge-upload" data-knowledge-file hidden><input type="file" name="knowledge_file" accept=".txt,.pdf,.rtf,.doc,.docx"><span><i data-lucide="cloud-upload"></i><b>Choose a document</b><small>Maximum 20 MiB. Scanned PDFs require OCR before upload.</small></span></label>
                <label class="sensecms-knowledge-active"><input type="checkbox" name="active" value="1" <?= !$editing||($editing['status']??'published')==='published'?'checked':'' ?>><span><b>Approved for retrieval</b><small>Only approved and indexed sources may be used in visitor answers.</small></span></label>
                <footer><?php if($editing): ?><a class="btn bg-default-150" href="/ai/knowledge?tab=sources">Cancel editing</a><?php endif; ?><button class="btn bg-primary text-white" type="submit"><i data-lucide="save"></i><?= $editing?'Save and reindex':'Add source' ?></button></footer>
            </form>
        </section>
        <section class="card sensecms-knowledge-sources">
            <div class="card-header"><div><h6 class="card-title">Knowledge sources</h6><p>Every answer can be traced back to one or more of these controlled sources.</p></div></div>
            <form class="sensecms-knowledge-filter" method="get" action="/ai/knowledge"><input type="hidden" name="tab" value="sources"><label><i data-lucide="search"></i><input class="form-input" type="search" name="q" value="<?= $escape($knowledgeQuery) ?>" placeholder="Search sources…"></label><select class="form-input" name="type"><option value="all">All source types</option><?php foreach(['manual'=>'Manual text','file'=>'Files','page'=>'Pages','post'=>'Posts']as$key=>$label): ?><option value="<?= $key ?>" <?= $knowledgeType===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select><select class="form-input" name="status"><option value="all">All states</option><?php foreach(['published'=>'Approved','draft'=>'Disabled','archived'=>'Archived']as$key=>$label): ?><option value="<?= $key ?>" <?= $knowledgeStatus===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select><button class="btn bg-default-150" type="submit">Filter</button></form>
            <div class="sensecms-knowledge-source-list"><?php if(!$documents): ?><div class="sensecms-knowledge-empty"><i data-lucide="book-open"></i><strong>No knowledge sources yet</strong><span>Add approved text or a document to create the first RAG source.</span></div><?php endif; ?><?php foreach($documents as$document):$state=(string)$document['status'];$index=(string)$document['index_status']; ?><article><span class="sensecms-knowledge-source-icon is-<?= $escape((string)$document['source_type']) ?>"><i data-lucide="<?= match($document['source_type']){'file'=>'file-text','page'=>'panels-top-left','post'=>'newspaper',default=>'text'} ?>"></i></span><div><header><strong><?= $escape($document['title']) ?></strong><span class="is-<?= $escape($state) ?>"><?= $escape($state==='published'?'Approved':ucfirst($state)) ?></span></header><p><?= $escape(ucfirst((string)$document['source_type'])) ?><?= !empty($document['original_name'])?' · '.$escape($document['original_name']):'' ?><?= !empty($document['locale'])?' · '.strtoupper($escape($document['locale'])):' · All languages' ?></p><small><i data-lucide="<?= $index==='ready'?'circle-check':($index==='failed'?'circle-x':'clock-3') ?>"></i><?= $escape($index==='ready'?(int)$document['chunk_count'].' chunks · indexed '.(string)$document['indexed_at']:($index==='failed'?(string)$document['index_error']:'Waiting for indexing')) ?></small></div><nav><?php if(in_array($document['source_type'],['manual','file'],true)): ?><a href="/ai/knowledge?tab=sources&edit=<?= (int)$document['id'] ?>" aria-label="Edit <?= $escape($document['title']) ?>"><i data-lucide="pencil"></i></a><?php endif; ?><form method="post" action="/ai/knowledge/documents/<?= (int)$document['id'] ?>/reindex"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" aria-label="Reindex"><i data-lucide="refresh-cw"></i></button></form><form method="post" action="/ai/knowledge/documents/<?= (int)$document['id'] ?>/<?= $state==='published'?'draft':'publish' ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" aria-label="<?= $state==='published'?'Disable':'Approve' ?>"><i data-lucide="<?= $state==='published'?'circle-pause':'circle-play' ?>"></i></button></form><form method="post" action="/ai/knowledge/documents/<?= (int)$document['id'] ?>/delete" data-knowledge-delete data-title="<?= $escape($document['title']) ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" aria-label="Delete"><i data-lucide="trash-2"></i></button></form></nav></article><?php endforeach; ?></div>
            <?php if(($pagination['pages']??1)>1): ?><footer class="sensecms-knowledge-pagination"><span><?= (int)$pagination['total'] ?> sources</span><div><?php for($page=1;$page<=(int)$pagination['pages'];$page++): ?><a class="<?= $page===(int)$pagination['page']?'is-active':'' ?>" href="/ai/knowledge?tab=sources&page=<?= $page ?>&q=<?= rawurlencode($knowledgeQuery) ?>&type=<?= rawurlencode($knowledgeType) ?>&status=<?= rawurlencode($knowledgeStatus) ?>"><?= $page ?></a><?php endfor; ?></div></footer><?php endif; ?>
        </section>
    </div>
    <?php elseif($tab==='content'): ?>
    <section class="card sensecms-knowledge-content">
        <div class="card-header"><div><h6 class="card-title">Website content sources</h6><p>Published content is synchronized into language-specific RAG sources. Draft, private and future content is never indexed.</p></div><form method="get" action="/ai/knowledge"><input type="hidden" name="tab" value="content"><label><i data-lucide="search"></i><input class="form-input" type="search" name="q" value="<?= $escape($knowledgeQuery) ?>" placeholder="Find a page or post…"></label><select class="form-input" name="content_type"><option value="all">Pages and posts</option><option value="page" <?= ($_GET['content_type']??'')==='page'?'selected':'' ?>>Pages</option><option value="post" <?= ($_GET['content_type']??'')==='post'?'selected':'' ?>>Posts</option></select><button class="btn bg-default-150" type="submit">Filter</button></form></div>
        <div class="sensecms-knowledge-content-list"><?php foreach($knowledgeSiteContent as$item): ?><article><span><i data-lucide="<?= $item['source_type']==='page'?'panels-top-left':'newspaper' ?>"></i></span><div><strong><?= $escape($item['title']) ?></strong><small><?= $escape(ucfirst($item['source_type']).' · '.$item['status'].' · '.(int)$item['translation_count'].' language versions') ?></small></div><label><input type="checkbox" data-knowledge-source-type="<?= $escape($item['source_type']) ?>" data-knowledge-source-id="<?= (int)$item['id'] ?>" <?= !empty($item['ai_knowledge_enabled'])?'checked':'' ?>><span><?= !empty($item['ai_knowledge_enabled'])?'Included':'Excluded' ?></span></label></article><?php endforeach; ?><?php if(!$knowledgeSiteContent): ?><div class="sensecms-knowledge-empty"><i data-lucide="search-x"></i><strong>No matching content</strong><span>Adjust the filters or create a page or post first.</span></div><?php endif; ?></div>
        <footer><span><i data-lucide="info"></i>Changes control the next rebuild. Existing indexed copies are removed when Rebuild index runs.</span><form method="post" action="/ai/knowledge/rebuild" data-knowledge-rebuild><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button class="btn bg-primary text-white" type="submit"><i data-lucide="refresh-cw"></i>Save changes and rebuild</button></form></footer>
    </section>
    <?php elseif($tab==='index'): ?>
    <section class="sensecms-knowledge-index-grid"><article class="card"><div class="card-header"><div><span class="sensecms-overline">RETRIEVAL PIPELINE</span><h6 class="card-title">Core RAG index</h6><p>Sense CMS extracts approved text, splits it into bounded overlapping chunks and retrieves only relevant language-matched sources.</p></div><span class="sensecms-index-health <?= empty($summary['failed'])?'is-ready':'has-errors' ?>"><i data-lucide="<?= empty($summary['failed'])?'shield-check':'triangle-alert' ?>"></i><?= empty($summary['failed'])?'Healthy':(int)$summary['failed'].' failed' ?></span></div><div class="card-body"><ol><li><span>1</span><div><b>Collect</b><small>Manual text, private files, published pages and published posts.</small></div></li><li><span>2</span><div><b>Normalize</b><small>Remove markup and unsafe control data without changing the approved source.</small></div></li><li><span>3</span><div><b>Chunk</b><small>Build bounded passages with overlap and source identity.</small></div></li><li><span>4</span><div><b>Retrieve</b><small>Rank matching passages by query, language and current source state.</small></div></li></ol></div></article><article class="card sensecms-knowledge-rebuild"><div><span class="sensecms-section-icon"><i data-lucide="database-zap"></i></span><span><small>LAST CONTROLLED BUILD</small><strong><?= (int)($summary['ready']??0) ?> ready sources</strong><p><?= (int)($summary['chunks']??0) ?> chunks are available for retrieval. Rebuilding does not call a text-generation model.</p></span></div><dl><div><dt>Pending</dt><dd><?= max(0,(int)($summary['active']??0)-(int)($summary['ready']??0)-(int)($summary['failed']??0)) ?></dd></div><div><dt>Failed</dt><dd><?= (int)($summary['failed']??0) ?></dd></div><div><dt>Source storage</dt><dd><?= $escape($formatBytes((int)($summary['bytes']??0))) ?></dd></div></dl><form method="post" action="/ai/knowledge/rebuild" data-knowledge-rebuild><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button class="btn bg-primary text-white" type="submit"><i data-lucide="refresh-cw"></i>Rebuild complete index</button></form></article></section>
    <?php else: ?>
    <section class="sensecms-training-overview card">
        <div class="card-header"><div><span class="sensecms-overline">REVIEW-FIRST MODEL OPTIMIZATION</span><h6 class="card-title">Training workspace</h6><p>Fine-tuning changes model behaviour, not factual knowledge. Raw documents and visitor conversations are never copied into a dataset automatically.</p></div><span class="sensecms-index-health"><i data-lucide="lock-keyhole"></i>Cost locked</span></div>
        <div class="sensecms-ai-summary"><?php foreach([['Datasets',$knowledgeTraining['datasets']],['Approved examples',$knowledgeTraining['approved_examples']],['Evaluation cases',$knowledgeTraining['evaluations']],['Training jobs',$knowledgeTraining['jobs']]]as[$label,$value]): ?><article><span><?= $escape($label) ?></span><strong><?= (int)$value ?></strong></article><?php endforeach; ?></div>
    </section>
    <div class="sensecms-training-workspace">
        <section class="card sensecms-training-panel">
            <div class="card-header"><div><h6 class="card-title">Datasets</h6><p>Bind curated examples to a provider and base model without sending anything yet.</p></div><i data-lucide="layers-3"></i></div>
            <form method="post" action="/ai/knowledge/training/datasets" class="sensecms-training-form">
                <input type="hidden" name="csrf" value="<?= $escape($csrf) ?>">
                <label><span>Name</span><input class="form-input" name="name" maxlength="190" required placeholder="Visitor assistant tone · v1"></label>
                <label><span>Description</span><textarea class="form-input" name="description" rows="3" maxlength="1000" placeholder="Purpose, language and editorial rules"></textarea></label>
                <div><label><span>Provider</span><select class="form-input" name="provider_id"><option value="">Choose later</option><?php foreach($providers as$provider): ?><option value="<?= (int)$provider['id'] ?>"><?= $escape($provider['name']) ?><?= empty($provider['enabled'])?' · disabled':'' ?></option><?php endforeach; ?></select></label><label><span>Base model</span><input class="form-input" name="base_model" maxlength="150" placeholder="Uses provider default when empty"></label></div>
                <button class="btn bg-primary text-white" type="submit"><i data-lucide="plus"></i>Create dataset</button>
            </form>
            <div class="sensecms-training-list"><?php if(!$datasets): ?><div class="sensecms-training-empty">No datasets yet.</div><?php endif; ?><?php foreach($datasets as$dataset):$all=(int)$dataset['example_count'];$approved=(int)$dataset['approved_count']; ?><article><div><header><strong><?= $escape($dataset['name']) ?></strong><span class="is-<?= $escape($dataset['status']) ?>"><?= $escape($dataset['status']) ?></span></header><small><?= $escape(($dataset['provider_name']?:'Provider not selected').' · '.($dataset['base_model']?:'model not selected')) ?></small><p><?= $approved ?>/<?= $all ?> approved examples<?= $all<10?' · at least 10 required':'' ?></p></div><nav><?php if($dataset['status']==='ready'): ?><form method="post" action="/ai/knowledge/training/dataset/<?= (int)$dataset['id'] ?>/draft"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" title="Return to draft"><i data-lucide="undo-2"></i></button></form><?php else: ?><form method="post" action="/ai/knowledge/training/dataset/<?= (int)$dataset['id'] ?>/ready"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" title="Mark ready"><i data-lucide="badge-check"></i></button></form><?php endif; ?><form method="post" action="/ai/knowledge/training/dataset/<?= (int)$dataset['id'] ?>/archive"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" title="Archive"><i data-lucide="archive"></i></button></form></nav></article><?php endforeach; ?></div>
        </section>

        <section class="card sensecms-training-panel">
            <div class="card-header"><div><h6 class="card-title">Curated examples</h6><p>Write the exact input and ideal response. Each example requires human approval.</p></div><i data-lucide="messages-square"></i></div>
            <form method="post" action="/ai/knowledge/training/examples" class="sensecms-training-form">
                <input type="hidden" name="csrf" value="<?= $escape($csrf) ?>">
                <label><span>Dataset</span><select class="form-input" name="dataset_id" required><option value="">Choose dataset</option><?php foreach($datasets as$dataset): ?><option value="<?= (int)$dataset['id'] ?>"><?= $escape($dataset['name']) ?></option><?php endforeach; ?></select></label>
                <label><span>User input</span><textarea class="form-input" name="input_text" rows="3" maxlength="12000" required placeholder="A representative user request"></textarea></label>
                <label><span>Ideal answer</span><textarea class="form-input" name="ideal_output" rows="5" maxlength="24000" required placeholder="The reviewed answer the model should learn to produce"></textarea></label>
                <div><label><span>Language</span><select class="form-input" name="locale"><option value="">Any language</option><?php foreach($languages as$language): ?><option value="<?= $escape($language['locale']) ?>"><?= $escape($language['native_name']?:$language['name']) ?></option><?php endforeach; ?></select></label><label><span>Instructions</span><input class="form-input" name="instructions" maxlength="4000" placeholder="Optional style or behaviour rule"></label></div>
                <label class="sensecms-training-approval"><input type="checkbox" name="approved" value="1"><span><b>Approve immediately</b><small>Use only after reviewing both sides of this example.</small></span></label>
                <button class="btn bg-primary text-white" type="submit" <?= !$datasets?'disabled':'' ?>><i data-lucide="plus"></i>Add example</button>
            </form>
            <div class="sensecms-training-list is-scrollable"><?php if(!$examples): ?><div class="sensecms-training-empty">No curated examples yet.</div><?php endif; ?><?php foreach($examples as$example): ?><article><div><header><strong><?= $escape($example['dataset_name']) ?></strong><span class="<?= !empty($example['approved'])?'is-ready':'is-draft' ?>"><?= !empty($example['approved'])?'approved':'review' ?></span></header><p><?= $escape(mb_strimwidth((string)$example['input_text'],0,150,'…')) ?></p><small><?= $escape(!empty($example['locale'])?strtoupper($example['locale']):'Any language') ?> · by <?= $escape($example['created_by_name']) ?></small></div><nav><form method="post" action="/ai/knowledge/training/example/<?= (int)$example['id'] ?>/<?= !empty($example['approved'])?'unapprove':'approve' ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" title="<?= !empty($example['approved'])?'Return to review':'Approve' ?>"><i data-lucide="<?= !empty($example['approved'])?'circle-pause':'circle-check' ?>"></i></button></form><form method="post" action="/ai/knowledge/training/example/<?= (int)$example['id'] ?>/delete"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" title="Delete"><i data-lucide="trash-2"></i></button></form></nav></article><?php endforeach; ?></div>
        </section>

        <section class="card sensecms-training-panel">
            <div class="card-header"><div><h6 class="card-title">Evaluation cases</h6><p>Keep test questions separate from training data to measure factual quality.</p></div><i data-lucide="list-checks"></i></div>
            <form method="post" action="/ai/knowledge/training/evaluations" class="sensecms-training-form">
                <input type="hidden" name="csrf" value="<?= $escape($csrf) ?>">
                <label><span>Case name</span><input class="form-input" name="name" maxlength="190" required placeholder="Returns policy accuracy"></label>
                <label><span>Question</span><textarea class="form-input" name="question" rows="3" maxlength="8000" required></textarea></label>
                <label><span>Expected answer</span><textarea class="form-input" name="expected_answer" rows="5" maxlength="24000" required></textarea></label>
                <div><label><span>Language</span><select class="form-input" name="locale"><option value="">Any language</option><?php foreach($languages as$language): ?><option value="<?= $escape($language['locale']) ?>"><?= $escape($language['native_name']?:$language['name']) ?></option><?php endforeach; ?></select></label><label><span>Required source key</span><input class="form-input" name="required_source_key" maxlength="191" placeholder="Optional traceability requirement"></label></div>
                <button class="btn bg-primary text-white" type="submit"><i data-lucide="plus"></i>Add evaluation</button>
            </form>
            <div class="sensecms-training-list is-scrollable"><?php if(!$evaluations): ?><div class="sensecms-training-empty">No evaluation cases yet.</div><?php endif; ?><?php foreach($evaluations as$evaluation): ?><article><div><header><strong><?= $escape($evaluation['name']) ?></strong><span class="is-ready">active</span></header><p><?= $escape(mb_strimwidth((string)$evaluation['question'],0,150,'…')) ?></p><small><?= $escape(!empty($evaluation['locale'])?strtoupper($evaluation['locale']):'Any language') ?> · by <?= $escape($evaluation['created_by_name']) ?></small></div><nav><form method="post" action="/ai/knowledge/training/evaluation/<?= (int)$evaluation['id'] ?>/delete"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button type="submit" title="Delete"><i data-lucide="trash-2"></i></button></form></nav></article><?php endforeach; ?></div>
        </section>
    </div>
    <section class="card sensecms-training-locked"><div><span class="sensecms-section-icon is-ai"><i data-lucide="shield-check"></i></span><span><strong>Paid training remains locked</strong><p>When enabled in a later stage, Sense CMS will first show the provider, model, dataset version and estimated cost, and will require a separate explicit confirmation.</p></span></div><button class="btn bg-default-150" type="button" disabled><i data-lucide="play"></i>Start fine-tuning</button><small><i data-lucide="circle-dollar-sign"></i>No API request or charge has been made.</small></section>
    <?php endif; ?>
</section>
