<?php
$mediaBootstrap=['data'=>$mediaData,'filters'=>$mediaFilters,'folders'=>$mediaFolders,'tags'=>$mediaTags,'languages'=>$languages,'facilities'=>$facilities,'can_global'=>$mediaCanGlobal,'can_delete'=>$mediaCanDelete,'csrf'=>$csrf];
?>
<div class="sensecms-media-shell" data-media-library>
    <?php $sectionHero=['overline'=>'CONTENT · DIGITAL ASSET MANAGEMENT','title'=>'Media Library','description'=>'Organize reusable assets, prepare responsive image variants and protect every file already used by school content.','icon'=>'images','action_button'=>'data-media-upload-open','action_label'=>'Upload media','action_icon'=>'cloud-upload'];require __DIR__.'/console-section-hero.php'; ?>
    <section class="sensecms-media-summary" data-media-summary>
        <?php foreach([['files','All assets',(int)($mediaData['summary']['total']??0)],['image','Images',(int)($mediaData['summary']['images']??0)],['video','Videos',(int)($mediaData['summary']['videos']??0)],['archive-restore','Trash',(int)($mediaData['summary']['trash']??0)]]as[$icon,$label,$value]): ?><article><i data-lucide="<?= $icon ?>"></i><div><b><?= $value ?></b><span><?= $label ?></span></div></article><?php endforeach; ?>
    </section>
    <section class="card sensecms-media-toolbar"><label class="sensecms-media-search"><i data-lucide="search"></i><input type="search" value="<?= $escape($mediaFilters['q']??'') ?>" placeholder="Search filename, title, alternative text or tag…" data-media-filter="q"></label><select class="form-input" data-media-filter="kind" aria-label="File type"><?php foreach(['all'=>'All file types','image'=>'Images','video'=>'Videos','audio'=>'Audio','document'=>'Documents']as$value=>$label): ?><option value="<?= $value ?>" <?= ($mediaFilters['kind']??'all')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select><select class="form-input" data-media-filter="orientation" aria-label="Orientation"><?php foreach(['all'=>'Any orientation','landscape'=>'Landscape','portrait'=>'Portrait','square'=>'Square']as$value=>$label): ?><option value="<?= $value ?>" <?= ($mediaFilters['orientation']??'all')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select><select class="form-input" data-media-filter="tag" aria-label="Tag"><option value="0">All tags</option><?php foreach($mediaTags as$tag): ?><option value="<?= (int)$tag['id'] ?>" <?= (int)($mediaFilters['tag']??0)===(int)$tag['id']?'selected':'' ?>><?= $escape($tag['name']) ?> (<?= (int)$tag['media_count'] ?>)</option><?php endforeach; ?></select><select class="form-input" data-media-filter="facility" aria-label="Facility"><option value="all">All accessible libraries</option><option value="shared" <?= ($mediaFilters['facility']??'all')==='shared'?'selected':'' ?>>Shared library</option><?php foreach($facilities as$facility): ?><option value="<?= (int)$facility['id'] ?>" <?= (string)($mediaFilters['facility']??'')===(string)$facility['id']?'selected':'' ?>><?= $escape(($facility['city_name']??$facility['city_slug']).' · '.($facility['name']??$facility['facility_slug'])) ?></option><?php endforeach; ?></select><select class="form-input" data-media-filter="sort" aria-label="Sort order"><?php foreach(['newest'=>'Newest first','oldest'=>'Oldest first','name'=>'Name A–Z','size'=>'Largest first']as$value=>$label): ?><option value="<?= $value ?>" <?= ($mediaFilters['sort']??'newest')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select><div class="sensecms-media-status-toggle"><button type="button" class="<?= ($mediaFilters['status']??'active')==='active'?'is-active':'' ?>" data-media-status="active">Library</button><button type="button" class="<?= ($mediaFilters['status']??'active')==='trash'?'is-active':'' ?>" data-media-status="trash">Trash</button></div></section>
    <div class="sensecms-media-layout">
        <aside class="card sensecms-media-folders"><header><div><span class="sensecms-overline">ORGANIZATION</span><h3>Folders</h3></div><button type="button" data-folder-create aria-label="Create folder"><i data-lucide="folder-plus"></i></button></header><nav data-media-folders><button class="is-active" type="button" data-folder="-1"><i data-lucide="library"></i><span>All media</span></button><button type="button" data-folder="0"><i data-lucide="folder-open"></i><span>Unfiled</span></button><?php foreach($mediaFolders as$folder): ?><button type="button" data-folder="<?= (int)$folder['id'] ?>"><i data-lucide="folder"></i><span><?= $escape($folder['name']) ?><small><?= $escape($folder['facility_name']) ?></small></span><b><?= (int)$folder['media_count'] ?></b></button><?php endforeach; ?></nav><footer><span>Storage used</span><strong data-media-storage><?= number_format(((int)($mediaData['summary']['bytes']??0))/1048576,1) ?> MB</strong></footer></aside>
        <main class="card sensecms-media-content"><header><div><span class="sensecms-overline" data-media-result-overline><?= (int)($mediaData['pagination']['total']??0) ?> MATCHING ASSETS</span><h3 data-media-result-title><?= ($mediaFilters['status']??'active')==='trash'?'Media trash':'Your media' ?></h3></div><?php if($mediaCanDelete): ?><button class="btn bg-default-150" type="button" data-empty-media-trash <?= ($mediaFilters['status']??'active')==='trash'?'':'hidden' ?>><i data-lucide="trash-2"></i>Empty trash</button><?php endif; ?></header><div class="sensecms-media-grid" data-media-grid aria-live="polite"></div><footer class="sensecms-media-pagination" data-media-pagination></footer></main>
    </div>

    <div class="sensecms-media-overlay" data-media-upload hidden><section class="sensecms-media-dialog"><header><div><span class="sensecms-overline">SECURE UPLOAD</span><h3>Add media assets</h3></div><button type="button" data-media-upload-close aria-label="Close upload"><i data-lucide="x"></i></button></header><form data-media-upload-form><label class="sensecms-media-drop"><input type="file" name="assets[]" multiple accept="image/jpeg,image/png,image/webp,video/mp4,audio/mpeg,application/pdf"><i data-lucide="cloud-upload"></i><strong>Choose files or drop them here</strong><span>Up to 10 files · images 8 MB · video 80 MB · audio and PDF 20 MB</span></label><div class="sensecms-media-dialog-fields"><label><span>Library scope</span><select class="form-input" name="facility_id"><?php if($mediaCanGlobal): ?><option value="">Shared library</option><?php endif; ?><?php foreach($facilities as$facility): ?><option value="<?= (int)$facility['id'] ?>"><?= $escape(($facility['city_name']??$facility['city_slug']).' · '.($facility['name']??$facility['facility_slug'])) ?></option><?php endforeach; ?></select></label><label><span>Folder</span><select class="form-input" name="folder_id"><option value="">Unfiled</option><?php foreach($mediaFolders as$folder): ?><option value="<?= (int)$folder['id'] ?>" data-facility="<?= (int)($folder['facility_id']??0) ?>"><?= $escape($folder['name']) ?></option><?php endforeach; ?></select></label></div><div class="sensecms-media-dialog-actions"><button class="btn bg-default-150" type="button" data-media-upload-close>Cancel</button><button class="btn bg-primary text-white" type="submit"><i data-lucide="upload"></i>Upload and optimize</button></div></form></section></div>
    <div class="sensecms-media-overlay is-inspector" data-media-inspector hidden><aside class="sensecms-media-inspector"><header><div><span class="sensecms-overline">ASSET DETAILS</span><h3 data-media-inspector-title>Media details</h3></div><button type="button" data-media-inspector-close aria-label="Close details"><i data-lucide="x"></i></button></header><div data-media-inspector-body class="sensecms-media-inspector-body"></div></aside></div>
    <div class="sensecms-media-overlay" data-folder-dialog hidden><section class="sensecms-media-dialog is-folder"><header><div><span class="sensecms-overline">ORGANIZATION</span><h3 data-folder-title>Create a folder</h3></div><button type="button" data-folder-close><i data-lucide="x"></i></button></header><form data-folder-form><input type="hidden" name="id"><label><span>Folder name</span><input class="form-input" name="name" maxlength="120" required></label><label><span>Library scope</span><select class="form-input" name="facility_id"><?php if($mediaCanGlobal): ?><option value="">Shared library</option><?php endif; ?><?php foreach($facilities as$facility): ?><option value="<?= (int)$facility['id'] ?>"><?= $escape(($facility['city_name']??$facility['city_slug']).' · '.($facility['name']??$facility['facility_slug'])) ?></option><?php endforeach; ?></select></label><label><span>Parent folder</span><select class="form-input" name="parent_id"><option value="">Top level</option><?php foreach($mediaFolders as$folder): ?><option value="<?= (int)$folder['id'] ?>" data-facility="<?= (int)($folder['facility_id']??0) ?>"><?= $escape($folder['name']) ?></option><?php endforeach; ?></select></label><div class="sensecms-media-dialog-actions"><button class="btn text-danger" type="button" data-folder-delete hidden><i data-lucide="trash-2"></i>Delete empty folder</button><button class="btn bg-default-150" type="button" data-folder-close>Cancel</button><button class="btn bg-primary text-white" type="submit" data-folder-submit><i data-lucide="folder-plus"></i><span>Create folder</span></button></div></form></section></div>
    <script nonce="<?= htmlspecialchars((string) ($_SERVER['SENSE_CSP_NONCE'] ?? ''), ENT_QUOTES, 'UTF-8') ?>" type="application/json" data-media-bootstrap><?= json_encode($mediaBootstrap,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
</div>
