<?php $inbox=$formInbox??['items'=>[],'pagination'=>[],'counts'=>[]]; ?>
<section class="sensecms-form-inbox sensecms-unified-workspace" data-form-inbox data-csrf="<?= $escape($csrf) ?>">
    <?php $sectionHero=['overline'=>'ENGAGEMENT · WEBSITE ENQUIRIES','title'=>'Form inbox','description'=>'Review multilingual form submissions, track handling status and keep every facility enquiry in a secure operational inbox.','icon'=>'inbox','action_url'=>'/forms/submissions/export?status='.rawurlencode((string)($formStatus??'all')),'action_label'=>'Export CSV','action_icon'=>'download'];require __DIR__.'/console-section-hero.php'; ?>
    <div class="sensecms-inbox-grid">
        <aside class="card sensecms-inbox-list">
            <form data-inbox-filter data-sensecms-bound="1"><div class="sensecms-inbox-search"><i data-lucide="search"></i><input type="search" name="q" value="<?= $escape($formQuery??'') ?>" placeholder="Search submissions…"></div><select class="form-select" name="status"><?php foreach(['all'=>'All submissions','new'=>'Unread','read'=>'Read','handled'=>'Handled','spam'=>'Spam','archived'=>'Archived']as$value=>$label):?><option value="<?= $value ?>" <?= ($formStatus??'all')===$value?'selected':'' ?>><?= $label ?> (<?= (int)($inbox['counts'][$value]??0) ?>)</option><?php endforeach;?></select></form>
            <div class="sensecms-inbox-items" data-inbox-items><?php foreach($inbox['items']as$item):?><button type="button" data-submission-id="<?= (int)$item['id'] ?>" class="sensecms-inbox-item <?= $item['status']==='new'?'is-new':'' ?>"><span class="sensecms-inbox-avatar"><?= $escape(mb_strtoupper(mb_substr((string)$item['sender'],0,1))) ?></span><span><b><?= $escape($item['sender']) ?></b><small><?= $escape($item['form_name']) ?> · <?= $escape(strtoupper((string)$item['locale'])) ?></small><em><?= $escape($item['preview']) ?></em></span><time><?= $escape(date('M j',strtotime((string)$item['created_at']))) ?></time></button><?php endforeach;?></div>
            <footer data-inbox-pagination><span><?= (int)($inbox['pagination']['total']??0) ?> submissions</span><div><button type="button" data-page="<?= max(1,(int)($inbox['pagination']['page']??1)-1) ?>" <?= ($inbox['pagination']['page']??1)<=1?'disabled':'' ?>><i data-lucide="chevron-left"></i></button><b><?= (int)($inbox['pagination']['page']??1) ?> / <?= (int)($inbox['pagination']['pages']??1) ?></b><button type="button" data-page="<?= min((int)($inbox['pagination']['pages']??1),(int)($inbox['pagination']['page']??1)+1) ?>" <?= ($inbox['pagination']['page']??1)>=($inbox['pagination']['pages']??1)?'disabled':'' ?>><i data-lucide="chevron-right"></i></button></div></footer>
        </aside>
        <main class="card sensecms-inbox-detail" data-inbox-detail><div class="sensecms-inbox-empty"><span><i data-lucide="mail-open"></i></span><h6>Select a submission</h6><p>Choose an enquiry to view its complete, language-aware form data.</p></div></main>
    </div>
</section>
