<?php
$activeLocale=(string)($_GET['lang']??($languages[0]['locale']??'en'));
$localeCodes=array_column($languages,'locale');
if(!in_array($activeLocale,$localeCodes,true))$activeLocale=(string)($languages[0]['locale']??'en');
$editId=max(0,(int)($_GET['edit']??0));$editing=null;
foreach($categories as$category)if((int)$category['id']===$editId){$editing=$category;break;}
$defaultLanguage=array_values(array_filter($languages,static fn(array$language):bool=>(bool)($language['is_default']??false)))[0]??($languages[0]??['locale'=>'en']);
$defaultLocale=(string)$defaultLanguage['locale'];
?>
<section class="sensecms-category-workspace">
    <?php $sectionHero=['overline'=>'CONTENT · TAXONOMY','title'=>'Categories','description'=>'Build a multilingual editorial structure without deleting relationships to existing posts.','icon'=>'tags','action_url'=>'/content/categories','action_label'=>'New category','action_icon'=>'tag'];require __DIR__.'/console-section-hero.php'; ?>
    <div class="sensecms-taxonomy-grid">
        <form method="post" action="/content/categories" class="card sensecms-taxonomy-editor" data-content-form><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="id" value="<?= (int)($editing['id']??0) ?>"><input type="hidden" name="ui_locale" value="<?= $escape($activeLocale) ?>" data-ui-locale>
            <div class="card-header"><div><span class="sensecms-overline"><?= $editing?'EDITING CATEGORY':'NEW CATEGORY' ?></span><h6 class="card-title"><?= $escape($editing['translations'][$defaultLocale]['name']??($editing['slug']??'Create a category')) ?></h6><p class="mt-1 text-sm text-default-500">Names and descriptions are maintained independently for each active language.</p></div><span class="sensecms-lifecycle <?= !empty($editing['archived_at'])?'is-archived':'is-published' ?>"><?= !empty($editing['archived_at'])?'Archived':'Active' ?></span></div>
            <?php $localeTabsId='category-editor-locales';$localeTabsActive=$activeLocale;require __DIR__.'/console-language-tabs.php'; ?>
            <div class="card-body grid gap-5"><label><span>System slug</span><input class="form-input" required maxlength="150" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" name="slug" value="<?= $escape($editing['slug']??'') ?>" placeholder="school-life"><small>Stable internal identifier. Lowercase letters, numbers and hyphens only.</small></label>
                <?php foreach($languages as$language):$locale=(string)$language['locale'];$translation=(array)($editing['translations'][$locale]??[]); ?><section data-language-panel="<?= $escape($locale) ?>" <?= $locale!==$activeLocale?'hidden':'' ?>><div class="sensecms-editor-language-head"><img src="<?= $escape($language['flag']?:'/sensecms/images/flags/gb.svg') ?>" alt=""><div><strong><?= $escape($language['native_name']?:$language['name']) ?></strong><span><?= $locale===$defaultLocale?'Default language · required':'Localized content · optional until completed' ?></span></div></div><div class="grid gap-4"><label><span>Category name</span><input class="form-input" maxlength="150" name="translations[<?= $escape($locale) ?>][name]" value="<?= $escape($translation['name']??'') ?>" <?= $locale===$defaultLocale?'required':'' ?>></label><label><span>Description</span><textarea class="form-input" maxlength="1000" rows="5" name="translations[<?= $escape($locale) ?>][description]"><?= $escape($translation['description']??'') ?></textarea></label></div></section><?php endforeach; ?>
            </div><div class="sensecms-taxonomy-actions"><span><i data-lucide="shield-check"></i>Archiving preserves every assigned post.</span><button class="btn bg-primary text-white" type="submit"><i data-lucide="save"></i><?= $editing?'Save category':'Create category' ?></button></div>
        </form>
        <section class="card sensecms-taxonomy-list"><div class="card-header"><div><span class="sensecms-overline">CATEGORY DIRECTORY</span><h6 class="card-title"><?= count($categories) ?> categories</h6></div></div><div class="sensecms-taxonomy-items"><?php foreach($categories as$category):$translation=(array)($category['translations'][$defaultLocale]??[]);$archived=!empty($category['archived_at']); ?><article class="<?= $archived?'is-archived':'' ?>"><span class="sensecms-taxonomy-icon"><i data-lucide="tag"></i></span><div><strong><?= $escape($translation['name']??$category['slug']) ?></strong><small>/<?= $escape($category['slug']) ?> · <?= (int)$category['posts'] ?> <?= (int)$category['posts']===1?'post':'posts' ?></small></div><span class="sensecms-lifecycle <?= $archived?'is-archived':'is-published' ?>"><?= $archived?'Archived':'Active' ?></span><div class="sensecms-row-actions"><a href="/content/categories?edit=<?= (int)$category['id'] ?>&lang=<?= rawurlencode($activeLocale) ?>" data-content-link aria-label="Edit category"><i data-lucide="pencil"></i></a><form method="post" action="/content/categories/<?= (int)$category['id'] ?>/<?= $archived?'restore':'archive' ?>" data-sensecms-confirm="<?= $archived?'Restore this category?':'Archive this category? Assigned posts will remain intact.' ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><button class="<?= $archived?'is-restore':'is-danger' ?>" aria-label="<?= $archived?'Restore':'Archive' ?> category"><i data-lucide="<?= $archived?'archive-restore':'archive' ?>"></i></button></form></div></article><?php endforeach; ?><?php if(!$categories): ?><div class="sensecms-content-empty"><i data-lucide="tags"></i><strong>No categories yet</strong><span>Create the first multilingual category.</span></div><?php endif; ?></div></section>
    </div>
</section>
