<?php
declare(strict_types=1);
$calendarBoot=is_array($calendarBoot??null)?$calendarBoot:[];$calendarCopy=is_array($calendarCopy??null)?$calendarCopy:[];$calendarLocale=(string)($calendarLocale??'en');
$tr=static function(string$key)use($calendarCopy):string{$value=$calendarCopy;foreach(explode('.',$key)as$part)$value=is_array($value)?($value[$part]??null):null;return is_string($value)?$value:$key;};
$h=static fn(string$value):string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');
?>
<div class="calendar-app" data-calendar-app lang="<?=$h($calendarLocale)?>">
<script type="application/json" data-calendar-boot><?=json_encode($calendarBoot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?></script>
<header class="calendar-hero"><div><p class="calendar-eyebrow"><i data-lucide="calendar-days"></i> <?=$h($tr('hero.eyebrow'))?></p><h1><?=$h($tr('hero.title'))?></h1><p><?=$h($tr('hero.description'))?></p></div><div class="calendar-hero-actions">
<label class="calendar-language"><span class="sr-only"><?=$h($tr('language'))?></span><i data-lucide="languages"></i><select data-calendar-language aria-label="<?=$h($tr('language'))?>"><?php foreach((array)($calendarBoot['locales']??[])as$locale):?><option value="<?=$h((string)$locale)?>"<?=$locale===$calendarLocale?' selected':''?>><?=$h($tr('languages.'.$locale))?></option><?php endforeach?></select></label>
<?php if(!empty($calendarBoot['permissions']['resources'])):?><button class="calendar-icon-button" type="button" data-calendar-resource aria-label="<?=$h($tr('actions.add_resource'))?>"><i data-lucide="building-2"></i></button><?php endif?>
<?php if(!empty($calendarBoot['permissions']['settings'])):?><button class="calendar-icon-button" type="button" data-calendar-integrations aria-label="<?=$h($tr('actions.integrations'))?>"><i data-lucide="plug-zap"></i></button><?php endif?>
<button class="calendar-icon-button" type="button" data-calendar-notifications aria-label="<?=$h($tr('actions.notifications'))?>"><i data-lucide="bell"></i><span data-calendar-notification-count hidden>0</span></button><button class="btn bg-primary text-white" type="button" data-calendar-new<?=empty($calendarBoot['permissions']['manage'])?' disabled':''?>><i data-lucide="plus"></i> <?=$h($tr('actions.new_event'))?></button></div></header>
<section class="calendar-toolbar" aria-label="<?=$h($tr('filters.view'))?>"><div class="calendar-nav"><button class="calendar-icon-button" type="button" data-calendar-prev aria-label="<?=$h($tr('actions.previous'))?>"><i data-lucide="chevron-left"></i></button><button class="calendar-today" type="button" data-calendar-today><?=$h($tr('actions.today'))?></button><button class="calendar-icon-button" type="button" data-calendar-next aria-label="<?=$h($tr('actions.next'))?>"><i data-lucide="chevron-right"></i></button><h2 data-calendar-title></h2></div><div class="calendar-filters"><label><span class="sr-only"><?=$h($tr('filters.facility'))?></span><select data-calendar-filter="facility_id"><option value=""><?=$h($tr('filters.all_facilities'))?></option></select></label><label><span class="sr-only"><?=$h($tr('filters.event_type'))?></span><select data-calendar-filter="event_type"><option value=""><?=$h($tr('filters.all_types'))?></option></select></label><div class="calendar-view-switch" role="group" aria-label="<?=$h($tr('filters.view'))?>"><button class="is-active" type="button" data-calendar-view="month"><?=$h($tr('filters.month'))?></button><button type="button" data-calendar-view="agenda"><?=$h($tr('filters.agenda'))?></button></div></div></section>
<?php if (!empty($calendarBoot['permissions']['settings'])): ?>
<details class="card mb-5"><summary class="card-header"><?=$h($tr('categories.title'))?></summary>
<div class="card-body"><p class="mb-4 text-sm text-default-500"><?=$h($tr('categories.help'))?></p>
<label class="calendar-field mb-4"><span><?=$h($tr('categories.choose'))?></span><select data-category-picker></select></label>
<form class="grid gap-4 md:grid-cols-2" data-category-form>
    <input type="hidden" name="id" value="0">
    <label class="calendar-field"><span><?=$h($tr('categories.name'))?></span><input name="name" minlength="2" maxlength="100" required></label>
    <label class="calendar-field"><span><?=$h($tr('categories.slug'))?></span><input name="slug" maxlength="40" pattern="[a-z0-9]+(-[a-z0-9]+)*" required></label>
    <label class="calendar-field"><span><?=$h($tr('categories.color'))?></span><input name="color" type="color" value="#2563eb"></label>
    <label class="calendar-check"><input type="checkbox" name="active" checked> <?=$h($tr('categories.active'))?></label>
    <div><button class="btn bg-primary text-white" type="submit"><i data-lucide="save"></i><?=$h($tr('categories.save'))?></button></div>
</form></div></details>
<?php endif; ?>
<main class="calendar-stage"><section class="calendar-month" data-calendar-month aria-label="<?=$h($tr('calendar.monthly'))?>"></section><section class="calendar-agenda" data-calendar-agenda hidden aria-label="<?=$h($tr('calendar.agenda'))?>"></section></main>
<aside class="calendar-drawer" data-calendar-drawer hidden aria-label="<?=$h($tr('notifications.title'))?>"><header><div><p class="calendar-eyebrow"><?=$h($tr('notifications.eyebrow'))?></p><h2><?=$h($tr('notifications.title'))?></h2></div><button class="calendar-icon-button" type="button" data-calendar-close-drawer aria-label="<?=$h($tr('actions.close'))?>"><i data-lucide="x"></i></button></header><div data-calendar-notification-list></div><button class="calendar-drawer-read" type="button" data-calendar-read-all><?=$h($tr('actions.mark_read'))?></button></aside>
<div class="calendar-overlay" data-calendar-overlay hidden></div>
<section class="calendar-modal" data-calendar-modal hidden role="dialog" aria-modal="true" aria-labelledby="calendar-modal-title"><form data-calendar-form><header><div><p class="calendar-eyebrow"><?=$h($tr('event.eyebrow'))?></p><h2 id="calendar-modal-title" data-calendar-modal-title><?=$h($tr('event.new'))?></h2></div><button class="calendar-icon-button" type="button" data-calendar-close aria-label="<?=$h($tr('actions.close'))?>"><i data-lucide="x"></i></button></header><div class="calendar-form-body">
<input type="hidden" name="id"><div class="calendar-field calendar-field-wide"><label for="calendar-title"><?=$h($tr('event.title'))?></label><input id="calendar-title" name="title" maxlength="180" required autocomplete="off"></div><div class="calendar-form-grid">
<div class="calendar-field" data-calendar-timed><label for="calendar-start"><?=$h($tr('event.starts'))?></label><input id="calendar-start" name="start_at" type="datetime-local" required></div><div class="calendar-field" data-calendar-timed><label for="calendar-end"><?=$h($tr('event.ends'))?></label><input id="calendar-end" name="end_at" type="datetime-local" required></div>
<div class="calendar-field" data-calendar-all-day hidden><label for="calendar-start-date"><?=$h($tr('event.start_date'))?></label><input id="calendar-start-date" name="start_date" type="date"></div><div class="calendar-field" data-calendar-all-day hidden><label for="calendar-end-date"><?=$h($tr('event.end_date'))?></label><input id="calendar-end-date" name="end_date" type="date"><small><?=$h($tr('event.end_inclusive'))?></small></div>
<div class="calendar-field"><label for="calendar-timezone"><?=$h($tr('event.timezone'))?></label><input id="calendar-timezone" name="timezone" list="calendar-timezones" required autocomplete="off"><datalist id="calendar-timezones"><?php foreach((array)($calendarBoot['options']['timezones']??[])as$timezone):?><option value="<?=$h((string)$timezone)?>"><?php endforeach?></datalist><small><?=$h($tr('event.timezone_help'))?></small></div><div class="calendar-field"><label for="calendar-type"><?=$h($tr('event.type'))?></label><select id="calendar-type" name="event_type"></select></div>
<div class="calendar-field"><label for="calendar-facility"><?=$h($tr('event.facility'))?></label><select id="calendar-facility" name="facility_id"><option value=""><?=$h($tr('filters.all_facilities'))?></option></select></div><div class="calendar-field"><label for="calendar-location"><?=$h($tr('event.location'))?></label><input id="calendar-location" name="location" maxlength="255"></div>
<div class="calendar-field"><label for="calendar-visibility"><?=$h($tr('event.visibility'))?></label><select id="calendar-visibility" name="visibility"><?php foreach(['participants','facility','private','public']as$option):?><option value="<?=$option?>"><?=$h($tr('event.visibility_options.'.$option))?></option><?php endforeach?></select></div><div class="calendar-field"><label for="calendar-recurrence"><?=$h($tr('event.repeat'))?></label><select id="calendar-recurrence" name="recurrence"><?php foreach(['none','daily','weekly','monthly']as$option):?><option value="<?=$option?>"><?=$h($tr('event.recurrence_options.'.$option))?></option><?php endforeach?></select></div>
<div class="calendar-field" data-calendar-until hidden><label for="calendar-recurrence-until"><?=$h($tr('event.repeat_until'))?></label><input id="calendar-recurrence-until" name="recurrence_until" type="date"></div><div class="calendar-field" data-calendar-edit-scope hidden><label for="calendar-edit-scope"><?=$h($tr('event.edit_scope'))?></label><select id="calendar-edit-scope" name="edit_scope"><option value="single"><?=$h($tr('event.scope_single'))?></option><option value="following"><?=$h($tr('event.scope_following'))?></option><option value="series"><?=$h($tr('event.scope_series'))?></option></select><small><?=$h($tr('event.series_help'))?></small></div></div>
<label class="calendar-check"><input name="all_day" type="checkbox" data-calendar-all-day-toggle> <?=$h($tr('event.all_day'))?></label><div class="calendar-field calendar-field-wide"><label for="calendar-description"><?=$h($tr('event.description'))?></label><textarea id="calendar-description" name="description" rows="3" maxlength="5000"></textarea></div>
<div class="calendar-form-grid"><fieldset class="calendar-choices"><legend><?=$h($tr('event.participants'))?></legend><div data-calendar-participants></div></fieldset><fieldset class="calendar-choices"><legend><?=$h($tr('event.resources'))?></legend><div data-calendar-resources></div></fieldset><fieldset class="calendar-choices"><legend><?=$h($tr('event.reminders'))?> <small><?=$h($tr('event.up_to_five'))?></small></legend><div data-calendar-reminders></div></fieldset><fieldset class="calendar-choices"><legend><?=$h($tr('event.channels'))?></legend><div data-calendar-channels></div></fieldset></div><div class="calendar-conflicts" data-calendar-conflicts hidden><i data-lucide="triangle-alert"></i><div><strong><?=$h($tr('conflict.title'))?></strong><div data-calendar-conflict-list></div><label class="calendar-check" data-calendar-override-option hidden><input name="override_conflicts" type="checkbox"> <?=$h($tr('conflict.override'))?></label></div></div></div>
<footer><button class="calendar-danger" type="button" data-calendar-cancel-event hidden><?=$h($tr('actions.cancel_event'))?></button><span></span><button class="calendar-secondary" type="button" data-calendar-close><?=$h($tr('actions.close'))?></button><button class="btn bg-primary text-white" type="submit" data-calendar-save><i data-lucide="check"></i> <?=$h($tr('actions.save_event'))?></button></footer></form></section>
<section class="calendar-modal calendar-integration-modal" data-integration-modal hidden role="dialog" aria-modal="true" aria-labelledby="calendar-integrations-title"><header><div><p class="calendar-eyebrow"><?=$h($tr('integrations.eyebrow'))?></p><h2 id="calendar-integrations-title"><?=$h($tr('integrations.title'))?></h2></div><button class="calendar-icon-button" type="button" data-integration-close aria-label="<?=$h($tr('actions.close'))?>"><i data-lucide="x"></i></button></header><div class="calendar-form-body"><p class="calendar-integration-lead"><?=$h($tr('integrations.lead'))?></p><section class="calendar-delivery-health" data-calendar-delivery-health></section><div class="calendar-integration-list" data-integration-list></div></div><footer><span></span><button class="calendar-secondary" type="button" data-integration-close><?=$h($tr('actions.close'))?></button></footer></section>
<dialog class="calendar-confirm" data-resource-dialog aria-labelledby="calendar-resource-title"><form data-resource-form><h2 id="calendar-resource-title"><?=$h($tr('resource.title'))?></h2><div class="calendar-field"><label for="calendar-resource-name"><?=$h($tr('resource.name'))?></label><input id="calendar-resource-name" name="name" required minlength="2" maxlength="150"></div><div class="calendar-field"><label for="calendar-resource-facility"><?=$h($tr('resource.facility'))?></label><select id="calendar-resource-facility" name="facility_id"><option value=""><?=$h($tr('filters.all_facilities'))?></option></select></div><div class="calendar-field"><label for="calendar-resource-type"><?=$h($tr('resource.type'))?></label><select id="calendar-resource-type" name="resource_type"><?php foreach(['room','equipment','vehicle','facility']as$type):?><option value="<?=$type?>"><?=$h($tr('resource.types.'.$type))?></option><?php endforeach?></select></div><div class="calendar-field"><label for="calendar-resource-capacity"><?=$h($tr('resource.capacity'))?></label><input id="calendar-resource-capacity" name="capacity" type="number" min="0" max="100000"></div><button class="calendar-secondary" type="button" data-resource-close><?=$h($tr('actions.close'))?></button> <button class="btn bg-primary text-white" type="submit"><?=$h($tr('actions.add'))?></button></form></dialog>
<dialog class="calendar-confirm" data-calendar-confirm aria-labelledby="calendar-confirm-title"><i data-lucide="calendar-x"></i><h2 id="calendar-confirm-title"><?=$h($tr('confirm.title'))?></h2><p><?=$h($tr('confirm.body'))?></p><label class="calendar-field" data-calendar-cancel-scope hidden><span><?=$h($tr('event.cancel_scope'))?></span><select name="cancel_scope"><option value="single"><?=$h($tr('event.scope_single'))?></option><option value="following"><?=$h($tr('event.scope_following'))?></option><option value="series"><?=$h($tr('event.scope_series'))?></option></select></label><div><button type="button" class="calendar-secondary" data-confirm-no><?=$h($tr('actions.keep_event'))?></button><button type="button" class="calendar-danger" data-confirm-yes><?=$h($tr('actions.confirm_cancel'))?></button></div></dialog>
<div class="calendar-toast" data-calendar-toast hidden role="status" aria-live="polite"></div></div>
