<?php

declare(strict_types=1);

use App\Core\ExtensionContext;
use App\Core\Runtime;
use SenseCMS\Bluesky\BlueskyOnboardingClient;
use SenseCMS\Social\SocialIntegrationManager;

require_once __DIR__.'/src/BlueskyOnboardingClient.php';

return static function(string$method,string$path,ExtensionContext$context):bool{
    $disconnect=preg_match('#^/social-publishing/bluesky/connections/(\d+)/disconnect$#D',$path,$matches)===1;
    if(!in_array($path,['/social-publishing/bluesky','/social-publishing/bluesky/status','/social-publishing/bluesky/connect','/social-publishing/bluesky/callback'],true)&&!$disconnect)return false;
    if(!$context->auth->check()){header('Location: /login',true,302);exit;}$context->access->assert('social.settings.manage');$foundation=$context->root.'/addons/social-publishing/src/SocialIntegrationManager.php';if(!is_file($foundation))throw new RuntimeException('The Social Publishing add-on is required.');
    require_once$foundation;$manager=new SocialIntegrationManager($context->db,$context->root,(string)($context->config['secrets_key']??''));
    if($method==='GET'&&$path==='/social-publishing/bluesky'){$provider=null;foreach($manager->catalog()as$item)if($item['slug']==='bluesky-publisher'){$provider=$item;break;}$context->dashboard->extensionPage('Bluesky Publisher',__DIR__.'/views/bluesky.php',['blueskyProvider'=>$provider,'blueskyOAuthRevision'=>(int)($_SESSION['bluesky_oauth_revision']??0),'blueskyOAuthOutcome'=>(string)($_SESSION['flash_type']??''),'csrf'=>$context->auth->csrf(),'extensionActive'=>'/social-publishing','extensionStyles'=>['/extension-assets/addon/social-publishing/social.css?v=0.4.1','/extension-assets/plugin/bluesky-publisher/bluesky.css?v=0.1.4'],'extensionScripts'=>['/extension-assets/plugin/bluesky-publisher/bluesky.js?v=0.1.4']]);}
    if($method==='GET'&&$path==='/social-publishing/bluesky/status'){$connections=[];foreach($manager->catalog()as$item)if($item['slug']==='bluesky-publisher'){$connections=(array)($item['connections']??[]);break;}header('Cache-Control: no-store');header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'data'=>['connected'=>$connections!==[],'connected_count'=>count($connections),'connection_ids'=>array_values(array_map(static fn(array$item):int=>(int)$item['id'],$connections)),'revision'=>(int)($_SESSION['bluesky_oauth_revision']??0)]],JSON_THROW_ON_ERROR);exit;}
    if($method==='POST'&&$path==='/social-publishing/bluesky/connect'){if(!$context->auth->verifyCsrf($_POST['csrf']??null))throw new RuntimeException('Your session token is invalid. Refresh and try again.',419);$base=(string)($context->config['integrations']['bluesky_social_broker_url']??'');$client=new BlueskyOnboardingClient((new Runtime($context->root))->license(),$base,(string)$context->config['base_url']);$url=$client->start();if(str_contains((string)($_SERVER['HTTP_ACCEPT']??''),'application/json')){header('Cache-Control: no-store');header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'authorize_url'=>$url],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);exit;}header('Location: '.$url,true,302);exit;}
    if($method==='GET'&&$path==='/social-publishing/bluesky/callback'){try{if(!isset($_GET['claim']))throw new RuntimeException('Bluesky authorization was cancelled.');$base=(string)($context->config['integrations']['bluesky_social_broker_url']??'');$client=new BlueskyOnboardingClient((new Runtime($context->root))->license(),$base,(string)$context->config['base_url']);$data=$client->claim((string)$_GET['claim']);$manager->save('bluesky-publisher',(string)$data['did'],'@'.(string)$data['handle'],$data);$_SESSION['bluesky_oauth_revision']=(int)($_SESSION['bluesky_oauth_revision']??0)+1;$_SESSION['flash']='Bluesky account connected successfully.';$_SESSION['flash_type']='success';}catch(Throwable$error){error_log('Bluesky connection failed: '.get_class($error));$_SESSION['flash']='Bluesky could not be connected. Verify the account authorization and try again.';$_SESSION['flash_type']='error';}header('Location: /social-publishing/bluesky',true,302);exit;}
    if($method==='POST'&&$disconnect){if(!$context->auth->verifyCsrf($_POST['csrf']??null))throw new RuntimeException('Your session token is invalid. Refresh and try again.',419);$manager->disconnect('bluesky-publisher',(int)$matches[1]);$_SESSION['flash']='Bluesky account disconnected. Existing delivery history was preserved.';$_SESSION['flash_type']='success';header('Location: /social-publishing/bluesky',true,302);exit;}
    http_response_code(405);header('Allow: GET, POST');exit;
};
